import { $APP, shadow$provide } from "./nbb_core.js";
import "./nbb_api.js";
const shadow_esm_import = function(x) { return import(x) };
import*as esm_import$node_net from"node:net";import*as esm_import$node_process from"node:process";import*as esm_import$node_readline from"node:readline";import*as esm_import$node_vm from"node:vm";
var $Qa=function(a){var b=function(){var g=$APP.jq.j(a,"(");return $APP.k(g)?new $APP.D(null,2,5,$APP.E,[$APP.vj.l(a,0,g+1),$APP.vj.j(a,g+1)],null):new $APP.D(null,2,5,$APP.E,[null,a],null)}(),c=$APP.w.l(b,0,null),d=$APP.w.l(b,1,null);b=$APP.y;var e=b.j;try{var f=$APP.MGa(new $APP.F(null,2,[$APP.S,""+$APP.G.h($APP.yc(h4)),$APP.$N,d],null))}catch(g){console.warn(""+$APP.Wza,$APP.Jk(g)),f=null}f=e.call(b,f,"completions");return $APP.rk.j(function(g){return""+$APP.G.h(c)+$APP.G.h(g)},$APP.sh(function(g){return $APP.La(g,
d)},$APP.rk.j(function(g){return $APP.y.j(g,"candidate")},f)))},aRa=function(a){return[$APP.Fu.h($Qa(a)),a]},l4=function(a,b){$APP.$g(i4,!1);a.setPrompt(""+$APP.G.h($APP.yc(h4))+"\x3d\x3e ");a.prompt();return $APP.Dl($APP.yc(j4))?null:k4.j?k4.j(b,a):k4.call(null,b,a)},bRa=function(a){var b=$APP.Ul(a);a=$APP.Vl(a);var c=$APP.xl($APP.yc(j4));b=$APP.hh.j(b-1,c);c=$APP.n(b);b=$APP.p(c);c=$APP.q(c);a=$APP.k(b)?$APP.vj.j(b,a):null;$APP.$g(j4,$APP.Vn.j("\n",$APP.cg(a,c)))},cRa=function(a,b){b={f:b};esm_import$node_vm.createContext(b);
try{return $APP.k($APP.k(m4)?$APP.Ab(a):m4)&&esm_import$node_process.stdin.setRawMode(!1),esm_import$node_vm.runInContext("f()",b,{displayErrors:!0,breakOnSigint:!0,microtaskMode:"afterEvaluate"}).then(function(c){var d={f:$APP.k(a)?function(){return c}:function(){var e=$APP.p(c);if($APP.k($APP.Sy(e)))return e.then(function(f){$APP.Dp.o($APP.x(["#\x3cPromise "+$APP.G.h($APP.Xj.o($APP.x([f],0)))+"\x3e"],0));return c});$APP.Qy.o($APP.x([e],0));return c}};esm_import$node_vm.createContext(d);return esm_import$node_vm.runInContext("f()",
d,{displayErrors:!0,breakOnSigint:!0,microtaskMode:"afterEvaluate"})}).finally(function(){return $APP.k($APP.k(m4)?$APP.Ab(a):m4)?esm_import$node_process.stdin.setRawMode(!0):null})}catch(c){return b=c,$APP.k($APP.k(m4)?$APP.Ab(a):m4)&&esm_import$node_process.stdin.setRawMode(!0),Promise.reject(b)}},k4=function(a,b){if($APP.k(function(){var e=$APP.yc(i4);return $APP.k(e)?e:$APP.Dl($APP.yc(j4))}()))return null;$APP.$g(i4,!0);var c=$APP.Cma($APP.yc(j4)),d=function(){try{var e=$APP.zg([$APP.kt,$APP.yc(h4)]);
$APP.Bs(e);try{return $APP.Zma(c)}finally{$APP.Ds()}}catch(f){e=f;if($APP.Qa($APP.Jk(e),"EOF while reading"))return dRa;bRa(c);$APP.Qy.o($APP.x([""+$APP.G.h(e)],0));return eRa}}();if($APP.Fe.j(eRa,d))return l4(b,a);if($APP.Fe.j(dRa,d))return $APP.$g(i4,!1);bRa(c);if($APP.Fe.j($APP.MM,d))return $APP.$g(i4,!1);$APP.Bs($APP.zg([$APP.kt,$APP.yc(h4)]));return cRa(a,function(){return $APP.CGa(d,new $APP.F(null,3,[$APP.S,$APP.yc(h4),$APP.J,$APP.yc($APP.Xs),$APP.Jo,$APP.SA],null))}).then(function(e){var f=
$APP.w.l(e,0,null);e=$APP.w.l(e,1,null);e=$APP.Bg(e);e=$APP.y.j(e,$APP.S);$APP.$g(h4,e);$APP.OX.j($APP.tX,$APP.Yg($APP.yc($APP.sX)));$APP.OX.j($APP.sX,$APP.Yg($APP.yc($APP.rX)));$APP.OX.j($APP.rX,$APP.Yg(f));if($APP.k($APP.k(a)?$APP.Sy(f):a))return f.then(function(g){a.write("#\x3cPromise "+$APP.G.h($APP.Xj.o($APP.x([g],0)))+"\x3e\n");return l4(b,a)});$APP.k(a)&&a.write($APP.nC.o($APP.x([f],0)));return l4(b,a)}).catch(function(e){$APP.Qy.o($APP.x([""+$APP.G.h(e)],0));$APP.OX.j($APP.uX,$APP.Yg(e));
return l4(b,a)}).finally(function(){return $APP.Ds()})},fRa=function(a,b){a.on("line",function(c){$APP.bk.C(j4,$APP.G,c,"\n");return k4(b,a)})},gRa=function(a){return esm_import$node_readline.createInterface({input:a,output:a,completer:aRa})},hRa=function(a){var b=gRa(a);fRa(b,a);a.setNoDelay(!0);return a.on("close",function(){return $APP.Dp.o($APP.x(["Client closed connection."],0))})},dRa=new $APP.B("nbb.impl.repl","eof-while-reading","nbb.impl.repl/eof-while-reading",1743626215),iRa=new $APP.l(null,
"completer*","completer*",-648150376,null),jRa=new $APP.B(null,"init","init",-1875481434),kRa=new $APP.l(null,"get-completions","get-completions",1933789168,null),eRa=new $APP.B("nbb.impl.repl","continue","nbb.impl.repl/continue",-1326808644);var h4=$APP.ak.h($APP.yc($APP.kt)),j4=$APP.ak.h(""),i4=$APP.ak.h(!1),m4,lRa=esm_import$node_process.stdout.isTTY;m4=$APP.k(lRa)?esm_import$node_process.stdin.setRawMode:lRa;var n4=$APP.SX.j($APP.MC,null),o4=function o4(a){switch(arguments.length){case 0:return o4.A();case 1:return o4.h(arguments[0]);default:throw Error(["Invalid arity: ",arguments.length].join(""));}};o4.A=function(){return o4.h(null)};
o4.h=function(a){var b=function(){var d=$APP.ZL.h(a);return $APP.k(d)?d:0}(),c=esm_import$node_net.createServer(hRa);return c.listen(b,"127.0.0.1",function(){var d=c.address(),e=d.address;return $APP.Dp.o($APP.x(["Socket REPL listening on port "+$APP.G.h(d.port)+" on host "+$APP.G.h(e)],0))})};o4.v=1;var p4=function p4(a){switch(arguments.length){case 0:return p4.A();case 1:return p4.h(arguments[0]);default:throw Error(["Invalid arity: ",arguments.length].join(""));}};p4.A=function(){return p4.h(null)};
p4.h=function(a){function b(e){return $APP.zGa(new $APP.A(null,$APP.al,new $APP.A(null,new $APP.A(null,$APP.al,new $APP.A(null,e,null,1,null),2,null),null,1,null),2,null))}$APP.k(m4)&&esm_import$node_process.stdin.setRawMode(!0);var c=$APP.w.l($APP.ZX,0,null),d=$APP.w.l($APP.ZX,1,null);$APP.Dp.o($APP.x(["Welcome to "+$APP.G.h("nbb")+" v"+$APP.G.h($APP.qz())+"!"],0));return b(c).then(function(){return b(d)}).then(jRa.j(a,$APP.Hf)).then(function(){return new Promise(function(e){var f=$APP.k(null)?gRa(null):
esm_import$node_readline.createInterface({input:esm_import$node_process.stdin,output:esm_import$node_process.stdout,completer:aRa});fRa(f,null);f.setPrompt(""+$APP.G.h($APP.yc(h4))+"\x3d\x3e ");f.on("close",e);return f.prompt()})})};p4.v=1;
var mRa=new $APP.F(null,3,[$APP.VZ,$APP.Ms(p4,$APP.VZ,new $APP.F(null,7,[$APP.Q,$APP.VZ,$APP.P,null,$APP.X,$APP.H($APP.rh,new $APP.D(null,1,5,$APP.E,[$APP.iM],null)),$APP.J,"nbb/impl/repl.cljs",$APP.K,194,$APP.M,7,$APP.S,n4],null),n4),kRa,$APP.Ms($Qa,iRa,new $APP.F(null,7,[$APP.Q,iRa,$APP.P,"Given a line, returns a flat vector of completions",$APP.X,$APP.H(new $APP.D(null,1,5,$APP.E,[$APP.Lra],null)),$APP.J,"nbb/impl/repl.cljs",$APP.K,16,$APP.M,7,$APP.S,n4],null),n4),$APP.UZ,$APP.Ms(o4,$APP.UZ,new $APP.F(null,
7,[$APP.Q,$APP.UZ,$APP.P,null,$APP.X,$APP.H($APP.rh,new $APP.D(null,1,5,$APP.E,[$APP.iM],null)),$APP.J,"nbb/impl/repl.cljs",$APP.K,179,$APP.M,7,$APP.S,n4],null),n4)],null);$APP.lz(new $APP.F(null,1,[$APP.it,new $APP.F(null,1,[$APP.MC,mRa],null)],null));