import { $APP, shadow$provide } from "./nbb_core.js";
const shadow_esm_import = function(x) { return import(x) };
var UZa,WZa,XZa,i3,j3,YZa,ZZa,$Za,a_a,b_a,c_a,d_a,e_a,l3,f_a,n3,g_a,h_a,i_a,j_a,p3,q3,r3,k_a,u3,l_a,m_a,n_a,o_a,w3,p_a,q_a,t_a,z3,u_a,v_a,w_a,x_a,y_a,A_a,C_a,D_a,F_a,G3,J_a,L_a,M_a,N_a,O_a,P_a,Q_a,T_a,H3,U_a,V_a,W_a,X_a,Z_a,I3,a0a,b0a,c0a,d0a,e0a,f0a,g0a,j0a,m0a,n0a,o0a,p0a,s0a,t0a,GZa,q5,HZa,IZa,JZa,KZa,NZa,DZa,OZa,s5,PZa,QZa,RZa,SZa,TZa,B_a,H_a,K_a,n5,R_a,BZa,k0a,q0a,r0a,t5,u0a,CZa,v0a,w0a,m5,x0a,y0a,z0a,p5,A0a,B0a,C0a,D0a,E0a,r5,F0a,G0a,H0a,I0a,FZa,J0a,K0a,L0a,v5,M0a,N0a,O0a,P0a,Q0a,R0a,S0a,T0a,
w5,U0a,V0a,EZa,W0a,X0a,Y0a,Z0a,$0a,a1a,b1a,c1a,zZa,d1a,e1a,AZa,f1a,g1a;UZa=function(a){return $APP.De(a)<2?$APP.rl(a):""+$APP.I.h($APP.rl($APP.tj.l(a,0,1)))+$APP.I.h($APP.tj.j(a,1))};WZa=function(a){if(typeof a==="string")return a;a=$APP.cj(a);var b=$APP.wl.j(a,/-/),c=$APP.n(b);b=$APP.p(c);c=$APP.r(c);return $APP.k(VZa.h?VZa.h(b):VZa.call(null,b))?a:$APP.Tg.l($APP.I,b,$APP.pk.j(UZa,c))};
XZa=function(a){var b=function(){var c=function(){var d=$APP.Oe(a);if(d){d=a.displayName;if($APP.k(d))return d;d=a.name;return typeof d==="string"&&$APP.n(d)?d:null}return d}();if($APP.k(c))return c;c=function(){var d=a!=null?a.N&4096||$APP.Yd===a.Ce?!0:!1:!1;return d?$APP.cj(a):d}();if($APP.k(c))return c;c=$APP.Re(a);return $APP.Ze(c)?$APP.R.h(c):null}();return $APP.k(b)?$APP.pl(""+$APP.I.h(b),"$","."):null};i3=function(a){return a instanceof $APP.D||a instanceof $APP.l};
j3=function(a){if($APP.Ze(a))try{var b=$APP.z.j(a,$APP.FN)}catch(c){b=null}else b=null;return b};YZa=function(a){var b=$APP.FN.h($APP.Re(a));if($APP.k(b))return b;b=j3($APP.x.l(a,1,null));if($APP.k(b))return b;b=$APP.x.l(a,0,null);switch(b instanceof $APP.D?b.ca:null){case "\x3e":case "f\x3e":return j3($APP.x.l(a,2,null));case "r\x3e":return a=$APP.x.l(a,2,null),a==null?null:a.key;default:return null}};ZZa=function(a){return setTimeout(a,16)};$Za=function(a,b){return a.Eh-b.Eh};a_a=function(){return null};
b_a=function(a){for(var b=a.length,c=0;;)if(c<b){var d=a[c];d.B?d.B():d.call(null);c+=1}else return null};c_a=function(a,b,c){b.push(c);return a.schedule()};d_a=function(){this.$g=!1};e_a=function(a){if($APP.k(a.cljsIsDirty))return null;a.cljsIsDirty=!0;return k3.queue_render(a)};l3=function(a){if(a!=null&&a.wl!=null)a=a.id;else{var b=l3[$APP.ca(a==null?null:a)];if(b!=null)a=b.h?b.h(a):b.call(null,a);else if(b=l3._,b!=null)a=b.h?b.h(a):b.call(null,a);else throw $APP.Gb("Compiler.get-id",a);}return a};
f_a=function(a,b,c){if(a!=null&&a.qj!=null)a=a.qj(a,b,c);else{var d=f_a[$APP.ca(a==null?null:a)];if(d!=null)a=d.l?d.l(a,b,c):d.call(null,a,b,c);else if(d=f_a._,d!=null)a=d.l?d.l(a,b,c):d.call(null,a,b,c);else throw $APP.Gb("Compiler.parse-tag",a);}return a};
$APP.m3=function(a,b){if(a!=null&&a.oj!=null)a=a.oj(a,b);else{var c=$APP.m3[$APP.ca(a==null?null:a)];if(c!=null)a=c.j?c.j(a,b):c.call(null,a,b);else if(c=$APP.m3._,c!=null)a=c.j?c.j(a,b):c.call(null,a,b);else throw $APP.Gb("Compiler.as-element",a);}return a};
n3=function(a,b,c,d,e){if(a!=null&&a.pj!=null)a=a.pj(a,b,c,d,e);else{var f=n3[$APP.ca(a==null?null:a)];if(f!=null)a=f.O?f.O(a,b,c,d,e):f.call(null,a,b,c,d,e);else if(f=n3._,f!=null)a=f.O?f.O(a,b,c,d,e):f.call(null,a,b,c,d,e);else throw $APP.Gb("Compiler.make-element",a);}return a};
g_a=function(a,b){b.mh=null;var c=o3;o3=b;try{var d=a.B?a.B():a.call(null)}finally{o3=c}a=b.mh;b.se=!1;a:{c=b.Xe;var e=a==null?0:a.length,f=e===(c==null?0:c.length);if(f){for(f=0;;){var g=f===e;if(g){c=g;break a}if(a[f]===c[f])f+=1;else{c=!1;break a}}c=void 0}else c=f}c||b._update_watching(a);return d};h_a=function(a){var b=o3;if(b!=null){var c=b.mh;c==null?b.mh=[a]:c.push(a)}};i_a=function(a,b,c){b=$APP.Ti.l(a.Hb,b,c);a.Hb=b;return a.Xh=null};
j_a=function(a,b){b=$APP.fm.j(a.Hb,b);a.Hb=b;return a.Xh=null};p3=function(a,b,c){var d=a.Xh;d=d==null?a.Xh=$APP.zf(function(q,t,w){q.push(t);q.push(w);return q},[],a.Hb):d;for(var e=d.length,f=0;;)if(f<e){var g=d[f],m=d[f+1];m.D?m.D(g,a,b,c):m.call(null,g,a,b,c);f=2+f}else return null};q3=function(a,b,c,d){$APP.Wc(a,"#object[reagent.ratom."+$APP.I.h(c)+" ");c=o3;o3=null;o3=c;$APP.Bj(d,a,b);return $APP.Wc(a,"]")};
r3=function(a,b,c,d){this.state=a;this.K=b;this.gh=c;this.Hb=d;this.H=2154201088;this.N=114690};k_a=function(a,b,c,d,e){var f=b.Rh;f=f==null?$APP.xg:f;var g=f.j?f.j(c,null):f.call(null,c,null);if(g!=null)return $APP.wc(g);if(o3==null)return a.B?a.B():a.call(null);g=function(){function q(t){var w=$APP.fm.j(b.Rh,c);b.Rh=w;d!=null&&(d.eg=null);return e!=null?e.h?e.h(t):e.call(null,t):null}return s3.l?s3.l(a,m5,q):s3.call(null,a,m5,q)}();var m=$APP.wc(g);b.Rh=$APP.Ti.l(f,c,g);d!=null&&(d.eg=g);return m};
u3=function(a,b){this.f=a;this.uf=b;this.eg=null;this.H=2153807872;this.N=0};l_a=function(a,b){return new u3(a,b)};m_a=function(a,b){var c=l_a(a,b);a=function(){function d(){return c.Ja(null)}return s3.l?s3.l(d,n5,!0):s3.call(null,d,n5,!0)}();$APP.wc(a);return a};n_a=function(a,b){this.Mb=a;this.path=b;this.Hb=this.state=this.eg=null;this.H=2153807872;this.N=114690};o_a=function(a){a=a.destroy;return a==null?null:a.B?a.B():a.call(null)};
w3=function(a){if(a!=null&&a.Sh!=null)a=a.Sh(a);else{var b=w3[$APP.ca(a==null?null:a)];if(b!=null)a=b.h?b.h(a):b.call(null,a);else if(b=w3._,b!=null)a=b.h?b.h(a):b.call(null,a);else throw $APP.Gb("IDisposable.dispose!",a);}return a};p_a=function(a,b,c,d){return a._handle_change(b,c,d)};q_a=function(a){this.f=a;this.state=null;this.se=!0;this.Ji=!1;this.nh=this.Ud=this.Hb=this.Xe=null;this.H=2153807872;this.N=114690};
$APP.y3=function(){for(;;){var a=x3;if(a==null)return null;x3=null;for(var b=a.length,c=0;;)if(c<b)a[c]._queued_run(),c+=1;else break}};t_a=function(a,b){var c=r_a,d=s_a,e=g_a(a,d);d.Xe!=null&&(s_a=s3(null),d._set_opts(c),d.f=a,d.Ud=function(){return e_a.h?e_a.h(b):e_a.call(null,b)},b.cljsRatom=d);return e};
z3=function(a,b){var c=b.argv;if(c==null){c=$APP.F;a=a.constructor;a:{for(var d=$APP.Na(b),e=d.length,f=$APP.xg,g=0;;)if(g<e){var m=d[g];f=$APP.Ti.l(f,$APP.Cj.h(m),$APP.Ra(b,m));g+=1}else{b=f;break a}b=void 0}b=new $APP.E(null,2,5,c,[a,b],null)}else b=c;return b};u_a=function(a){var b;if(b=$APP.Oe(a))a=a==null?null:a.prototype,b=(a==null?null:a.ve)!=null;return b};v_a=function(a){var b;if(b=$APP.Oe(a))a=a==null?null:a.prototype,b=(a==null?null:a.render)!=null;return b};
w_a=function(a,b){for(;;){var c=a.ve,d=a.ik===!0?c.call(a,a):function(){var e=z3(a,a.props);switch($APP.De(e)){case 1:return c.call(a);case 2:return c.call(a,$APP.x.j(e,1));case 3:return c.call(a,$APP.x.j(e,1),$APP.x.j(e,2));case 4:return c.call(a,$APP.x.j(e,1),$APP.x.j(e,2),$APP.x.j(e,3));case 5:return c.call(a,$APP.x.j(e,1),$APP.x.j(e,2),$APP.x.j(e,3),$APP.x.j(e,4));default:return c.apply(a,$APP.Uu.h(e).slice(1))}}();if($APP.af(d))return $APP.m3(b,d);if($APP.hf(d))a.ve=u_a(d)?function(e,f,g,m,q){return function(){function t(A){var C=
null;if(arguments.length>0){C=0;for(var v=Array(arguments.length-0);C<v.length;)v[C]=arguments[C+0],++C;C=new $APP.ee(v,0,null)}return w.call(this,C)}function w(A){return $APP.m3(f,$APP.Tg.l($APP.RE,q,A))}t.A=0;t.C=function(A){A=$APP.n(A);return w(A)};t.o=w;return t}()}(a,b,c,null,d):d;else return d}};x_a=function(a,b){var c=A3;A3=a;try{return w_a(a,b)}finally{A3=c}};
y_a=function(a,b){switch(a instanceof $APP.D?a.ca:null){case "getDefaultProps":throw Error("getDefaultProps not supported");case "getDerivedStateFromProps":return function(c,d){var e=b.call,f=c.argv;f!=null&&(c=$APP.x.l(f,1,null),c=$APP.Ze(c)?c:null);return e.call(b,null,c,d)};case "getInitialState":return function(c){var d=c.kk;d=d!=null?d:c.kk=B3.h(null);return $APP.Xg(d,b.call(c,c))};case "getSnapshotBeforeUpdate":return function(c,d){return b.call(this,this,z3(this,c),d)};case "componentWillReceiveProps":return function(c){return b.call(this,
this,z3(this,c))};case "UNSAFE_componentWillReceiveProps":return function(c){return b.call(this,this,z3(this,c))};case "shouldComponentUpdate":return function(c){if($APP.k(!1))return!1;var d=this.props.argv,e=c.argv,f=d==null||e==null;if(b==null){if(f)return f;try{return $APP.Si.j(d,e)}catch(g){return!1}}else return f?b.call(this,this,z3(this,this.props),z3(this,c)):b.call(this,this,d,e)};case "componentWillUpdate":return function(c,d){return b.call(this,this,z3(this,c),d)};case "UNSAFE_componentWillUpdate":return function(c,
d){return b.call(this,this,z3(this,c),d)};case "componentDidUpdate":return function(c,d,e){return b.call(this,this,z3(this,c),d,e)};case "componentWillMount":return function(){return b.call(this,this)};case "UNSAFE_componentWillMount":return function(){return b.call(this,this)};case "componentDidMount":return function(){return b.call(this,this)};case "componentWillUnmount":return function(){var c=$APP.Ra(this,"cljsRatom");c!=null&&w3(c);this.cljsIsDirty=!1;return b==null?null:b.call(this,this)};case "componentDidCatch":return function(c,
d){return b.call(this,this,c,d)};default:return null}};A_a=function(a){return $APP.zf(function(b,c,d){return $APP.Ti.l(b,$APP.Cj.h(z_a(c)),d)},$APP.xg,a)};
C_a=function(a,b){var c=function(){var g=p5.h(a);return $APP.k(g)?g:q5.h(a)}(),d=p5.h(a)==null,e=function(){var g=r5.h(a);if($APP.k(g))return g;g=XZa(c);return $APP.k(g)?g:""+$APP.I.h($APP.Aq.h("reagent"))}(),f=$APP.zf(function(g,m,q){var t=$APP.Ti.l,w=y_a(m,q);return t.call($APP.Ti,g,m,$APP.k(w)?w:q)},$APP.xg,a);return $APP.Ti.o(f,r5,e,$APP.y([zZa,d,p5,c,q5,function(){var g=this;if($APP.F3)return x_a(g,b);var m=$APP.Ra(g,"cljsRatom");g.cljsIsDirty=!1;return m==null?t_a(function(){return x_a(g,b)},
g):m._run(!1)}],0))};D_a=function(a){return $APP.zf(function(b,c,d){c=$APP.cj(c);b[c]=d;return b},{},a)};F_a=function(a,b){a=A_a(a);a=$APP.em.o($APP.y([E_a,a],0));return C_a(a,b)};
G3=function(a,b){function c(m,q,t){$APP.aD.nbb$internal$react.Component.call(this,m,q,t);$APP.k(g)&&(g.j?g.j(this,m):g.call(null,this,m));$APP.k(f)&&(this.state=f.h?f.h(this):f.call(null,this));this.Eh=G_a+=1;return this}a=F_a(a,b);b=D_a($APP.Tg.o($APP.fm,a,r5,AZa,$APP.nx,$APP.y([q5,p5,I_a],0)));var d=D_a($APP.Ui(a,I_a)),e=r5.h(a),f=AZa.h(a),g=$APP.nx.h(a);$APP.Xa(c.prototype,$APP.aD.nbb$internal$react.Component.prototype,b);$APP.k(q5.h(a))&&(c.prototype.render=q5.h(a));$APP.k(p5.h(a))&&(c.prototype.ve=
p5.h(a));$APP.k(zZa.h(a))&&(c.prototype.ik=zZa.h(a));$APP.Xa(c,$APP.aD.nbb$internal$react.Component,d);$APP.k(e)&&(c.displayName=e,c.Gg=e,c.hk=function(m){return $APP.Wc(m,e)},Object.defineProperty(c,"name",{value:e,writable:!1}));c.Ci=!0;return c.prototype.constructor=c};J_a=function(a,b,c){a=l3(a);return b[a]=c};L_a=function(a,b){var c=$APP.Ra(a,l3(b));c==null?u_a(a)?a=J_a(b,a,a):(c=$APP.Re(a),c=$APP.Ti.l(c,BZa,a),c=G3(c,b),a=J_a(b,a,c)):a=c;return a};
M_a=function(a,b){for(;;){var c=b.ve,d=b.argv,e=$APP.Tg.j(c,d);if($APP.af(e))return $APP.m3(a,e);if($APP.hf(e))b.ve=u_a(e)?function(f,g,m,q,t,w){return function(){function A(v){var H=null;if(arguments.length>0){H=0;for(var P=Array(arguments.length-0);H<P.length;)P[H]=arguments[H+0],++H;H=new $APP.ee(P,0,null)}return C.call(this,H)}function C(v){return $APP.m3(f,$APP.Tg.l($APP.RE,w,v))}A.A=0;A.C=function(v){v=$APP.n(v);return C(v)};A.o=C;return A}()}(a,b,c,null,d,e):e;else return e}};
N_a=function(a,b){var c=A3;A3=b;try{return M_a(a,b)}finally{A3=c}};
O_a=function(a,b){if($APP.F3)return N_a(a,b);var c=b.argv,d=b.ve;b=$APP.aD.nbb$internal$react.useState(0);$APP.x.l(b,0,null);var e=$APP.x.l(b,1,null),f=$APP.aD.nbb$internal$react.useRef();$APP.k(f.current)||function(){var m={forceUpdate:function(){return e.h?e.h($APP.qe):e.call(null,$APP.qe)}};m.Eh=G_a+=1;m.constructor=d;m.ve=d;return f.current=m}();var g=f.current;b=$APP.Ra(g,"cljsRatom");$APP.aD.nbb$internal$react.useEffect(function(){return function(){var m=$APP.Ra(g,"cljsRatom");return m==null?
null:w3(m)}},[]);g.argv=c;g.cljsIsDirty=!1;return b==null?t_a(function(){return N_a(a,g)},g):b._run(!1)};P_a=function(a,b){a=a.argv;b=b.argv;try{return $APP.u.j(a,b)}catch(c){return!1}};Q_a=function(a,b){function c(e){return O_a(a,e)}var d=$APP.Ra(b,l3(a));if($APP.k(d))return d;d=XZa(b);c.displayName=d;Object.defineProperty(c,"name",{value:d,writable:!1});d=$APP.aD.nbb$internal$react.memo(c,P_a);J_a(a,b,d);return d};
T_a=function(a,b,c,d){var e=$APP.yg($APP.xg);e=$APP.z.j(e,CZa);if(a===document.activeElement&&$APP.qf(S_a,a.type)&&typeof b==="string"&&typeof c==="string"){var f=a.value;if($APP.Si.j(f,c))return k3.add_after_render(function(){return H3.h?H3.h(d):H3.call(null,d)});c=$APP.De(f)-a.selectionStart;c=$APP.De(b)-c;d.Hg=b;a.value=b;$APP.Oe(e)&&(e.h?e.h(b):e.call(null,b));a.selectionStart=c;return a.selectionEnd=c}d.Hg=b;a.value=b;return $APP.Oe(e)?e.h?e.h(b):e.call(null,b):null};
H3=function(a){if($APP.k(a.Dh)){a.Ei=!1;var b=a.jk,c=a.Hg,d=a.Kh;return $APP.Si.j(b,c)?T_a(d,b,c,a):null}return null};U_a=function(a,b,c){a.Hg=c.target.value;$APP.k(a.Ei)||(a.Ei=!0,k3.add_after_render(function(){return H3(a)}));return b.h?b.h(c):b.call(null,c)};
V_a=function(a){var b=A3;if($APP.k(function(){var f=a!=null;return f?(f=a.hasOwnProperty("onChange"),$APP.k(f)?a.hasOwnProperty("value"):f):f}())){var c=a.value;c=c==null?"":c;var d=a.onChange,e=a.ref;$APP.k(b.Dh)||(b.Dh=!0,b.Hg=c);$APP.k(b.rj)||(b.rj=$APP.Oe(e)?function(f){b.Kh=f;return e.h?e.h(f):e.call(null,f)}:$APP.k($APP.k(e)?e.hasOwnProperty("current"):e)?function(f){b.Kh=f;return e.current=f}:function(f){return b.Kh=f});b.jk=c;delete a.value;a.defaultValue=c;a.onChange=function(f){return U_a(b,
d,f)};a.ref=b.rj}};W_a=function(a){this.tag=a;this.className=this.id=null};X_a=function(a,b){return a.hasOwnProperty(b)?$APP.Ra(a,b):null};Z_a=function(a,b,c){if(i3(b)){var d=X_a(Y_a,$APP.cj(b));d==null?(d=WZa(b),b=$APP.cj(b),b=Y_a[b]=d):b=d}c=I3.h?I3.h(c):I3.call(null,c);a[b]=c;return a};
I3=function(a){return"object"!==$APP.ca(a)?a:i3(a)?$APP.cj(a):$APP.Ze(a)?$APP.zf(Z_a,{},a):$APP.Ve(a)?$APP.PG(a):$APP.hf(a)?function(){function b(d){var e=null;if(arguments.length>0){e=0;for(var f=Array(arguments.length-0);e<f.length;)f[e]=arguments[e+0],++e;e=new $APP.ee(f,0,null)}return c.call(this,e)}function c(d){return $APP.Tg.j(a,d)}b.A=0;b.C=function(d){d=$APP.n(d);return c(d)};b.o=c;return b}():$APP.PG(a)};
a0a=function(a,b,c){if(i3(b)){var d=X_a($_a,$APP.cj(b));d==null?(d=WZa(b),b=$APP.cj(b),b=$_a[b]=d):b=d}c=I3(c);a[b]=c;return a};
b0a=function(a){return"object"!==$APP.ca(a)?a:i3(a)?$APP.cj(a):$APP.Ze(a)?$APP.zf(a0a,{},a):$APP.Ve(a)?$APP.PG(a):$APP.hf(a)?function(){function b(d){var e=null;if(arguments.length>0){e=0;for(var f=Array(arguments.length-0);e<f.length;)f[e]=arguments[e+0],++e;e=new $APP.ee(f,0,null)}return c.call(this,e)}function c(d){return $APP.Tg.j(a,d)}b.A=0;b.C=function(d){d=$APP.n(d);return c(d)};b.o=c;return b}():$APP.PG(a)};
c0a=function(a,b,c,d,e){switch($APP.De(b)-e){case 0:return $APP.aD.nbb$internal$react.createElement(c,d);case 1:return $APP.aD.nbb$internal$react.createElement(c,d,$APP.m3(a,$APP.x.l(b,e,null)));default:return $APP.aD.nbb$internal$react.createElement.apply(null,$APP.zf(function(f,g,m){g>=e&&f.push($APP.m3(a,m));return f},[c,d],b))}};d0a=function(a,b,c,d){this.tag=a;this.id=b;this.className=c;this.rk=d};
e0a=function(a,b,c){a=L_a(a,c);c={};c.argv=b;b=YZa(b);b!=null&&(c.key=b);return $APP.aD.nbb$internal$react.createElement(a,c)};f0a=function(a,b,c,d){var e={};e.ve=a;e.argv=$APP.vl.j(b,c);b=YZa(b);b!=null&&(e.key=b);return $APP.aD.nbb$internal$react.createElement(Q_a(d,a),e)};g0a=function(a,b,c){return v_a(a)?e0a(a,b,c):f0a(a,b,1,c)};
j0a=function(a,b){a=X_a(h0a,b);if(a==null){var c=$APP.r($APP.oj(i0a,$APP.cj(b)));a=$APP.x.l(c,0,null);var d=$APP.x.l(c,1,null);c=$APP.x.l(c,2,null);c=c==null?null:$APP.pl(c,/\./," ");var e=$APP.Si.j(-1,a.indexOf("-"));a=new d0a(a,d,c,e);return h0a[b]=a}return a};
m0a=function(a,b,c,d){var e=a.tag,f=$APP.x.l(b,c,null),g=f==null||$APP.Ze(f),m=function(){var w=g?f:null;var A=$APP.Gu.h(w);A=$APP.k(A)?$APP.Ti.l(w,$APP.Gu,J3.h(A)):w;var C=a.id;w=a.className;C=C!=null&&$APP.rt.h(A)==null?$APP.Ti.l(A,$APP.rt,C):A;if($APP.k(w)){var v=$APP.Ti.l,H=J3.j,P=$APP.Gu.h(A);A=$APP.k(P)?P:DZa.h(A);w=v.call($APP.Ti,C,$APP.Gu,H.call(J3,w,A))}else w=C;w=$APP.k(a.rk)?b0a(w):I3(w);return $APP.k(w)?w:{}}();c+=g?1:0;a:switch(e){case "input":case "textarea":var q=!0;break a;default:q=
!1}if(q){q=j3(f);var t=function(){var w=d.xl;if($APP.k(w))return w;w=G3(l0a,d);return d.xl=w}();return $APP.m3(d,$APP.Qe(new $APP.E(null,6,5,$APP.F,[t,b,e,m,c,d],null),$APP.em.o($APP.y([$APP.k(q)?new $APP.G(null,1,[$APP.FN,q],null):null,$APP.Re(b)],0))))}q=j3($APP.Re(b));q!=null&&(m.key=q);return n3(d,b,e,m,c)};n0a=function(a,b){return $APP.Uu.h($APP.pk.j(function(c){return $APP.m3(b,c)},a))};
o0a=function(a,b,c){b==null&&console.error("vec-to-elem",$APP.Wj.o($APP.y([a],0)));var d=$APP.x.l(a,0,null);switch(d instanceof $APP.D?d.ca:null){case "\x3e":return c=$APP.x.l(a,1,null),m0a(new d0a(c,null,null,null),a,2,b);case "r\x3e":c=$APP.x.l(a,1,null);d=$APP.x.l(a,2,null);d=$APP.k(d)?d:{};var e=j3($APP.Re(a));e!=null&&(d.key=e);return n3(b,a,c,d,3);case "f\x3e":return f0a($APP.x.l(a,1,null),a,2,b);case "\x3c\x3e":return d=$APP.x.l(a,1,null),c=d==null||$APP.Ze(d),d=I3(c?d:null),d=$APP.k(d)?d:
{},c=1+(c?1:0),e=YZa(a),e!=null&&(d.key=e),n3(b,a,$APP.aD.nbb$internal$react.Fragment,d,c);default:if(i3(d)||typeof d==="string")a:{for(;;){c=$APP.x.l(a,0,null);d=$APP.cj(c);e=d.indexOf("\x3e");switch(e){case -1:b=m0a(f_a(b,d,c),a,1,b);break a;case 0:b=null;break a;default:a=$APP.Qe(new $APP.E(null,2,5,$APP.F,[$APP.tj.l(d,0,e),$APP.Ti.l($APP.Qe(a,null),0,$APP.tj.j(d,e+1))],null),$APP.Re(a));continue}break}b=void 0}else b=d instanceof W_a?m0a(d,a,1,b):c.l?c.l(d,a,b):c.call(null,d,a,b);return b}};
p0a=function(a,b,c,d,e){this.Nc=a;this.id=b;this.Hi=c;this.Tg=d;this.el=e;this.H=393216;this.N=0};s0a=function(a){var b=$APP.Aq.h("reagent-compiler"),c=$APP.k(EZa.h(a))?g0a:e0a,d=$APP.z.l(a,FZa,j0a);return new p0a(a,b,c,d,$APP.xg)};t0a=function(a){return new W_a(a)};GZa=new $APP.l(null,"-generation","-generation",627658965,null);q5=new $APP.D(null,"render","render",-1408033454);HZa=new $APP.l(null,"on-set","on-set",1499578057,null);
IZa=new $APP.l("reagent.ratom","make-reaction","reagent.ratom/make-reaction",272608527,null);JZa=new $APP.l(null,"dispose!","dispose!",-395693497,null);KZa=new $APP.l("reagent.ratom","-destroy","reagent.ratom/-destroy",-1284026419,null);NZa=new $APP.D(null,"componentWillUnmount","componentWillUnmount",1573788814);DZa=new $APP.D(null,"className","className",-1983287057);OZa=new $APP.l(null,"-tracking?","-tracking?",-1106885352,null);s5=new $APP.l(null,"with-let","with-let",-1310113408,null);
PZa=new $APP.l(null,"with-let-values","with-let-values",1929572375,null);QZa=new $APP.l(null,"create-class","create-class",-665911586,null);RZa=new $APP.D(null,"childContextTypes","childContextTypes",578717991);SZa=new $APP.l(null,"class2","class2",-1266396392,null);TZa=new $APP.l(null,"class1","class1",-1905977651,null);B_a=new $APP.l(null,"auto-run","auto-run",-696035332,null);H_a=new $APP.l(null,"-set-ratom-generation!","-set-ratom-generation!",-1545989828,null);
K_a=new $APP.l(null,"-destroy","-destroy",-557272508,null);n5=new $APP.D(null,"auto-run","auto-run",1958400437);R_a=new $APP.l(null,"track-console","track-console",17070495,null);BZa=new $APP.D(null,"reagent-render","reagent-render",-985383853);k0a=new $APP.D(null,"contextTypes","contextTypes",-2023853910);q0a=new $APP.l(null,"create-compiler","create-compiler",1059333141,null);r0a=new $APP.l(null,"props","props",2093813254,null);t5=new $APP.l(null,"reaction","reaction",2131401315,null);
u0a=new $APP.D(null,"on-set","on-set",-140953470);CZa=new $APP.D(null,"on-write","on-write",31519475);v0a=new $APP.l(null,"reactive?","reactive?",1213887990,null);w0a=new $APP.l(null,"destroy__40306__auto__","destroy__40306__auto__",1526978455,null);m5=new $APP.D(null,"on-dispose","on-dispose",2105306360);$APP.u5=new $APP.l(null,"compiler","compiler",1372604796,null);x0a=new $APP.l("reagent.ratom","-destroy!","reagent.ratom/-destroy!",-337873850,null);
y0a=new $APP.l(null,"-destroy!","-destroy!",143253949,null);z0a=new $APP.l("sci.configs.reagent.reagent","error","sci.configs.reagent.reagent/error",1433174531,null);p5=new $APP.D(null,"reagentRender","reagentRender",-358306383);A0a=new $APP.l(null,"cursor","cursor",-1642498285,null);B0a=new $APP.l(null,"make-reaction","make-reaction",1935680112,null);C0a=new $APP.D(null,"contextType","contextType",1033066077);D0a=new $APP.D(null,"component-did-update","component-did-update",-1468549173);
E0a=new $APP.l(null,"src","src",-10544524,null);r5=new $APP.D(null,"displayName","displayName",-809144601);F0a=new $APP.D(null,"display-name","display-name",694513143);G0a=new $APP.l("sci.configs.reagent.reagent","reaction","sci.configs.reagent.reagent/reaction",-1324858361,null);H0a=new $APP.l(null,"others","others",-569561186,null);I0a=new $APP.D(null,"getDerivedStateFromProps","getDerivedStateFromProps",-991834739);FZa=new $APP.D(null,"parse-tag","parse-tag",1427313738);
J0a=new $APP.l(null,"destroy","destroy",796871122,null);K0a=new $APP.D(null,"shouldComponentUpdate","shouldComponentUpdate",1795750960);L0a=new $APP.l(null,"-ratom-generation","-ratom-generation",-176468250,null);v5=new $APP.l(null,"adapt-react-class","adapt-react-class",1221068673,null);M0a=new $APP.l(null,"track","track",1836319014,null);N0a=new $APP.l(null,".hasOwnProperty",".hasOwnProperty",-1264659034,null);O0a=new $APP.l(null,"reagent.debug","reagent.debug",1010511129,null);
P0a=new $APP.l(null,"reactify-component","reactify-component",-882526483,null);Q0a=new $APP.l("js","console","js/console",-1426368245,null);R0a=new $APP.l(null,"sci.configs.reagent.reagent","sci.configs.reagent.reagent",94604865,null);S0a=new $APP.D(null,"no-cache","no-cache",1588056370);T0a=new $APP.l("cljs.core","zero?","cljs.core/zero?",-341242858,null);w5=new $APP.l(null,"track!","track!",-516308489,null);U0a=new $APP.l(null,".error",".error",1756007195,null);
V0a=new $APP.l("reagent.debug","-tracking?","reagent.debug/-tracking?",409956583,null);EZa=new $APP.D(null,"function-components","function-components",1492814963);W0a=new $APP.l("reagent.ratom","reactive?","reagent.ratom/reactive?",-358553475,null);X0a=new $APP.l(null,"as-element","as-element",-2139409597,null);Y0a=new $APP.l(null,"make-track","make-track",-1388299455,null);Z0a=new $APP.l("reagent.debug","track-console","reagent.debug/track-console",-1553126476,null);
$0a=new $APP.l(null,"on-dispose","on-dispose",-549129409,null);a1a=new $APP.D(null,"component-will-unmount","component-will-unmount",-2058314698);b1a=new $APP.l("reagent.ratom","with-let-values","reagent.ratom/with-let-values",-575838306,null);c1a=new $APP.l(null,"-ratom-context","-ratom-context",1646839514,null);zZa=new $APP.D(null,"cljsLegacyRender","cljsLegacyRender",-1527295613);d1a=new $APP.l("sci.configs.reagent.reagent","with-let","sci.configs.reagent.reagent/with-let",65759084,null);
e1a=new $APP.l(null,"class-names","class-names",-1397320704,null);AZa=new $APP.D(null,"getInitialState","getInitialState",1541760916);f1a=new $APP.D(null,"getDerivedStateFromError","getDerivedStateFromError",166658477);g1a=new $APP.l(null,"create-element","create-element",1833774591,null);var A1a=$APP.Zj.h(null),B1a=function(){var a={};a.warn=function(){function b(d){var e=null;if(arguments.length>0){e=0;for(var f=Array(arguments.length-0);e<f.length;)f[e]=arguments[e+0],++e;e=new $APP.ee(f,0,null)}return c.call(this,e)}function c(d){return $APP.ak.o(A1a,$APP.cm,new $APP.E(null,1,5,$APP.F,[$APP.IGa],null),$APP.Wf,$APP.y([$APP.Tg.j($APP.I,d)],0))}b.A=0;b.C=function(d){d=$APP.n(d);return c(d)};b.o=c;return b}();a.error=function(){function b(d){var e=null;if(arguments.length>0){e=0;for(var f=
Array(arguments.length-0);e<f.length;)f[e]=arguments[e+0],++e;e=new $APP.ee(f,0,null)}return c.call(this,e)}function c(d){return $APP.ak.o(A1a,$APP.cm,new $APP.E(null,1,5,$APP.F,[$APP.aq],null),$APP.Wf,$APP.y([$APP.Tg.j($APP.I,d)],0))}b.A=0;b.C=function(d){d=$APP.n(d);return c(d)};b.o=c;return b}();return a}();var C1a,VZa,J3;C1a=typeof window!=="undefined"&&window.document!=null;$APP.F3=!1;VZa=new $APP.Wi(null,new $APP.G(null,2,["aria",null,"data",null],null),null);J3=function J3(a){switch(arguments.length){case 0:return J3.B();case 1:return J3.h(arguments[0]);case 2:return J3.j(arguments[0],arguments[1]);default:for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return J3.o(arguments[0],arguments[1],2<c.length?new $APP.ee(c.slice(2),0,null):null)}};J3.B=function(){return null};
J3.h=function(a){return $APP.Ve(a)?(a=$APP.ho.j(function(b){return $APP.k(b)?i3(b)?$APP.cj(b):b:null},a),$APP.n(a)?$APP.Un.j(" ",a):null):i3(a)?$APP.cj(a):a};J3.j=function(a,b){return $APP.k(a)?$APP.k(b)?""+$APP.I.h(J3.h(a))+" "+$APP.I.h(J3.h(b)):J3.h(a):J3.h(b)};J3.o=function(a,b,c){return $APP.yf.l(J3,J3.j(a,b),c)};J3.C=function(a){var b=$APP.p(a),c=$APP.r(a);a=$APP.p(c);c=$APP.r(c);return this.o(b,a,c)};J3.A=2;var G_a=0,D1a=C1a?function(){var a=window;return function(){var b=a.requestAnimationFrame;if($APP.k(b))return b;b=a.webkitRequestAnimationFrame;if($APP.k(b))return b;b=a.mozRequestAnimationFrame;if($APP.k(b))return b;b=a.msRequestAnimationFrame;return $APP.k(b)?b:ZZa}().bind(a)}():ZZa;$APP.h=d_a.prototype;$APP.h.flush_after_render=function(){var a=this.rg;if(a==null)return null;this.rg=null;return b_a(a)};
$APP.h.queue_render=function(a){this.componentQueue==null&&(this.componentQueue=[]);return c_a(this,this.componentQueue,a)};$APP.h.schedule=function(){function a(){return b.run_queues()}var b=this;if(this.$g)return null;this.$g=!0;return D1a.h?D1a.h(a):D1a.call(null,a)};$APP.h.flush_before_flush=function(){var a=this.ug;if(a==null)return null;this.ug=null;return b_a(a)};$APP.h.flush_queues=function(){this.flush_before_flush();a_a();this.flush_render();return this.flush_after_render()};
$APP.h.run_queues=function(){this.$g=!1;return this.flush_queues()};$APP.h.add_before_flush=function(a){this.ug==null&&(this.ug=[]);return c_a(this,this.ug,a)};$APP.h.add_after_render=function(a){this.rg==null&&(this.rg=[]);return c_a(this,this.rg,a)};$APP.h.flush_render=function(){var a=this.componentQueue;if(a==null)return null;this.componentQueue=null;a:{a.sort($Za);for(var b=a.length,c=0;;)if(c<b){var d=a[c];d.cljsIsDirty===!0&&d.forceUpdate();c+=1}else{a=null;break a}a=void 0}return a};
var k3=new d_a;var o3;$APP.Zj.h(0);var x3=null;$APP.h=r3.prototype;$APP.h.V=function(a,b,c){return q3(b,c,"RAtom",new $APP.G(null,1,[$APP.Ly,this.Ja(null)],null))};$APP.h.W=function(){return this.K};$APP.h.ba=function(){return $APP.na(this)};$APP.h.R=function(a,b){return this===b};$APP.h.uc=function(a,b){a=this.state;this.state=b;this.Hb!=null&&p3(this,a,b);return b};$APP.h.Ff=function(a,b){return this.uc(null,b.h?b.h(this.state):b.call(null,this.state))};
$APP.h.Gf=function(a,b,c){return this.uc(null,b.j?b.j(this.state,c):b.call(null,this.state,c))};$APP.h.Hf=function(a,b,c,d){return this.uc(null,b.l?b.l(this.state,c,d):b.call(null,this.state,c,d))};$APP.h.If=function(a,b,c,d,e){return this.uc(null,$APP.Tg.O(b,this.state,c,d,e))};$APP.h.qe=function(a,b,c){return p3(this,b,c)};$APP.h.Fe=function(a,b,c){return i_a(this,b,c)};$APP.h.Ge=function(a,b){return j_a(this,b)};$APP.h.Z=function(a,b){return new r3(this.state,b,this.gh,this.Hb)};
$APP.h.Ja=function(){h_a(this);return this.state};var B3=function B3(a){switch(arguments.length){case 1:return B3.h(arguments[0]);default:for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return B3.o(arguments[0],1<c.length?new $APP.ee(c.slice(1),0,null):null)}};B3.h=function(a){return new r3(a,null,null,null)};B3.o=function(a,b){var c=$APP.yg(b);b=$APP.z.j(c,$APP.zj);c=$APP.z.j(c,$APP.Qoa);return new r3(a,b,c,null)};
B3.C=function(a){var b=$APP.p(a);a=$APP.r(a);return this.o(b,a)};B3.A=1;u3.prototype.Ja=function(){var a=this,b=a.eg;return b==null?k_a(function(){return $APP.Tg.j(a.f,a.uf)},a.f,a.uf,this,null):$APP.wc(b)};u3.prototype.R=function(a,b){return b instanceof u3&&$APP.u.j(this.f,b.f)&&$APP.u.j(this.uf,b.uf)};u3.prototype.ba=function(){return $APP.Zd(new $APP.E(null,2,5,$APP.F,[this.f,this.uf],null))};
u3.prototype.V=function(a,b,c){return q3(b,c,"Track",new $APP.G(null,2,[$APP.Ly,this.Ja(null),$APP.aU,this.f],null))};var P3=function P3(a){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return P3.o(arguments[0],1<c.length?new $APP.ee(c.slice(1),0,null):null)};P3.o=function(a,b){return m_a(a,b)};P3.A=1;P3.C=function(a){var b=$APP.p(a);a=$APP.r(a);return this.o(b,a)};$APP.h=n_a.prototype;
$APP.h._peek=function(){var a=o3;o3=null;try{return this.Ja(null)}finally{o3=a}};$APP.h._set_state=function(a,b){if(a===b)return null;this.state=b;return this.Hb!=null?p3(this,a,b):null};$APP.h.V=function(a,b,c){return q3(b,c,"RCursor",new $APP.G(null,2,[$APP.Ly,this.Ja(null),$APP.es,this.path],null))};$APP.h.ba=function(){return $APP.Zd(new $APP.E(null,2,5,$APP.F,[this.Mb,this.path],null))};$APP.h.R=function(a,b){return b instanceof n_a&&$APP.u.j(this.path,b.path)&&$APP.u.j(this.Mb,b.Mb)};
$APP.h.uc=function(a,b){this._set_state(this.state,b);(this.Mb!=null?this.Mb.H&32768||$APP.Yd===this.Mb.Ae||(this.Mb.H?0:$APP.Eb($APP.vc,this.Mb)):$APP.Eb($APP.vc,this.Mb))?$APP.u.j(this.path,$APP.nh)?$APP.Xg(this.Mb,b):$APP.ak.D(this.Mb,$APP.ko,this.path,b):this.Mb.j?this.Mb.j(this.path,b):this.Mb.call(null,this.path,b);return b};$APP.h.Ff=function(a,b){a=this.uc;var c=this._peek();b=b.h?b.h(c):b.call(null,c);return a.call(this,null,b)};
$APP.h.Gf=function(a,b,c){a=this.uc;var d=this._peek();b=b.j?b.j(d,c):b.call(null,d,c);return a.call(this,null,b)};$APP.h.Hf=function(a,b,c,d){a=this.uc;var e=this._peek();b=b.l?b.l(e,c,d):b.call(null,e,c,d);return a.call(this,null,b)};$APP.h.If=function(a,b,c,d,e){return this.uc(null,$APP.Tg.O(b,this._peek(),c,d,e))};$APP.h.qe=function(a,b,c){return p3(this,b,c)};$APP.h.Fe=function(a,b,c){return i_a(this,b,c)};$APP.h.Ge=function(a,b){return j_a(this,b)};
$APP.h.Ja=function(){var a=this,b=this,c=a.state,d=function(){var e=a.eg;return e==null?k_a((a.Mb!=null?a.Mb.H&32768||$APP.Yd===a.Mb.Ae||(a.Mb.H?0:$APP.Eb($APP.vc,a.Mb)):$APP.Eb($APP.vc,a.Mb))?function(){return $APP.Zn.j($APP.wc(a.Mb),a.path)}:function(){return a.Mb.h?a.Mb.h(a.path):a.Mb.call(null,a.path)},a.Mb,a.path,b,null):$APP.wc(e)}();b._set_state(c,d);return d};$APP.h=q_a.prototype;$APP.h._peek_at=function(){var a=o3;o3=null;try{return this.Ja(null)}finally{o3=a}};
$APP.h._handle_change=function(a,b,c){return b===c||this.se?null:this.Ud==null?(this.se=!0,x3==null&&(x3=[],k3.$g===!1&&k3.schedule()),x3.push(this)):this.Ud===!0?this._run(!1):this.Ud.h?this.Ud.h(this):this.Ud.call(null,this)};
$APP.h._update_watching=function(a){var b=$APP.aj(a),c=$APP.aj(this.Xe);this.Xe=a;a=$APP.n($APP.iV.j(b,c));for(var d=null,e=0,f=0;;)if(f<e){var g=d.S(null,f);$APP.hd(g,this,p_a);f+=1}else if(a=$APP.n(a))d=a,$APP.bf(d)?(a=$APP.Cd(d),f=$APP.Dd(d),d=a,e=$APP.De(a),a=f):(a=$APP.p(d),$APP.hd(a,this,p_a),a=$APP.r(d),d=null,e=0),f=0;else break;b=$APP.n($APP.iV.j(c,b));c=null;for(e=d=0;;)if(e<d)a=c.S(null,e),$APP.id(a,this),e+=1;else if(b=$APP.n(b))c=b,$APP.bf(c)?(b=$APP.Cd(c),d=$APP.Dd(c),c=b,a=$APP.De(b),
b=d,d=a):(a=$APP.p(c),$APP.id(a,this),b=$APP.r(c),c=null,d=0),e=0;else return null};$APP.h._queued_run=function(){return this.se&&this.Xe!=null?this._run(!0):null};$APP.h._try_capture=function(a){try{return this.nh=null,g_a(a,this)}catch(b){return this.nh=this.state=a=b,this.se=!1}};$APP.h._run=function(a){var b=this.state;a=$APP.k(a)?this._try_capture(this.f):g_a(this.f,this);this.Ji||(this.state=a,this.Hb==null||$APP.u.j(b,a)||p3(this,b,a));return a};
$APP.h._set_opts=function(a){var b=$APP.yg(a);a=$APP.z.j(b,n5);var c=$APP.z.j(b,u0a),d=$APP.z.j(b,m5);b=$APP.z.j(b,S0a);a!=null&&(this.Ud=a);c!=null&&(this.ml=c);d!=null&&(this.Li=d);return b!=null?this.Ji=b:null};$APP.h.V=function(a,b,c){return q3(b,c,"Reaction",new $APP.G(null,1,[$APP.Ly,this.Ja(null)],null))};$APP.h.ba=function(){return $APP.na(this)};$APP.h.R=function(a,b){return this===b};
$APP.h.Sh=function(){var a=this.state,b=this.Xe;this.Ud=this.state=this.Xe=null;this.se=!0;b=$APP.n($APP.aj(b));for(var c=null,d=0,e=0;;)if(e<d){var f=c.S(null,e);$APP.id(f,this);e+=1}else if(b=$APP.n(b))c=b,$APP.bf(c)?(b=$APP.Cd(c),e=$APP.Dd(c),c=b,d=$APP.De(b),b=e):(b=$APP.p(c),$APP.id(b,this),b=$APP.r(c),c=null,d=0),e=0;else break;this.Li!=null&&this.Li(a);a=this.am;if(a==null)return null;b=a.length;for(c=0;;)if(c<b)d=a[c],d.h?d.h(this):d.call(null,this),c+=1;else return null};
$APP.h.uc=function(a,b){a=this.state;this.state=b;this.ml(a,b);p3(this,a,b);return b};$APP.h.Ff=function(a,b){a=this.uc;var c=this._peek_at();b=b.h?b.h(c):b.call(null,c);return a.call(this,null,b)};$APP.h.Gf=function(a,b,c){a=this.uc;var d=this._peek_at();b=b.j?b.j(d,c):b.call(null,d,c);return a.call(this,null,b)};$APP.h.Hf=function(a,b,c,d){a=this.uc;var e=this._peek_at();b=b.l?b.l(e,c,d):b.call(null,e,c,d);return a.call(this,null,b)};
$APP.h.If=function(a,b,c,d,e){return this.uc(null,$APP.Tg.O(b,this._peek_at(),c,d,e))};$APP.h.qe=function(a,b,c){return p3(this,b,c)};$APP.h.Fe=function(a,b,c){return i_a(this,b,c)};$APP.h.Ge=function(a,b){a=$APP.Ue(this.Hb);j_a(this,b);return!a&&$APP.Ue(this.Hb)&&this.Ud==null?this.Sh(null):null};
$APP.h.Ja=function(){var a=this.nh;if(a!=null)throw a;(a=o3==null)&&($APP.y3.B?$APP.y3.B():$APP.y3.call(null));a&&this.Ud==null?this.se&&(a=this.state,this.state=this.f.B?this.f.B():this.f.call(null),this.Hb==null||$APP.u.j(a,this.state)||p3(this,a,this.state)):(h_a(this),this.se&&this._run(!1));return this.state};a_a=$APP.y3;var s3=function s3(a){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return s3.o(arguments[0],1<c.length?new $APP.ee(c.slice(1),0,null):null)};
s3.o=function(a,b){var c=$APP.yg(b);b=$APP.z.j(c,n5);var d=$APP.z.j(c,u0a);c=$APP.z.j(c,m5);a=new q_a(a);a._set_opts(new $APP.G(null,3,[n5,b,u0a,d,m5,c],null));return a};s3.A=1;s3.C=function(a){var b=$APP.p(a);a=$APP.r(a);return this.o(b,a)};var s_a=s3(null);var A3,r_a=new $APP.G(null,1,[S0a,!0],null),E_a=new $APP.G(null,2,[K0a,null,NZa,null],null),z_a=function(a){var b=$APP.Zj.h($APP.xg);return function(c){var d=$APP.z.j($APP.wc(b),c);if(d!=null)return d;d=a.h?a.h(c):a.call(null,c);$APP.ak.D(b,$APP.Ti,c,d);return d}}(function(a){if(typeof a==="string")return a;a=$APP.cj(a);a=$APP.pl(a,/(unsafe|UNSAFE)[-_]/,"UNSAFE_");a=$APP.wl.j(a,/-/);var b=$APP.n(a);a=$APP.p(b);b=$APP.r(b);return $APP.Tg.l($APP.I,a,$APP.pk.j(UZa,b))}),I_a=new $APP.E(null,5,5,$APP.F,
[RZa,k0a,C0a,I0a,f1a],null);var S_a=new $APP.Wi(null,new $APP.G(null,6,["url",null,"tel",null,"text",null,"textarea",null,"password",null,"search",null],null),null),l0a=new $APP.G(null,4,[F0a,"ReagentInput",D0a,H3,a1a,function(a){return a.Dh=null},BZa,function(a,b,c,d,e){V_a(c);return n3(e,a,b,c,d)}],null);var i0a=/([^\s\.#]+)(?:#([^\s\.#]+))?(?:\.([^\s#]+))?/,Y_a={"class":"className","for":"htmlFor",charset:"charSet"},$_a={},h0a={};$APP.h=p0a.prototype;$APP.h.Z=function(a,b){return new p0a(this.Nc,this.id,this.Hi,this.Tg,b)};$APP.h.W=function(){return this.el};$APP.h.wl=function(){return this.id};$APP.h.qj=function(a,b,c){return this.Tg.l?this.Tg.l(this,b,c):this.Tg.call(null,this,b,c)};
$APP.h.oj=function(a,b){return"object"!==$APP.ca(b)?b:$APP.af(b)?o0a(b,this,this.Hi):$APP.ff(b)?n0a(b,this):i3(b)?$APP.cj(b):(b!=null?b.H&2147483648||$APP.Yd===b.Ia||(b.H?0:$APP.Eb($APP.Zc,b)):$APP.Eb($APP.Zc,b))?$APP.Wj.o($APP.y([b],0)):b};$APP.h.pj=function(a,b,c,d,e){return c0a(this,b,c,d,e)};$APP.Q3=s0a($APP.xg);var R3=function R3(a){switch(arguments.length){case 1:return R3.h(arguments[0]);case 2:return R3.j(arguments[0],arguments[1]);case 3:return R3.l(arguments[0],arguments[1],arguments[2]);default:for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return R3.o(arguments[0],arguments[1],arguments[2],3<c.length?new $APP.ee(c.slice(3),0,null):null)}};R3.h=function(a){return R3.j(a,null)};R3.j=function(a,b){return $APP.aD.nbb$internal$react.createElement(a,b)};
R3.l=function(a,b,c){return $APP.aD.nbb$internal$react.createElement(a,b,c)};R3.o=function(a,b,c,d){return $APP.Tg.O($APP.aD.nbb$internal$react.createElement,a,b,c,d)};R3.C=function(a){var b=$APP.p(a),c=$APP.r(a);a=$APP.p(c);var d=$APP.r(c);c=$APP.p(d);d=$APP.r(d);return this.o(b,a,c,d)};R3.A=3;var S3=function S3(a){switch(arguments.length){case 1:return S3.h(arguments[0]);case 2:return S3.j(arguments[0],arguments[1]);default:throw Error(["Invalid arity: ",arguments.length].join(""));}};
S3.h=function(a){return $APP.m3($APP.Q3,a)};S3.j=function(a,b){return $APP.m3(b,a)};S3.A=2;var T3=function T3(a){switch(arguments.length){case 1:return T3.h(arguments[0]);case 2:return T3.j(arguments[0],arguments[1]);default:throw Error(["Invalid arity: ",arguments.length].join(""));}};T3.h=function(a){return T3.j(a,$APP.Q3)};T3.j=function(a,b){return v_a(a)?a:L_a(a,b)};T3.A=2;
var U3=function U3(a){switch(arguments.length){case 1:return U3.h(arguments[0]);case 2:return U3.j(arguments[0],arguments[1]);default:throw Error(["Invalid arity: ",arguments.length].join(""));}};U3.h=function(a){return G3(a,$APP.Q3)};U3.j=function(a,b){return G3(a,b)};U3.A=2;
var V3=function V3(a){switch(arguments.length){case 0:return V3.B();case 1:return V3.h(arguments[0]);case 2:return V3.j(arguments[0],arguments[1]);default:for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return V3.o(arguments[0],arguments[1],2<c.length?new $APP.ee(c.slice(2),0,null):null)}};V3.B=function(){return null};V3.h=function(a){return J3.h(a)};V3.j=function(a,b){return J3.j(a,b)};V3.o=function(a,b,c){return $APP.Tg.D(J3,a,b,c)};
V3.C=function(a){var b=$APP.p(a),c=$APP.r(a);a=$APP.p(c);c=$APP.r(c);return this.o(b,a,c)};V3.A=2;var W3=function W3(a){switch(arguments.length){case 1:return W3.h(arguments[0]);default:for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return W3.o(arguments[0],1<c.length?new $APP.ee(c.slice(1),0,null):null)}};W3.h=function(a){return B3.h(a)};W3.o=function(a,b){return $APP.Tg.l(B3,a,b)};W3.C=function(a){var b=$APP.p(a);a=$APP.r(a);return this.o(b,a)};W3.A=1;
var X3=function X3(a){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return X3.o(arguments[0],1<c.length?new $APP.ee(c.slice(1),0,null):null)};X3.o=function(a,b){return l_a(a,b)};X3.A=1;X3.C=function(a){var b=$APP.p(a);a=$APP.r(a);return this.o(b,a)};var Y3=function Y3(a){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return Y3.o(arguments[0],1<c.length?new $APP.ee(c.slice(1),0,null):null)};Y3.o=function(a,b){return m_a(a,b)};
Y3.A=1;Y3.C=function(a){var b=$APP.p(a);a=$APP.r(a);return this.o(b,a)};var Z3=function Z3(a){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return Z3.o(arguments[0],arguments[1],arguments[2],3<c.length?new $APP.ee(c.slice(3),0,null):null)};
Z3.o=function(a,b,c,d){var e=$APP.Aq.h("with-let");a=$APP.Cj.h(e);var f=$APP.Aq.h("init");c=$APP.ai.j(new $APP.E(null,2,5,$APP.F,[f,$APP.U.h($APP.n($APP.O.j(new $APP.B(null,T0a,null,1,null),new $APP.B(null,$APP.U.h($APP.n($APP.O.j(new $APP.B(null,$APP.oDa,null,1,null),new $APP.B(null,e,null,1,null)))),null,1,null))))],null),$APP.bz.j(function(q,t){if($APP.Rg(q))return t;q=$APP.Jf(q,2);return $APP.U.h($APP.n($APP.O.o(new $APP.B(null,$APP.Pk,null,1,null),new $APP.B(null,$APP.U.h($APP.n($APP.O.o(new $APP.B(null,
$APP.aS,null,1,null),new $APP.B(null,f,null,1,null),$APP.y([new $APP.B(null,$APP.U.h($APP.n($APP.O.j(new $APP.B(null,$APP.sy,null,1,null),new $APP.B(null,$APP.U.h($APP.n($APP.O.o(new $APP.B(null,N0a,null,1,null),new $APP.B(null,e,null,1,null),$APP.y([new $APP.B(null,q,null,1,null)],0)))),null,1,null)))),null,1,null)],0)))),null,1,null),$APP.y([new $APP.B(null,$APP.U.h($APP.n($APP.O.o(new $APP.B(null,$APP.HCa,null,1,null),new $APP.B(null,e,null,1,null),$APP.y([new $APP.B(null,q,null,1,null),new $APP.B(null,
t,null,1,null)],0)))),null,1,null),new $APP.B(null,$APP.U.h($APP.n($APP.O.o(new $APP.B(null,$APP.xta,null,1,null),new $APP.B(null,e,null,1,null),$APP.y([new $APP.B(null,q,null,1,null)],0)))),null,1,null)],0))))},c));var g=function(){var q=$APP.Le(d);return $APP.ff(q)&&$APP.u.j($APP.Mk,$APP.p(q))?new $APP.E(null,2,5,$APP.F,[$APP.bj(d),$APP.U.h($APP.n($APP.O.o(new $APP.B(null,$APP.du,null,1,null),new $APP.B(null,$APP.Dh($APP.U.h($APP.n($APP.O.B()))),null,1,null),$APP.y([$APP.ie(q)],0))))],null):new $APP.E(null,
2,5,$APP.F,[d,null],null)}();b=$APP.x.l(g,0,null);g=$APP.x.l(g,1,null);g=$APP.k(g)?new $APP.B(null,$APP.U.h($APP.n($APP.O.o(new $APP.B(null,$APP.Bt,null,1,null),new $APP.B(null,$APP.Dh($APP.U.h($APP.n($APP.O.j(new $APP.B(null,w0a,null,1,null),new $APP.B(null,g,null,1,null))))),null,1,null),$APP.y([new $APP.B(null,$APP.U.h($APP.n($APP.O.o(new $APP.B(null,$APP.Pk,null,1,null),new $APP.B(null,$APP.U.h($APP.n($APP.O.h(new $APP.B(null,W0a,null,1,null)))),null,1,null),$APP.y([new $APP.B(null,$APP.U.h($APP.n($APP.O.o(new $APP.B(null,
$APP.RH,null,1,null),new $APP.B(null,$APP.U.h($APP.n($APP.O.j(new $APP.B(null,$APP.BQ,null,1,null),new $APP.B(null,$APP.U.h($APP.n($APP.O.j(new $APP.B(null,KZa,null,1,null),new $APP.B(null,e,null,1,null)))),null,1,null)))),null,1,null),$APP.y([new $APP.B(null,$APP.U.h($APP.n($APP.O.o(new $APP.B(null,x0a,null,1,null),new $APP.B(null,e,null,1,null),$APP.y([new $APP.B(null,w0a,null,1,null)],0)))),null,1,null)],0)))),null,1,null),new $APP.B(null,$APP.U.h($APP.n($APP.O.h(new $APP.B(null,w0a,null,1,null)))),
null,1,null)],0)))),null,1,null)],0)))),null,1,null):null;var m=$APP.Aq.h("res");return $APP.U.h($APP.n($APP.O.o(new $APP.B(null,$APP.Bt,null,1,null),new $APP.B(null,$APP.Dh($APP.U.h($APP.n($APP.O.j(new $APP.B(null,e,null,1,null),new $APP.B(null,$APP.U.h($APP.n($APP.O.j(new $APP.B(null,b1a,null,1,null),new $APP.B(null,a,null,1,null)))),null,1,null))))),null,1,null),$APP.y([new $APP.B(null,null,null,1,null),new $APP.B(null,$APP.U.h($APP.n($APP.O.o(new $APP.B(null,$APP.Bt,null,1,null),new $APP.B(null,
$APP.ai.j(c,new $APP.E(null,2,5,$APP.F,[m,$APP.U.h($APP.n($APP.O.j(new $APP.B(null,$APP.Ok,null,1,null),b)))],null)),null,1,null),$APP.y([g,new $APP.B(null,m,null,1,null)],0)))),null,1,null)],0))))};Z3.A=3;Z3.C=function(a){var b=$APP.p(a),c=$APP.r(a);a=$APP.p(c);var d=$APP.r(c);c=$APP.p(d);d=$APP.r(d);return this.o(b,a,c,d)};var $3=function $3(a){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return $3.o(0<c.length?new $APP.ee(c.slice(0),0,null):null)};
$3.o=function(a){return $APP.U.h($APP.n($APP.O.j(new $APP.B(null,IZa,null,1,null),new $APP.B(null,$APP.U.h($APP.n($APP.O.o(new $APP.B(null,$APP.du,null,1,null),new $APP.B(null,$APP.Dh($APP.U.h($APP.n($APP.O.B()))),null,1,null),$APP.y([a],0)))),null,1,null))))};$3.A=0;$3.C=function(a){return this.o($APP.n(a))};
var a4=$APP.gX.j($APP.IQ,null),E1a=$APP.Fi([QZa,M0a,s5,$APP.KH,e1a,t5,X0a,P0a,g1a,JZa,A0a,w5,q0a,v5],[$APP.Zs(U3,QZa,new $APP.G(null,7,[$APP.R,QZa,$APP.Q,"Creates JS class based on provided Clojure map, for example:\n\n  ```cljs\n  {;; Constructor\n   :constructor (fn [this props])\n   :get-initial-state (fn [this])\n   ;; Static methods\n   :get-derived-state-from-props (fn [props state] partial-state)\n   :get-derived-state-from-error (fn [error] partial-state)\n   ;; Methods\n   :get-snapshot-before-update (fn [this old-argv new-argv] snapshot)\n   :should-component-update (fn [this old-argv new-argv])\n   :component-did-mount (fn [this])\n   :component-did-update (fn [this old-argv old-state snapshot])\n   :component-will-unmount (fn [this])\n   :component-did-catch (fn [this error info])\n   :reagent-render (fn [args....])\n   ;; Or alternatively:\n   :render (fn [this])\n   ;; Deprecated methods:\n   :UNSAFE_component-will-receive-props (fn [this new-argv])\n   :UNSAFE_component-will-update (fn [this new-argv new-state])\n   :UNSAFE_component-will-mount (fn [this])}\n  ```\n\n  Everything is optional, except either :reagent-render or :render.\n\n  Map keys should use `React.Component` method names (https://reactjs.org/docs/react-component.html),\n  and can be provided in snake-case or camelCase.\n\n  State can be initialized using constructor, which matches React.Component class,\n  or using getInitialState which matches old React createClass function and is\n  now implemented by Reagent for compatibility.\n\n  State can usually be anything, e.g. Cljs object. But if using getDerivedState\n  methods, the state has to be plain JS object as React implementation uses\n  Object.assign to merge partial state into the current state.\n\n  React built-in static methods or properties are automatically defined as statics.",$APP.Y,
$APP.J(new $APP.E(null,1,5,$APP.F,[$APP.ZG],null),new $APP.E(null,2,5,$APP.F,[$APP.ZG,$APP.u5],null)),$APP.K,"reagent/core.cljs",$APP.M,68,$APP.N,7,$APP.T,a4],null),a4),$APP.Zs(X3,M0a,new $APP.G(null,7,[$APP.R,M0a,$APP.Q,"Takes a function and optional arguments, and returns a derefable\n  containing the output of that function. If the function derefs\n  Reagent atoms (or track, etc), the value will be updated whenever\n  the atom changes.\n\n  In other words, `@(track foo bar)` will produce the same result\n  as `(foo bar)`, but foo will only be called again when the atoms it\n  depends on changes, and will only trigger updates of components when\n  its result changes.\n\n  track is lazy, i.e the function is only evaluated on deref.",
$APP.Y,$APP.J($APP.Qe(new $APP.E(null,3,5,$APP.F,[$APP.mS,$APP.Jk,$APP.HL],null),new $APP.G(null,1,[$APP.Fp,new $APP.E(null,1,5,$APP.F,[$APP.J($APP.aQ,$APP.mS)],null)],null))),$APP.K,"reagent/core.cljs",$APP.M,218,$APP.N,7,$APP.T,a4],null),a4),$APP.Zs($APP.ve(new $APP.be(function(){return Z3},d1a,$APP.Fi([$APP.T,$APP.R,$APP.K,$APP.Gt,$APP.NS,$APP.N,$APP.M,$APP.ct,$APP.Ft,$APP.Y,$APP.Q,$APP.xO],[R0a,s5,"sci/configs/reagent/reagent.cljs",23,new $APP.G(null,6,[$APP.eo,!0,$APP.Zv,1,$APP.MT,1,$APP.wT,
$APP.J($APP.J($APP.xH,$APP.OJ)),$APP.Y,$APP.J(new $APP.E(null,3,5,$APP.F,[$APP.xH,$APP.Jk,$APP.OJ],null)),$APP.mO,$APP.J(null)],null),1,10,!0,10,$APP.J(new $APP.E(null,3,5,$APP.F,[$APP.xH,$APP.Jk,$APP.OJ],null)),null,$APP.k(Z3)?Z3.X:null]))),s5,new $APP.G(null,8,[$APP.R,s5,$APP.Q,null,$APP.ct,!0,$APP.Y,$APP.J(new $APP.E(null,5,5,$APP.F,[$APP.rw,$APP.rw,$APP.xH,$APP.Jk,$APP.OJ],null)),$APP.K,"sci/configs/reagent/reagent.cljs",$APP.M,10,$APP.N,15,$APP.T,a4],null),a4),$APP.Zs(W3,$APP.KH,new $APP.G(null,
7,[$APP.R,$APP.KH,$APP.Q,"Like clojure.core/atom, except that it keeps track of derefs.\n  Reagent components that derefs one of these are automatically\n  re-rendered.",$APP.Y,$APP.J(new $APP.E(null,1,5,$APP.F,[$APP.zS],null),new $APP.E(null,3,5,$APP.F,[$APP.zS,$APP.Jk,$APP.TI],null)),$APP.K,"reagent/core.cljs",$APP.M,211,$APP.N,7,$APP.T,a4],null),a4),$APP.Zs(V3,e1a,new $APP.G(null,7,[$APP.R,e1a,$APP.Q,"Function which normalizes and combines class values to a string\n\n  Reagent allows classes to be defined as:\n  - Strings\n  - Named objects (Symbols or Keywords)\n  - Collections of previous types",
$APP.Y,$APP.J($APP.nh,new $APP.E(null,1,5,$APP.F,[$APP.HM],null),new $APP.E(null,2,5,$APP.F,[TZa,SZa],null),new $APP.E(null,4,5,$APP.F,[TZa,SZa,$APP.Jk,H0a],null)),$APP.K,"reagent/core.cljs",$APP.M,179,$APP.N,7,$APP.T,a4],null),a4),$APP.Zs($APP.ve(new $APP.be(function(){return $3},G0a,$APP.Fi([$APP.T,$APP.R,$APP.K,$APP.Gt,$APP.NS,$APP.N,$APP.M,$APP.ct,$APP.Ft,$APP.Y,$APP.Q,$APP.xO],[R0a,t5,"sci/configs/reagent/reagent.cljs",23,new $APP.G(null,6,[$APP.eo,!0,$APP.Zv,-2,$APP.MT,-2,$APP.wT,$APP.J($APP.he),
$APP.Y,$APP.J($APP.nh),$APP.mO,$APP.J(null)],null),1,62,!0,62,$APP.J($APP.nh),null,$APP.k($3)?$3.X:null]))),t5,new $APP.G(null,8,[$APP.R,t5,$APP.Q,null,$APP.ct,!0,$APP.Y,$APP.J(new $APP.E(null,2,5,$APP.F,[$APP.Jk,$APP.OJ],null)),$APP.K,"sci/configs/reagent/reagent.cljs",$APP.M,62,$APP.N,15,$APP.T,a4],null),a4),$APP.Zs(S3,X0a,new $APP.G(null,7,[$APP.R,X0a,$APP.Q,"Turns a vector of Hiccup syntax into a React element. Returns form\n  unchanged if it is not a vector.",$APP.Y,$APP.J(new $APP.E(null,1,
5,$APP.F,[$APP.YR],null),new $APP.E(null,2,5,$APP.F,[$APP.YR,$APP.u5],null)),$APP.K,"reagent/core.cljs",$APP.M,46,$APP.N,7,$APP.T,a4],null),a4),$APP.Zs(T3,P0a,new $APP.G(null,7,[$APP.R,P0a,$APP.Q,"Returns an adapter for a Reagent component, that may be used from\n  React, for example in JSX. A single argument, props, is passed to\n  the component, converted to a map.",$APP.Y,$APP.J(new $APP.E(null,1,5,$APP.F,[$APP.lS],null),new $APP.E(null,2,5,$APP.F,[$APP.lS,$APP.u5],null)),$APP.K,"reagent/core.cljs",
$APP.M,59,$APP.N,7,$APP.T,a4],null),a4),$APP.Zs(R3,g1a,new $APP.G(null,7,[$APP.R,g1a,$APP.Q,'Create a native React element, by calling React.createElement directly.\n\n  That means the second argument must be a javascript object (or nil), and\n  that any Reagent hiccup forms must be processed with as-element. For example\n  like this:\n\n  ```cljs\n  (r/create-element "div" #js{:className "foo"}\n    "Hi " (r/as-element [:strong "world!"])\n  ```\n\n  which is equivalent to\n\n  ```cljs\n  [:div.foo "Hi" [:strong "world!"]]\n  ```',
$APP.Y,$APP.J(new $APP.E(null,1,5,$APP.F,[$APP.tN],null),new $APP.E(null,2,5,$APP.F,[$APP.tN,r0a],null),new $APP.E(null,3,5,$APP.F,[$APP.tN,r0a,$APP.eS],null),new $APP.E(null,5,5,$APP.F,[$APP.tN,r0a,$APP.eS,$APP.Jk,$APP.lQ],null)),$APP.K,"reagent/core.cljs",$APP.M,17,$APP.N,7,$APP.T,a4],null),a4),$APP.Zs(function(a){return w3(a)},JZa,new $APP.G(null,7,[$APP.R,JZa,$APP.Q,"Stop the result of track! from updating.",$APP.Y,$APP.J(new $APP.E(null,1,5,$APP.F,[$APP.zS],null)),$APP.K,"reagent/core.cljs",
$APP.M,242,$APP.N,7,$APP.T,a4],null),a4),$APP.Zs(function(a,b){return new n_a(a,b)},A0a,new $APP.G(null,7,[$APP.R,A0a,$APP.Q,"Provide a cursor into a Reagent atom.\n\n  Behaves like a Reagent atom but focuses updates and derefs to\n  the specified path within the wrapped Reagent atom. e.g.,\n\n  ```cljs\n  (let [c (cursor ra [:nested :content])]\n    ... @c ;; equivalent to (get-in @ra [:nested :content])\n    ... (reset! c 42) ;; equivalent to (swap! ra assoc-in [:nested :content] 42)\n    ... (swap! c inc) ;; equivalence to (swap! ra update-in [:nested :content] inc)\n    )\n  ```\n\n  The first parameter can also be a function, that should look\n  something like this:\n\n  ```cljs\n  (defn set-get\n    ([k] (get-in @state k))\n    ([k v] (swap! state assoc-in k v)))\n  ```\n\n  The function will be called with one argument – the path passed to\n  cursor – when the cursor is deref'ed, and two arguments (path and\n  new value) when the cursor is modified.\n\n  Given that set-get function, (and that state is a Reagent atom, or\n  another cursor) these cursors are equivalent:\n  `(cursor state [:foo])` and `(cursor set-get [:foo])`.\n\n  Note that a cursor is lazy: its value will not change until it is\n  used. This may be noticed with add-watch.",
$APP.Y,$APP.J(new $APP.E(null,2,5,$APP.F,[E0a,$APP.xY],null)),$APP.K,"reagent/core.cljs",$APP.M,272,$APP.N,7,$APP.T,a4],null),a4),$APP.Zs(Y3,w5,new $APP.G(null,7,[$APP.R,w5,$APP.Q,"An eager version of track. The function passed is called\n  immediately, and continues to be called when needed, until stopped\n  with dispose!.",$APP.Y,$APP.J($APP.Qe(new $APP.E(null,3,5,$APP.F,[$APP.mS,$APP.Jk,$APP.HL],null),new $APP.G(null,1,[$APP.Fp,new $APP.E(null,1,5,$APP.F,[$APP.J($APP.aQ,$APP.mS)],null)],null))),
$APP.K,"reagent/core.cljs",$APP.M,234,$APP.N,7,$APP.T,a4],null),a4),$APP.Zs(function(a){return s0a(a)},q0a,new $APP.G(null,7,[$APP.R,q0a,$APP.Q,"Creates Compiler object with given `opts`,\n  this can be passed to `render`, `as-element` and other functions to control\n  how they turn the Reagent-style Hiccup into React components and elements.",$APP.Y,$APP.J(new $APP.E(null,1,5,$APP.F,[$APP.rQ],null)),$APP.K,"reagent/core.cljs",$APP.M,353,$APP.N,7,$APP.T,a4],null),a4),$APP.Zs(t0a,v5,new $APP.G(null,
7,[$APP.R,v5,$APP.Q,"Returns an adapter for a native React class, that may be used\n  just like a Reagent component function or class in Hiccup forms.",$APP.Y,$APP.J(new $APP.E(null,1,5,$APP.F,[$APP.lS],null)),$APP.K,"reagent/core.cljs",$APP.M,52,$APP.N,7,$APP.T,a4],null),a4)]),b4=$APP.gX.j($APP.gY,null),F1a=$APP.Fi([PZa,$APP.KH,Y0a,K_a,H_a,v0a,y0a,B0a,c1a,GZa,w5,L0a],[$APP.Zs(function(a){var b=o3;return b==null?[]:k_a($APP.Lb,b,a,null,o_a)},PZa,new $APP.G(null,7,[$APP.R,PZa,$APP.Q,null,$APP.Y,$APP.J(new $APP.E(null,
1,5,$APP.F,[$APP.dR],null)),$APP.K,"reagent/ratom.cljs",$APP.M,329,$APP.N,7,$APP.T,b4],null),b4),$APP.Zs(B3,$APP.KH,new $APP.G(null,7,[$APP.R,$APP.KH,$APP.Q,"Like clojure.core/atom, except that it keeps track of derefs.",$APP.Y,$APP.J(new $APP.E(null,1,5,$APP.F,[$APP.zS],null),new $APP.E(null,3,5,$APP.F,[$APP.zS,$APP.Jk,new $APP.G(null,1,[$APP.LJ,new $APP.E(null,2,5,$APP.F,[$APP.mI,$APP.iEa],null)],null)],null)),$APP.K,"reagent/ratom.cljs",$APP.M,172,$APP.N,7,$APP.T,a4],null),a4),$APP.Zs(l_a,Y0a,
new $APP.G(null,7,[$APP.R,Y0a,$APP.Q,null,$APP.Y,$APP.J(new $APP.E(null,2,5,$APP.F,[$APP.mS,$APP.HL],null)),$APP.K,"reagent/ratom.cljs",$APP.M,228,$APP.N,7,$APP.T,a4],null),a4),$APP.Zs(function(a){return a.destroy},K_a,new $APP.G(null,7,[$APP.R,K_a,$APP.Q,null,$APP.Y,$APP.J(new $APP.E(null,1,5,$APP.F,[$APP.Qe($APP.yS,new $APP.G(null,1,[$APP.$m,$APP.TK],null))],null)),$APP.K,"sci/configs/reagent/reagent.cljs",$APP.M,106,$APP.N,7,$APP.T,b4],null),b4),$APP.Zs(function(a,b){return a.generation=b.ratomGeneration},
H_a,new $APP.G(null,7,[$APP.R,H_a,$APP.Q,null,$APP.Y,$APP.J(new $APP.E(null,2,5,$APP.F,[$APP.Qe($APP.yS,new $APP.G(null,1,[$APP.$m,$APP.TK],null)),$APP.Qe($APP.lS,new $APP.G(null,1,[$APP.$m,$APP.TK],null))],null)),$APP.K,"sci/configs/reagent/reagent.cljs",$APP.M,98,$APP.N,7,$APP.T,b4],null),b4),$APP.Zs(function(){return o3!=null},v0a,new $APP.G(null,8,[$APP.R,v0a,$APP.Q,null,$APP.Y,$APP.J($APP.nh),$APP.$m,$APP.DR,$APP.K,"reagent/ratom.cljs",$APP.M,17,$APP.N,16,$APP.T,b4],null),b4),$APP.Zs(function(a,
b){return a.destroy=b},y0a,new $APP.G(null,7,[$APP.R,y0a,$APP.Q,null,$APP.Y,$APP.J(new $APP.E(null,2,5,$APP.F,[$APP.Qe($APP.yS,new $APP.G(null,1,[$APP.$m,$APP.TK],null)),J0a],null)),$APP.K,"sci/configs/reagent/reagent.cljs",$APP.M,102,$APP.N,7,$APP.T,b4],null),b4),$APP.Zs(s3,B0a,new $APP.G(null,7,[$APP.R,B0a,$APP.Q,null,$APP.Y,$APP.J(new $APP.E(null,3,5,$APP.F,[$APP.mS,$APP.Jk,new $APP.G(null,1,[$APP.LJ,new $APP.E(null,3,5,$APP.F,[B_a,HZa,$0a],null)],null)],null)),$APP.K,"reagent/ratom.cljs",$APP.M,
517,$APP.N,7,$APP.T,a4],null),a4),$APP.Zs(function(){return o3},c1a,new $APP.G(null,7,[$APP.R,c1a,$APP.Q,"Read-only access to the ratom context.",$APP.Y,$APP.J($APP.nh),$APP.K,"sci/configs/reagent/reagent.cljs",$APP.M,85,$APP.N,7,$APP.T,b4],null),b4),$APP.Zs(function(a){return a.generation},GZa,new $APP.G(null,7,[$APP.R,GZa,$APP.Q,null,$APP.Y,$APP.J(new $APP.E(null,1,5,$APP.F,[$APP.Qe($APP.zS,new $APP.G(null,1,[$APP.$m,$APP.TK],null))],null)),$APP.K,"sci/configs/reagent/reagent.cljs",$APP.M,90,$APP.N,
7,$APP.T,b4],null),b4),$APP.Zs(P3,w5,new $APP.G(null,7,[$APP.R,w5,$APP.Q,null,$APP.Y,$APP.J($APP.Qe(new $APP.E(null,3,5,$APP.F,[$APP.mS,$APP.Jk,$APP.HL],null),new $APP.G(null,1,[$APP.Fp,new $APP.E(null,1,5,$APP.F,[$APP.J($APP.aQ,$APP.mS)],null)],null))),$APP.K,"reagent/ratom.cljs",$APP.M,242,$APP.N,7,$APP.T,a4],null),a4),$APP.Zs(function(a){return a.ratomGeneration},L0a,new $APP.G(null,7,[$APP.R,L0a,$APP.Q,null,$APP.Y,$APP.J(new $APP.E(null,1,5,$APP.F,[$APP.Qe($APP.zS,new $APP.G(null,1,[$APP.$m,$APP.TK],
null))],null)),$APP.K,"sci/configs/reagent/reagent.cljs",$APP.M,94,$APP.N,7,$APP.T,b4],null),b4)]),c4=$APP.gX.j(O0a,null),d4=function d4(a){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return d4.o(arguments[0],arguments[1],2<c.length?new $APP.ee(c.slice(2),0,null):null)};
d4.o=function(a,b,c){return $APP.k(!0)?$APP.U.h($APP.n($APP.O.o(new $APP.B(null,$APP.RH,null,1,null),new $APP.B(null,$APP.U.h($APP.n($APP.O.j(new $APP.B(null,$APP.ty,null,1,null),new $APP.B(null,Q0a,null,1,null)))),null,1,null),$APP.y([new $APP.B(null,$APP.U.h($APP.n($APP.O.o(new $APP.B(null,U0a,null,1,null),new $APP.B(null,$APP.U.h($APP.n($APP.O.o(new $APP.B(null,$APP.Pk,null,1,null),new $APP.B(null,$APP.U.h($APP.n($APP.O.h(new $APP.B(null,V0a,null,1,null)))),null,1,null),$APP.y([new $APP.B(null,
Z0a,null,1,null),new $APP.B(null,Q0a,null,1,null)],0)))),null,1,null),$APP.y([new $APP.B(null,$APP.U.h($APP.n($APP.O.j(new $APP.B(null,$APP.ny,null,1,null),c))),null,1,null)],0)))),null,1,null)],0)))):null};d4.A=2;d4.C=function(a){var b=$APP.p(a),c=$APP.r(a);a=$APP.p(c);c=$APP.r(c);return this.o(b,a,c)};
var G1a=new $APP.G(null,3,[$APP.tQ,$APP.Zs($APP.ve(new $APP.be(function(){return d4},z0a,$APP.Fi([$APP.T,$APP.R,$APP.K,$APP.Gt,$APP.NS,$APP.N,$APP.M,$APP.ct,$APP.Ft,$APP.Y,$APP.Q,$APP.xO],[R0a,$APP.tQ,"sci/configs/reagent/reagent.cljs",20,new $APP.G(null,6,[$APP.eo,!0,$APP.Zv,0,$APP.MT,0,$APP.wT,$APP.J($APP.J($APP.wP)),$APP.Y,$APP.J(new $APP.E(null,2,5,$APP.F,[$APP.Jk,$APP.wP],null)),$APP.mO,$APP.J(null)],null),1,132,!0,132,$APP.J(new $APP.E(null,2,5,$APP.F,[$APP.Jk,$APP.wP],null)),"Print with console.error.",
$APP.k(d4)?d4.X:null]))),$APP.tQ,new $APP.G(null,8,[$APP.R,$APP.tQ,$APP.Q,"Print with console.error.",$APP.ct,!0,$APP.Y,$APP.J(new $APP.E(null,4,5,$APP.F,[$APP.rw,$APP.rw,$APP.Jk,$APP.wP],null)),$APP.K,"sci/configs/reagent/reagent.cljs",$APP.M,132,$APP.N,15,$APP.T,c4],null),c4),OZa,$APP.Zs(function(){return!1},OZa,new $APP.G(null,7,[$APP.R,OZa,$APP.Q,null,$APP.Y,$APP.J($APP.nh),$APP.K,"sci/configs/reagent/reagent.cljs",$APP.M,129,$APP.N,7,$APP.T,c4],null),c4),R_a,$APP.Zs(B1a,R_a,new $APP.G(null,7,
[$APP.R,R_a,$APP.Q,null,$APP.$m,$APP.ZR,$APP.K,"reagent/debug.cljs",$APP.M,10,$APP.N,10,$APP.T,c4],null),c4)],null);$APP.rD(new $APP.G(null,1,[$APP.vt,new $APP.G(null,3,[$APP.IQ,$APP.Ti.l(E1a,v5,$APP.Zs(t0a,v5,new $APP.G(null,7,[$APP.R,v5,$APP.Q,"Returns an adapter for a native React class, that may be used\n  just like a Reagent component function or class in Hiccup forms.",$APP.Y,$APP.J(new $APP.E(null,1,5,$APP.F,[$APP.lS],null)),$APP.K,"reagent/core.cljs",$APP.M,52,$APP.N,7,$APP.T,$APP.gX.h($APP.IQ)],null),$APP.gX.h($APP.IQ))),$APP.gY,F1a,O0a,G1a],null)],null));