import { $APP, shadow$provide } from "./nbb_core.js";
const shadow_esm_import = function(x) { return import(x) };
var IHa=function(a,b){b&=63;if(b==0)return a;var c=a.mb;return b<32?$APP.pa(a.Gb>>>b|c<<32-b,c>>>b):b==32?$APP.pa(c,0):$APP.pa(c>>>b-32,0)},eX=function(){return Math.round(Math.random()*15).toString(16)},JHa=function(a,b){if(a.length>3){if(b)return!0;b=a.charAt(1);return a.charAt(0)==="~"?b===":"||b==="$"||b==="#":!1}return!1},KHa=function(a){var b=Math.floor(a/44);a=String.fromCharCode(a%44+48);return b===0?"^"+a:"^"+String.fromCharCode(b+48)+a},LHa=function(){this.Ej=this.Ff=this.qb=0;this.cache=
{}},fX=function(){this.qb=0;this.cache=[]},hX=function(a,b){if(a==null)return b==null;if(a===b)return!0;if(typeof a==="object"){if(gX(a)){if(gX(b)&&a.length===b.length){for(var c=0;c<a.length;c++)if(!hX(a[c],b[c]))return!1;return!0}return!1}if(a.jd)return a.jd(b);if(b!=null&&typeof b==="object"){if(b.jd)return b.jd(a);c=0;var d=iX(b).length,e;for(e in a)if(a.hasOwnProperty(e)&&(c++,!b.hasOwnProperty(e)||!hX(a[e],b[e])))return!1;return c===d}}return!1},MHa=function(a,b){return a^b+2654435769+(a<<6)+
(a>>2)},NHa=function(a){var b=0;if(a.forEach!=null)a.forEach(function(h,m){b=(b+(jX(m)^jX(h)))%4503599627370496});else for(var c=iX(a),d=0;d<c.length;d++){var e=c[d],f=a[e];b=(b+(jX(e)^jX(f)))%4503599627370496}return b},OHa=function(a){var b=0;if(gX(a))for(var c=0;c<a.length;c++)b=MHa(b,jX(a[c]));else a.forEach&&a.forEach(function(d){b=MHa(b,jX(d))});return b},jX=function(a){if(a==null)return 0;switch(typeof a){case "number":return a;case "boolean":return a===!0?1:0;case "string":var b=PHa[a];if(b!=
null)a=b;else{for(var c=b=0;c<a.length;++c)b=31*b+a.charCodeAt(c),b%=4294967296;QHa++;QHa>=256&&(PHa={},QHa=1);a=PHa[a]=b}return a;case "function":return b=a.transit$hashCode$,b||(b=RHa,typeof Object.defineProperty!="undefined"?Object.defineProperty(a,"transit$hashCode$",{value:b,enumerable:!1}):a.transit$hashCode$=b,RHa++),b;default:return a instanceof Date?a.valueOf():gX(a)?OHa(a):a.Ad?a.Ad():NHa(a)}},kX=function(a,b){this.tag=a;this.rep=b;this.Cb=-1},lX=function(a,b){return new kX(a,b)},UHa=function(a){if(typeof a===
"number"||a instanceof $APP.oa)return a;a=$APP.za(a,10);return a.compare(SHa)>0||a.compare(THa)<0?a:$APP.Aa(a)},mX=function(a){this.Pb=a;this.Cb=-1},nX=function(a){this.Pb=a;this.Cb=-1},oX=function(a,b,c){var d="";c=c||b+1;for(var e=(7-b)*8,f=$APP.faa(255).shiftLeft(e);b<c;b++,e-=8,f=IHa(f,8)){var h=IHa(a.and(f),e).toString(16);h.length==1&&(h="0"+h);d+=h}return d},pX=function(a,b){this.high=a;this.low=b;this.Cb=-1},qX=function(a,b){this.entries=a;this.type=b||0;this.qb=0},rX=function(a,b){this.map=
a;this.type=b||0;this.keys=this.map.He();this.qb=0;this.se=null;this.he=0},VHa=function(a,b){if(a instanceof sX&&(b instanceof tX||b instanceof sX)){if(a.size!==b.size)return!1;for(var c in a.map)for(var d=a.map[c],e=0;e<d.length;e+=2)if(!hX(d[e+1],b.get(d[e])))return!1;return!0}if(a instanceof tX&&(b instanceof tX||b instanceof sX)){if(a.size!==b.size)return!1;a=a.Eb;for(e=0;e<a.length;e+=2)if(!hX(a[e+1],b.get(a[e])))return!1;return!0}if(b!=null&&typeof b==="object"&&(e=iX(b),c=e.length,a.size===
c)){for(d=0;d<c;d++){var f=e[d];if(!a.has(f)||!hX(b[f],a.get(f)))return!1}return!0}return!1},WHa=function(a){return a==null?"null":$APP.ca(a)==="array"?"["+a.toString()+"]":$APP.ca(a)==="string"?'"'+a+'"':a.toString()},XHa=function(a){var b=0,c="TransitMap {";a.forEach(function(d,e){c+=WHa(e)+" \x3d\x3e "+WHa(d);b<a.size-1&&(c+=", ");b++});return c+"}"},YHa=function(a){var b=0,c="TransitSet {";a.forEach(function(d){c+=WHa(d);b<a.size-1&&(c+=", ");b++});return c+"}"},tX=function(a){this.Eb=a;this.Db=
null;this.Cb=-1;this.size=a.length/2;this.Jh=0},ZHa=function(a){if(a.Db)throw Error("Invalid operation, already converted");if(a.size<8)return!1;a.Jh++;return a.Jh>32?(a.Db=uX(a.Eb,!1,!0),a.Eb=[],!0):!1},sX=function(a,b,c){this.map=b||{};this.Ue=a||[];this.size=c||0;this.Cb=-1},uX=function(a,b,c){a=a||[];b=b===!1?b:!0;if((c!==!0||!c)&&a.length<=64){if(b){var d=a;a=[];for(b=0;b<d.length;b+=2){var e=!1;for(c=0;c<a.length;c+=2)if(hX(a[c],d[b])){a[c+1]=d[b+1];e=!0;break}e||(a.push(d[b]),a.push(d[b+1]))}}return new tX(a)}d=
{};e=[];var f=0;for(b=0;b<a.length;b+=2){c=jX(a[b]);var h=d[c];if(h==null)e.push(c),d[c]=[a[b],a[b+1]],f++;else{var m=!0;for(c=0;c<h.length;c+=2)if(hX(h[c],a[b])){h[c+1]=a[b+1];m=!1;break}m&&(h.push(a[b]),h.push(a[b+1]),f++)}}return new sX(e,d,f)},vX=function(a){this.map=a;this.size=a.size},$Ha=function(a){a=a||[];for(var b={},c=[],d=0,e=0;e<a.length;e++){var f=jX(a[e]),h=b[f];if(h==null)c.push(f),b[f]=[a[e],a[e]],d++;else{f=!0;for(var m=0;m<h.length;m+=2)if(hX(h[m],a[e])){f=!1;break}f&&(h.push(a[e]),
h.push(a[e]),d++)}}return new vX(new sX(c,b,d))},aIa=function(a){this.wc=a},wX=function(a){this.options=a||{};this.bc={};for(var b in this.Cf.bc)this.bc[b]=this.Cf.bc[b];for(b in this.options.handlers){a:{switch(b){case "_":case "s":case "?":case "i":case "d":case "b":case "'":case "array":case "map":a=!0;break a}a=!1}if(a)throw Error('Cannot override handler for ground type "'+b+'"');this.bc[b]=this.options.handlers[b]}this.Fg=this.options.preferStrings!=null?this.options.preferStrings:this.Cf.Fg;
this.yh=this.options.preferBuffers!=null?this.options.preferBuffers:this.Cf.yh;this.sh=this.options.defaultHandler||this.Cf.sh;this.od=this.options.mapBuilder;this.Ve=this.options.arrayBuilder},bIa=function(a,b,c,d,e){if(e){var f=[];for(e=0;e<b.length;e++)f.push(a.decode(b[e],c,d,!1));return f}f=c&&c.qb;if(b.length===2&&typeof b[0]==="string"&&(e=a.decode(b[0],c,!1,!1))&&e instanceof aIa)return b=b[1],f=a.bc[e.wc],f!=null?f=f(a.decode(b,c,d,!0),a):lX(e.wc,a.decode(b,c,d,!1));c&&f!=c.qb&&(c.qb=f);
if(a.Ve){if(b.length<=32&&a.Ve.fromArray){f=[];for(e=0;e<b.length;e++)f.push(a.decode(b[e],c,d,!1));return a.Ve.fromArray(f,b)}f=a.Ve.init(b);for(e=0;e<b.length;e++)f=a.Ve.add(f,a.decode(b[e],c,d,!1),b);return a.Ve.finalize(f,b)}f=[];for(e=0;e<b.length;e++)f.push(a.decode(b[e],c,d,!1));return f},cIa=function(a,b){if(b.charAt(0)==="~"){var c=b.charAt(1);if(c==="~"||c==="^"||c==="`")return b.substring(1);if(c==="#")return new aIa(b.substring(2));var d=a.bc[c];return d==null?a.sh(c,b.substring(2)):d(b.substring(2),
a)}return b},dIa=function(a){this.bk=new wX(a)},xX=function(a,b){this.qm=a;this.options=b||{};this.cache=this.options.cache?this.options.cache:new fX},gIa=function(a){if(a==null)return"null";if(a===String)return"string";if(a===Boolean)return"boolean";if(a===Number)return"number";if(a===Array)return"array";if(a===Object)return"map";var b=a[eIa];b==null&&(typeof Object.defineProperty!="undefined"?(b=++fIa,Object.defineProperty(a,eIa,{value:b,enumerable:!1})):a[eIa]=b=++fIa);return b},yX=function(a,
b){a=a.toString();for(var c=a.length;c<b;c++)a="0"+a;return a},zX=function(){},AX=function(){},BX=function(){},CX=function(){},DX=function(){},EX=function(){},FX=function(){},GX=function(){},HX=function(){},IX=function(){},JX=function(){},KX=function(){},LX=function(){},MX=function(){},NX=function(){},OX=function(){},PX=function(){},QX=function(){},RX=function(){this.bc={};this.set(null,new zX);this.set(String,new AX);this.set(Number,new BX);this.set($APP.oa,new CX);this.set(Boolean,new DX);this.set(Array,
new EX);this.set(Object,new FX);this.set(Date,new HX);this.set(pX,new IX);this.set(mX,new JX);this.set(nX,new KX);this.set(kX,new LX);this.set(vX,new MX);this.set(tX,new NX);this.set(sX,new OX);typeof $APP.mz.Tg!="undefined"&&this.set($APP.mz.Tg,new PX);typeof Uint8Array!="undefined"&&this.set(Uint8Array,new QX)},hIa=function(a){this.Lc=a||{};this.Fg=this.Lc.preferStrings!=null?this.Lc.preferStrings:!0;this.vi=this.Lc.objectBuilder||null;this.transform=this.Lc.transform||null;this.bc=new RX;if(a=
this.Lc.handlers){if(gX(a)||!a.forEach)throw Error('transit writer "handlers" option must be a map');var b=this;a.forEach(function(c,d){if(d!==void 0)b.bc.set(d,c);else throw Error("Cannot create handler for JavaScript undefined");})}this.Gf=this.Lc.handlerForForeign;this.Pg=this.Lc.unpack||function(c){return c instanceof tX&&c.Db===null?c.Eb:!1};this.Yf=this.Lc&&this.Lc.verbose||!1},iIa=function(a,b){var c=a.bc.get(b==null?null:b.constructor);return c!=null?c:(b=b&&b.transitTag)?a.bc.get(b):null},
SX=function(a,b,c,d,e){a=a+b+c;return e?e.write(a,d):a},jIa=function(a,b,c){var d=[];if(gX(b))for(var e=0;e<b.length;e++)d.push(TX(a,b[e],!1,c));else b.forEach(function(f){d.push(TX(a,f,!1,c))});return d},kIa=function(a,b){return typeof b!=="string"?(a=iIa(a,b))&&a.tag(b).length===1:!0},lIa=function(a,b){var c=a.Pg(b),d=!0;if(c){for(b=0;b<c.length&&(d=kIa(a,c[b]),d);b+=2);return d}if(b.keys){c=b.keys();var e=null;if(c.next){for(e=c.next();!e.done;){d=kIa(a,e.value);if(!d)break;e=c.next()}return d}}if(b.forEach)return b.forEach(function(f,
h){d=d&&kIa(a,h)}),d;throw Error("Cannot walk keys of object type "+(b==null?null:b.constructor).name);},mIa=function(a){if(a.constructor.transit$isObject)return!0;var b=a.constructor.toString();b=b.substr(9);b=b.substr(0,b.indexOf("("));b=b=="Object";typeof Object.defineProperty!="undefined"?Object.defineProperty(a.constructor,"transit$isObject",{value:b,enumerable:!1}):a.constructor.transit$isObject=b;return b},nIa=function(a,b,c){var d=null,e=null,f=null;d=null;var h=0;if(b.constructor===Object||
b.forEach!=null||a.Gf&&mIa(b)){if(a.Yf){if(b.forEach!=null)if(lIa(a,b)){var m={};b.forEach(function(r,u){m[TX(a,u,!0,!1)]=TX(a,r,!1,c)})}else{d=a.Pg(b);e=[];f=SX("~#","cmap","",!0,c);if(d)for(;h<d.length;h+=2)e.push(TX(a,d[h],!1,!1)),e.push(TX(a,d[h+1],!1,c));else b.forEach(function(r,u){e.push(TX(a,u,!1,!1));e.push(TX(a,r,!1,c))});m={};m[f]=e}else for(d=iX(b),m={};h<d.length;h++)m[TX(a,d[h],!0,!1)]=TX(a,b[d[h]],!1,c);return m}if(b.forEach!=null){if(lIa(a,b)){d=a.Pg(b);m=["^ "];if(d)for(;h<d.length;h+=
2)m.push(TX(a,d[h],!0,c)),m.push(TX(a,d[h+1],!1,c));else b.forEach(function(r,u){m.push(TX(a,u,!0,c));m.push(TX(a,r,!1,c))});return m}d=a.Pg(b);e=[];f=SX("~#","cmap","",!0,c);if(d)for(;h<d.length;h+=2)e.push(TX(a,d[h],!1,c)),e.push(TX(a,d[h+1],!1,c));else b.forEach(function(r,u){e.push(TX(a,u,!1,c));e.push(TX(a,r,!1,c))});return[f,e]}m=["^ "];for(d=iX(b);h<d.length;h++)m.push(TX(a,d[h],!0,c)),m.push(TX(a,b[d[h]],!1,c));return m}if(a.vi!=null)return a.vi(b,function(r){return TX(a,r,!0,c)},function(r){return TX(a,
r,!1,c)});h=(b==null?null:b.constructor).name;d=Error("Cannot write "+h);d.data={ta:b,type:h};throw d;},TX=function(a,b,c,d){a.transform!==null&&(b=a.transform(b));var e=iIa(a,b)||(a.Gf?a.Gf(b,a.bc):null),f=e?e.tag(b):null,h=e?e.rep(b):null;if(e!=null&&f!=null)switch(f){case "_":return c?SX("~","_","",c,d):null;case "s":return h.length>0?(a=h.charAt(0),a=a==="~"||a==="^"||a==="`"?"~"+h:h):a=h,SX("","",a,c,d);case "?":return c?SX("~","?",h.toString()[0],c,d):h;case "i":return h===Infinity?SX("~","z",
"INF",c,d):h===-Infinity?SX("~","z","-INF",c,d):isNaN(h)?SX("~","z","NaN",c,d):c||typeof h==="string"||h instanceof $APP.oa?SX("~","i",h.toString(),c,d):h;case "d":return c?SX(h.wm,"d",h,c,d):h;case "b":return SX("~","b",h,c,d);case "'":return a.Yf?(c={},b=SX("~#","'","",!0,d),c[b]=TX(a,h,!1,d),d=c):d=[SX("~#","'","",!0,d),TX(a,h,!1,d)],d;case "array":return jIa(a,h,d);case "map":return nIa(a,h,d);default:a:{if(f.length===1){if(typeof h==="string"){d=SX("~",f,h,c,d);break a}if(c||a.Fg){(a=a.Yf&&e.getVerboseHandler())?
(f=a.tag(b),h=a.stringRep(b,a)):h=e.stringRep(b,e);if(h!==null){d=SX("~",f,h,c,d);break a}d=Error('Tag "'+f+'" cannot be encoded as string');d.data={tag:f,rep:h,ta:b};throw d;}}c=f;b=h;a.Yf?(e={},e[SX("~#",c,"",!0,d)]=TX(a,b,!1,d),d=e):d=[SX("~#",c,"",!0,d),TX(a,b,!1,d)]}return d}else throw d=(b==null?null:b.constructor).name,a=Error("Cannot write "+d),a.data={ta:b,type:d},a;},UX=function(a,b){this.lf=a;this.options=b||{};this.cache=this.options.cache===!1?null:this.options.cache?this.options.cache:
new LHa},oIa=function(a,b){if(a==="json"||a==="json-verbose"||a==null)return a=new dIa(b),new xX(a,b);throw Error("Cannot create reader of type "+a);},pIa=function(a,b){if(a==="json"||a==="json-verbose"||a==null)return a==="json-verbose"&&(b==null&&(b={}),b.verbose=!0),a=new hIa(b),new UX(a,b);b=Error('Type must be "json"');b.data={type:a};throw b;},qIa=function(a,b){for(var c=$APP.n($APP.La(b)),d=null,e=0,f=0;;)if(f<e){var h=d.U(null,f);a[h]=$APP.Sa(b,h);f+=1}else if(c=$APP.n(c))d=c,$APP.df(d)?(c=
$APP.Dd(d),f=$APP.Fd(d),d=c,e=$APP.De(c),c=f):(c=$APP.p(d),a[c]=$APP.Sa(b,c),c=$APP.q(d),d=null,e=0),f=0;else break;return a},VX=function(){},WX=function(){},XX=function(){},YX=function(){},ZX=function(){},$X=function(){},aY=function(){},bY=function(){},cY=function(){},rIa=function(a,b){this.value=a;this.K=b},dY=function(){},sIa=function(a,b,c,d,e){this.Og=a;this.Hg=b;this.Xf=c;this.Zf=d;this.Ck=e;this.D=393216;this.I=0};$APP.oa.prototype.Cb=$APP.ba(0,function(){return this.Gb^this.mb});
var tIa=new $APP.l(null,"write-meta","write-meta",-1711397117,null),uIa=new $APP.l(null,"from-rep","from-rep",911750077,null),vIa=new $APP.l(null,"str-rep-fn","str-rep-fn",-1179615016,null),wIa=new $APP.l(null,"ListHandler","ListHandler",-856350412,null),eY=new $APP.C(null,"handlers","handlers",79528781),xIa=new $APP.C(null,"arrayBuilder","arrayBuilder",1446317421),yIa=new $APP.C(null,"mapBuilder","mapBuilder",-278083754),zIa=new $APP.C(null,"preferStrings","preferStrings",-1532249482),AIa=new $APP.l(null,
"tag-fn","tag-fn",242055482,null),BIa=new $APP.l(null,"rep-fn","rep-fn",-1724891035,null),CIa=new $APP.l(null,"rep","rep",413710963,null),DIa=new $APP.l(null,"tagged-value","tagged-value",-110559503,null),EIa=new $APP.l(null,"write-handler","write-handler",-692059351,null),FIa=new $APP.C(null,"map-builder","map-builder",-1843343288),GIa=new $APP.C(null,"prefer-strings","prefer-strings",1254507185),HIa=new $APP.C(null,"array-builder","array-builder",1275998041),IIa=new $APP.l(null,"read-handler","read-handler",
1426618230,null),JIa=new $APP.C(null,"prefer-buffers","prefer-buffers",377042081),LIa=new $APP.l(null,"w","w",1994700528,null),MIa=new $APP.C(null,"preferBuffers","preferBuffers",1843176451),NIa=new $APP.l(null,"verbose-handler-fn","verbose-handler-fn",547340594,null),OIa=new $APP.l(null,"integer","integer",1035809817,null),PIa=new $APP.l(null,"write","write",-217117641,null);var iX=typeof Object.keys!="undefined"?function(a){return Object.keys(a)}:function(a){return $APP.La(a)},gX=typeof Array.isArray!="undefined"?function(a){return Array.isArray(a)}:function(a){return $APP.ca(a)==="array"};LHa.prototype.write=function(a,b){return JHa(a,b)?(this.Ej===4096?(this.clear(),this.Ff=0,this.cache={}):this.qb===1936&&this.clear(),b=this.cache[a],b==null?(this.cache[a]=[KHa(this.qb),this.Ff],this.qb++,a):b[1]!=this.Ff?(b[1]=this.Ff,b[0]=KHa(this.qb),this.qb++,a):b[0]):a};LHa.prototype.clear=function(){this.qb=0;this.Ff++};fX.prototype.write=function(a){this.qb==1936&&(this.qb=0);this.cache[this.qb]=a;this.qb++;return a};
fX.prototype.read=function(a){return this.cache[a.length===2?a.charCodeAt(1)-48:(a.charCodeAt(1)-48)*44+(a.charCodeAt(2)-48)]};fX.prototype.clear=function(){this.qb=0};var RHa=1,PHa={},QHa=0;var fY=typeof Symbol!="undefined"?Symbol.iterator:"@@iterator";kX.prototype.toString=function(){return"[TaggedValue: "+this.tag+", "+this.rep+"]"};kX.prototype.equiv=function(a){return hX(this,a)};kX.prototype.equiv=kX.prototype.equiv;kX.prototype.jd=function(a){return a instanceof kX?this.tag===a.tag&&hX(this.rep,a.rep):!1};kX.prototype.Ad=function(){this.Cb===-1&&(this.Cb=MHa(jX(this.tag),jX(this.rep)));return this.Cb};var SHa=$APP.za("9007199254740991"),THa=$APP.za("-9007199254740991");
$APP.oa.prototype.equiv=function(a){return hX(this,a)};$APP.oa.prototype.equiv=$APP.oa.prototype.equiv;$APP.oa.prototype.jd=function(a){return a instanceof $APP.oa&&$APP.Ca(this,a)};$APP.oa.prototype.Ad=function(){return this.Gb};mX.prototype.toString=function(){return":"+this.Pb};mX.prototype.namespace=function(){var a=this.Pb.indexOf("/");return a!=-1?this.Pb.substring(0,a):null};mX.prototype.name=function(){var a=this.Pb.indexOf("/");return a!=-1?this.Pb.substring(a+1,this.Pb.length):this.Pb};
mX.prototype.equiv=function(a){return hX(this,a)};mX.prototype.equiv=mX.prototype.equiv;mX.prototype.jd=function(a){return a instanceof mX&&this.Pb==a.Pb};mX.prototype.Ad=function(){this.Cb===-1&&(this.Cb=jX(this.Pb));return this.Cb};nX.prototype.namespace=function(){var a=this.Pb.indexOf("/");return a!=-1?this.Pb.substring(0,a):null};nX.prototype.name=function(){var a=this.Pb.indexOf("/");return a!=-1?this.Pb.substring(a+1,this.Pb.length):this.Pb};nX.prototype.toString=function(){return this.Pb};
nX.prototype.equiv=function(a){return hX(this,a)};nX.prototype.equiv=nX.prototype.equiv;nX.prototype.jd=function(a){return a instanceof nX&&this.Pb==a.Pb};nX.prototype.Ad=function(){this.Cb===-1&&(this.Cb=jX(this.Pb));return this.Cb};pX.prototype.toString=function(){var a=this.high,b=this.low;var c=oX(a,0,4)+"-";c+=oX(a,4,6)+"-";c+=oX(a,6,8)+"-";c+=oX(b,0,2)+"-";return c+=oX(b,2,8)};pX.prototype.equiv=function(a){return hX(this,a)};pX.prototype.equiv=pX.prototype.equiv;
pX.prototype.jd=function(a){return a instanceof pX&&$APP.Ca(this.high,a.high)&&$APP.Ca(this.low,a.low)};pX.prototype.Ad=function(){this.Cb===-1&&(this.Cb=jX(this.toString()));return this.Cb};Date.prototype.jd=function(a){return a instanceof Date?this.valueOf()===a.valueOf():!1};Date.prototype.Ad=function(){return this.valueOf()};
qX.prototype.next=function(){if(this.qb<this.entries.length){var a={value:this.type===0?this.entries[this.qb]:this.type===1?this.entries[this.qb+1]:[this.entries[this.qb],this.entries[this.qb+1]],done:!1};this.qb+=2;return a}return{value:null,done:!0}};qX.prototype.next=qX.prototype.next;qX.prototype[fY]=function(){return this};
rX.prototype.next=function(){if(this.qb<this.map.size){this.se!=null&&this.he<this.se.length||(this.se=this.map.map[this.keys[this.qb]],this.he=0);var a={value:this.type===0?this.se[this.he]:this.type===1?this.se[this.he+1]:[this.se[this.he],this.se[this.he+1]],done:!1};this.qb++;this.he+=2;return a}return{value:null,done:!0}};rX.prototype.next=rX.prototype.next;rX.prototype[fY]=function(){return this};tX.prototype.toString=function(){return XHa(this)};tX.prototype.inspect=function(){return this.toString()};
tX.prototype.clear=function(){this.Cb=-1;this.Db?this.Db.clear():this.Eb=[];this.size=0};tX.prototype.clear=tX.prototype.clear;tX.prototype.keys=function(){return this.Db?this.Db.keys():new qX(this.Eb,0)};tX.prototype.keys=tX.prototype.keys;tX.prototype.Ke=function(){if(this.Db)return this.Db.Ke();for(var a=[],b=0,c=0;c<this.Eb.length;b++,c+=2)a[b]=this.Eb[c];return a};tX.prototype.keySet=tX.prototype.Ke;tX.prototype.entries=function(){return this.Db?this.Db.entries():new qX(this.Eb,2)};
tX.prototype.entries=tX.prototype.entries;tX.prototype.values=function(){return this.Db?this.Db.values():new qX(this.Eb,1)};tX.prototype.values=tX.prototype.values;tX.prototype.forEach=function(a){if(this.Db)this.Db.forEach(a);else for(var b=0;b<this.Eb.length;b+=2)a(this.Eb[b+1],this.Eb[b])};tX.prototype.forEach=tX.prototype.forEach;
tX.prototype.get=function(a,b){if(this.Db)return this.Db.get(a);if(ZHa(this))return this.get(a);for(var c=0;c<this.Eb.length;c+=2)if(hX(this.Eb[c],a))return this.Eb[c+1];return b};tX.prototype.get=tX.prototype.get;tX.prototype.has=function(a){if(this.Db)return this.Db.has(a);if(ZHa(this))return this.has(a);for(var b=0;b<this.Eb.length;b+=2)if(hX(this.Eb[b],a))return!0;return!1};tX.prototype.has=tX.prototype.has;
tX.prototype.set=function(a,b){this.Cb=-1;if(this.Db)this.Db.set(a,b),this.size=this.Db.size;else{for(var c=0;c<this.Eb.length;c+=2)if(hX(this.Eb[c],a)){this.Eb[c+1]=b;return}this.Eb.push(a);this.Eb.push(b);this.size++;this.size>32&&(this.Db=uX(this.Eb,!1,!0),this.Eb=null)}};tX.prototype.set=tX.prototype.set;
tX.prototype["delete"]=function(a){this.Cb=-1;if(this.Db)return a=this.Db.delete(a),this.size=this.Db.size,a;for(var b=0;b<this.Eb.length;b+=2)if(hX(this.Eb[b],a))return a=this.Eb[b+1],this.Eb.splice(b,2),this.size--,a};tX.prototype.clone=function(){var a=uX();this.forEach(function(b,c){a.set(c,b)});return a};tX.prototype.clone=tX.prototype.clone;tX.prototype[fY]=function(){return this.entries()};tX.prototype.Ad=function(){if(this.Db)return this.Db.Ad();this.Cb===-1&&(this.Cb=NHa(this));return this.Cb};
tX.prototype.jd=function(a){return this.Db?VHa(this.Db,a):VHa(this,a)};sX.prototype.toString=function(){return XHa(this)};sX.prototype.inspect=function(){return this.toString()};sX.prototype.clear=function(){this.Cb=-1;this.map={};this.Ue=[];this.size=0};sX.prototype.clear=sX.prototype.clear;sX.prototype.He=function(){return this.Ue!=null?this.Ue:iX(this.map)};
sX.prototype["delete"]=function(a){this.Cb=-1;this.Ue=null;for(var b=jX(a),c=this.map[b],d=0;d<c.length;d+=2)if(hX(a,c[d]))return a=c[d+1],c.splice(d,2),c.length===0&&delete this.map[b],this.size--,a};sX.prototype.entries=function(){return new rX(this,2)};sX.prototype.entries=sX.prototype.entries;sX.prototype.forEach=function(a){for(var b=this.He(),c=0;c<b.length;c++)for(var d=this.map[b[c]],e=0;e<d.length;e+=2)a(d[e+1],d[e],this)};sX.prototype.forEach=sX.prototype.forEach;
sX.prototype.get=function(a,b){var c=jX(a);c=this.map[c];if(c!=null)for(b=0;b<c.length;b+=2){if(hX(a,c[b]))return c[b+1]}else return b};sX.prototype.get=sX.prototype.get;sX.prototype.has=function(a){var b=jX(a);b=this.map[b];if(b!=null)for(var c=0;c<b.length;c+=2)if(hX(a,b[c]))return!0;return!1};sX.prototype.has=sX.prototype.has;sX.prototype.keys=function(){return new rX(this,0)};sX.prototype.keys=sX.prototype.keys;
sX.prototype.Ke=function(){for(var a=this.He(),b=[],c=0;c<a.length;c++)for(var d=this.map[a[c]],e=0;e<d.length;e+=2)b.push(d[e]);return b};sX.prototype.keySet=sX.prototype.Ke;sX.prototype.set=function(a,b){this.Cb=-1;var c=jX(a),d=this.map[c];if(d==null)this.Ue&&this.Ue.push(c),this.map[c]=[a,b],this.size++;else{c=!0;for(var e=0;e<d.length;e+=2)if(hX(b,d[e])){c=!1;d[e]=b;break}c&&(d.push(a),d.push(b),this.size++)}};sX.prototype.set=sX.prototype.set;
sX.prototype.values=function(){return new rX(this,1)};sX.prototype.values=sX.prototype.values;sX.prototype.clone=function(){var a=uX();this.forEach(function(b,c){a.set(c,b)});return a};sX.prototype.clone=sX.prototype.clone;sX.prototype[fY]=function(){return this.entries()};sX.prototype.Ad=function(){this.Cb===-1&&(this.Cb=NHa(this));return this.Cb};sX.prototype.jd=function(a){return VHa(this,a)};vX.prototype.toString=function(){return YHa(this)};vX.prototype.inspect=function(){return this.toString()};
vX.prototype.add=function(a){this.map.set(a,a);this.size=this.map.size};vX.prototype.add=vX.prototype.add;vX.prototype.clear=function(){this.map=new sX;this.size=0};vX.prototype.clear=vX.prototype.clear;vX.prototype["delete"]=function(a){a=this.map.delete(a);this.size=this.map.size;return a};vX.prototype.entries=function(){return this.map.entries()};vX.prototype.entries=vX.prototype.entries;vX.prototype.forEach=function(a){var b=this;this.map.forEach(function(c,d){a(d,b)})};vX.prototype.forEach=vX.prototype.forEach;
vX.prototype.has=function(a){return this.map.has(a)};vX.prototype.has=vX.prototype.has;vX.prototype.keys=function(){return this.map.keys()};vX.prototype.keys=vX.prototype.keys;vX.prototype.Ke=function(){return this.map.Ke()};vX.prototype.keySet=vX.prototype.Ke;vX.prototype.values=function(){return this.map.values()};vX.prototype.values=vX.prototype.values;vX.prototype.clone=function(){var a=$Ha();this.forEach(function(b){a.add(b)});return a};vX.prototype.clone=vX.prototype.clone;
vX.prototype[fY]=function(){return this.values()};vX.prototype.jd=function(a){if(a instanceof vX){if(this.size===a.size)return hX(this.map,a.map)}else return!1};vX.prototype.Ad=function(){return jX(this.map)};wX.prototype.Cf={bc:{_:function(){return null},"?":function(a){return a==="t"},b:function(a,b){if(b&&b.yh===!1||typeof $APP.mz.Tg=="undefined")if(typeof Uint8Array!="undefined"){if(typeof atob!="undefined")var c=atob(a);else{a=String(a).replace(/=+$/,"");if(a.length%4==1)throw Error("'atob' failed: The string to be decoded is not correctly encoded.");b=0;for(var d,e=0,f="";d=a.charAt(e++);~d&&(c=b%4?c*64+d:d,b++%4)?f+=String.fromCharCode(255&c>>(-2*b&6)):0)d="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/\x3d".indexOf(d);
c=f}a=c.length;b=new Uint8Array(a);for(d=0;d<a;d++)b[d]=c.charCodeAt(d);c=b}else c=lX("b",a);else c=new $APP.mz.Tg(a,"base64");return c},i:function(a){return UHa(a)},n:function(a){return lX("n",a)},d:function(a){return parseFloat(a)},f:function(a){return lX("f",a)},c:function(a){return a},":":function(a){return new mX(a)},$:function(a){return new nX(a)},r:function(a){return lX("r",a)},z:function(a){a:switch(a){case "-INF":a=-Infinity;break a;case "INF":a=Infinity;break a;case "NaN":a=NaN;break a;
default:throw Error("Invalid special double value "+a);}return a},"'":function(a){return a},m:function(a){a=typeof a==="number"?a:parseInt(a,10);return new Date(a)},t:function(a){return new Date(a)},u:function(a){a=a.replace(/-/g,"");var b,c;var d=b=0;for(c=24;d<8;d+=2,c-=8)b|=parseInt(a.substring(d,d+2),16)<<c;var e=0;d=8;for(c=24;d<16;d+=2,c-=8)e|=parseInt(a.substring(d,d+2),16)<<c;var f=$APP.pa(e,b);b=0;d=16;for(c=24;d<24;d+=2,c-=8)b|=parseInt(a.substring(d,d+2),16)<<c;e=0;for(c=d=24;d<32;d+=2,
c-=8)e|=parseInt(a.substring(d,d+2),16)<<c;return new pX(f,$APP.pa(e,b))},set:function(a){return $Ha(a)},list:function(a){return lX("list",a)},link:function(a){return lX("link",a)},cmap:function(a){return uX(a,!1)}},sh:function(a,b){return lX(a,b)},Fg:!0,yh:!0};
wX.prototype.decode=function(a,b,c,d){if(a==null)return null;switch(typeof a){case "string":return JHa(a,c)?(a=cIa(this,a),b&&b.write(a,c),b=a):b=a.charAt(0)==="^"&&a.charAt(1)!==" "?b.read(a,c):cIa(this,a),b;case "object":if(gX(a))if(a[0]==="^ ")if(this.od)if(a.length<17&&this.od.fromArray){d=[];for(c=1;c<a.length;c+=2)d.push(this.decode(a[c],b,!0,!1)),d.push(this.decode(a[c+1],b,!1,!1));b=this.od.fromArray(d,a)}else{d=this.od.init(a);for(c=1;c<a.length;c+=2)d=this.od.add(d,this.decode(a[c],b,!0,
!1),this.decode(a[c+1],b,!1,!1),a);b=this.od.finalize(d,a)}else{d=[];for(c=1;c<a.length;c+=2)d.push(this.decode(a[c],b,!0,!1)),d.push(this.decode(a[c+1],b,!1,!1));b=uX(d,!1)}else b=bIa(this,a,b,c,d);else{c=iX(a);var e=c[0];if((d=c.length==1?this.decode(e,b,!1,!1):null)&&d instanceof aIa)a=a[e],c=this.bc[d.wc],b=c!=null?c(this.decode(a,b,!1,!0),this):lX(d.wc,this.decode(a,b,!1,!1));else if(this.od)if(c.length<16&&this.od.fromArray){var f=[];for(d=0;d<c.length;d++)e=c[d],f.push(this.decode(e,b,!0,!1)),
f.push(this.decode(a[e],b,!1,!1));b=this.od.fromArray(f,a)}else{f=this.od.init(a);for(d=0;d<c.length;d++)e=c[d],f=this.od.add(f,this.decode(e,b,!0,!1),this.decode(a[e],b,!1,!1),a);b=this.od.finalize(f,a)}else{f=[];for(d=0;d<c.length;d++)e=c[d],f.push(this.decode(e,b,!0,!1)),f.push(this.decode(a[e],b,!1,!1));b=uX(f,!1)}}return b}return a};wX.prototype.decode=wX.prototype.decode;xX.prototype.read=function(a){var b=this.cache;a=this.qm.bk.decode(JSON.parse(a),b);this.cache.clear();return a};xX.prototype.read=xX.prototype.read;var fIa=0,QIa=(8|3&Math.round(Math.random()*14)).toString(16),eIa="transit$guid$"+(eX()+eX()+eX()+eX()+eX()+eX()+eX()+eX()+"-"+eX()+eX()+eX()+eX()+"-4"+eX()+eX()+eX()+"-"+QIa+eX()+eX()+eX()+"-"+eX()+eX()+eX()+eX()+eX()+eX()+eX()+eX()+eX()+eX()+eX()+eX());zX.prototype.tag=function(){return"_"};zX.prototype.rep=function(){return null};zX.prototype.stringRep=function(){return"null"};AX.prototype.tag=function(){return"s"};AX.prototype.rep=function(a){return a};AX.prototype.stringRep=function(a){return a};
BX.prototype.tag=function(){return"i"};BX.prototype.rep=function(a){return a};BX.prototype.stringRep=function(a){return a.toString()};CX.prototype.tag=function(){return"i"};CX.prototype.rep=function(a){return a.toString()};CX.prototype.stringRep=function(a){return a.toString()};DX.prototype.tag=function(){return"?"};DX.prototype.rep=function(a){return a};DX.prototype.stringRep=function(a){return a.toString()};EX.prototype.tag=function(){return"array"};EX.prototype.rep=function(a){return a};
EX.prototype.stringRep=function(){return null};FX.prototype.tag=function(){return"map"};FX.prototype.rep=function(a){return a};FX.prototype.stringRep=function(){return null};GX.prototype.tag=function(){return"t"};GX.prototype.rep=function(a){return a.getUTCFullYear()+"-"+yX(a.getUTCMonth()+1,2)+"-"+yX(a.getUTCDate(),2)+"T"+yX(a.getUTCHours(),2)+":"+yX(a.getUTCMinutes(),2)+":"+yX(a.getUTCSeconds(),2)+"."+yX(a.getUTCMilliseconds(),3)+"Z"};GX.prototype.stringRep=function(a,b){return b.rep(a)};
HX.prototype.tag=function(){return"m"};HX.prototype.rep=function(a){return a.valueOf()};HX.prototype.stringRep=function(a){return a.valueOf().toString()};HX.prototype.getVerboseHandler=function(){return new GX};IX.prototype.tag=function(){return"u"};IX.prototype.rep=function(a){return a.toString()};IX.prototype.stringRep=function(a){return a.toString()};JX.prototype.tag=function(){return":"};JX.prototype.rep=function(a){return a.Pb};JX.prototype.stringRep=function(a,b){return b.rep(a)};
KX.prototype.tag=function(){return"$"};KX.prototype.rep=function(a){return a.Pb};KX.prototype.stringRep=function(a,b){return b.rep(a)};LX.prototype.tag=function(a){return a.tag};LX.prototype.rep=function(a){return a.rep};LX.prototype.stringRep=function(){return null};MX.prototype.tag=function(){return"set"};MX.prototype.rep=function(a){var b=[];a.forEach(function(c){b.push(c)});return lX("array",b)};MX.prototype.stringRep=function(){return null};NX.prototype.tag=function(){return"map"};
NX.prototype.rep=function(a){return a};NX.prototype.stringRep=function(){return null};OX.prototype.tag=function(){return"map"};OX.prototype.rep=function(a){return a};OX.prototype.stringRep=function(){return null};PX.prototype.tag=function(){return"b"};PX.prototype.rep=function(a){return a.toString("base64")};PX.prototype.stringRep=function(){return null};QX.prototype.tag=function(){return"b"};
QX.prototype.rep=function(a){for(var b,c=0,d=a.length,e="",f;c<d;)f=a.subarray(c,Math.min(c+32768,d)),e+=String.fromCharCode.apply(null,f),c+=32768;if(typeof btoa!="undefined")b=btoa(e);else{a=String(e);d=0;e="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/\x3d";for(f="";a.charAt(d|0)||(e="\x3d",d%1);f+=e.charAt(63&b>>8-d%1*8)){c=a.charCodeAt(d+=.75);if(c>255)throw Error("'btoa' failed: The string to be encoded contains characters outside of the Latin1 range.");b=b<<8|c}b=f}return b};
QX.prototype.stringRep=function(){return null};RX.prototype.get=function(a){a=typeof a==="string"?this.bc[a]:this.bc[gIa(a)];return a!=null?a:this.bc["default"]};RX.prototype.get=RX.prototype.get;RX.prototype.set=function(a,b){var c;if(c=typeof a==="string")a:{switch(a){case "null":case "string":case "boolean":case "number":case "array":case "map":c=!1;break a}c=!0}c?this.bc[a]=b:this.bc[gIa(a)]=b};UX.prototype.tk=function(){return this.lf};UX.prototype.marshaller=UX.prototype.tk;
UX.prototype.write=function(a,b){var c=b||{};b=c.asMapKey||!1;var d=this.lf.Yf?!1:this.cache;if(c.marshalTop===!1)a=TX(this.lf,a,b,d);else{c=this.lf;var e=JSON,f=e.stringify,h=TX;var m=iIa(c,a)||(c.Gf?c.Gf(a,c.bc):null);if(m!=null)a=m.tag(a).length===1?lX("'",a):a;else throw b=(a==null?null:a.constructor).name,d=Error("Cannot write "+b),d.data={ta:a,type:b},d;a=f.call(e,h(c,a,b,d))}this.cache!=null&&this.cache.clear();return a};UX.prototype.write=UX.prototype.write;
UX.prototype.register=function(a,b){this.lf.bc.set(a,b)};UX.prototype.register=UX.prototype.register;$APP.Dk.prototype.We=$APP.$d;$APP.Dk.prototype.T=function(a,b){return b instanceof $APP.Dk?this.$c===b.$c:b instanceof pX?this.$c===b.toString():!1};$APP.Dk.prototype.cd=$APP.$d;$APP.Dk.prototype.Oc=function(a,b){if(b instanceof $APP.Dk||b instanceof pX)return $APP.vf(this.toString(),b.toString());throw Error("Cannot compare "+$APP.G.h(this)+" to "+$APP.G.h(b));};pX.prototype.cd=$APP.$d;
pX.prototype.Oc=function(a,b){if(b instanceof $APP.Dk||b instanceof pX)return $APP.vf(this.toString(),b.toString());throw Error("Cannot compare "+$APP.G.h(this)+" to "+$APP.G.h(b));};$APP.oa.prototype.We=$APP.$d;$APP.oa.prototype.T=function(a,b){return this.equiv(b)};pX.prototype.We=$APP.$d;pX.prototype.T=function(a,b){return b instanceof $APP.Dk?b.T(null,this):this.equiv(b)};kX.prototype.We=$APP.$d;kX.prototype.T=function(a,b){return this.equiv(b)};$APP.oa.prototype.uf=$APP.$d;
$APP.oa.prototype.fa=function(){return jX(this)};pX.prototype.uf=$APP.$d;pX.prototype.fa=function(){return $APP.ae(this.toString())};kX.prototype.uf=$APP.$d;kX.prototype.fa=function(){return jX(this)};pX.prototype.jh=$APP.$d;pX.prototype.Ia=$APP.$d;pX.prototype.Z=function(a,b){return $APP.Yc(b,'#uuid "'+$APP.G.h(this.toString())+'"')};VX.prototype.init=function(){return $APP.jd($APP.zg)};VX.prototype.add=function(a,b,c){return $APP.ei.l(a,b,c)};VX.prototype.finalize=function(a){return $APP.nd(a)};
VX.prototype.fromArray=function(a){return $APP.ai.l?$APP.ai.l(a,!0,!0):$APP.ai.call(null,a,!0,!0)};WX.prototype.init=function(){return $APP.jd($APP.ph)};WX.prototype.add=function(a,b){return $APP.oh.j(a,b)};WX.prototype.finalize=function(a){return $APP.nd(a)};WX.prototype.fromArray=function(a){return $APP.Bh.j?$APP.Bh.j(a,!0):$APP.Bh.call(null,a,!0)};
var gY=function gY(a){switch(arguments.length){case 1:return gY.h(arguments[0]);case 2:return gY.j(arguments[0],arguments[1]);default:throw Error(["Invalid arity: ",arguments.length].join(""));}};gY.h=function(a){return gY.j(a,null)};
gY.j=function(a,b){return oIa($APP.ej(a),qIa({handlers:$APP.TC($APP.gm.o($APP.v([new $APP.F(null,6,["$",function(c){return $APP.Lj.h(c)},":",function(c){return $APP.Dj.h(c)},"set",function(c){return $APP.ci.j($APP.$i,c)},"list",function(c){return $APP.ci.j($APP.ie,c.reverse())},"cmap",function(c){for(var d=0,e=$APP.jd($APP.zg);;)if(d<c.length){var f=d+2;e=$APP.ei.l(e,c[d],c[d+1]);d=f}else return $APP.nd(e)},"with-meta",function(c){return $APP.Se(c[0],c[1])}],null),$APP.hm.j(eY.h(b),$APP.kn)],0))),
defaultHandler:$APP.kn.h(eY.h(b)),mapBuilder:new VX,arrayBuilder:new WX,preferStrings:!1,preferBuffers:!1},$APP.TC($APP.Sx($APP.hm.j(b,eY),new $APP.F(null,4,[HIa,xIa,FIa,yIa,GIa,zIa,JIa,MIa],null)))))};gY.A=2;XX.prototype.tag=function(){return":"};XX.prototype.rep=function(a){return a.aa};XX.prototype.stringRep=function(a){return a.aa};YX.prototype.tag=function(){return"$"};YX.prototype.rep=function(a){return a.wc};YX.prototype.stringRep=function(a){return a.wc};ZX.prototype.tag=function(){return"list"};
ZX.prototype.rep=function(a){var b=[];a=$APP.n(a);for(var c=null,d=0,e=0;;)if(e<d){var f=c.U(null,e);b.push(f);e+=1}else if(a=$APP.n(a))c=a,$APP.df(c)?(a=$APP.Dd(c),e=$APP.Fd(c),c=a,d=$APP.De(a),a=e):(a=$APP.p(c),b.push(a),a=$APP.q(c),c=null,d=0),e=0;else break;return lX("array",b)};ZX.prototype.stringRep=function(){return null};$X.prototype.tag=function(){return"map"};$X.prototype.rep=function(a){return a};$X.prototype.stringRep=function(){return null};aY.prototype.tag=function(){return"set"};
aY.prototype.rep=function(a){var b=[];a=$APP.n(a);for(var c=null,d=0,e=0;;)if(e<d){var f=c.U(null,e);b.push(f);e+=1}else if(a=$APP.n(a))c=a,$APP.df(c)?(a=$APP.Dd(c),e=$APP.Fd(c),c=a,d=$APP.De(a),a=e):(a=$APP.p(c),b.push(a),a=$APP.q(c),c=null,d=0),e=0;else break;return lX("array",b)};aY.prototype.stringRep=function(){return null};bY.prototype.tag=function(){return"array"};
bY.prototype.rep=function(a){var b=[];a=$APP.n(a);for(var c=null,d=0,e=0;;)if(e<d){var f=c.U(null,e);b.push(f);e+=1}else if(a=$APP.n(a))c=a,$APP.df(c)?(a=$APP.Dd(c),e=$APP.Fd(c),c=a,d=$APP.De(a),a=e):(a=$APP.p(c),b.push(a),a=$APP.q(c),c=null,d=0),e=0;else break;return b};bY.prototype.stringRep=function(){return null};cY.prototype.tag=function(){return"u"};cY.prototype.rep=function(a){return a.$c};cY.prototype.stringRep=function(a){return this.rep(a)};dY.prototype.tag=function(){return"with-meta"};
dY.prototype.rep=function(a){return lX("array",[a.value,a.K])};dY.prototype.stringRep=function(){return null};var hY=function hY(a){switch(arguments.length){case 1:return hY.h(arguments[0]);case 2:return hY.j(arguments[0],arguments[1]);default:throw Error(["Invalid arity: ",arguments.length].join(""));}};hY.h=function(a){return hY.j(a,null)};
hY.j=function(a,b){var c=new ZX,d=new $X,e=new aY,f=new bY,h=$APP.gm.o($APP.v([$APP.Hi([$APP.Gi,$APP.$f,$APP.F,$APP.xi,$APP.Th,$APP.fe,$APP.C,$APP.Oi,$APP.Uf,$APP.jg,$APP.Kh,$APP.Sh,$APP.Bi,$APP.Ti,rIa,$APP.Zh,$APP.D,$APP.A,$APP.Je,$APP.Zi,$APP.Pi,$APP.Ri,$APP.Gh,$APP.bj,$APP.og,$APP.l,$APP.Dk,$APP.mj,$APP.Ki,$APP.Mi],[d,c,d,c,c,c,new XX,f,c,c,f,c,c,c,new dY,c,f,c,c,e,d,c,c,e,c,new YX,new cY,c,c,f]),typeof $APP.CB!=="undefined"&&typeof $APP.DB!=="undefined"&&typeof $APP.Rj!=="undefined"?$APP.yg([$APP.Rj,
c]):null,typeof $APP.CB!=="undefined"&&typeof $APP.DB!=="undefined"&&typeof $APP.jh!=="undefined"?$APP.yg([$APP.jh,c]):null,typeof $APP.CB!=="undefined"&&typeof $APP.DB!=="undefined"&&typeof $APP.sf!=="undefined"?$APP.yg([$APP.sf,f]):null,eY.h(b)],0));return pIa($APP.ej(a),qIa({objectBuilder:function(m,r,u){return $APP.Bf(function(x,z,B){x.push(r.h?r.h(z):r.call(null,z),u.h?u.h(B):u.call(null,B));return x},["^ "],m)},handlers:function(){var m=$APP.Qb(h);m.forEach=function(r){for(var u=$APP.n(this),
x=null,z=0,B=0;;)if(B<z){var w=x.U(null,B),P=$APP.t.l(w,0,null);w=$APP.t.l(w,1,null);$APP.Ee.j($APP.kn,P)?r.j?r.j(w,"default"):r.call(null,w,"default"):r.j?r.j(w,P):r.call(null,w,P);B+=1}else if(u=$APP.n(u))$APP.df(u)?(x=$APP.Dd(u),u=$APP.Fd(u),P=x,z=$APP.De(x),x=P):(x=$APP.p(u),P=$APP.t.l(x,0,null),w=$APP.t.l(x,1,null),$APP.Ee.j($APP.kn,P)?r.j?r.j(w,"default"):r.call(null,w,"default"):r.j?r.j(w,P):r.call(null,w,P),u=$APP.q(u),x=null,z=0),B=0;else return null};return m}(),unpack:function(m){return m instanceof
$APP.F?m.F:!1}},$APP.TC($APP.hm.j(b,eY))))};hY.A=2;$APP.g=sIa.prototype;$APP.g.S=function(a,b){return new sIa(this.Og,this.Hg,this.Xf,this.Zf,b)};$APP.g.R=function(){return this.Ck};$APP.g.tag=function(a){return this.Og.h?this.Og.h(a):this.Og.call(null,a)};$APP.g.rep=function(a){return this.Hg.h?this.Hg.h(a):this.Hg.call(null,a)};$APP.g.stringRep=function(a){return $APP.k(this.Xf)?this.Xf.h?this.Xf.h(a):this.Xf.call(null,a):null};
$APP.g.getVerboseHandler=function(){return $APP.k(this.Zf)?this.Zf.v?this.Zf.v():this.Zf.call(null):null};var iY=function iY(a){switch(arguments.length){case 2:return iY.j(arguments[0],arguments[1]);case 3:return iY.l(arguments[0],arguments[1],arguments[2]);case 4:return iY.C(arguments[0],arguments[1],arguments[2],arguments[3]);default:throw Error(["Invalid arity: ",arguments.length].join(""));}};iY.j=function(a,b){return iY.C(a,b,null,null)};iY.l=function(a,b,c){return iY.C(a,b,c,null)};
iY.C=function(a,b,c,d){return new sIa($APP.Qe(a)?a:$APP.Yg(a),$APP.Qe(b)?b:$APP.Yg(b),$APP.Qe(c)?c:$APP.Yg(c),$APP.Qe(d)?d:$APP.Yg(d),$APP.zg)};iY.A=4;var jY=$APP.GW.j($APP.KO,null),RIa=$APP.Hi([EIa,DIa,PIa,$APP.iG,wIa,tIa,OIa,IIa,$APP.nE,$APP.QD],[$APP.at(iY,EIa,new $APP.F(null,7,[$APP.Q,EIa,$APP.O,"Creates a transit write handler whose tag, rep,\n   stringRep, and verboseWriteHandler methods\n   invoke the provided fns.",$APP.Y,$APP.H(new $APP.D(null,2,5,$APP.E,[AIa,BIa],null),new $APP.D(null,3,5,$APP.E,[AIa,BIa,vIa],null),new $APP.D(null,4,5,$APP.E,[AIa,BIa,vIa,NIa],null)),$APP.I,"cognitect/transit.cljs",$APP.J,309,$APP.M,7,$APP.S,jY],null),
jY),$APP.at(function(a,b){return lX(a,b)},DIa,new $APP.F(null,7,[$APP.Q,DIa,$APP.O,"Construct a tagged value. tag must be a string and rep can\n   be any transit encodeable value.",$APP.Y,$APP.H(new $APP.D(null,2,5,$APP.E,[$APP.vO,CIa],null)),$APP.I,"cognitect/transit.cljs",$APP.J,332,$APP.M,7,$APP.S,jY],null),jY),$APP.at(function(a,b){return a.write(b)},PIa,new $APP.F(null,7,[$APP.Q,PIa,$APP.O,"Encode an object into a transit string given a transit writer.",$APP.Y,$APP.H(new $APP.D(null,2,5,$APP.E,
[LIa,$APP.oQ],null)),$APP.I,"cognitect/transit.cljs",$APP.J,294,$APP.M,7,$APP.S,jY],null),jY),$APP.at(function(a,b){return a.read(b)},$APP.iG,new $APP.F(null,7,[$APP.Q,$APP.iG,$APP.O,"Read a transit encoded string into ClojureScript values given a\n   transit reader.",$APP.Y,$APP.H(new $APP.D(null,2,5,$APP.E,[$APP.pQ,$APP.fO],null)),$APP.I,"cognitect/transit.cljs",$APP.J,146,$APP.M,7,$APP.S,jY],null),jY),$APP.at(ZX,wIa,new $APP.F(null,7,[$APP.Q,wIa,$APP.O,null,$APP.bn,$APP.OI,$APP.I,"cognitect/transit.cljs",
$APP.J,164,$APP.M,19,$APP.S,jY],null),jY),$APP.at(function(a){if(a!=null&&(a.D&131072||$APP.$d===a.Yd)){var b=a.R(null);return b!=null?new rIa(a.S(null,null),b):a}return a},tIa,new $APP.F(null,7,[$APP.Q,tIa,$APP.O,"For :transform. Will write any metadata present on the value.",$APP.Y,$APP.H(new $APP.D(null,1,5,$APP.E,[$APP.uQ],null)),$APP.I,"cognitect/transit.cljs",$APP.J,432,$APP.M,7,$APP.S,jY],null),jY),$APP.at(function(a){return UHa(a)},OIa,new $APP.F(null,7,[$APP.Q,OIa,$APP.O,"Construct a transit integer value. Returns JavaScript number if\n  in the 53bit integer range, a goog.math.Long instance if above. s\n  may be a string or a JavaScript number.",
$APP.Y,$APP.H(new $APP.D(null,1,5,$APP.E,[$APP.rQ],null)),$APP.I,"cognitect/transit.cljs",$APP.J,343,$APP.M,7,$APP.S,jY],null),jY),$APP.at(function(a){return a},IIa,new $APP.F(null,7,[$APP.Q,IIa,$APP.O,"Construct a read handler. Implemented as identity, exists primarily\n   for API compatiblity with transit-clj",$APP.Y,$APP.H(new $APP.D(null,1,5,$APP.E,[uIa],null)),$APP.I,"cognitect/transit.cljs",$APP.J,299,$APP.M,7,$APP.S,jY],null),jY),$APP.at(gY,$APP.nE,new $APP.F(null,7,[$APP.Q,$APP.nE,$APP.O,
"Return a transit reader. type may be either :json or :json-verbose.\n   opts may be a map optionally containing a :handlers entry. The value\n   of :handlers should be map from string tag to a decoder function of one\n   argument which returns the in-memory representation of the semantic transit\n   value. If a :default handler is provided, it will be used when no matching\n   read handler can be found.",$APP.Y,$APP.H(new $APP.D(null,1,5,$APP.E,[$APP.FJ],null),new $APP.D(null,2,5,$APP.E,[$APP.FJ,
$APP.QM],null)),$APP.I,"cognitect/transit.cljs",$APP.J,106,$APP.M,7,$APP.S,jY],null),jY),$APP.at(hY,$APP.QD,new $APP.F(null,7,[$APP.Q,$APP.QD,$APP.O,"Return a transit writer. type maybe either :json or :json-verbose.\n  opts is a map with the following optional keys:\n\n    :handlers  - a map of type constructors to handler instances. Can optionally\n                 provide a :default write handler which will be used if no\n                 matching handler can be found.\n    :transform - a function of one argument returning a transformed value. Will\n                 be invoked on a value before it is written.",
$APP.Y,$APP.H(new $APP.D(null,1,5,$APP.E,[$APP.FJ],null),new $APP.D(null,2,5,$APP.E,[$APP.FJ,$APP.QM],null)),$APP.I,"cognitect/transit.cljs",$APP.J,212,$APP.M,7,$APP.S,jY],null),jY)]);$APP.Dz(new $APP.F(null,1,[$APP.xt,new $APP.F(null,1,[$APP.KO,RIa],null)],null));