import { $APP, shadow$provide } from "./nbb_core.js";
const shadow_esm_import = function(x) { return import(x) };
var BHa=function(a,b){b&=63;if(b==0)return a;var c=a.kb;return b<32?$APP.ua(a.Eb>>>b|c<<32-b,c>>>b):b==32?$APP.ua(c,0):$APP.ua(c>>>b-32,0)},iZ=function(){return Math.round(Math.random()*15).toString(16)},CHa=function(a,b){if(a.length>3){if(b)return!0;b=a.charAt(1);return a.charAt(0)==="~"?b===":"||b==="$"||b==="#":!1}return!1},DHa=function(a){var b=Math.floor(a/44);a=String.fromCharCode(a%44+48);return b===0?"^"+a:"^"+String.fromCharCode(b+48)+a},EHa=function(){this.Cj=this.Df=this.ob=0;this.cache=
{}},jZ=function(){this.ob=0;this.cache=[]},lZ=function(a,b){if(a==null)return b==null;if(a===b)return!0;if(typeof a==="object"){if(kZ(a)){if(kZ(b)&&a.length===b.length){for(var c=0;c<a.length;c++)if(!lZ(a[c],b[c]))return!1;return!0}return!1}if(a.gd)return a.gd(b);if(b!=null&&typeof b==="object"){if(b.gd)return b.gd(a);c=0;var d=mZ(b).length,e;for(e in a)if(a.hasOwnProperty(e)&&(c++,!b.hasOwnProperty(e)||!lZ(a[e],b[e])))return!1;return c===d}}return!1},FHa=function(a,b){return a^b+2654435769+(a<<6)+
(a>>2)},GHa=function(a){var b=0;if(a.forEach!=null)a.forEach(function(g,k){b=(b+(nZ(k)^nZ(g)))%4503599627370496});else for(var c=mZ(a),d=0;d<c.length;d++){var e=c[d],f=a[e];b=(b+(nZ(e)^nZ(f)))%4503599627370496}return b},HHa=function(a){var b=0;if(kZ(a))for(var c=0;c<a.length;c++)b=FHa(b,nZ(a[c]));else a.forEach&&a.forEach(function(d){b=FHa(b,nZ(d))});return b},nZ=function(a){if(a==null)return 0;switch(typeof a){case "number":return a;case "boolean":return a===!0?1:0;case "string":var b=IHa[a];if(b!=
null)a=b;else{for(var c=b=0;c<a.length;++c)b=31*b+a.charCodeAt(c),b%=4294967296;JHa++;JHa>=256&&(IHa={},JHa=1);a=IHa[a]=b}return a;case "function":return b=a.transit$hashCode$,b||(b=KHa,typeof Object.defineProperty!="undefined"?Object.defineProperty(a,"transit$hashCode$",{value:b,enumerable:!1}):a.transit$hashCode$=b,KHa++),b;default:return a instanceof Date?a.valueOf():kZ(a)?HHa(a):a.yd?a.yd():GHa(a)}},oZ=function(a,b){this.tag=a;this.rep=b;this.Ab=-1},pZ=function(a,b){return new oZ(a,b)},NHa=function(a){if(typeof a===
"number"||a instanceof $APP.sa)return a;a=$APP.Ba(a,10);return a.compare(LHa)>0||a.compare(MHa)<0?a:$APP.Ga(a)},qZ=function(a){this.Nb=a;this.Ab=-1},rZ=function(a){this.Nb=a;this.Ab=-1},sZ=function(a,b,c){var d="";c=c||b+1;for(var e=(7-b)*8,f=$APP.faa(255).shiftLeft(e);b<c;b++,e-=8,f=BHa(f,8)){var g=BHa(a.and(f),e).toString(16);g.length==1&&(g="0"+g);d+=g}return d},tZ=function(a,b){this.high=a;this.low=b;this.Ab=-1},uZ=function(a,b){this.entries=a;this.type=b||0;this.ob=0},vZ=function(a,b){this.map=
a;this.type=b||0;this.keys=this.map.Ge();this.ob=0;this.pe=null;this.fe=0},OHa=function(a,b){if(a instanceof wZ&&(b instanceof yZ||b instanceof wZ)){if(a.size!==b.size)return!1;for(var c in a.map)for(var d=a.map[c],e=0;e<d.length;e+=2)if(!lZ(d[e+1],b.get(d[e])))return!1;return!0}if(a instanceof yZ&&(b instanceof yZ||b instanceof wZ)){if(a.size!==b.size)return!1;a=a.Cb;for(e=0;e<a.length;e+=2)if(!lZ(a[e+1],b.get(a[e])))return!1;return!0}if(b!=null&&typeof b==="object"&&(e=mZ(b),c=e.length,a.size===
c)){for(d=0;d<c;d++){var f=e[d];if(!a.has(f)||!lZ(b[f],a.get(f)))return!1}return!0}return!1},PHa=function(a){return a==null?"null":$APP.ca(a)==="array"?"["+a.toString()+"]":$APP.ca(a)==="string"?'"'+a+'"':a.toString()},QHa=function(a){var b=0,c="TransitMap {";a.forEach(function(d,e){c+=PHa(e)+" \x3d\x3e "+PHa(d);b<a.size-1&&(c+=", ");b++});return c+"}"},RHa=function(a){var b=0,c="TransitSet {";a.forEach(function(d){c+=PHa(d);b<a.size-1&&(c+=", ");b++});return c+"}"},yZ=function(a){this.Cb=a;this.Bb=
null;this.Ab=-1;this.size=a.length/2;this.Hh=0},SHa=function(a){if(a.Bb)throw Error("Invalid operation, already converted");if(a.size<8)return!1;a.Hh++;return a.Hh>32?(a.Bb=zZ(a.Cb,!1,!0),a.Cb=[],!0):!1},wZ=function(a,b,c){this.map=b||{};this.Te=a||[];this.size=c||0;this.Ab=-1},zZ=function(a,b,c){a=a||[];b=b===!1?b:!0;if((c!==!0||!c)&&a.length<=64){if(b){var d=a;a=[];for(b=0;b<d.length;b+=2){var e=!1;for(c=0;c<a.length;c+=2)if(lZ(a[c],d[b])){a[c+1]=d[b+1];e=!0;break}e||(a.push(d[b]),a.push(d[b+1]))}}return new yZ(a)}d=
{};e=[];var f=0;for(b=0;b<a.length;b+=2){c=nZ(a[b]);var g=d[c];if(g==null)e.push(c),d[c]=[a[b],a[b+1]],f++;else{var k=!0;for(c=0;c<g.length;c+=2)if(lZ(g[c],a[b])){g[c+1]=a[b+1];k=!1;break}k&&(g.push(a[b]),g.push(a[b+1]),f++)}}return new wZ(e,d,f)},AZ=function(a){this.map=a;this.size=a.size},THa=function(a){a=a||[];for(var b={},c=[],d=0,e=0;e<a.length;e++){var f=nZ(a[e]),g=b[f];if(g==null)c.push(f),b[f]=[a[e],a[e]],d++;else{f=!0;for(var k=0;k<g.length;k+=2)if(lZ(g[k],a[e])){f=!1;break}f&&(g.push(a[e]),
g.push(a[e]),d++)}}return new AZ(new wZ(c,b,d))},UHa=function(a){this.uc=a},BZ=function(a){this.options=a||{};this.Zb={};for(var b in this.Af.Zb)this.Zb[b]=this.Af.Zb[b];for(b in this.options.handlers){a:{switch(b){case "_":case "s":case "?":case "i":case "d":case "b":case "'":case "array":case "map":a=!0;break a}a=!1}if(a)throw Error('Cannot override handler for ground type "'+b+'"');this.Zb[b]=this.options.handlers[b]}this.Dg=this.options.preferStrings!=null?this.options.preferStrings:this.Af.Dg;
this.wh=this.options.preferBuffers!=null?this.options.preferBuffers:this.Af.wh;this.qh=this.options.defaultHandler||this.Af.qh;this.md=this.options.mapBuilder;this.Ue=this.options.arrayBuilder},VHa=function(a,b,c,d,e){if(e){var f=[];for(e=0;e<b.length;e++)f.push(a.decode(b[e],c,d,!1));return f}f=c&&c.ob;if(b.length===2&&typeof b[0]==="string"&&(e=a.decode(b[0],c,!1,!1))&&e instanceof UHa)return b=b[1],f=a.Zb[e.uc],f!=null?f=f(a.decode(b,c,d,!0),a):pZ(e.uc,a.decode(b,c,d,!1));c&&f!=c.ob&&(c.ob=f);
if(a.Ue){if(b.length<=32&&a.Ue.fromArray){f=[];for(e=0;e<b.length;e++)f.push(a.decode(b[e],c,d,!1));return a.Ue.fromArray(f,b)}f=a.Ue.init(b);for(e=0;e<b.length;e++)f=a.Ue.add(f,a.decode(b[e],c,d,!1),b);return a.Ue.finalize(f,b)}f=[];for(e=0;e<b.length;e++)f.push(a.decode(b[e],c,d,!1));return f},WHa=function(a,b){if(b.charAt(0)==="~"){var c=b.charAt(1);if(c==="~"||c==="^"||c==="`")return b.substring(1);if(c==="#")return new UHa(b.substring(2));var d=a.Zb[c];return d==null?a.qh(c,b.substring(2)):d(b.substring(2),
a)}return b},XHa=function(a){this.$j=new BZ(a)},CZ=function(a,b){this.tl=a;this.options=b||{};this.cache=this.options.cache?this.options.cache:new jZ},$Ha=function(a){if(a==null)return"null";if(a===String)return"string";if(a===Boolean)return"boolean";if(a===Number)return"number";if(a===Array)return"array";if(a===Object)return"map";var b=a[YHa];b==null&&(typeof Object.defineProperty!="undefined"?(b=++ZHa,Object.defineProperty(a,YHa,{value:b,enumerable:!1})):a[YHa]=b=++ZHa);return b},DZ=function(a,
b){a=a.toString();for(var c=a.length;c<b;c++)a="0"+a;return a},EZ=function(){},FZ=function(){},GZ=function(){},HZ=function(){},IZ=function(){},JZ=function(){},KZ=function(){},LZ=function(){},MZ=function(){},NZ=function(){},OZ=function(){},PZ=function(){},QZ=function(){},RZ=function(){},SZ=function(){},TZ=function(){},UZ=function(){},VZ=function(){},WZ=function(){this.Zb={};this.set(null,new EZ);this.set(String,new FZ);this.set(Number,new GZ);this.set($APP.sa,new HZ);this.set(Boolean,new IZ);this.set(Array,
new JZ);this.set(Object,new KZ);this.set(Date,new MZ);this.set(tZ,new NZ);this.set(qZ,new OZ);this.set(rZ,new PZ);this.set(oZ,new QZ);this.set(AZ,new RZ);this.set(yZ,new SZ);this.set(wZ,new TZ);typeof $APP.Uz.Rg!="undefined"&&this.set($APP.Uz.Rg,new UZ);typeof Uint8Array!="undefined"&&this.set(Uint8Array,new VZ)},aIa=function(a){this.Jc=a||{};this.Dg=this.Jc.preferStrings!=null?this.Jc.preferStrings:!0;this.ti=this.Jc.objectBuilder||null;this.transform=this.Jc.transform||null;this.Zb=new WZ;if(a=
this.Jc.handlers){if(kZ(a)||!a.forEach)throw Error('transit writer "handlers" option must be a map');var b=this;a.forEach(function(c,d){if(d!==void 0)b.Zb.set(d,c);else throw Error("Cannot create handler for JavaScript undefined");})}this.Ef=this.Jc.handlerForForeign;this.Ng=this.Jc.unpack||function(c){return c instanceof yZ&&c.Bb===null?c.Cb:!1};this.Wf=this.Jc&&this.Jc.verbose||!1},bIa=function(a,b){var c=a.Zb.get(b==null?null:b.constructor);return c!=null?c:(b=b&&b.transitTag)?a.Zb.get(b):null},
XZ=function(a,b,c,d,e){a=a+b+c;return e?e.write(a,d):a},cIa=function(a,b,c){var d=[];if(kZ(b))for(var e=0;e<b.length;e++)d.push(YZ(a,b[e],!1,c));else b.forEach(function(f){d.push(YZ(a,f,!1,c))});return d},dIa=function(a,b){return typeof b!=="string"?(a=bIa(a,b))&&a.tag(b).length===1:!0},eIa=function(a,b){var c=a.Ng(b),d=!0;if(c){for(b=0;b<c.length&&(d=dIa(a,c[b]),d);b+=2);return d}if(b.keys){c=b.keys();var e=null;if(c.next){for(e=c.next();!e.done;){d=dIa(a,e.value);if(!d)break;e=c.next()}return d}}if(b.forEach)return b.forEach(function(f,
g){d=d&&dIa(a,g)}),d;throw Error("Cannot walk keys of object type "+(b==null?null:b.constructor).name);},fIa=function(a){if(a.constructor.transit$isObject)return!0;var b=a.constructor.toString();b=b.substr(9);b=b.substr(0,b.indexOf("("));b=b=="Object";typeof Object.defineProperty!="undefined"?Object.defineProperty(a.constructor,"transit$isObject",{value:b,enumerable:!1}):a.constructor.transit$isObject=b;return b},gIa=function(a,b,c){var d=null,e=null,f=null;d=null;var g=0;if(b.constructor===Object||
b.forEach!=null||a.Ef&&fIa(b)){if(a.Wf){if(b.forEach!=null)if(eIa(a,b)){var k={};b.forEach(function(q,t){k[YZ(a,t,!0,!1)]=YZ(a,q,!1,c)})}else{d=a.Ng(b);e=[];f=XZ("~#","cmap","",!0,c);if(d)for(;g<d.length;g+=2)e.push(YZ(a,d[g],!1,!1)),e.push(YZ(a,d[g+1],!1,c));else b.forEach(function(q,t){e.push(YZ(a,t,!1,!1));e.push(YZ(a,q,!1,c))});k={};k[f]=e}else for(d=mZ(b),k={};g<d.length;g++)k[YZ(a,d[g],!0,!1)]=YZ(a,b[d[g]],!1,c);return k}if(b.forEach!=null){if(eIa(a,b)){d=a.Ng(b);k=["^ "];if(d)for(;g<d.length;g+=
2)k.push(YZ(a,d[g],!0,c)),k.push(YZ(a,d[g+1],!1,c));else b.forEach(function(q,t){k.push(YZ(a,t,!0,c));k.push(YZ(a,q,!1,c))});return k}d=a.Ng(b);e=[];f=XZ("~#","cmap","",!0,c);if(d)for(;g<d.length;g+=2)e.push(YZ(a,d[g],!1,c)),e.push(YZ(a,d[g+1],!1,c));else b.forEach(function(q,t){e.push(YZ(a,t,!1,c));e.push(YZ(a,q,!1,c))});return[f,e]}k=["^ "];for(d=mZ(b);g<d.length;g++)k.push(YZ(a,d[g],!0,c)),k.push(YZ(a,b[d[g]],!1,c));return k}if(a.ti!=null)return a.ti(b,function(q){return YZ(a,q,!0,c)},function(q){return YZ(a,
q,!1,c)});g=(b==null?null:b.constructor).name;d=Error("Cannot write "+g);d.data={ra:b,type:g};throw d;},YZ=function(a,b,c,d){a.transform!==null&&(b=a.transform(b));var e=bIa(a,b)||(a.Ef?a.Ef(b,a.Zb):null),f=e?e.tag(b):null,g=e?e.rep(b):null;if(e!=null&&f!=null)switch(f){case "_":return c?XZ("~","_","",c,d):null;case "s":return g.length>0?(a=g.charAt(0),a=a==="~"||a==="^"||a==="`"?"~"+g:g):a=g,XZ("","",a,c,d);case "?":return c?XZ("~","?",g.toString()[0],c,d):g;case "i":return g===Infinity?XZ("~","z",
"INF",c,d):g===-Infinity?XZ("~","z","-INF",c,d):isNaN(g)?XZ("~","z","NaN",c,d):c||typeof g==="string"||g instanceof $APP.sa?XZ("~","i",g.toString(),c,d):g;case "d":return c?XZ(g.zl,"d",g,c,d):g;case "b":return XZ("~","b",g,c,d);case "'":return a.Wf?(c={},b=XZ("~#","'","",!0,d),c[b]=YZ(a,g,!1,d),d=c):d=[XZ("~#","'","",!0,d),YZ(a,g,!1,d)],d;case "array":return cIa(a,g,d);case "map":return gIa(a,g,d);default:a:{if(f.length===1){if(typeof g==="string"){d=XZ("~",f,g,c,d);break a}if(c||a.Dg){(a=a.Wf&&e.getVerboseHandler())?
(f=a.tag(b),g=a.stringRep(b,a)):g=e.stringRep(b,e);if(g!==null){d=XZ("~",f,g,c,d);break a}d=Error('Tag "'+f+'" cannot be encoded as string');d.data={tag:f,rep:g,ra:b};throw d;}}c=f;b=g;a.Wf?(e={},e[XZ("~#",c,"",!0,d)]=YZ(a,b,!1,d),d=e):d=[XZ("~#",c,"",!0,d),YZ(a,b,!1,d)]}return d}else throw d=(b==null?null:b.constructor).name,a=Error("Cannot write "+d),a.data={ra:b,type:d},a;},ZZ=function(a,b){this.kf=a;this.options=b||{};this.cache=this.options.cache===!1?null:this.options.cache?this.options.cache:
new EHa},hIa=function(a,b){if(a==="json"||a==="json-verbose"||a==null)return a=new XHa(b),new CZ(a,b);throw Error("Cannot create reader of type "+a);},iIa=function(a,b){if(a==="json"||a==="json-verbose"||a==null)return a==="json-verbose"&&(b==null&&(b={}),b.verbose=!0),a=new aIa(b),new ZZ(a,b);b=Error('Type must be "json"');b.data={type:a};throw b;},jIa=function(a,b){for(var c=$APP.n($APP.Va(b)),d=null,e=0,f=0;;)if(f<e){var g=d.R(null,f);a[g]=$APP.Xa(b,g);f+=1}else if(c=$APP.n(c))d=c,$APP.ff(d)?(c=
$APP.Ed(d),f=$APP.Fd(d),d=c,e=$APP.Ee(c),c=f):(c=$APP.p(d),a[c]=$APP.Xa(b,c),c=$APP.r(d),d=null,e=0),f=0;else break;return a},$Z=function(){},a_=function(){},b_=function(){},c_=function(){},d_=function(){},e_=function(){},f_=function(){},g_=function(){},h_=function(){},kIa=function(a,b){this.value=a;this.I=b},i_=function(){},lIa=function(a,b,c,d,e){this.Mg=a;this.Fg=b;this.Vf=c;this.Xf=d;this.Bk=e;this.G=393216;this.K=0};$APP.sa.prototype.Ab=$APP.ba(0,function(){return this.Eb^this.kb});
var mIa=new $APP.m(null,"write-meta","write-meta",-1711397117,null),nIa=new $APP.m(null,"from-rep","from-rep",911750077,null),oIa=new $APP.m(null,"str-rep-fn","str-rep-fn",-1179615016,null),pIa=new $APP.m(null,"ListHandler","ListHandler",-856350412,null),j_=new $APP.C(null,"handlers","handlers",79528781),qIa=new $APP.C(null,"arrayBuilder","arrayBuilder",1446317421),rIa=new $APP.C(null,"mapBuilder","mapBuilder",-278083754),sIa=new $APP.C(null,"preferStrings","preferStrings",-1532249482),tIa=new $APP.m(null,
"tag-fn","tag-fn",242055482,null),uIa=new $APP.m(null,"rep-fn","rep-fn",-1724891035,null),vIa=new $APP.m(null,"rep","rep",413710963,null),wIa=new $APP.m(null,"tagged-value","tagged-value",-110559503,null),xIa=new $APP.m(null,"write-handler","write-handler",-692059351,null),yIa=new $APP.C(null,"map-builder","map-builder",-1843343288),zIa=new $APP.C(null,"prefer-strings","prefer-strings",1254507185),AIa=new $APP.C(null,"array-builder","array-builder",1275998041),BIa=new $APP.m(null,"read-handler","read-handler",
1426618230,null),CIa=new $APP.C(null,"prefer-buffers","prefer-buffers",377042081),DIa=new $APP.m(null,"w","w",1994700528,null),EIa=new $APP.C(null,"preferBuffers","preferBuffers",1843176451),FIa=new $APP.m(null,"verbose-handler-fn","verbose-handler-fn",547340594,null),GIa=new $APP.m(null,"integer","integer",1035809817,null),HIa=new $APP.m(null,"write","write",-217117641,null);var mZ=typeof Object.keys!="undefined"?function(a){return Object.keys(a)}:function(a){return $APP.Va(a)},kZ=typeof Array.isArray!="undefined"?function(a){return Array.isArray(a)}:function(a){return $APP.ca(a)==="array"};EHa.prototype.write=function(a,b){return CHa(a,b)?(this.Cj===4096?(this.clear(),this.Df=0,this.cache={}):this.ob===1936&&this.clear(),b=this.cache[a],b==null?(this.cache[a]=[DHa(this.ob),this.Df],this.ob++,a):b[1]!=this.Df?(b[1]=this.Df,b[0]=DHa(this.ob),this.ob++,a):b[0]):a};EHa.prototype.clear=function(){this.ob=0;this.Df++};jZ.prototype.write=function(a){this.ob==1936&&(this.ob=0);this.cache[this.ob]=a;this.ob++;return a};
jZ.prototype.read=function(a){return this.cache[a.length===2?a.charCodeAt(1)-48:(a.charCodeAt(1)-48)*44+(a.charCodeAt(2)-48)]};jZ.prototype.clear=function(){this.ob=0};var KHa=1,IHa={},JHa=0;var k_=typeof Symbol!="undefined"?Symbol.iterator:"@@iterator";oZ.prototype.toString=function(){return"[TaggedValue: "+this.tag+", "+this.rep+"]"};oZ.prototype.equiv=function(a){return lZ(this,a)};oZ.prototype.equiv=oZ.prototype.equiv;oZ.prototype.gd=function(a){return a instanceof oZ?this.tag===a.tag&&lZ(this.rep,a.rep):!1};oZ.prototype.yd=function(){this.Ab===-1&&(this.Ab=FHa(nZ(this.tag),nZ(this.rep)));return this.Ab};var LHa=$APP.Ba("9007199254740991"),MHa=$APP.Ba("-9007199254740991");
$APP.sa.prototype.equiv=function(a){return lZ(this,a)};$APP.sa.prototype.equiv=$APP.sa.prototype.equiv;$APP.sa.prototype.gd=function(a){return a instanceof $APP.sa&&$APP.Ia(this,a)};$APP.sa.prototype.yd=function(){return this.Eb};qZ.prototype.toString=function(){return":"+this.Nb};qZ.prototype.namespace=function(){var a=this.Nb.indexOf("/");return a!=-1?this.Nb.substring(0,a):null};qZ.prototype.name=function(){var a=this.Nb.indexOf("/");return a!=-1?this.Nb.substring(a+1,this.Nb.length):this.Nb};
qZ.prototype.equiv=function(a){return lZ(this,a)};qZ.prototype.equiv=qZ.prototype.equiv;qZ.prototype.gd=function(a){return a instanceof qZ&&this.Nb==a.Nb};qZ.prototype.yd=function(){this.Ab===-1&&(this.Ab=nZ(this.Nb));return this.Ab};rZ.prototype.namespace=function(){var a=this.Nb.indexOf("/");return a!=-1?this.Nb.substring(0,a):null};rZ.prototype.name=function(){var a=this.Nb.indexOf("/");return a!=-1?this.Nb.substring(a+1,this.Nb.length):this.Nb};rZ.prototype.toString=function(){return this.Nb};
rZ.prototype.equiv=function(a){return lZ(this,a)};rZ.prototype.equiv=rZ.prototype.equiv;rZ.prototype.gd=function(a){return a instanceof rZ&&this.Nb==a.Nb};rZ.prototype.yd=function(){this.Ab===-1&&(this.Ab=nZ(this.Nb));return this.Ab};tZ.prototype.toString=function(){var a=this.high,b=this.low;var c=sZ(a,0,4)+"-";c+=sZ(a,4,6)+"-";c+=sZ(a,6,8)+"-";c+=sZ(b,0,2)+"-";return c+=sZ(b,2,8)};tZ.prototype.equiv=function(a){return lZ(this,a)};tZ.prototype.equiv=tZ.prototype.equiv;
tZ.prototype.gd=function(a){return a instanceof tZ&&$APP.Ia(this.high,a.high)&&$APP.Ia(this.low,a.low)};tZ.prototype.yd=function(){this.Ab===-1&&(this.Ab=nZ(this.toString()));return this.Ab};Date.prototype.gd=function(a){return a instanceof Date?this.valueOf()===a.valueOf():!1};Date.prototype.yd=function(){return this.valueOf()};
uZ.prototype.next=function(){if(this.ob<this.entries.length){var a={value:this.type===0?this.entries[this.ob]:this.type===1?this.entries[this.ob+1]:[this.entries[this.ob],this.entries[this.ob+1]],done:!1};this.ob+=2;return a}return{value:null,done:!0}};uZ.prototype.next=uZ.prototype.next;uZ.prototype[k_]=function(){return this};
vZ.prototype.next=function(){if(this.ob<this.map.size){this.pe!=null&&this.fe<this.pe.length||(this.pe=this.map.map[this.keys[this.ob]],this.fe=0);var a={value:this.type===0?this.pe[this.fe]:this.type===1?this.pe[this.fe+1]:[this.pe[this.fe],this.pe[this.fe+1]],done:!1};this.ob++;this.fe+=2;return a}return{value:null,done:!0}};vZ.prototype.next=vZ.prototype.next;vZ.prototype[k_]=function(){return this};yZ.prototype.toString=function(){return QHa(this)};yZ.prototype.inspect=function(){return this.toString()};
yZ.prototype.clear=function(){this.Ab=-1;this.Bb?this.Bb.clear():this.Cb=[];this.size=0};yZ.prototype.clear=yZ.prototype.clear;yZ.prototype.keys=function(){return this.Bb?this.Bb.keys():new uZ(this.Cb,0)};yZ.prototype.keys=yZ.prototype.keys;yZ.prototype.Je=function(){if(this.Bb)return this.Bb.Je();for(var a=[],b=0,c=0;c<this.Cb.length;b++,c+=2)a[b]=this.Cb[c];return a};yZ.prototype.keySet=yZ.prototype.Je;yZ.prototype.entries=function(){return this.Bb?this.Bb.entries():new uZ(this.Cb,2)};
yZ.prototype.entries=yZ.prototype.entries;yZ.prototype.values=function(){return this.Bb?this.Bb.values():new uZ(this.Cb,1)};yZ.prototype.values=yZ.prototype.values;yZ.prototype.forEach=function(a){if(this.Bb)this.Bb.forEach(a);else for(var b=0;b<this.Cb.length;b+=2)a(this.Cb[b+1],this.Cb[b])};yZ.prototype.forEach=yZ.prototype.forEach;
yZ.prototype.get=function(a,b){if(this.Bb)return this.Bb.get(a);if(SHa(this))return this.get(a);for(var c=0;c<this.Cb.length;c+=2)if(lZ(this.Cb[c],a))return this.Cb[c+1];return b};yZ.prototype.get=yZ.prototype.get;yZ.prototype.has=function(a){if(this.Bb)return this.Bb.has(a);if(SHa(this))return this.has(a);for(var b=0;b<this.Cb.length;b+=2)if(lZ(this.Cb[b],a))return!0;return!1};yZ.prototype.has=yZ.prototype.has;
yZ.prototype.set=function(a,b){this.Ab=-1;if(this.Bb)this.Bb.set(a,b),this.size=this.Bb.size;else{for(var c=0;c<this.Cb.length;c+=2)if(lZ(this.Cb[c],a)){this.Cb[c+1]=b;return}this.Cb.push(a);this.Cb.push(b);this.size++;this.size>32&&(this.Bb=zZ(this.Cb,!1,!0),this.Cb=null)}};yZ.prototype.set=yZ.prototype.set;
yZ.prototype["delete"]=function(a){this.Ab=-1;if(this.Bb)return a=this.Bb.delete(a),this.size=this.Bb.size,a;for(var b=0;b<this.Cb.length;b+=2)if(lZ(this.Cb[b],a))return a=this.Cb[b+1],this.Cb.splice(b,2),this.size--,a};yZ.prototype.clone=function(){var a=zZ();this.forEach(function(b,c){a.set(c,b)});return a};yZ.prototype.clone=yZ.prototype.clone;yZ.prototype[k_]=function(){return this.entries()};yZ.prototype.yd=function(){if(this.Bb)return this.Bb.yd();this.Ab===-1&&(this.Ab=GHa(this));return this.Ab};
yZ.prototype.gd=function(a){return this.Bb?OHa(this.Bb,a):OHa(this,a)};wZ.prototype.toString=function(){return QHa(this)};wZ.prototype.inspect=function(){return this.toString()};wZ.prototype.clear=function(){this.Ab=-1;this.map={};this.Te=[];this.size=0};wZ.prototype.clear=wZ.prototype.clear;wZ.prototype.Ge=function(){return this.Te!=null?this.Te:mZ(this.map)};
wZ.prototype["delete"]=function(a){this.Ab=-1;this.Te=null;for(var b=nZ(a),c=this.map[b],d=0;d<c.length;d+=2)if(lZ(a,c[d]))return a=c[d+1],c.splice(d,2),c.length===0&&delete this.map[b],this.size--,a};wZ.prototype.entries=function(){return new vZ(this,2)};wZ.prototype.entries=wZ.prototype.entries;wZ.prototype.forEach=function(a){for(var b=this.Ge(),c=0;c<b.length;c++)for(var d=this.map[b[c]],e=0;e<d.length;e+=2)a(d[e+1],d[e],this)};wZ.prototype.forEach=wZ.prototype.forEach;
wZ.prototype.get=function(a,b){var c=nZ(a);c=this.map[c];if(c!=null)for(b=0;b<c.length;b+=2){if(lZ(a,c[b]))return c[b+1]}else return b};wZ.prototype.get=wZ.prototype.get;wZ.prototype.has=function(a){var b=nZ(a);b=this.map[b];if(b!=null)for(var c=0;c<b.length;c+=2)if(lZ(a,b[c]))return!0;return!1};wZ.prototype.has=wZ.prototype.has;wZ.prototype.keys=function(){return new vZ(this,0)};wZ.prototype.keys=wZ.prototype.keys;
wZ.prototype.Je=function(){for(var a=this.Ge(),b=[],c=0;c<a.length;c++)for(var d=this.map[a[c]],e=0;e<d.length;e+=2)b.push(d[e]);return b};wZ.prototype.keySet=wZ.prototype.Je;wZ.prototype.set=function(a,b){this.Ab=-1;var c=nZ(a),d=this.map[c];if(d==null)this.Te&&this.Te.push(c),this.map[c]=[a,b],this.size++;else{c=!0;for(var e=0;e<d.length;e+=2)if(lZ(b,d[e])){c=!1;d[e]=b;break}c&&(d.push(a),d.push(b),this.size++)}};wZ.prototype.set=wZ.prototype.set;
wZ.prototype.values=function(){return new vZ(this,1)};wZ.prototype.values=wZ.prototype.values;wZ.prototype.clone=function(){var a=zZ();this.forEach(function(b,c){a.set(c,b)});return a};wZ.prototype.clone=wZ.prototype.clone;wZ.prototype[k_]=function(){return this.entries()};wZ.prototype.yd=function(){this.Ab===-1&&(this.Ab=GHa(this));return this.Ab};wZ.prototype.gd=function(a){return OHa(this,a)};AZ.prototype.toString=function(){return RHa(this)};AZ.prototype.inspect=function(){return this.toString()};
AZ.prototype.add=function(a){this.map.set(a,a);this.size=this.map.size};AZ.prototype.add=AZ.prototype.add;AZ.prototype.clear=function(){this.map=new wZ;this.size=0};AZ.prototype.clear=AZ.prototype.clear;AZ.prototype["delete"]=function(a){a=this.map.delete(a);this.size=this.map.size;return a};AZ.prototype.entries=function(){return this.map.entries()};AZ.prototype.entries=AZ.prototype.entries;AZ.prototype.forEach=function(a){var b=this;this.map.forEach(function(c,d){a(d,b)})};AZ.prototype.forEach=AZ.prototype.forEach;
AZ.prototype.has=function(a){return this.map.has(a)};AZ.prototype.has=AZ.prototype.has;AZ.prototype.keys=function(){return this.map.keys()};AZ.prototype.keys=AZ.prototype.keys;AZ.prototype.Je=function(){return this.map.Je()};AZ.prototype.keySet=AZ.prototype.Je;AZ.prototype.values=function(){return this.map.values()};AZ.prototype.values=AZ.prototype.values;AZ.prototype.clone=function(){var a=THa();this.forEach(function(b){a.add(b)});return a};AZ.prototype.clone=AZ.prototype.clone;
AZ.prototype[k_]=function(){return this.values()};AZ.prototype.gd=function(a){if(a instanceof AZ){if(this.size===a.size)return lZ(this.map,a.map)}else return!1};AZ.prototype.yd=function(){return nZ(this.map)};BZ.prototype.Af={Zb:{_:function(){return null},"?":function(a){return a==="t"},b:function(a,b){if(b&&b.wh===!1||typeof $APP.Uz.Rg=="undefined")if(typeof Uint8Array!="undefined"){if(typeof atob!="undefined")var c=atob(a);else{a=String(a).replace(/=+$/,"");if(a.length%4==1)throw Error("'atob' failed: The string to be decoded is not correctly encoded.");b=0;for(var d,e=0,f="";d=a.charAt(e++);~d&&(c=b%4?c*64+d:d,b++%4)?f+=String.fromCharCode(255&c>>(-2*b&6)):0)d="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/\x3d".indexOf(d);
c=f}a=c.length;b=new Uint8Array(a);for(d=0;d<a;d++)b[d]=c.charCodeAt(d);c=b}else c=pZ("b",a);else c=new $APP.Uz.Rg(a,"base64");return c},i:function(a){return NHa(a)},n:function(a){return pZ("n",a)},d:function(a){return parseFloat(a)},f:function(a){return pZ("f",a)},c:function(a){return a},":":function(a){return new qZ(a)},$:function(a){return new rZ(a)},r:function(a){return pZ("r",a)},z:function(a){a:switch(a){case "-INF":a=-Infinity;break a;case "INF":a=Infinity;break a;case "NaN":a=NaN;break a;
default:throw Error("Invalid special double value "+a);}return a},"'":function(a){return a},m:function(a){a=typeof a==="number"?a:parseInt(a,10);return new Date(a)},t:function(a){return new Date(a)},u:function(a){a=a.replace(/-/g,"");var b,c;var d=b=0;for(c=24;d<8;d+=2,c-=8)b|=parseInt(a.substring(d,d+2),16)<<c;var e=0;d=8;for(c=24;d<16;d+=2,c-=8)e|=parseInt(a.substring(d,d+2),16)<<c;var f=$APP.ua(e,b);b=0;d=16;for(c=24;d<24;d+=2,c-=8)b|=parseInt(a.substring(d,d+2),16)<<c;e=0;for(c=d=24;d<32;d+=2,
c-=8)e|=parseInt(a.substring(d,d+2),16)<<c;return new tZ(f,$APP.ua(e,b))},set:function(a){return THa(a)},list:function(a){return pZ("list",a)},link:function(a){return pZ("link",a)},cmap:function(a){return zZ(a,!1)}},qh:function(a,b){return pZ(a,b)},Dg:!0,wh:!0};
BZ.prototype.decode=function(a,b,c,d){if(a==null)return null;switch(typeof a){case "string":return CHa(a,c)?(a=WHa(this,a),b&&b.write(a,c),b=a):b=a.charAt(0)==="^"&&a.charAt(1)!==" "?b.read(a,c):WHa(this,a),b;case "object":if(kZ(a))if(a[0]==="^ ")if(this.md)if(a.length<17&&this.md.fromArray){d=[];for(c=1;c<a.length;c+=2)d.push(this.decode(a[c],b,!0,!1)),d.push(this.decode(a[c+1],b,!1,!1));b=this.md.fromArray(d,a)}else{d=this.md.init(a);for(c=1;c<a.length;c+=2)d=this.md.add(d,this.decode(a[c],b,!0,
!1),this.decode(a[c+1],b,!1,!1),a);b=this.md.finalize(d,a)}else{d=[];for(c=1;c<a.length;c+=2)d.push(this.decode(a[c],b,!0,!1)),d.push(this.decode(a[c+1],b,!1,!1));b=zZ(d,!1)}else b=VHa(this,a,b,c,d);else{c=mZ(a);var e=c[0];if((d=c.length==1?this.decode(e,b,!1,!1):null)&&d instanceof UHa)a=a[e],c=this.Zb[d.uc],b=c!=null?c(this.decode(a,b,!1,!0),this):pZ(d.uc,this.decode(a,b,!1,!1));else if(this.md)if(c.length<16&&this.md.fromArray){var f=[];for(d=0;d<c.length;d++)e=c[d],f.push(this.decode(e,b,!0,!1)),
f.push(this.decode(a[e],b,!1,!1));b=this.md.fromArray(f,a)}else{f=this.md.init(a);for(d=0;d<c.length;d++)e=c[d],f=this.md.add(f,this.decode(e,b,!0,!1),this.decode(a[e],b,!1,!1),a);b=this.md.finalize(f,a)}else{f=[];for(d=0;d<c.length;d++)e=c[d],f.push(this.decode(e,b,!0,!1)),f.push(this.decode(a[e],b,!1,!1));b=zZ(f,!1)}}return b}return a};BZ.prototype.decode=BZ.prototype.decode;CZ.prototype.read=function(a){var b=this.cache;a=this.tl.$j.decode(JSON.parse(a),b);this.cache.clear();return a};CZ.prototype.read=CZ.prototype.read;var ZHa=0,LIa=(8|3&Math.round(Math.random()*14)).toString(16),YHa="transit$guid$"+(iZ()+iZ()+iZ()+iZ()+iZ()+iZ()+iZ()+iZ()+"-"+iZ()+iZ()+iZ()+iZ()+"-4"+iZ()+iZ()+iZ()+"-"+LIa+iZ()+iZ()+iZ()+"-"+iZ()+iZ()+iZ()+iZ()+iZ()+iZ()+iZ()+iZ()+iZ()+iZ()+iZ()+iZ());EZ.prototype.tag=function(){return"_"};EZ.prototype.rep=function(){return null};EZ.prototype.stringRep=function(){return"null"};FZ.prototype.tag=function(){return"s"};FZ.prototype.rep=function(a){return a};FZ.prototype.stringRep=function(a){return a};
GZ.prototype.tag=function(){return"i"};GZ.prototype.rep=function(a){return a};GZ.prototype.stringRep=function(a){return a.toString()};HZ.prototype.tag=function(){return"i"};HZ.prototype.rep=function(a){return a.toString()};HZ.prototype.stringRep=function(a){return a.toString()};IZ.prototype.tag=function(){return"?"};IZ.prototype.rep=function(a){return a};IZ.prototype.stringRep=function(a){return a.toString()};JZ.prototype.tag=function(){return"array"};JZ.prototype.rep=function(a){return a};
JZ.prototype.stringRep=function(){return null};KZ.prototype.tag=function(){return"map"};KZ.prototype.rep=function(a){return a};KZ.prototype.stringRep=function(){return null};LZ.prototype.tag=function(){return"t"};LZ.prototype.rep=function(a){return a.getUTCFullYear()+"-"+DZ(a.getUTCMonth()+1,2)+"-"+DZ(a.getUTCDate(),2)+"T"+DZ(a.getUTCHours(),2)+":"+DZ(a.getUTCMinutes(),2)+":"+DZ(a.getUTCSeconds(),2)+"."+DZ(a.getUTCMilliseconds(),3)+"Z"};LZ.prototype.stringRep=function(a,b){return b.rep(a)};
MZ.prototype.tag=function(){return"m"};MZ.prototype.rep=function(a){return a.valueOf()};MZ.prototype.stringRep=function(a){return a.valueOf().toString()};MZ.prototype.getVerboseHandler=function(){return new LZ};NZ.prototype.tag=function(){return"u"};NZ.prototype.rep=function(a){return a.toString()};NZ.prototype.stringRep=function(a){return a.toString()};OZ.prototype.tag=function(){return":"};OZ.prototype.rep=function(a){return a.Nb};OZ.prototype.stringRep=function(a,b){return b.rep(a)};
PZ.prototype.tag=function(){return"$"};PZ.prototype.rep=function(a){return a.Nb};PZ.prototype.stringRep=function(a,b){return b.rep(a)};QZ.prototype.tag=function(a){return a.tag};QZ.prototype.rep=function(a){return a.rep};QZ.prototype.stringRep=function(){return null};RZ.prototype.tag=function(){return"set"};RZ.prototype.rep=function(a){var b=[];a.forEach(function(c){b.push(c)});return pZ("array",b)};RZ.prototype.stringRep=function(){return null};SZ.prototype.tag=function(){return"map"};
SZ.prototype.rep=function(a){return a};SZ.prototype.stringRep=function(){return null};TZ.prototype.tag=function(){return"map"};TZ.prototype.rep=function(a){return a};TZ.prototype.stringRep=function(){return null};UZ.prototype.tag=function(){return"b"};UZ.prototype.rep=function(a){return a.toString("base64")};UZ.prototype.stringRep=function(){return null};VZ.prototype.tag=function(){return"b"};
VZ.prototype.rep=function(a){for(var b,c=0,d=a.length,e="",f;c<d;)f=a.subarray(c,Math.min(c+32768,d)),e+=String.fromCharCode.apply(null,f),c+=32768;if(typeof btoa!="undefined")b=btoa(e);else{a=String(e);d=0;e="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/\x3d";for(f="";a.charAt(d|0)||(e="\x3d",d%1);f+=e.charAt(63&b>>8-d%1*8)){c=a.charCodeAt(d+=.75);if(c>255)throw Error("'btoa' failed: The string to be encoded contains characters outside of the Latin1 range.");b=b<<8|c}b=f}return b};
VZ.prototype.stringRep=function(){return null};WZ.prototype.get=function(a){a=typeof a==="string"?this.Zb[a]:this.Zb[$Ha(a)];return a!=null?a:this.Zb["default"]};WZ.prototype.get=WZ.prototype.get;WZ.prototype.set=function(a,b){var c;if(c=typeof a==="string")a:{switch(a){case "null":case "string":case "boolean":case "number":case "array":case "map":c=!1;break a}c=!0}c?this.Zb[a]=b:this.Zb[$Ha(a)]=b};ZZ.prototype.rk=function(){return this.kf};ZZ.prototype.marshaller=ZZ.prototype.rk;
ZZ.prototype.write=function(a,b){var c=b||{};b=c.asMapKey||!1;var d=this.kf.Wf?!1:this.cache;if(c.marshalTop===!1)a=YZ(this.kf,a,b,d);else{c=this.kf;var e=JSON,f=e.stringify,g=YZ;var k=bIa(c,a)||(c.Ef?c.Ef(a,c.Zb):null);if(k!=null)a=k.tag(a).length===1?pZ("'",a):a;else throw b=(a==null?null:a.constructor).name,d=Error("Cannot write "+b),d.data={ra:a,type:b},d;a=f.call(e,g(c,a,b,d))}this.cache!=null&&this.cache.clear();return a};ZZ.prototype.write=ZZ.prototype.write;
ZZ.prototype.register=function(a,b){this.kf.Zb.set(a,b)};ZZ.prototype.register=ZZ.prototype.register;$APP.Fk.prototype.ve=$APP.ae;$APP.Fk.prototype.P=function(a,b){return b instanceof $APP.Fk?this.Yc===b.Yc:b instanceof tZ?this.Yc===b.toString():!1};$APP.Fk.prototype.ad=$APP.ae;$APP.Fk.prototype.Mc=function(a,b){if(b instanceof $APP.Fk||b instanceof tZ)return $APP.yf(this.toString(),b.toString());throw Error("Cannot compare "+$APP.H.h(this)+" to "+$APP.H.h(b));};tZ.prototype.ad=$APP.ae;
tZ.prototype.Mc=function(a,b){if(b instanceof $APP.Fk||b instanceof tZ)return $APP.yf(this.toString(),b.toString());throw Error("Cannot compare "+$APP.H.h(this)+" to "+$APP.H.h(b));};$APP.sa.prototype.ve=$APP.ae;$APP.sa.prototype.P=function(a,b){return this.equiv(b)};tZ.prototype.ve=$APP.ae;tZ.prototype.P=function(a,b){return b instanceof $APP.Fk?b.P(null,this):this.equiv(b)};oZ.prototype.ve=$APP.ae;oZ.prototype.P=function(a,b){return this.equiv(b)};$APP.sa.prototype.Ve=$APP.ae;
$APP.sa.prototype.ea=function(){return nZ(this)};tZ.prototype.Ve=$APP.ae;tZ.prototype.ea=function(){return $APP.ce(this.toString())};oZ.prototype.Ve=$APP.ae;oZ.prototype.ea=function(){return nZ(this)};tZ.prototype.hh=$APP.ae;tZ.prototype.Ga=$APP.ae;tZ.prototype.Y=function(a,b){return $APP.cd(b,'#uuid "'+$APP.H.h(this.toString())+'"')};$Z.prototype.init=function(){return $APP.od($APP.Ag)};$Z.prototype.add=function(a,b,c){return $APP.ji.l(a,b,c)};$Z.prototype.finalize=function(a){return $APP.rd(a)};
$Z.prototype.fromArray=function(a){return $APP.ei.l?$APP.ei.l(a,!0,!0):$APP.ei.call(null,a,!0,!0)};a_.prototype.init=function(){return $APP.od($APP.sh)};a_.prototype.add=function(a,b){return $APP.rh.j(a,b)};a_.prototype.finalize=function(a){return $APP.rd(a)};a_.prototype.fromArray=function(a){return $APP.Dh.j?$APP.Dh.j(a,!0):$APP.Dh.call(null,a,!0)};
var l_=function l_(a){switch(arguments.length){case 1:return l_.h(arguments[0]);case 2:return l_.j(arguments[0],arguments[1]);default:throw Error(["Invalid arity: ",arguments.length].join(""));}};l_.h=function(a){return l_.j(a,null)};
l_.j=function(a,b){return hIa($APP.hj(a),jIa({handlers:$APP.KD($APP.lm.o($APP.x([new $APP.G(null,6,["$",function(c){return $APP.Mj.h(c)},":",function(c){return $APP.Gj.h(c)},"set",function(c){return $APP.gi.j($APP.bj,c)},"list",function(c){return $APP.gi.j($APP.le,c.reverse())},"cmap",function(c){for(var d=0,e=$APP.od($APP.Ag);;)if(d<c.length){var f=d+2;e=$APP.ji.l(e,c[d],c[d+1]);d=f}else return $APP.rd(e)},"with-meta",function(c){return $APP.Te(c[0],c[1])}],null),$APP.mm.j(j_.h(b),$APP.mn)],0))),
defaultHandler:$APP.mn.h(j_.h(b)),mapBuilder:new $Z,arrayBuilder:new a_,preferStrings:!1,preferBuffers:!1},$APP.KD($APP.Rx($APP.mm.j(b,j_),new $APP.G(null,4,[AIa,qIa,yIa,rIa,zIa,sIa,CIa,EIa],null)))))};l_.v=2;b_.prototype.tag=function(){return":"};b_.prototype.rep=function(a){return a.aa};b_.prototype.stringRep=function(a){return a.aa};c_.prototype.tag=function(){return"$"};c_.prototype.rep=function(a){return a.uc};c_.prototype.stringRep=function(a){return a.uc};d_.prototype.tag=function(){return"list"};
d_.prototype.rep=function(a){var b=[];a=$APP.n(a);for(var c=null,d=0,e=0;;)if(e<d){var f=c.R(null,e);b.push(f);e+=1}else if(a=$APP.n(a))c=a,$APP.ff(c)?(a=$APP.Ed(c),e=$APP.Fd(c),c=a,d=$APP.Ee(a),a=e):(a=$APP.p(c),b.push(a),a=$APP.r(c),c=null,d=0),e=0;else break;return pZ("array",b)};d_.prototype.stringRep=function(){return null};e_.prototype.tag=function(){return"map"};e_.prototype.rep=function(a){return a};e_.prototype.stringRep=function(){return null};f_.prototype.tag=function(){return"set"};
f_.prototype.rep=function(a){var b=[];a=$APP.n(a);for(var c=null,d=0,e=0;;)if(e<d){var f=c.R(null,e);b.push(f);e+=1}else if(a=$APP.n(a))c=a,$APP.ff(c)?(a=$APP.Ed(c),e=$APP.Fd(c),c=a,d=$APP.Ee(a),a=e):(a=$APP.p(c),b.push(a),a=$APP.r(c),c=null,d=0),e=0;else break;return pZ("array",b)};f_.prototype.stringRep=function(){return null};g_.prototype.tag=function(){return"array"};
g_.prototype.rep=function(a){var b=[];a=$APP.n(a);for(var c=null,d=0,e=0;;)if(e<d){var f=c.R(null,e);b.push(f);e+=1}else if(a=$APP.n(a))c=a,$APP.ff(c)?(a=$APP.Ed(c),e=$APP.Fd(c),c=a,d=$APP.Ee(a),a=e):(a=$APP.p(c),b.push(a),a=$APP.r(c),c=null,d=0),e=0;else break;return b};g_.prototype.stringRep=function(){return null};h_.prototype.tag=function(){return"u"};h_.prototype.rep=function(a){return a.Yc};h_.prototype.stringRep=function(a){return this.rep(a)};i_.prototype.tag=function(){return"with-meta"};
i_.prototype.rep=function(a){return pZ("array",[a.value,a.I])};i_.prototype.stringRep=function(){return null};var m_=function m_(a){switch(arguments.length){case 1:return m_.h(arguments[0]);case 2:return m_.j(arguments[0],arguments[1]);default:throw Error(["Invalid arity: ",arguments.length].join(""));}};m_.h=function(a){return m_.j(a,null)};
m_.j=function(a,b){var c=new d_,d=new e_,e=new f_,f=new g_,g=$APP.lm.o($APP.x([$APP.Ji([$APP.Ii,$APP.bg,$APP.G,$APP.yi,$APP.Xh,$APP.ie,$APP.C,$APP.Pi,$APP.Zf,$APP.lg,$APP.Nh,$APP.Wh,$APP.Ci,$APP.Ui,kIa,$APP.ci,$APP.D,$APP.A,$APP.Je,$APP.aj,$APP.Qi,$APP.Si,$APP.Jh,$APP.ej,$APP.pg,$APP.m,$APP.Fk,$APP.oj,$APP.Mi,$APP.Oi],[d,c,d,c,c,c,new b_,f,c,c,f,c,c,c,new i_,c,f,c,c,e,d,c,c,e,c,new c_,new h_,c,c,f]),typeof $APP.cC!=="undefined"&&typeof $APP.dC!=="undefined"&&typeof $APP.Sj!=="undefined"?$APP.zg([$APP.Sj,
c]):null,typeof $APP.cC!=="undefined"&&typeof $APP.dC!=="undefined"&&typeof $APP.kh!=="undefined"?$APP.zg([$APP.kh,c]):null,typeof $APP.cC!=="undefined"&&typeof $APP.dC!=="undefined"&&typeof $APP.wf!=="undefined"?$APP.zg([$APP.wf,f]):null,j_.h(b)],0));return iIa($APP.hj(a),jIa({objectBuilder:function(k,q,t){return $APP.Gf(function(v,z,B){v.push(q.h?q.h(z):q.call(null,z),t.h?t.h(B):t.call(null,B));return v},["^ "],k)},handlers:function(){var k=$APP.Sb(g);k.forEach=function(q){for(var t=$APP.n(this),
v=null,z=0,B=0;;)if(B<z){var u=v.R(null,B),F=$APP.w.l(u,0,null);u=$APP.w.l(u,1,null);$APP.Fe.j($APP.mn,F)?q.j?q.j(u,"default"):q.call(null,u,"default"):q.j?q.j(u,F):q.call(null,u,F);B+=1}else if(t=$APP.n(t))$APP.ff(t)?(v=$APP.Ed(t),t=$APP.Fd(t),F=v,z=$APP.Ee(v),v=F):(v=$APP.p(t),F=$APP.w.l(v,0,null),u=$APP.w.l(v,1,null),$APP.Fe.j($APP.mn,F)?q.j?q.j(u,"default"):q.call(null,u,"default"):q.j?q.j(u,F):q.call(null,u,F),t=$APP.r(t),v=null,z=0),B=0;else return null};return k}(),unpack:function(k){return k instanceof
$APP.G?k.D:!1}},$APP.KD($APP.mm.j(b,j_))))};m_.v=2;$APP.h=lIa.prototype;$APP.h.X=function(a,b){return new lIa(this.Mg,this.Fg,this.Vf,this.Xf,b)};$APP.h.U=function(){return this.Bk};$APP.h.tag=function(a){return this.Mg.h?this.Mg.h(a):this.Mg.call(null,a)};$APP.h.rep=function(a){return this.Fg.h?this.Fg.h(a):this.Fg.call(null,a)};$APP.h.stringRep=function(a){return $APP.l(this.Vf)?this.Vf.h?this.Vf.h(a):this.Vf.call(null,a):null};
$APP.h.getVerboseHandler=function(){return $APP.l(this.Xf)?this.Xf.A?this.Xf.A():this.Xf.call(null):null};var n_=function n_(a){switch(arguments.length){case 2:return n_.j(arguments[0],arguments[1]);case 3:return n_.l(arguments[0],arguments[1],arguments[2]);case 4:return n_.C(arguments[0],arguments[1],arguments[2],arguments[3]);default:throw Error(["Invalid arity: ",arguments.length].join(""));}};n_.j=function(a,b){return n_.C(a,b,null,null)};n_.l=function(a,b,c){return n_.C(a,b,c,null)};
n_.C=function(a,b,c,d){return new lIa($APP.Qe(a)?a:$APP.Yg(a),$APP.Qe(b)?b:$APP.Yg(b),$APP.Qe(c)?c:$APP.Yg(c),$APP.Qe(d)?d:$APP.Yg(d),$APP.Ag)};n_.v=4;var o_=$APP.vY.j($APP.TO,null),JIa=$APP.Ji([xIa,wIa,HIa,$APP.IG,pIa,mIa,GIa,BIa,$APP.eF,$APP.HE],[$APP.bt(n_,xIa,new $APP.G(null,7,[$APP.P,xIa,$APP.O,"Creates a transit write handler whose tag, rep,\n   stringRep, and verboseWriteHandler methods\n   invoke the provided fns.",$APP.X,$APP.I(new $APP.D(null,2,5,$APP.E,[tIa,uIa],null),new $APP.D(null,3,5,$APP.E,[tIa,uIa,oIa],null),new $APP.D(null,4,5,$APP.E,[tIa,uIa,oIa,FIa],null)),$APP.J,"cognitect/transit.cljs",$APP.K,309,$APP.M,7,$APP.S,o_],null),
o_),$APP.bt(function(a,b){return pZ(a,b)},wIa,new $APP.G(null,7,[$APP.P,wIa,$APP.O,"Construct a tagged value. tag must be a string and rep can\n   be any transit encodeable value.",$APP.X,$APP.I(new $APP.D(null,2,5,$APP.E,[$APP.DO,vIa],null)),$APP.J,"cognitect/transit.cljs",$APP.K,332,$APP.M,7,$APP.S,o_],null),o_),$APP.bt(function(a,b){return a.write(b)},HIa,new $APP.G(null,7,[$APP.P,HIa,$APP.O,"Encode an object into a transit string given a transit writer.",$APP.X,$APP.I(new $APP.D(null,2,5,$APP.E,
[DIa,$APP.yQ],null)),$APP.J,"cognitect/transit.cljs",$APP.K,294,$APP.M,7,$APP.S,o_],null),o_),$APP.bt(function(a,b){return a.read(b)},$APP.IG,new $APP.G(null,7,[$APP.P,$APP.IG,$APP.O,"Read a transit encoded string into ClojureScript values given a\n   transit reader.",$APP.X,$APP.I(new $APP.D(null,2,5,$APP.E,[$APP.zQ,$APP.mO],null)),$APP.J,"cognitect/transit.cljs",$APP.K,146,$APP.M,7,$APP.S,o_],null),o_),$APP.bt(d_,pIa,new $APP.G(null,7,[$APP.P,pIa,$APP.O,null,$APP.dn,$APP.jJ,$APP.J,"cognitect/transit.cljs",
$APP.K,164,$APP.M,19,$APP.S,o_],null),o_),$APP.bt(function(a){if(a!=null&&(a.G&131072||$APP.ae===a.Wd)){var b=a.U(null);return b!=null?new kIa(a.X(null,null),b):a}return a},mIa,new $APP.G(null,7,[$APP.P,mIa,$APP.O,"For :transform. Will write any metadata present on the value.",$APP.X,$APP.I(new $APP.D(null,1,5,$APP.E,[$APP.FQ],null)),$APP.J,"cognitect/transit.cljs",$APP.K,432,$APP.M,7,$APP.S,o_],null),o_),$APP.bt(function(a){return NHa(a)},GIa,new $APP.G(null,7,[$APP.P,GIa,$APP.O,"Construct a transit integer value. Returns JavaScript number if\n  in the 53bit integer range, a goog.math.Long instance if above. s\n  may be a string or a JavaScript number.",
$APP.X,$APP.I(new $APP.D(null,1,5,$APP.E,[$APP.CQ],null)),$APP.J,"cognitect/transit.cljs",$APP.K,343,$APP.M,7,$APP.S,o_],null),o_),$APP.bt(function(a){return a},BIa,new $APP.G(null,7,[$APP.P,BIa,$APP.O,"Construct a read handler. Implemented as identity, exists primarily\n   for API compatiblity with transit-clj",$APP.X,$APP.I(new $APP.D(null,1,5,$APP.E,[nIa],null)),$APP.J,"cognitect/transit.cljs",$APP.K,299,$APP.M,7,$APP.S,o_],null),o_),$APP.bt(l_,$APP.eF,new $APP.G(null,7,[$APP.P,$APP.eF,$APP.O,
"Return a transit reader. type may be either :json or :json-verbose.\n   opts may be a map optionally containing a :handlers entry. The value\n   of :handlers should be map from string tag to a decoder function of one\n   argument which returns the in-memory representation of the semantic transit\n   value. If a :default handler is provided, it will be used when no matching\n   read handler can be found.",$APP.X,$APP.I(new $APP.D(null,1,5,$APP.E,[$APP.fK],null),new $APP.D(null,2,5,$APP.E,[$APP.fK,
$APP.$M],null)),$APP.J,"cognitect/transit.cljs",$APP.K,106,$APP.M,7,$APP.S,o_],null),o_),$APP.bt(m_,$APP.HE,new $APP.G(null,7,[$APP.P,$APP.HE,$APP.O,"Return a transit writer. type maybe either :json or :json-verbose.\n  opts is a map with the following optional keys:\n\n    :handlers  - a map of type constructors to handler instances. Can optionally\n                 provide a :default write handler which will be used if no\n                 matching handler can be found.\n    :transform - a function of one argument returning a transformed value. Will\n                 be invoked on a value before it is written.",
$APP.X,$APP.I(new $APP.D(null,1,5,$APP.E,[$APP.fK],null),new $APP.D(null,2,5,$APP.E,[$APP.fK,$APP.$M],null)),$APP.J,"cognitect/transit.cljs",$APP.K,212,$APP.M,7,$APP.S,o_],null),o_)]);$APP.kA(new $APP.G(null,1,[$APP.yt,new $APP.G(null,1,[$APP.TO,JIa],null)],null));