import { $APP, shadow$provide } from "./nbb_core.js";
const shadow_esm_import = function(x) { return import(x) };
var c4=function(a,b){return $APP.Fe.j(a,b)?new $APP.D(null,3,5,$APP.E,[null,null,a],null):new $APP.D(null,3,5,$APP.E,[a,b,null],null)},rRa=function(a){return $APP.n(a)?$APP.Df.l(function(b,c){var d=$APP.w.l(c,0,null);c=$APP.w.l(c,1,null);return $APP.Wi.l(b,d,c)},$APP.Gh($APP.Ao.j($APP.Wg.j($APP.Bo,$APP.Si(a)),null)),a):null},tRa=function(a,b,c){var d=$APP.y.j(a,c),e=$APP.y.j(b,c),f=sRa(d,e),g=$APP.w.l(f,0,null),m=$APP.w.l(f,1,null);f=$APP.w.l(f,2,null);a=$APP.sf(a,c);b=$APP.sf(b,c);d=a&&b&&(f!=null||
d==null&&e==null);return new $APP.D(null,3,5,$APP.E,[!a||g==null&&d?null:$APP.zg([c,g]),!b||m==null&&d?null:$APP.zg([c,m]),d?$APP.zg([c,f]):null],null)},uRa=function(a,b){return $APP.Gh($APP.qk.j(rRa,d4.l($APP.df(a)?a:$APP.Gh(a),$APP.df(b)?b:$APP.Gh(b),$APP.Fo.h($APP.Bo.j($APP.Ee(a),$APP.Ee(b))))))},vRa=function(a,b){return new $APP.D(null,3,5,$APP.E,[$APP.Cg($APP.eW.j(a,b)),$APP.Cg($APP.eW.j(b,a)),$APP.Cg($APP.dW.j(a,b))],null)},e4=function(a){if(a!=null&&a.Vj!=null)a=a.Vj(a);else{var b=e4[$APP.ca(a==
null?null:a)];if(b!=null)a=b.h?b.h(a):b.call(null,a);else if(b=e4._,b!=null)a=b.h?b.h(a):b.call(null,a);else throw $APP.Jb("EqualityPartition.equality-partition",a);}return a},f4=function(a,b){if(a!=null&&a.Uj!=null)a=a.Uj(a,b);else{var c=f4[$APP.ca(a==null?null:a)];if(c!=null)a=c.j?c.j(a,b):c.call(null,a,b);else if(c=f4._,c!=null)a=c.j?c.j(a,b):c.call(null,a,b);else throw $APP.Jb("Diff.diff-similar",a);}return a},sRa=function(a,b){return $APP.Fe.j(a,b)?new $APP.D(null,3,5,$APP.E,[null,null,a],null):
$APP.Fe.j(e4(a),e4(b))?f4(a,b):c4(a,b)},wRa=new $APP.B(null,"sequential","sequential",-1082983960),g4=new $APP.B(null,"atom","atom",-397043653),xRa=new $APP.l(null,"diff","diff",-518492986,null);var d4=function d4(a){switch(arguments.length){case 2:return d4.j(arguments[0],arguments[1]);case 3:return d4.l(arguments[0],arguments[1],arguments[2]);default:throw Error(["Invalid arity: ",arguments.length].join(""));}};d4.j=function(a,b){return d4.l(a,b,$APP.cW.j($APP.Si(a),$APP.Si(b)))};d4.l=function(a,b,c){return $APP.Df.l(function(d,e){return $APP.rq.h($APP.qk.l($APP.km,d,e))},new $APP.D(null,3,5,$APP.E,[null,null,null],null),$APP.qk.j($APP.nm.l(tRa,a,b),c))};d4.v=3;e4["null"]=function(){return g4};
e4.string=function(){return g4};e4.number=function(){return g4};e4.array=function(){return wRa};e4["function"]=function(){return g4};e4["boolean"]=function(){return g4};e4._=function(a){return(a!=null?a.G&1024||$APP.ae===a.dh||(a.G?0:$APP.Hb($APP.lc,a)):$APP.Hb($APP.lc,a))?$APP.Vm:(a!=null?a.G&4096||$APP.ae===a.fh||(a.G?0:$APP.Hb($APP.qc,a)):$APP.Hb($APP.qc,a))?$APP.en:(a!=null?a.G&16777216||$APP.ae===a.tf||(a.G?0:$APP.Hb($APP.Nc,a)):$APP.Hb($APP.Nc,a))?wRa:g4};
f4["null"]=function(a,b){return c4(a,b)};f4.string=function(a,b){return c4(a,b)};f4.number=function(a,b){return c4(a,b)};f4.array=function(a,b){return uRa(a,b)};f4["function"]=function(a,b){return c4(a,b)};f4["boolean"]=function(a,b){return c4(a,b)};
f4._=function(a,b){var c=function(){var d=e4(a);d=d instanceof $APP.B?d.aa:null;switch(d){case "atom":return c4;case "set":return vRa;case "sequential":return uRa;case "map":return d4;default:throw Error("No matching clause: "+$APP.G.h(d));}}();return c.j?c.j(a,b):c.call(null,a,b)};var yRa=$APP.fY.j($APP.PR,null),zRa=new $APP.F(null,1,[xRa,$APP.at(sRa,xRa,new $APP.F(null,7,[$APP.P,xRa,$APP.O,"Recursively compares a and b, returning a tuple of\n  [things-only-in-a things-only-in-b things-in-both].\n  Comparison rules:\n\n  * For equal a and b, return [nil nil a].\n  * Maps are subdiffed where keys match and values differ.\n  * Sets are never subdiffed.\n  * All sequential things are treated as associative collections\n    by their indexes, with results returned as vectors.\n  * Everything else (including strings!) is treated as\n    an atom and compared for equality.",
$APP.X,$APP.I(new $APP.D(null,2,5,$APP.E,[$APP.OP,$APP.NP],null)),$APP.J,"clojure/data.cljs",$APP.K,144,$APP.M,7,$APP.S,yRa],null),yRa)],null);$APP.Hz(new $APP.F(null,1,[$APP.xt,new $APP.F(null,1,[$APP.PR,zRa],null)],null));