import { $APP, shadow$provide } from "./nbb_core.js";
const shadow_esm_import = function(x) { return import(x) };
import*as esm_import$node_process from"node:process";import*as esm_import$node_module from"node:module";import*as esm_import$node_fs from"node:fs";import*as esm_import$import_meta_resolve from"import-meta-resolve";import*as esm_import$node_path from"node:path";import*as esm_import$node_url from"node:url";var jJa,lJa,dJa,cJa,hJa,mJa,kJa,nJa;
$APP.bJa=function(a){a=$APP.ke(a);a=$APP.Po.j($APP.bg,a);a=$APP.Fo.j(function(d){return $APP.Ry($APP.rs(),d)},a);var b=$APP.xc($APP.zt),c=$APP.xc($APP.lt);return $APP.kz(a,new $APP.F(null,2,[$APP.S,b,$APP.I,c],null))};$APP.eJa=function(a,b){return cJa(dJa,a,b)};
$APP.lY=function(a,b){return Promise.resolve($APP.k($APP.xc(fJa))?null:function(){var c=esm_import$node_path.resolve($APP.k(a)?a:"script.cljs"),d=$APP.k($APP.rz.h(b))?$APP.Wi.o(b,$APP.$S,esm_import$node_path.dirname(esm_import$node_path.resolve($APP.rz.h(b))),$APP.v([$APP.rz,$APP.eU.h(esm_import$node_fs.readFileSync($APP.rz.h(b),"utf8"))],0)):function(){var h;a:{for(h=c;;){var m=esm_import$node_fs.existsSync(h);m=$APP.k(m)?esm_import$node_fs.lstatSync(h).isDirectory():m;if($APP.k(m)){m=esm_import$node_path.resolve(h,
"nbb.edn");if($APP.k(esm_import$node_fs.existsSync(m))){h=m;break a}m=esm_import$node_path.dirname(h)}else m=esm_import$node_path.dirname(h);if($APP.Ee.j(m,h)){h=null;break a}h=m}h=void 0}return $APP.k(h)?(m=$APP.eU.h(esm_import$node_fs.readFileSync(h,"utf8")),$APP.Wi.o(b,$APP.rz,m,$APP.v([$APP.$S,esm_import$node_path.dirname(h)],0))):b}(),e=gJa.h?gJa.h(c):gJa.call(null,c),f=""+$APP.G.h(esm_import$node_url.pathToFileURL(c));$APP.mz.require=e;$APP.bk.C($APP.oz,$APP.Wi,$APP.ko,e);$APP.bk.C($APP.oz,
$APP.Wi,$APP.pz,function(h){return esm_import$import_meta_resolve.resolve(h,f)});$APP.$g($APP.qz,d);return Promise.resolve(function(){var h=function(){var B=$APP.yb(hJa.h(d));return B?$APP.rz.h(d):B}();if($APP.k(h)){h=$APP.ns.h(h);if($APP.k(h)){h=$APP.n(h);for(var m=null,r=0,u=0;;)if(u<r){var x=m.U(null,u);$APP.yb(esm_import$node_path.isAbsolute(x))?$APP.as(function(){var B=$APP.$S.h(d);return $APP.k(B)?esm_import$node_path.resolve(B,x):x}()):$APP.as(x);u+=1}else if(h=$APP.n(h)){m=h;if($APP.df(m))h=
$APP.Dd(m),u=$APP.Fd(m),m=h,r=$APP.De(h),h=u;else{var z=$APP.p(m);$APP.yb(esm_import$node_path.isAbsolute(z))?$APP.as(function(){var B=$APP.$S.h(d);return $APP.k(B)?esm_import$node_path.resolve(B,z):z}()):$APP.as(z);h=$APP.q(m);m=null;r=0}u=0}else break}else $APP.as(esm_import$node_process.cwd());return shadow_esm_import("./nbb_deps.js")}return $APP.as(esm_import$node_process.cwd())}()).then(function(){return $APP.$g(fJa,!0)})}())};$APP.iJa=function(a,b){return $APP.ey(a,b)};
jJa=function(a,b){b=$APP.Qy(a,$APP.ql("(keys (ns-map '%s))","%s",b));b=$APP.qk.j(function(c){return"`"+$APP.G.h(c)},b);b="["+$APP.G.h($APP.Wn.j(" ",b))+"]";a=$APP.Oy(a,b,null);return $APP.Po.j(function(c){return $APP.Dl(""+$APP.G.h(c),"nbb.internal")},a)};
lJa=function(a,b){var c=$APP.rs();b=$APP.xl.j(b,/\//);$APP.t.l(b,0,null);var d=$APP.t.l(b,1,null),e=$APP.Qy(c,$APP.Xj.o($APP.v([$APP.T.h($APP.n($APP.N.o(new $APP.A(null,$APP.Dt,null,1,null),new $APP.A(null,$APP.Fh($APP.T.h($APP.n($APP.N.j(new $APP.A(null,kJa,null,1,null),new $APP.A(null,$APP.T.h($APP.n($APP.N.j(new $APP.A(null,$APP.Vsa,null,1,null),new $APP.A(null,$APP.T.h($APP.n($APP.N.j(new $APP.A(null,$APP.bl,null,1,null),new $APP.A(null,a,null,1,null)))),null,1,null)))),null,1,null))))),null,
1,null),$APP.v([new $APP.A(null,$APP.T.h($APP.n($APP.N.o(new $APP.A(null,$APP.US,null,1,null),new $APP.A(null,$APP.T.h($APP.n($APP.N.j(new $APP.A(null,$APP.tva,null,1,null),new $APP.A(null,kJa,null,1,null)))),null,1,null),$APP.v([new $APP.A(null,kJa,null,1,null)],0)))),null,1,null)],0))))],0)));if($APP.k(e)&&(c=$APP.k(d)?function(){var m=$APP.Ha(d,"."),r=$APP.xl.j(d,/\./);m=m?r:$APP.dj(r);r=$APP.E;var u=""+$APP.G.h(a)+"/",x=$APP.G,z=x.h;if($APP.n(m)){var B=$APP.Wn.j(".",m);B=""+$APP.G.h(B)+"."}else B=
null;return new $APP.D(null,2,5,r,[u+z.call(x,B),$APP.Wg.l($APP.Na,e,m)],null)}():new $APP.D(null,2,5,$APP.E,[""+$APP.G.h(a)+"/",e],null),$APP.k(c))){var f=$APP.t.l(c,0,null),h=$APP.t.l(c,1,null);c=function(){for(var m=h,r=$APP.ph;;)if($APP.k(m)){var u=Object.getPrototypeOf(m);r=$APP.ci.j(r,Object.getOwnPropertyNames(m));m=u}else return r}();return $APP.qk.j(function(m){return new $APP.D(null,2,5,$APP.E,[null,""+$APP.G.h(f)+$APP.G.h(m)],null)},c)}return null};
$APP.oJa=function(a){var b=$APP.Ag(a);a=$APP.y.j(b,$APP.S);try{var c=$APP.rs(),d=$APP.k(a)?$APP.iJa(c,$APP.Lj.h(a)):null,e=$APP.yg([$APP.zt,$APP.k(d)?d:$APP.xc($APP.zt)]);$APP.Ss(e);try{var f=function(){var la=$APP.Zm.h(b);return $APP.k(la)?la:$APP.JO.h(b)}();if($APP.k(f)){var h=$APP.Ja(f,"/"),m=h?function(){var la=$APP.xl.j(f,/\//);la=la==null?null:$APP.p(la);return la==null?null:$APP.Lj.h(la)}():null,r=jJa(c,$APP.Oy(c,"(ns-name *ns*)",null)),u=$APP.qk.j(function(la){return new $APP.D(null,3,5,$APP.E,
[$APP.dg(la),$APP.ej(la),mJa],null)},r),x=$APP.Oy(c,"(let [m (ns-aliases *ns*)] (zipmap (keys m) (map ns-name (vals m))))",null),z=$APP.fj($APP.Ui(x),$APP.Si(x)),B=$APP.tq.h($APP.lh.o(function(la){var qa=$APP.y.j(x,la);la=$APP.Qy(c,$APP.ql("(keys (ns-publics '%s))","%s",qa));return $APP.qk.j(function(ua){return new $APP.D(null,3,5,$APP.E,[""+$APP.G.h(qa),""+$APP.G.h(ua),nJa],null)},la)},$APP.v([$APP.Si(x)],0))),w=$APP.qk.j(function(la){return new $APP.D(null,3,5,$APP.E,[""+$APP.G.h(la),null,nJa],
null)},$APP.Oy(c,"(all-ns)",null)),P=h?lJa(m,f):null,K=$APP.k(P)?null:h?function(){var la=$APP.y.l(x,m,m),qa=$APP.Qy(c,$APP.ql("(and (find-ns '%s)\n                                                                                         (keys (ns-publics '%s)))","%s",la));return $APP.qk.j(function(ua){return new $APP.D(null,3,5,$APP.E,[""+$APP.G.h(la),""+$APP.G.h(ua),nJa],null)},qa)}():null,U=$APP.N.o(u,B,$APP.v([w,K],0)),X=$APP.jo.j(function(la){var qa=$APP.t.l(la,0,null);var ua=$APP.t.l(la,1,null);
la=$APP.t.l(la,2,null);la=$APP.Ee.j(mJa,la)&&$APP.Ja(ua,f)?new $APP.D(null,2,5,$APP.E,[qa,ua],null):null;$APP.k(la)?qa=la:$APP.k(qa)?(la=""+$APP.G.h($APP.y.j(z,$APP.Lj.h(qa)))+"/"+$APP.G.h(ua),la=$APP.Ja(la,f)?new $APP.D(null,2,5,$APP.E,[qa,la],null):null,$APP.k(la)?qa=la:(ua=""+$APP.G.h(qa)+"/"+$APP.G.h(ua),qa=$APP.Ja(ua,f)?new $APP.D(null,2,5,$APP.E,[qa,ua],null):null)):qa=null;return qa},U),fa=$APP.N.j(X,P),ka=$APP.Fh($APP.ap.h($APP.qk.j(function(la){var qa=$APP.t.l(la,0,null);la=$APP.t.l(la,1,
null);la=new $APP.F(null,1,["candidate",""+$APP.G.h(la)],null);return $APP.k(qa)?$APP.Wi.l(la,"ns",""+$APP.G.h(qa)):la},fa)));return new $APP.F(null,2,["completions",ka,"status",new $APP.D(null,1,5,$APP.E,["done"],null)],null)}return new $APP.F(null,1,["status",new $APP.D(null,1,5,$APP.E,["done"],null)],null)}finally{$APP.Us()}}catch(la){return console.warn(la),new $APP.F(null,2,["completions",$APP.ph,"status",new $APP.D(null,1,5,$APP.E,["done"],null)],null)}};dJa={};
cJa=function cJa(a,b,c){for(;;){if(b instanceof Promise)return b;if(dJa===a){if($APP.hf(b))return $APP.PW(b,b,c,cJa);a=$APP.xz(b,c)}else{b=Promise;var e=b.resolve;var f=$APP.Lo.h(c);f=$APP.k(f)?f:$APP.Cf;c=new $APP.F(null,1,[$APP.S,$APP.S.h(c)],null);c=f.j?f.j(a,c):f.call(null,a,c);return e.call(b,c)}}};$APP.mY=new $APP.l(null,"socket-repl","socket-repl",-1615225633,null);$APP.nY=new $APP.l(null,"repl","repl",1605132860,null);hJa=new $APP.C(null,"disableConfig","disableConfig",844586790);
mJa=new $APP.C(null,"unqualified","unqualified",-98904653);kJa=new $APP.l(null,"resolved__36920__auto__","resolved__36920__auto__",1919998472,null);nJa=new $APP.C(null,"qualified","qualified",-2065109343);$APP.oY=new $APP.l(null,"start-server!","start-server!",203437330,null);$APP.pY=new $APP.C(null,"classpath","classpath",299521985);var gJa,fJa;gJa=function(){var a=esm_import$node_module.createRequire;return $APP.k(a)?a:function(){return function(){throw Error("createRequire is not defined, this is a no-op");}}}();fJa=$APP.ak.h(!1);$APP.qY=function qY(a){switch(arguments.length){case 1:return qY.h(arguments[0]);case 2:return qY.j(arguments[0],arguments[1]);default:throw Error(["Invalid arity: ",arguments.length].join(""));}};$APP.qY.h=function(a){return $APP.qY.j(a,null)};
$APP.qY.j=function(a,b){b=$APP.sz.o(b,$APP.v([$APP.VC,!0],0));var c=esm_import$node_path.resolve(a);$APP.$g($APP.IGa,c);return $APP.lY(c,b).then(function(){return $APP.Cz(c)})};$APP.qY.A=2;$APP.rY=function rY(a){switch(arguments.length){case 1:return rY.h(arguments[0]);case 2:return rY.j(arguments[0],arguments[1]);default:throw Error(["Invalid arity: ",arguments.length].join(""));}};$APP.rY.h=function(a){return $APP.rY.j(a,null)};
$APP.rY.j=function(a,b){b=$APP.sz.o(b,$APP.v([$APP.VC,!0],0));return $APP.lY(null,b).then(function(){return $APP.Bz(a)})};$APP.rY.A=2;export const loadFile=$APP.qY;export const loadString=$APP.rY;export const getClassPath=function(){return $APP.$r()};export const addClassPath=function(a){return $APP.as(a)};export const version=function(){return $APP.Jz()};export const registerModule=function(a,b){b=$APP.Jla($APP.kl(b));return $APP.bk.C($APP.nz,$APP.Wi,b,a)};export const printErrorReport=$APP.SW;