import { $APP, shadow$provide } from "./nbb_core.js";
import "./nbb_api.js";
import "./nbb_impl_main.js";
const shadow_esm_import = function(x) { return import(x) };
import*as esm_import$node_process from"node:process";import*as esm_import$node_path from"node:path";
var $Va=function(a){a=$APP.Mj.h(a);var b=$APP.hg(a)?$APP.Mj.j(""+$APP.H.h(a),"-main"):a,c=$APP.fg(b);return $APP.ql("(require '$1) (apply $2 *command-line-args*)",/\$(\d)/,function(d){d=$APP.Ke(d);switch(d){case "1":return c;case "2":return b;default:throw Error("No matching clause: "+$APP.H.h(d));}})},aWa=function(a){var b=$APP.Mj.h(a),c=$APP.fg(b);return $APP.ql("\n(require '[babashka.cli])\n(require '$1)\n(let [the-var (resolve '$2)\n      the-var-meta (meta the-var)\n      ns (:ns (meta the-var))\n      ns-meta (meta ns)\n      cli-opts (babashka.cli/merge-opts (:org.babashka/cli ns-meta)\n                                        (:org.babashka/cli the-var-meta))\n      opts (babashka.cli/parse-opts *command-line-args* cli-opts)]\n  (the-var opts))\n",/\$(\d)/,
function(d){d=$APP.Ke(d);switch(d){case "1":return c;case "2":return b;default:throw Error("No matching clause: "+$APP.H.h(d));}})},bWa=function(a){for(var b=$APP.Ag,c=a;;){if($APP.l(c)){var d=$APP.p(c);a=$APP.r(c);switch(d){case "--help":case "-h":return $APP.Xi.l(b,$APP.aq,!0);case "--version":case "-v":return $APP.Xi.l(b,$APP.iTa,!0);case "-e":b=$APP.Xi.l(b,$APP.pr,$APP.p(a));c=a=$APP.r(a);continue;case "-m":case "--main":return $APP.Xi.o(b,$APP.pr,$Va($APP.p(a)),$APP.x([$APP.wo,$APP.r(a)],0));
case "-x":case "--exec":return $APP.Xi.o(b,$APP.pr,aWa($APP.p(a)),$APP.x([$APP.wo,$APP.r(a)],0));case "-cp":case "--classpath":b=$APP.Xi.l(b,$APP.u_,$APP.p(a));c=a=$APP.r(a);continue;case "--config":b=$APP.Xi.l(b,$APP.Zz,$APP.p(a));c=a=$APP.r(a);continue;case "--debug":b=$APP.Xi.l(b,$APP.kz,!0);c=a;continue;case "nrepl-server":b=$APP.Xi.l(b,$APP.eTa,!0);c=a;continue;case "socket-repl":b=$APP.Xi.l(b,$APP.fTa,!0);c=a;continue;case ":port":case "--port":b=$APP.Xi.l(b,$APP.QM,$APP.p(a));c=a=$APP.r(a);
continue;case ":host":case "--host":b=$APP.Xi.l(b,$APP.TU,$APP.p(a));c=a=$APP.r(a);continue;case "repl":b=$APP.Xi.l(b,$APP.hTa,!0);c=a;continue;case "bundle":return $APP.Xi.l(b,$APP.dR,$APP.zp.j(a,new $APP.G(null,1,[$APP.ro,new $APP.G(null,2,[$APP.jTa,$APP.jBa,$APP.bq,$APP.aq],null)],null)));default:if($APP.Bb($APP.pr.h(c)))return $APP.Xi.o(b,$APP.gTa,d,$APP.x([$APP.wo,$APP.r(c)],0));throw $APP.wm.j("Unrecognized options:"+$APP.H.h(c),$APP.Ag);}}else return b;break}};if($APP.l(esm_import$node_process.on))esm_import$node_process.on("unhandledRejection",function(a){console.error($APP.Kk(a));return process.exitCode=1});(function(){var a=$APP.n(function(){var g=globalThis.nbb_args;return $APP.l(g)?g:esm_import$node_process.argv}());$APP.p(a);a=$APP.r(a);$APP.p(a);a=$APP.r(a);var b=bWa(a);$APP.$g($APP.kTa,b);var c=$APP.gTa.h(b),d=$APP.pr.h(b);a=$APP.u_.h(b);$APP.l(a)&&$APP.$r(a);a=$APP.eTa.h(b);var e=function(){var g=$APP.hTa.h(b);if($APP.l(g))return g;g=$APP.fTa.h(b);return $APP.l(g)?g:$APP.Xe($APP.mm.o(b,$APP.u_,$APP.x([$APP.kz,$APP.Zz],0)))}(),f=$APP.dR.h(b);$APP.l($APP.aq.h(b))&&($APP.Ep.o($APP.x([$APP.raa("nbb"),
"version:",$APP.pA()],0)),$APP.Ep.o($APP.x(["\nHelp:\n\n -h / --help: print this help text and exit.\n -v / --version: print the current version of nbb.\n\nGlobal options:\n\n --debug: print additional debug info.\n -cp / --classpath: set the classpath.\n\nEvaluation:\n\n -e: execute expression\n -m / --main: execute main function\n -x / --exec: execute function using babashka.cli\n\nREPL:\n\n repl: start console REPL.\n nrepl-server: start nrepl server. [1,2]\n socket-repl: start socket repl server. [1]\n\n 1: Provide :port \x3cport\x3e to specify port\n 2: Provide :host \x3chost\x3e to specify host\n\nTooling:\n\n  bundle: produce single JS file for usage with bundlers.\n"],
0)),esm_import$node_process.exit(0));$APP.l($APP.iTa.h(b))&&($APP.Ep.o($APP.x([""+$APP.H.h("nbb")+" v"+$APP.H.h($APP.pA())],0)),esm_import$node_process.exit(0));return $APP.l($APP.l(c)?c:$APP.l(d)?d:$APP.l(a)?a:$APP.l(e)?e:f)?($APP.rY.j($APP.bGa,$APP.Yg($APP.wo.h(b))),Promise.resolve($APP.q_($APP.l(e)?esm_import$node_path.resolve("script.cljs"):c,b)).then(function(){return($APP.l(c)?$APP.v_.h(c):$APP.l(d)?$APP.w_.h(d):$APP.l($APP.eTa.h(b))?shadow_esm_import("./nbb_nrepl_server.js").then(function(){var g=
$APP.y.j($APP.y.j($APP.yt.h($APP.xe($APP.tt.h($APP.qs()))),$APP.UE),$APP.t_);return g.h?g.h(b):g.call(null,b)}):$APP.l($APP.l(e)?$APP.fTa.h(b):e)?shadow_esm_import("./nbb_repl.js").then(function(){var g=new $APP.G(null,1,[$APP.QM,$APP.QM.h(b)],null),k=$APP.y.j($APP.y.j($APP.yt.h($APP.xe($APP.tt.h($APP.qs()))),$APP.VD),$APP.r_);return k.h?k.h(g):k.call(null,g)}):$APP.l($APP.dR.h(b))?shadow_esm_import("./nbb_bundler.js"):$APP.l(e)?shadow_esm_import("./nbb_repl.js").then(function(){var g=$APP.y.j($APP.y.j($APP.yt.h($APP.xe($APP.tt.h($APP.qs()))),
$APP.VD),$APP.s_);return g.A?g.A():g.call(null)}):null).then(function(g){$APP.l($APP.l(d)?g!=null:d)&&$APP.jz.o($APP.x([g],0));return g}).catch(function(g){$APP.Zma(g,b);$APP.l($APP.kz.h(b))&&console.error(g);throw Error($APP.Kk(g));})})):console.error("Usage: "+$APP.H.h("nbb")+" \x3cscript\x3e or nbb -e \x3cexpr\x3e.")})();