import { $APP, shadow$provide } from "./nbb_core.js";
const shadow_esm_import = function(x) { return import(x) };
var sOa,uOa,vOa,g3,h3,wOa,xOa,yOa,zOa,AOa,BOa,COa,DOa,j3,EOa,l3,FOa,GOa,HOa,IOa,n3,o3,p3,JOa,s3,KOa,LOa,MOa,NOa,u3,OOa,POa,SOa,x3,TOa,UOa,VOa,WOa,XOa,ZOa,aPa,bPa,dPa,E3,hPa,jPa,kPa,lPa,mPa,nPa,oPa,rPa,F3,sPa,tPa,uPa,vPa,xPa,G3,zPa,APa,BPa,CPa,DPa,EPa,FPa,IPa,LPa,MPa,NPa,OPa,RPa,SPa,TPa,B3,UPa,VPa,WPa,XPa,YPa,JPa,ZPa,I3,$Pa,aQa,bQa,cQa,dQa,eQa,fQa,gQa,hQa,t3,iQa,iPa,jQa,kQa,lQa,J3,mQa,pPa,nQa,r3,oQa,pQa,qQa,A3,rQa,sQa,tQa,uQa,vQa,C3,wQa,xQa,yQa,zQa,QPa,AQa,BQa,CQa,L3,DQa,EQa,FQa,GQa,HQa,IQa,JQa,KQa,
M3,LQa,MQa,PPa,NQa,OQa,PQa,QQa,RQa,SQa,TQa,UQa,$Oa,VQa,WQa,fPa,XQa,YQa;sOa=function(a){return $APP.Ee(a)<2?$APP.rl(a):""+$APP.G.h($APP.rl($APP.vj.l(a,0,1)))+$APP.G.h($APP.vj.j(a,1))};uOa=function(a){if(typeof a==="string")return a;a=$APP.fj(a);var b=$APP.wl.j(a,/-/),c=$APP.n(b);b=$APP.p(c);c=$APP.q(c);return $APP.k(tOa.h?tOa.h(b):tOa.call(null,b))?a:$APP.Wg.l($APP.G,b,$APP.qk.j(sOa,c))};
vOa=function(a){var b=function(){var c=function(){var d=$APP.Qe(a);if(d){d=a.displayName;if($APP.k(d))return d;d=a.name;return typeof d==="string"&&$APP.n(d)?d:null}return d}();if($APP.k(c))return c;c=function(){var d=a!=null?a.K&4096||$APP.ae===a.ve?!0:!1:!1;return d?$APP.fj(a):d}();if($APP.k(c))return c;c=$APP.Te(a);return $APP.bf(c)?$APP.P.h(c):null}();return $APP.k(b)?$APP.pl(""+$APP.G.h(b),"$","."):null};g3=function(a){return a instanceof $APP.B||a instanceof $APP.l};
h3=function(a){if($APP.bf(a))try{var b=$APP.y.j(a,$APP.OJ)}catch(c){b=null}else b=null;return b};wOa=function(a){var b=$APP.OJ.h($APP.Te(a));if($APP.k(b))return b;b=h3($APP.w.l(a,1,null));if($APP.k(b))return b;b=$APP.w.l(a,0,null);switch(b instanceof $APP.B?b.aa:null){case "\x3e":case "f\x3e":return h3($APP.w.l(a,2,null));case "r\x3e":return a=$APP.w.l(a,2,null),a==null?null:a.key;default:return null}};xOa=function(a){return setTimeout(a,16)};yOa=function(a,b){return a.oh-b.oh};zOa=function(){return null};
AOa=function(a){for(var b=a.length,c=0;;)if(c<b){var d=a[c];d.A?d.A():d.call(null);c+=1}else return null};BOa=function(a,b,c){b.push(c);return a.schedule()};COa=function(){this.Ig=!1};DOa=function(a){if($APP.k(a.cljsIsDirty))return null;a.cljsIsDirty=!0;return i3.queue_render(a)};j3=function(a){if(a!=null&&a.al!=null)a=a.id;else{var b=j3[$APP.ca(a==null?null:a)];if(b!=null)a=b.h?b.h(a):b.call(null,a);else if(b=j3._,b!=null)a=b.h?b.h(a):b.call(null,a);else throw $APP.Jb("Compiler.get-id",a);}return a};
EOa=function(a,b,c){if(a!=null&&a.Zi!=null)a=a.Zi(a,b,c);else{var d=EOa[$APP.ca(a==null?null:a)];if(d!=null)a=d.l?d.l(a,b,c):d.call(null,a,b,c);else if(d=EOa._,d!=null)a=d.l?d.l(a,b,c):d.call(null,a,b,c);else throw $APP.Jb("Compiler.parse-tag",a);}return a};
$APP.k3=function(a,b){if(a!=null&&a.Xi!=null)a=a.Xi(a,b);else{var c=$APP.k3[$APP.ca(a==null?null:a)];if(c!=null)a=c.j?c.j(a,b):c.call(null,a,b);else if(c=$APP.k3._,c!=null)a=c.j?c.j(a,b):c.call(null,a,b);else throw $APP.Jb("Compiler.as-element",a);}return a};
l3=function(a,b,c,d,e){if(a!=null&&a.Yi!=null)a=a.Yi(a,b,c,d,e);else{var f=l3[$APP.ca(a==null?null:a)];if(f!=null)a=f.N?f.N(a,b,c,d,e):f.call(null,a,b,c,d,e);else if(f=l3._,f!=null)a=f.N?f.N(a,b,c,d,e):f.call(null,a,b,c,d,e);else throw $APP.Jb("Compiler.make-element",a);}return a};
FOa=function(a,b){b.Vg=null;var c=m3;m3=b;try{var d=a.A?a.A():a.call(null)}finally{m3=c}a=b.Vg;b.ke=!1;a:{c=b.Qe;var e=a==null?0:a.length,f=e===(c==null?0:c.length);if(f){for(f=0;;){var g=f===e;if(g){c=g;break a}if(a[f]===c[f])f+=1;else{c=!1;break a}}c=void 0}else c=f}c||b._update_watching(a);return d};GOa=function(a){var b=m3;if(b!=null){var c=b.Vg;c==null?b.Vg=[a]:c.push(a)}};HOa=function(a,b,c){b=$APP.Wi.l(a.Fb,b,c);a.Fb=b;return a.Gh=null};
IOa=function(a,b){b=$APP.lm.j(a.Fb,b);a.Fb=b;return a.Gh=null};n3=function(a,b,c){var d=a.Gh;d=d==null?a.Gh=$APP.Ff(function(r,t,v){r.push(t);r.push(v);return r},[],a.Fb):d;for(var e=d.length,f=0;;)if(f<e){var g=d[f],m=d[f+1];m.C?m.C(g,a,b,c):m.call(null,g,a,b,c);f=2+f}else return null};o3=function(a,b,c,d){$APP.cd(a,"#object[reagent.ratom."+$APP.G.h(c)+" ");c=m3;m3=null;m3=c;$APP.Dj(d,a,b);return $APP.cd(a,"]")};
p3=function(a,b,c,d){this.state=a;this.I=b;this.Og=c;this.Fb=d;this.G=2154201088;this.K=114690};JOa=function(a,b,c,d,e){var f=b.Ah;f=f==null?$APP.Ag:f;var g=f.j?f.j(c,null):f.call(null,c,null);if(g!=null)return $APP.yc(g);if(m3==null)return a.A?a.A():a.call(null);g=function(){function r(t){var v=$APP.lm.j(b.Ah,c);b.Ah=v;d!=null&&(d.Qf=null);return e!=null?e.h?e.h(t):e.call(null,t):null}return q3.l?q3.l(a,r3,r):q3.call(null,a,r3,r)}();var m=$APP.yc(g);b.Ah=$APP.Wi.l(f,c,g);d!=null&&(d.Qf=g);return m};
s3=function(a,b){this.f=a;this.lf=b;this.Qf=null;this.G=2153807872;this.K=0};KOa=function(a,b){return new s3(a,b)};LOa=function(a,b){var c=KOa(a,b);a=function(){function d(){return c.Ha(null)}return q3.l?q3.l(d,t3,!0):q3.call(null,d,t3,!0)}();$APP.yc(a);return a};MOa=function(a,b){this.Kb=a;this.path=b;this.Fb=this.state=this.Qf=null;this.G=2153807872;this.K=114690};NOa=function(a){a=a.destroy;return a==null?null:a.A?a.A():a.call(null)};
u3=function(a){if(a!=null&&a.Bh!=null)a=a.Bh(a);else{var b=u3[$APP.ca(a==null?null:a)];if(b!=null)a=b.h?b.h(a):b.call(null,a);else if(b=u3._,b!=null)a=b.h?b.h(a):b.call(null,a);else throw $APP.Jb("IDisposable.dispose!",a);}return a};OOa=function(a,b,c,d){return a._handle_change(b,c,d)};POa=function(a){this.f=a;this.state=null;this.ke=!0;this.si=!1;this.Wg=this.Md=this.Fb=this.Qe=null;this.G=2153807872;this.K=114690};
$APP.w3=function(){for(;;){var a=v3;if(a==null)return null;v3=null;for(var b=a.length,c=0;;)if(c<b)a[c]._queued_run(),c+=1;else break}};SOa=function(a,b){var c=QOa,d=ROa,e=FOa(a,d);d.Qe!=null&&(ROa=q3(null),d._set_opts(c),d.f=a,d.Md=function(){return DOa.h?DOa.h(b):DOa.call(null,b)},b.cljsRatom=d);return e};
x3=function(a,b){var c=b.argv;if(c==null){c=$APP.E;a=a.constructor;a:{for(var d=$APP.Va(b),e=d.length,f=$APP.Ag,g=0;;)if(g<e){var m=d[g];f=$APP.Wi.l(f,$APP.Fj.h(m),$APP.Xa(b,m));g+=1}else{b=f;break a}b=void 0}b=new $APP.D(null,2,5,c,[a,b],null)}else b=c;return b};TOa=function(a){var b;if(b=$APP.Qe(a))a=a==null?null:a.prototype,b=(a==null?null:a.me)!=null;return b};UOa=function(a){var b;if(b=$APP.Qe(a))a=a==null?null:a.prototype,b=(a==null?null:a.render)!=null;return b};
VOa=function(a,b){for(;;){var c=a.me,d=a.Rj===!0?c.call(a,a):function(){var e=x3(a,a.props);switch($APP.Ee(e)){case 1:return c.call(a);case 2:return c.call(a,$APP.w.j(e,1));case 3:return c.call(a,$APP.w.j(e,1),$APP.w.j(e,2));case 4:return c.call(a,$APP.w.j(e,1),$APP.w.j(e,2),$APP.w.j(e,3));case 5:return c.call(a,$APP.w.j(e,1),$APP.w.j(e,2),$APP.w.j(e,3),$APP.w.j(e,4));default:return c.apply(a,$APP.Tu.h(e).slice(1))}}();if($APP.df(d))return $APP.k3(b,d);if($APP.lf(d))a.me=TOa(d)?function(e,f,g,m,r){return function(){function t(z){var C=
null;if(arguments.length>0){C=0;for(var u=Array(arguments.length-0);C<u.length;)u[C]=arguments[C+0],++C;C=new $APP.he(u,0,null)}return v.call(this,C)}function v(z){return $APP.k3(f,$APP.Wg.l($APP.gB,r,z))}t.v=0;t.B=function(z){z=$APP.n(z);return v(z)};t.o=v;return t}()}(a,b,c,null,d):d;else return d}};WOa=function(a,b){var c=y3;y3=a;try{return VOa(a,b)}finally{y3=c}};
XOa=function(a,b){switch(a instanceof $APP.B?a.aa:null){case "getDefaultProps":throw Error("getDefaultProps not supported");case "getDerivedStateFromProps":return function(c,d){var e=b.call,f=c.argv;f!=null&&(c=$APP.w.l(f,1,null),c=$APP.bf(c)?c:null);return e.call(b,null,c,d)};case "getInitialState":return function(c){var d=c.Tj;d=d!=null?d:c.Tj=z3.h(null);return $APP.$g(d,b.call(c,c))};case "getSnapshotBeforeUpdate":return function(c,d){return b.call(this,this,x3(this,c),d)};case "componentWillReceiveProps":return function(c){return b.call(this,
this,x3(this,c))};case "UNSAFE_componentWillReceiveProps":return function(c){return b.call(this,this,x3(this,c))};case "shouldComponentUpdate":return function(c){if($APP.k(!1))return!1;var d=this.props.argv,e=c.argv,f=d==null||e==null;if(b==null){if(f)return f;try{return $APP.Vi.j(d,e)}catch(g){return!1}}else return f?b.call(this,this,x3(this,this.props),x3(this,c)):b.call(this,this,d,e)};case "componentWillUpdate":return function(c,d){return b.call(this,this,x3(this,c),d)};case "UNSAFE_componentWillUpdate":return function(c,
d){return b.call(this,this,x3(this,c),d)};case "componentDidUpdate":return function(c,d,e){return b.call(this,this,x3(this,c),d,e)};case "componentWillMount":return function(){return b.call(this,this)};case "UNSAFE_componentWillMount":return function(){return b.call(this,this)};case "componentDidMount":return function(){return b.call(this,this)};case "componentWillUnmount":return function(){var c=$APP.Xa(this,"cljsRatom");c!=null&&u3(c);this.cljsIsDirty=!1;return b==null?null:b.call(this,this)};case "componentDidCatch":return function(c,
d){return b.call(this,this,c,d)};default:return null}};ZOa=function(a){return $APP.Ff(function(b,c,d){return $APP.Wi.l(b,$APP.Fj.h(YOa(c)),d)},$APP.Ag,a)};
aPa=function(a,b){var c=function(){var g=A3.h(a);return $APP.k(g)?g:B3.h(a)}(),d=A3.h(a)==null,e=function(){var g=C3.h(a);if($APP.k(g))return g;g=vOa(c);return $APP.k(g)?g:""+$APP.G.h($APP.Bq.h("reagent"))}(),f=$APP.Ff(function(g,m,r){var t=$APP.Wi.l,v=XOa(m,r);return t.call($APP.Wi,g,m,$APP.k(v)?v:r)},$APP.Ag,a);return $APP.Wi.o(f,C3,e,$APP.x([$Oa,d,A3,c,B3,function(){var g=this;if($APP.D3)return WOa(g,b);var m=$APP.Xa(g,"cljsRatom");g.cljsIsDirty=!1;return m==null?SOa(function(){return WOa(g,b)},
g):m._run(!1)}],0))};bPa=function(a){return $APP.Ff(function(b,c,d){c=$APP.fj(c);b[c]=d;return b},{},a)};dPa=function(a,b){a=ZOa(a);a=$APP.km.o($APP.x([cPa,a],0));return aPa(a,b)};
E3=function(a,b){function c(m,r,t){$APP.jz.nbb$internal$react.Component.call(this,m,r,t);$APP.k(g)&&(g.j?g.j(this,m):g.call(null,this,m));$APP.k(f)&&(this.state=f.h?f.h(this):f.call(null,this));this.oh=ePa+=1;return this}a=dPa(a,b);b=bPa($APP.Wg.o($APP.lm,a,C3,fPa,$APP.mx,$APP.x([B3,A3,gPa],0)));var d=bPa($APP.Xi(a,gPa)),e=C3.h(a),f=fPa.h(a),g=$APP.mx.h(a);$APP.Za(c.prototype,$APP.jz.nbb$internal$react.Component.prototype,b);$APP.k(B3.h(a))&&(c.prototype.render=B3.h(a));$APP.k(A3.h(a))&&(c.prototype.me=
A3.h(a));$APP.k($Oa.h(a))&&(c.prototype.Rj=$Oa.h(a));$APP.Za(c,$APP.jz.nbb$internal$react.Component,d);$APP.k(e)&&(c.displayName=e,c.qg=e,c.Qj=function(m){return $APP.cd(m,e)},Object.defineProperty(c,"name",{value:e,writable:!1}));c.ki=!0;return c.prototype.constructor=c};hPa=function(a,b,c){a=j3(a);return b[a]=c};jPa=function(a,b){var c=$APP.Xa(a,j3(b));c==null?TOa(a)?a=hPa(b,a,a):(c=$APP.Te(a),c=$APP.Wi.l(c,iPa,a),c=E3(c,b),a=hPa(b,a,c)):a=c;return a};
kPa=function(a,b){for(;;){var c=b.me,d=b.argv,e=$APP.Wg.j(c,d);if($APP.df(e))return $APP.k3(a,e);if($APP.lf(e))b.me=TOa(e)?function(f,g,m,r,t,v){return function(){function z(u){var H=null;if(arguments.length>0){H=0;for(var Q=Array(arguments.length-0);H<Q.length;)Q[H]=arguments[H+0],++H;H=new $APP.he(Q,0,null)}return C.call(this,H)}function C(u){return $APP.k3(f,$APP.Wg.l($APP.gB,v,u))}z.v=0;z.B=function(u){u=$APP.n(u);return C(u)};z.o=C;return z}()}(a,b,c,null,d,e):e;else return e}};
lPa=function(a,b){var c=y3;y3=b;try{return kPa(a,b)}finally{y3=c}};
mPa=function(a,b){if($APP.D3)return lPa(a,b);var c=b.argv,d=b.me;b=$APP.jz.nbb$internal$react.useState(0);$APP.w.l(b,0,null);var e=$APP.w.l(b,1,null),f=$APP.jz.nbb$internal$react.useRef();$APP.k(f.current)||function(){var m={forceUpdate:function(){return e.h?e.h($APP.te):e.call(null,$APP.te)}};m.oh=ePa+=1;m.constructor=d;m.me=d;return f.current=m}();var g=f.current;b=$APP.Xa(g,"cljsRatom");$APP.jz.nbb$internal$react.useEffect(function(){return function(){var m=$APP.Xa(g,"cljsRatom");return m==null?
null:u3(m)}},[]);g.argv=c;g.cljsIsDirty=!1;return b==null?SOa(function(){return lPa(a,g)},g):b._run(!1)};nPa=function(a,b){a=a.argv;b=b.argv;try{return $APP.Fe.j(a,b)}catch(c){return!1}};oPa=function(a,b){function c(e){return mPa(a,e)}var d=$APP.Xa(b,j3(a));if($APP.k(d))return d;d=vOa(b);c.displayName=d;Object.defineProperty(c,"name",{value:d,writable:!1});d=$APP.jz.nbb$internal$react.memo(c,nPa);hPa(a,b,d);return d};
rPa=function(a,b,c,d){var e=$APP.Bg($APP.Ag);e=$APP.y.j(e,pPa);if(a===document.activeElement&&$APP.sf(qPa,a.type)&&typeof b==="string"&&typeof c==="string"){var f=a.value;if($APP.Vi.j(f,c))return i3.add_after_render(function(){return F3.h?F3.h(d):F3.call(null,d)});c=$APP.Ee(f)-a.selectionStart;c=$APP.Ee(b)-c;d.rg=b;a.value=b;$APP.Qe(e)&&(e.h?e.h(b):e.call(null,b));a.selectionStart=c;return a.selectionEnd=c}d.rg=b;a.value=b;return $APP.Qe(e)?e.h?e.h(b):e.call(null,b):null};
F3=function(a){if($APP.k(a.nh)){a.mi=!1;var b=a.Sj,c=a.rg,d=a.th;return $APP.Vi.j(b,c)?rPa(d,b,c,a):null}return null};sPa=function(a,b,c){a.rg=c.target.value;$APP.k(a.mi)||(a.mi=!0,i3.add_after_render(function(){return F3(a)}));return b.h?b.h(c):b.call(null,c)};
tPa=function(a){var b=y3;if($APP.k(function(){var f=a!=null;return f?(f=a.hasOwnProperty("onChange"),$APP.k(f)?a.hasOwnProperty("value"):f):f}())){var c=a.value;c=c==null?"":c;var d=a.onChange,e=a.ref;$APP.k(b.nh)||(b.nh=!0,b.rg=c);$APP.k(b.$i)||(b.$i=$APP.Qe(e)?function(f){b.th=f;return e.h?e.h(f):e.call(null,f)}:$APP.k($APP.k(e)?e.hasOwnProperty("current"):e)?function(f){b.th=f;return e.current=f}:function(f){return b.th=f});b.Sj=c;delete a.value;a.defaultValue=c;a.onChange=function(f){return sPa(b,
d,f)};a.ref=b.$i}};uPa=function(a){this.tag=a;this.className=this.id=null};vPa=function(a,b){return a.hasOwnProperty(b)?$APP.Xa(a,b):null};xPa=function(a,b,c){if(g3(b)){var d=vPa(wPa,$APP.fj(b));d==null?(d=uOa(b),b=$APP.fj(b),b=wPa[b]=d):b=d}c=G3.h?G3.h(c):G3.call(null,c);a[b]=c;return a};
G3=function(a){return"object"!==$APP.ca(a)?a:g3(a)?$APP.fj(a):$APP.bf(a)?$APP.Ff(xPa,{},a):$APP.Xe(a)?$APP.PC(a):$APP.lf(a)?function(){function b(d){var e=null;if(arguments.length>0){e=0;for(var f=Array(arguments.length-0);e<f.length;)f[e]=arguments[e+0],++e;e=new $APP.he(f,0,null)}return c.call(this,e)}function c(d){return $APP.Wg.j(a,d)}b.v=0;b.B=function(d){d=$APP.n(d);return c(d)};b.o=c;return b}():$APP.PC(a)};
zPa=function(a,b,c){if(g3(b)){var d=vPa(yPa,$APP.fj(b));d==null?(d=uOa(b),b=$APP.fj(b),b=yPa[b]=d):b=d}c=G3(c);a[b]=c;return a};
APa=function(a){return"object"!==$APP.ca(a)?a:g3(a)?$APP.fj(a):$APP.bf(a)?$APP.Ff(zPa,{},a):$APP.Xe(a)?$APP.PC(a):$APP.lf(a)?function(){function b(d){var e=null;if(arguments.length>0){e=0;for(var f=Array(arguments.length-0);e<f.length;)f[e]=arguments[e+0],++e;e=new $APP.he(f,0,null)}return c.call(this,e)}function c(d){return $APP.Wg.j(a,d)}b.v=0;b.B=function(d){d=$APP.n(d);return c(d)};b.o=c;return b}():$APP.PC(a)};
BPa=function(a,b,c,d,e){switch($APP.Ee(b)-e){case 0:return $APP.jz.nbb$internal$react.createElement(c,d);case 1:return $APP.jz.nbb$internal$react.createElement(c,d,$APP.k3(a,$APP.w.l(b,e,null)));default:return $APP.jz.nbb$internal$react.createElement.apply(null,$APP.Ff(function(f,g,m){g>=e&&f.push($APP.k3(a,m));return f},[c,d],b))}};CPa=function(a,b,c,d){this.tag=a;this.id=b;this.className=c;this.Zj=d};
DPa=function(a,b,c){a=jPa(a,c);c={};c.argv=b;b=wOa(b);b!=null&&(c.key=b);return $APP.jz.nbb$internal$react.createElement(a,c)};EPa=function(a,b,c,d){var e={};e.me=a;e.argv=$APP.vl.j(b,c);b=wOa(b);b!=null&&(e.key=b);return $APP.jz.nbb$internal$react.createElement(oPa(d,a),e)};FPa=function(a,b,c){return UOa(a)?DPa(a,b,c):EPa(a,b,1,c)};
IPa=function(a,b){a=vPa(GPa,b);if(a==null){var c=$APP.q($APP.sj(HPa,$APP.fj(b)));a=$APP.w.l(c,0,null);var d=$APP.w.l(c,1,null);c=$APP.w.l(c,2,null);c=c==null?null:$APP.pl(c,/\./," ");var e=$APP.Vi.j(-1,a.indexOf("-"));a=new CPa(a,d,c,e);return GPa[b]=a}return a};
LPa=function(a,b,c,d){var e=a.tag,f=$APP.w.l(b,c,null),g=f==null||$APP.bf(f),m=function(){var v=g?f:null;var z=$APP.Fu.h(v);z=$APP.k(z)?$APP.Wi.l(v,$APP.Fu,H3.h(z)):v;var C=a.id;v=a.className;C=C!=null&&$APP.st.h(z)==null?$APP.Wi.l(z,$APP.st,C):z;if($APP.k(v)){var u=$APP.Wi.l,H=H3.j,Q=$APP.Fu.h(z);z=$APP.k(Q)?Q:JPa.h(z);v=u.call($APP.Wi,C,$APP.Fu,H.call(H3,v,z))}else v=C;v=$APP.k(a.Zj)?APa(v):G3(v);return $APP.k(v)?v:{}}();c+=g?1:0;a:switch(e){case "input":case "textarea":var r=!0;break a;default:r=
!1}if(r){r=h3(f);var t=function(){var v=d.bl;if($APP.k(v))return v;v=E3(KPa,d);return d.bl=v}();return $APP.k3(d,$APP.Se(new $APP.D(null,6,5,$APP.E,[t,b,e,m,c,d],null),$APP.km.o($APP.x([$APP.k(r)?new $APP.F(null,1,[$APP.OJ,r],null):null,$APP.Te(b)],0))))}r=h3($APP.Te(b));r!=null&&(m.key=r);return l3(d,b,e,m,c)};MPa=function(a,b){return $APP.Tu.h($APP.qk.j(function(c){return $APP.k3(b,c)},a))};
NPa=function(a,b,c){b==null&&console.error("vec-to-elem",$APP.Xj.o($APP.x([a],0)));var d=$APP.w.l(a,0,null);switch(d instanceof $APP.B?d.aa:null){case "\x3e":return c=$APP.w.l(a,1,null),LPa(new CPa(c,null,null,null),a,2,b);case "r\x3e":c=$APP.w.l(a,1,null);d=$APP.w.l(a,2,null);d=$APP.k(d)?d:{};var e=h3($APP.Te(a));e!=null&&(d.key=e);return l3(b,a,c,d,3);case "f\x3e":return EPa($APP.w.l(a,1,null),a,2,b);case "\x3c\x3e":return d=$APP.w.l(a,1,null),c=d==null||$APP.bf(d),d=G3(c?d:null),d=$APP.k(d)?d:
{},c=1+(c?1:0),e=wOa(a),e!=null&&(d.key=e),l3(b,a,$APP.jz.nbb$internal$react.Fragment,d,c);default:if(g3(d)||typeof d==="string")a:{for(;;){c=$APP.w.l(a,0,null);d=$APP.fj(c);e=d.indexOf("\x3e");switch(e){case -1:b=LPa(EOa(b,d,c),a,1,b);break a;case 0:b=null;break a;default:a=$APP.Se(new $APP.D(null,2,5,$APP.E,[$APP.vj.l(d,0,e),$APP.Wi.l($APP.Se(a,null),0,$APP.vj.j(d,e+1))],null),$APP.Te(a));continue}break}b=void 0}else b=d instanceof uPa?LPa(d,a,1,b):c.l?c.l(d,a,b):c.call(null,d,a,b);return b}};
OPa=function(a,b,c,d,e){this.Jc=a;this.id=b;this.pi=c;this.Cg=d;this.Mk=e;this.G=393216;this.K=0};RPa=function(a){var b=$APP.Bq.h("reagent-compiler"),c=$APP.k(PPa.h(a))?FPa:DPa,d=$APP.y.l(a,QPa,IPa);return new OPa(a,b,c,d,$APP.Ag)};SPa=function(a){return new uPa(a)};TPa=new $APP.l(null,"-generation","-generation",627658965,null);B3=new $APP.B(null,"render","render",-1408033454);UPa=new $APP.l(null,"on-set","on-set",1499578057,null);
VPa=new $APP.l("reagent.ratom","make-reaction","reagent.ratom/make-reaction",272608527,null);WPa=new $APP.l(null,"dispose!","dispose!",-395693497,null);XPa=new $APP.l("reagent.ratom","-destroy","reagent.ratom/-destroy",-1284026419,null);YPa=new $APP.B(null,"componentWillUnmount","componentWillUnmount",1573788814);JPa=new $APP.B(null,"className","className",-1983287057);ZPa=new $APP.l(null,"-tracking?","-tracking?",-1106885352,null);I3=new $APP.l(null,"with-let","with-let",-1310113408,null);
$Pa=new $APP.l(null,"with-let-values","with-let-values",1929572375,null);aQa=new $APP.l(null,"create-class","create-class",-665911586,null);bQa=new $APP.B(null,"childContextTypes","childContextTypes",578717991);cQa=new $APP.l(null,"class2","class2",-1266396392,null);dQa=new $APP.l(null,"class1","class1",-1905977651,null);eQa=new $APP.l(null,"auto-run","auto-run",-696035332,null);fQa=new $APP.l(null,"destroy__39132__auto__","destroy__39132__auto__",-1015722691,null);
gQa=new $APP.l(null,"-set-ratom-generation!","-set-ratom-generation!",-1545989828,null);hQa=new $APP.l(null,"-destroy","-destroy",-557272508,null);t3=new $APP.B(null,"auto-run","auto-run",1958400437);iQa=new $APP.l(null,"track-console","track-console",17070495,null);iPa=new $APP.B(null,"reagent-render","reagent-render",-985383853);jQa=new $APP.B(null,"contextTypes","contextTypes",-2023853910);kQa=new $APP.l(null,"create-compiler","create-compiler",1059333141,null);
lQa=new $APP.l(null,"props","props",2093813254,null);J3=new $APP.l(null,"reaction","reaction",2131401315,null);mQa=new $APP.B(null,"on-set","on-set",-140953470);pPa=new $APP.B(null,"on-write","on-write",31519475);nQa=new $APP.l(null,"reactive?","reactive?",1213887990,null);r3=new $APP.B(null,"on-dispose","on-dispose",2105306360);$APP.K3=new $APP.l(null,"compiler","compiler",1372604796,null);oQa=new $APP.l("reagent.ratom","-destroy!","reagent.ratom/-destroy!",-337873850,null);
pQa=new $APP.l(null,"-destroy!","-destroy!",143253949,null);qQa=new $APP.l("sci.configs.reagent.reagent","error","sci.configs.reagent.reagent/error",1433174531,null);A3=new $APP.B(null,"reagentRender","reagentRender",-358306383);rQa=new $APP.l(null,"cursor","cursor",-1642498285,null);sQa=new $APP.l(null,"make-reaction","make-reaction",1935680112,null);tQa=new $APP.B(null,"contextType","contextType",1033066077);uQa=new $APP.B(null,"component-did-update","component-did-update",-1468549173);
vQa=new $APP.l(null,"src","src",-10544524,null);C3=new $APP.B(null,"displayName","displayName",-809144601);wQa=new $APP.B(null,"display-name","display-name",694513143);xQa=new $APP.l("sci.configs.reagent.reagent","reaction","sci.configs.reagent.reagent/reaction",-1324858361,null);yQa=new $APP.l(null,"others","others",-569561186,null);zQa=new $APP.B(null,"getDerivedStateFromProps","getDerivedStateFromProps",-991834739);QPa=new $APP.B(null,"parse-tag","parse-tag",1427313738);
AQa=new $APP.l(null,"destroy","destroy",796871122,null);BQa=new $APP.B(null,"shouldComponentUpdate","shouldComponentUpdate",1795750960);CQa=new $APP.l(null,"-ratom-generation","-ratom-generation",-176468250,null);L3=new $APP.l(null,"adapt-react-class","adapt-react-class",1221068673,null);DQa=new $APP.l(null,"track","track",1836319014,null);EQa=new $APP.l(null,".hasOwnProperty",".hasOwnProperty",-1264659034,null);FQa=new $APP.l(null,"reagent.debug","reagent.debug",1010511129,null);
GQa=new $APP.l(null,"reactify-component","reactify-component",-882526483,null);HQa=new $APP.l("js","console","js/console",-1426368245,null);IQa=new $APP.l(null,"sci.configs.reagent.reagent","sci.configs.reagent.reagent",94604865,null);JQa=new $APP.B(null,"no-cache","no-cache",1588056370);KQa=new $APP.l("cljs.core","zero?","cljs.core/zero?",-341242858,null);M3=new $APP.l(null,"track!","track!",-516308489,null);LQa=new $APP.l(null,".error",".error",1756007195,null);
MQa=new $APP.l("reagent.debug","-tracking?","reagent.debug/-tracking?",409956583,null);PPa=new $APP.B(null,"function-components","function-components",1492814963);NQa=new $APP.l("reagent.ratom","reactive?","reagent.ratom/reactive?",-358553475,null);OQa=new $APP.l(null,"as-element","as-element",-2139409597,null);PQa=new $APP.l(null,"make-track","make-track",-1388299455,null);QQa=new $APP.l("reagent.debug","track-console","reagent.debug/track-console",-1553126476,null);
RQa=new $APP.l(null,"on-dispose","on-dispose",-549129409,null);SQa=new $APP.B(null,"component-will-unmount","component-will-unmount",-2058314698);TQa=new $APP.l("reagent.ratom","with-let-values","reagent.ratom/with-let-values",-575838306,null);UQa=new $APP.l(null,"-ratom-context","-ratom-context",1646839514,null);$Oa=new $APP.B(null,"cljsLegacyRender","cljsLegacyRender",-1527295613);VQa=new $APP.l("sci.configs.reagent.reagent","with-let","sci.configs.reagent.reagent/with-let",65759084,null);
WQa=new $APP.l(null,"class-names","class-names",-1397320704,null);fPa=new $APP.B(null,"getInitialState","getInitialState",1541760916);XQa=new $APP.B(null,"getDerivedStateFromError","getDerivedStateFromError",166658477);YQa=new $APP.l(null,"create-element","create-element",1833774591,null);var ZQa=$APP.ak.h(null),$Qa=function(){var a={};a.warn=function(){function b(d){var e=null;if(arguments.length>0){e=0;for(var f=Array(arguments.length-0);e<f.length;)f[e]=arguments[e+0],++e;e=new $APP.he(f,0,null)}return c.call(this,e)}function c(d){return $APP.bk.o(ZQa,$APP.im,new $APP.D(null,1,5,$APP.E,[$APP.eAa],null),$APP.$f,$APP.x([$APP.Wg.j($APP.G,d)],0))}b.v=0;b.B=function(d){d=$APP.n(d);return c(d)};b.o=c;return b}();a.error=function(){function b(d){var e=null;if(arguments.length>0){e=0;for(var f=
Array(arguments.length-0);e<f.length;)f[e]=arguments[e+0],++e;e=new $APP.he(f,0,null)}return c.call(this,e)}function c(d){return $APP.bk.o(ZQa,$APP.im,new $APP.D(null,1,5,$APP.E,[$APP.bq],null),$APP.$f,$APP.x([$APP.Wg.j($APP.G,d)],0))}b.v=0;b.B=function(d){d=$APP.n(d);return c(d)};b.o=c;return b}();return a}();var aRa,tOa,H3;aRa=typeof window!=="undefined"&&window.document!=null;$APP.D3=!1;tOa=new $APP.Zi(null,new $APP.F(null,2,["aria",null,"data",null],null),null);H3=function H3(a){switch(arguments.length){case 0:return H3.A();case 1:return H3.h(arguments[0]);case 2:return H3.j(arguments[0],arguments[1]);default:for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return H3.o(arguments[0],arguments[1],2<c.length?new $APP.he(c.slice(2),0,null):null)}};H3.A=function(){return null};
H3.h=function(a){return $APP.Xe(a)?(a=$APP.io.j(function(b){return $APP.k(b)?g3(b)?$APP.fj(b):b:null},a),$APP.n(a)?$APP.Un.j(" ",a):null):g3(a)?$APP.fj(a):a};H3.j=function(a,b){return $APP.k(a)?$APP.k(b)?""+$APP.G.h(H3.h(a))+" "+$APP.G.h(H3.h(b)):H3.h(a):H3.h(b)};H3.o=function(a,b,c){return $APP.Df.l(H3,H3.j(a,b),c)};H3.B=function(a){var b=$APP.p(a),c=$APP.q(a);a=$APP.p(c);c=$APP.q(c);return this.o(b,a,c)};H3.v=2;var ePa=0,bRa=aRa?function(){var a=window;return function(){var b=a.requestAnimationFrame;if($APP.k(b))return b;b=a.webkitRequestAnimationFrame;if($APP.k(b))return b;b=a.mozRequestAnimationFrame;if($APP.k(b))return b;b=a.msRequestAnimationFrame;return $APP.k(b)?b:xOa}().bind(a)}():xOa;$APP.h=COa.prototype;$APP.h.flush_after_render=function(){var a=this.$f;if(a==null)return null;this.$f=null;return AOa(a)};
$APP.h.queue_render=function(a){this.componentQueue==null&&(this.componentQueue=[]);return BOa(this,this.componentQueue,a)};$APP.h.schedule=function(){function a(){return b.run_queues()}var b=this;if(this.Ig)return null;this.Ig=!0;return bRa.h?bRa.h(a):bRa.call(null,a)};$APP.h.flush_before_flush=function(){var a=this.cg;if(a==null)return null;this.cg=null;return AOa(a)};$APP.h.flush_queues=function(){this.flush_before_flush();zOa();this.flush_render();return this.flush_after_render()};
$APP.h.run_queues=function(){this.Ig=!1;return this.flush_queues()};$APP.h.add_before_flush=function(a){this.cg==null&&(this.cg=[]);return BOa(this,this.cg,a)};$APP.h.add_after_render=function(a){this.$f==null&&(this.$f=[]);return BOa(this,this.$f,a)};$APP.h.flush_render=function(){var a=this.componentQueue;if(a==null)return null;this.componentQueue=null;a:{a.sort(yOa);for(var b=a.length,c=0;;)if(c<b){var d=a[c];d.cljsIsDirty===!0&&d.forceUpdate();c+=1}else{a=null;break a}a=void 0}return a};
var i3=new COa;var m3;$APP.ak.h(0);var v3=null;$APP.h=p3.prototype;$APP.h.Y=function(a,b,c){return o3(b,c,"RAtom",new $APP.F(null,1,[$APP.Ky,this.Ha(null)],null))};$APP.h.U=function(){return this.I};$APP.h.ea=function(){return $APP.sa(this)};$APP.h.P=function(a,b){return this===b};$APP.h.qc=function(a,b){a=this.state;this.state=b;this.Fb!=null&&n3(this,a,b);return b};$APP.h.uf=function(a,b){return this.qc(null,b.h?b.h(this.state):b.call(null,this.state))};
$APP.h.vf=function(a,b,c){return this.qc(null,b.j?b.j(this.state,c):b.call(null,this.state,c))};$APP.h.wf=function(a,b,c,d){return this.qc(null,b.l?b.l(this.state,c,d):b.call(null,this.state,c,d))};$APP.h.xf=function(a,b,c,d,e){return this.qc(null,$APP.Wg.N(b,this.state,c,d,e))};$APP.h.je=function(a,b,c){return n3(this,b,c)};$APP.h.ye=function(a,b,c){return HOa(this,b,c)};$APP.h.ze=function(a,b){return IOa(this,b)};$APP.h.X=function(a,b){return new p3(this.state,b,this.Og,this.Fb)};
$APP.h.Ha=function(){GOa(this);return this.state};var z3=function z3(a){switch(arguments.length){case 1:return z3.h(arguments[0]);default:for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return z3.o(arguments[0],1<c.length?new $APP.he(c.slice(1),0,null):null)}};z3.h=function(a){return new p3(a,null,null,null)};z3.o=function(a,b){var c=$APP.Bg(b);b=$APP.y.j(c,$APP.Bj);c=$APP.y.j(c,$APP.woa);return new p3(a,b,c,null)};
z3.B=function(a){var b=$APP.p(a);a=$APP.q(a);return this.o(b,a)};z3.v=1;s3.prototype.Ha=function(){var a=this,b=a.Qf;return b==null?JOa(function(){return $APP.Wg.j(a.f,a.lf)},a.f,a.lf,this,null):$APP.yc(b)};s3.prototype.P=function(a,b){return b instanceof s3&&$APP.Fe.j(this.f,b.f)&&$APP.Fe.j(this.lf,b.lf)};s3.prototype.ea=function(){return $APP.be(new $APP.D(null,2,5,$APP.E,[this.f,this.lf],null))};
s3.prototype.Y=function(a,b,c){return o3(b,c,"Track",new $APP.F(null,2,[$APP.Ky,this.Ha(null),$APP.sU,this.f],null))};var N3=function N3(a){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return N3.o(arguments[0],1<c.length?new $APP.he(c.slice(1),0,null):null)};N3.o=function(a,b){return LOa(a,b)};N3.v=1;N3.B=function(a){var b=$APP.p(a);a=$APP.q(a);return this.o(b,a)};$APP.h=MOa.prototype;
$APP.h._peek=function(){var a=m3;m3=null;try{return this.Ha(null)}finally{m3=a}};$APP.h._set_state=function(a,b){if(a===b)return null;this.state=b;return this.Fb!=null?n3(this,a,b):null};$APP.h.Y=function(a,b,c){return o3(b,c,"RCursor",new $APP.F(null,2,[$APP.Ky,this.Ha(null),$APP.es,this.path],null))};$APP.h.ea=function(){return $APP.be(new $APP.D(null,2,5,$APP.E,[this.Kb,this.path],null))};$APP.h.P=function(a,b){return b instanceof MOa&&$APP.Fe.j(this.path,b.path)&&$APP.Fe.j(this.Kb,b.Kb)};
$APP.h.qc=function(a,b){this._set_state(this.state,b);(this.Kb!=null?this.Kb.G&32768||$APP.ae===this.Kb.ue||(this.Kb.G?0:$APP.Hb($APP.xc,this.Kb)):$APP.Hb($APP.xc,this.Kb))?$APP.Fe.j(this.path,$APP.rh)?$APP.$g(this.Kb,b):$APP.bk.C(this.Kb,$APP.lo,this.path,b):this.Kb.j?this.Kb.j(this.path,b):this.Kb.call(null,this.path,b);return b};$APP.h.uf=function(a,b){a=this.qc;var c=this._peek();b=b.h?b.h(c):b.call(null,c);return a.call(this,null,b)};
$APP.h.vf=function(a,b,c){a=this.qc;var d=this._peek();b=b.j?b.j(d,c):b.call(null,d,c);return a.call(this,null,b)};$APP.h.wf=function(a,b,c,d){a=this.qc;var e=this._peek();b=b.l?b.l(e,c,d):b.call(null,e,c,d);return a.call(this,null,b)};$APP.h.xf=function(a,b,c,d,e){return this.qc(null,$APP.Wg.N(b,this._peek(),c,d,e))};$APP.h.je=function(a,b,c){return n3(this,b,c)};$APP.h.ye=function(a,b,c){return HOa(this,b,c)};$APP.h.ze=function(a,b){return IOa(this,b)};
$APP.h.Ha=function(){var a=this,b=this,c=a.state,d=function(){var e=a.Qf;return e==null?JOa((a.Kb!=null?a.Kb.G&32768||$APP.ae===a.Kb.ue||(a.Kb.G?0:$APP.Hb($APP.xc,a.Kb)):$APP.Hb($APP.xc,a.Kb))?function(){return $APP.$n.j($APP.yc(a.Kb),a.path)}:function(){return a.Kb.h?a.Kb.h(a.path):a.Kb.call(null,a.path)},a.Kb,a.path,b,null):$APP.yc(e)}();b._set_state(c,d);return d};$APP.h=POa.prototype;$APP.h._peek_at=function(){var a=m3;m3=null;try{return this.Ha(null)}finally{m3=a}};
$APP.h._handle_change=function(a,b,c){return b===c||this.ke?null:this.Md==null?(this.ke=!0,v3==null&&(v3=[],i3.Ig===!1&&i3.schedule()),v3.push(this)):this.Md===!0?this._run(!1):this.Md.h?this.Md.h(this):this.Md.call(null,this)};
$APP.h._update_watching=function(a){var b=$APP.cj(a),c=$APP.cj(this.Qe);this.Qe=a;a=$APP.n($APP.bW.j(b,c));for(var d=null,e=0,f=0;;)if(f<e){var g=d.R(null,f);$APP.kd(g,this,OOa);f+=1}else if(a=$APP.n(a))d=a,$APP.ef(d)?(a=$APP.Ed(d),f=$APP.Fd(d),d=a,e=$APP.Ee(a),a=f):(a=$APP.p(d),$APP.kd(a,this,OOa),a=$APP.q(d),d=null,e=0),f=0;else break;b=$APP.n($APP.bW.j(c,b));c=null;for(e=d=0;;)if(e<d)a=c.R(null,e),$APP.ld(a,this),e+=1;else if(b=$APP.n(b))c=b,$APP.ef(c)?(b=$APP.Ed(c),d=$APP.Fd(c),c=b,a=$APP.Ee(b),
b=d,d=a):(a=$APP.p(c),$APP.ld(a,this),b=$APP.q(c),c=null,d=0),e=0;else return null};$APP.h._queued_run=function(){return this.ke&&this.Qe!=null?this._run(!0):null};$APP.h._try_capture=function(a){try{return this.Wg=null,FOa(a,this)}catch(b){return this.Wg=this.state=a=b,this.ke=!1}};$APP.h._run=function(a){var b=this.state;a=$APP.k(a)?this._try_capture(this.f):FOa(this.f,this);this.si||(this.state=a,this.Fb==null||$APP.Fe.j(b,a)||n3(this,b,a));return a};
$APP.h._set_opts=function(a){var b=$APP.Bg(a);a=$APP.y.j(b,t3);var c=$APP.y.j(b,mQa),d=$APP.y.j(b,r3);b=$APP.y.j(b,JQa);a!=null&&(this.Md=a);c!=null&&(this.Tk=c);d!=null&&(this.ui=d);return b!=null?this.si=b:null};$APP.h.Y=function(a,b,c){return o3(b,c,"Reaction",new $APP.F(null,1,[$APP.Ky,this.Ha(null)],null))};$APP.h.ea=function(){return $APP.sa(this)};$APP.h.P=function(a,b){return this===b};
$APP.h.Bh=function(){var a=this.state,b=this.Qe;this.Md=this.state=this.Qe=null;this.ke=!0;b=$APP.n($APP.cj(b));for(var c=null,d=0,e=0;;)if(e<d){var f=c.R(null,e);$APP.ld(f,this);e+=1}else if(b=$APP.n(b))c=b,$APP.ef(c)?(b=$APP.Ed(c),e=$APP.Fd(c),c=b,d=$APP.Ee(b),b=e):(b=$APP.p(c),$APP.ld(b,this),b=$APP.q(c),c=null,d=0),e=0;else break;this.ui!=null&&this.ui(a);a=this.Gl;if(a==null)return null;b=a.length;for(c=0;;)if(c<b)d=a[c],d.h?d.h(this):d.call(null,this),c+=1;else return null};
$APP.h.qc=function(a,b){a=this.state;this.state=b;this.Tk(a,b);n3(this,a,b);return b};$APP.h.uf=function(a,b){a=this.qc;var c=this._peek_at();b=b.h?b.h(c):b.call(null,c);return a.call(this,null,b)};$APP.h.vf=function(a,b,c){a=this.qc;var d=this._peek_at();b=b.j?b.j(d,c):b.call(null,d,c);return a.call(this,null,b)};$APP.h.wf=function(a,b,c,d){a=this.qc;var e=this._peek_at();b=b.l?b.l(e,c,d):b.call(null,e,c,d);return a.call(this,null,b)};
$APP.h.xf=function(a,b,c,d,e){return this.qc(null,$APP.Wg.N(b,this._peek_at(),c,d,e))};$APP.h.je=function(a,b,c){return n3(this,b,c)};$APP.h.ye=function(a,b,c){return HOa(this,b,c)};$APP.h.ze=function(a,b){a=$APP.We(this.Fb);IOa(this,b);return!a&&$APP.We(this.Fb)&&this.Md==null?this.Bh(null):null};
$APP.h.Ha=function(){var a=this.Wg;if(a!=null)throw a;(a=m3==null)&&($APP.w3.A?$APP.w3.A():$APP.w3.call(null));a&&this.Md==null?this.ke&&(a=this.state,this.state=this.f.A?this.f.A():this.f.call(null),this.Fb==null||$APP.Fe.j(a,this.state)||n3(this,a,this.state)):(GOa(this),this.ke&&this._run(!1));return this.state};zOa=$APP.w3;var q3=function q3(a){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return q3.o(arguments[0],1<c.length?new $APP.he(c.slice(1),0,null):null)};
q3.o=function(a,b){var c=$APP.Bg(b);b=$APP.y.j(c,t3);var d=$APP.y.j(c,mQa);c=$APP.y.j(c,r3);a=new POa(a);a._set_opts(new $APP.F(null,3,[t3,b,mQa,d,r3,c],null));return a};q3.v=1;q3.B=function(a){var b=$APP.p(a);a=$APP.q(a);return this.o(b,a)};var ROa=q3(null);var y3,QOa=new $APP.F(null,1,[JQa,!0],null),cPa=new $APP.F(null,2,[BQa,null,YPa,null],null),YOa=function(a){var b=$APP.ak.h($APP.Ag);return function(c){var d=$APP.y.j($APP.yc(b),c);if(d!=null)return d;d=a.h?a.h(c):a.call(null,c);$APP.bk.C(b,$APP.Wi,c,d);return d}}(function(a){if(typeof a==="string")return a;a=$APP.fj(a);a=$APP.pl(a,/(unsafe|UNSAFE)[-_]/,"UNSAFE_");a=$APP.wl.j(a,/-/);var b=$APP.n(a);a=$APP.p(b);b=$APP.q(b);return $APP.Wg.l($APP.G,a,$APP.qk.j(sOa,b))}),gPa=new $APP.D(null,5,5,$APP.E,
[bQa,jQa,tQa,zQa,XQa],null);var qPa=new $APP.Zi(null,new $APP.F(null,6,["url",null,"tel",null,"text",null,"textarea",null,"password",null,"search",null],null),null),KPa=new $APP.F(null,4,[wQa,"ReagentInput",uQa,F3,SQa,function(a){return a.nh=null},iPa,function(a,b,c,d,e){tPa(c);return l3(e,a,b,c,d)}],null);var HPa=/([^\s\.#]+)(?:#([^\s\.#]+))?(?:\.([^\s#]+))?/,wPa={"class":"className","for":"htmlFor",charset:"charSet"},yPa={},GPa={};$APP.h=OPa.prototype;$APP.h.X=function(a,b){return new OPa(this.Jc,this.id,this.pi,this.Cg,b)};$APP.h.U=function(){return this.Mk};$APP.h.al=function(){return this.id};$APP.h.Zi=function(a,b,c){return this.Cg.l?this.Cg.l(this,b,c):this.Cg.call(null,this,b,c)};
$APP.h.Xi=function(a,b){return"object"!==$APP.ca(b)?b:$APP.df(b)?NPa(b,this,this.pi):$APP.hf(b)?MPa(b,this):g3(b)?$APP.fj(b):(b!=null?b.G&2147483648||$APP.ae===b.Ga||(b.G?0:$APP.Hb($APP.ed,b)):$APP.Hb($APP.ed,b))?$APP.Xj.o($APP.x([b],0)):b};$APP.h.Yi=function(a,b,c,d,e){return BPa(this,b,c,d,e)};$APP.O3=RPa($APP.Ag);var P3=function P3(a){switch(arguments.length){case 1:return P3.h(arguments[0]);case 2:return P3.j(arguments[0],arguments[1]);case 3:return P3.l(arguments[0],arguments[1],arguments[2]);default:for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return P3.o(arguments[0],arguments[1],arguments[2],3<c.length?new $APP.he(c.slice(3),0,null):null)}};P3.h=function(a){return P3.j(a,null)};P3.j=function(a,b){return $APP.jz.nbb$internal$react.createElement(a,b)};
P3.l=function(a,b,c){return $APP.jz.nbb$internal$react.createElement(a,b,c)};P3.o=function(a,b,c,d){return $APP.Wg.N($APP.jz.nbb$internal$react.createElement,a,b,c,d)};P3.B=function(a){var b=$APP.p(a),c=$APP.q(a);a=$APP.p(c);var d=$APP.q(c);c=$APP.p(d);d=$APP.q(d);return this.o(b,a,c,d)};P3.v=3;var Q3=function Q3(a){switch(arguments.length){case 1:return Q3.h(arguments[0]);case 2:return Q3.j(arguments[0],arguments[1]);default:throw Error(["Invalid arity: ",arguments.length].join(""));}};
Q3.h=function(a){return $APP.k3($APP.O3,a)};Q3.j=function(a,b){return $APP.k3(b,a)};Q3.v=2;var R3=function R3(a){switch(arguments.length){case 1:return R3.h(arguments[0]);case 2:return R3.j(arguments[0],arguments[1]);default:throw Error(["Invalid arity: ",arguments.length].join(""));}};R3.h=function(a){return R3.j(a,$APP.O3)};R3.j=function(a,b){return UOa(a)?a:jPa(a,b)};R3.v=2;
var S3=function S3(a){switch(arguments.length){case 1:return S3.h(arguments[0]);case 2:return S3.j(arguments[0],arguments[1]);default:throw Error(["Invalid arity: ",arguments.length].join(""));}};S3.h=function(a){return E3(a,$APP.O3)};S3.j=function(a,b){return E3(a,b)};S3.v=2;
var T3=function T3(a){switch(arguments.length){case 0:return T3.A();case 1:return T3.h(arguments[0]);case 2:return T3.j(arguments[0],arguments[1]);default:for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return T3.o(arguments[0],arguments[1],2<c.length?new $APP.he(c.slice(2),0,null):null)}};T3.A=function(){return null};T3.h=function(a){return H3.h(a)};T3.j=function(a,b){return H3.j(a,b)};T3.o=function(a,b,c){return $APP.Wg.C(H3,a,b,c)};
T3.B=function(a){var b=$APP.p(a),c=$APP.q(a);a=$APP.p(c);c=$APP.q(c);return this.o(b,a,c)};T3.v=2;var U3=function U3(a){switch(arguments.length){case 1:return U3.h(arguments[0]);default:for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return U3.o(arguments[0],1<c.length?new $APP.he(c.slice(1),0,null):null)}};U3.h=function(a){return z3.h(a)};U3.o=function(a,b){return $APP.Wg.l(z3,a,b)};U3.B=function(a){var b=$APP.p(a);a=$APP.q(a);return this.o(b,a)};U3.v=1;
var V3=function V3(a){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return V3.o(arguments[0],1<c.length?new $APP.he(c.slice(1),0,null):null)};V3.o=function(a,b){return KOa(a,b)};V3.v=1;V3.B=function(a){var b=$APP.p(a);a=$APP.q(a);return this.o(b,a)};var W3=function W3(a){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return W3.o(arguments[0],1<c.length?new $APP.he(c.slice(1),0,null):null)};W3.o=function(a,b){return LOa(a,b)};
W3.v=1;W3.B=function(a){var b=$APP.p(a);a=$APP.q(a);return this.o(b,a)};var X3=function X3(a){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return X3.o(arguments[0],arguments[1],arguments[2],3<c.length?new $APP.he(c.slice(3),0,null):null)};
X3.o=function(a,b,c,d){var e=$APP.Bq.h("with-let");a=$APP.Fj.h(e);var f=$APP.Bq.h("init");c=$APP.fi.j(new $APP.D(null,2,5,$APP.E,[f,$APP.T.h($APP.n($APP.N.j(new $APP.A(null,KQa,null,1,null),new $APP.A(null,$APP.T.h($APP.n($APP.N.j(new $APP.A(null,$APP.iQ,null,1,null),new $APP.A(null,e,null,1,null)))),null,1,null))))],null),$APP.az.j(function(r,t){if($APP.Ug(r))return t;r=$APP.Qf(r,2);return $APP.T.h($APP.n($APP.N.o(new $APP.A(null,$APP.Rk,null,1,null),new $APP.A(null,$APP.T.h($APP.n($APP.N.o(new $APP.A(null,
$APP.WO,null,1,null),new $APP.A(null,f,null,1,null),$APP.x([new $APP.A(null,$APP.T.h($APP.n($APP.N.j(new $APP.A(null,$APP.ry,null,1,null),new $APP.A(null,$APP.T.h($APP.n($APP.N.o(new $APP.A(null,EQa,null,1,null),new $APP.A(null,e,null,1,null),$APP.x([new $APP.A(null,r,null,1,null)],0)))),null,1,null)))),null,1,null)],0)))),null,1,null),$APP.x([new $APP.A(null,$APP.T.h($APP.n($APP.N.o(new $APP.A(null,$APP.Yxa,null,1,null),new $APP.A(null,e,null,1,null),$APP.x([new $APP.A(null,r,null,1,null),new $APP.A(null,
t,null,1,null)],0)))),null,1,null),new $APP.A(null,$APP.T.h($APP.n($APP.N.o(new $APP.A(null,$APP.gra,null,1,null),new $APP.A(null,e,null,1,null),$APP.x([new $APP.A(null,r,null,1,null)],0)))),null,1,null)],0))))},c));var g=function(){var r=$APP.Ne(d);return $APP.hf(r)&&$APP.Fe.j($APP.Ok,$APP.p(r))?new $APP.D(null,2,5,$APP.E,[$APP.ej(d),$APP.T.h($APP.n($APP.N.o(new $APP.A(null,$APP.cu,null,1,null),new $APP.A(null,$APP.Gh($APP.T.h($APP.n($APP.N.A()))),null,1,null),$APP.x([$APP.me(r)],0))))],null):new $APP.D(null,
2,5,$APP.E,[d,null],null)}();b=$APP.w.l(g,0,null);g=$APP.w.l(g,1,null);g=$APP.k(g)?new $APP.A(null,$APP.T.h($APP.n($APP.N.o(new $APP.A(null,$APP.Ct,null,1,null),new $APP.A(null,$APP.Gh($APP.T.h($APP.n($APP.N.j(new $APP.A(null,fQa,null,1,null),new $APP.A(null,g,null,1,null))))),null,1,null),$APP.x([new $APP.A(null,$APP.T.h($APP.n($APP.N.o(new $APP.A(null,$APP.Rk,null,1,null),new $APP.A(null,$APP.T.h($APP.n($APP.N.h(new $APP.A(null,NQa,null,1,null)))),null,1,null),$APP.x([new $APP.A(null,$APP.T.h($APP.n($APP.N.o(new $APP.A(null,
$APP.fE,null,1,null),new $APP.A(null,$APP.T.h($APP.n($APP.N.j(new $APP.A(null,$APP.JM,null,1,null),new $APP.A(null,$APP.T.h($APP.n($APP.N.j(new $APP.A(null,XPa,null,1,null),new $APP.A(null,e,null,1,null)))),null,1,null)))),null,1,null),$APP.x([new $APP.A(null,$APP.T.h($APP.n($APP.N.o(new $APP.A(null,oQa,null,1,null),new $APP.A(null,e,null,1,null),$APP.x([new $APP.A(null,fQa,null,1,null)],0)))),null,1,null)],0)))),null,1,null),new $APP.A(null,$APP.T.h($APP.n($APP.N.h(new $APP.A(null,fQa,null,1,null)))),
null,1,null)],0)))),null,1,null)],0)))),null,1,null):null;var m=$APP.Bq.h("res");return $APP.T.h($APP.n($APP.N.o(new $APP.A(null,$APP.Ct,null,1,null),new $APP.A(null,$APP.Gh($APP.T.h($APP.n($APP.N.j(new $APP.A(null,e,null,1,null),new $APP.A(null,$APP.T.h($APP.n($APP.N.j(new $APP.A(null,TQa,null,1,null),new $APP.A(null,a,null,1,null)))),null,1,null))))),null,1,null),$APP.x([new $APP.A(null,null,null,1,null),new $APP.A(null,$APP.T.h($APP.n($APP.N.o(new $APP.A(null,$APP.Ct,null,1,null),new $APP.A(null,
$APP.fi.j(c,new $APP.D(null,2,5,$APP.E,[m,$APP.T.h($APP.n($APP.N.j(new $APP.A(null,$APP.Qk,null,1,null),b)))],null)),null,1,null),$APP.x([g,new $APP.A(null,m,null,1,null)],0)))),null,1,null)],0))))};X3.v=3;X3.B=function(a){var b=$APP.p(a),c=$APP.q(a);a=$APP.p(c);var d=$APP.q(c);c=$APP.p(d);d=$APP.q(d);return this.o(b,a,c,d)};var Y3=function Y3(a){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return Y3.o(0<c.length?new $APP.he(c.slice(0),0,null):null)};
Y3.o=function(a){return $APP.T.h($APP.n($APP.N.j(new $APP.A(null,VPa,null,1,null),new $APP.A(null,$APP.T.h($APP.n($APP.N.o(new $APP.A(null,$APP.cu,null,1,null),new $APP.A(null,$APP.Gh($APP.T.h($APP.n($APP.N.A()))),null,1,null),$APP.x([a],0)))),null,1,null))))};Y3.v=0;Y3.B=function(a){return this.o($APP.n(a))};
var Z3=$APP.cY.j($APP.WN,null),cRa=$APP.Hi([aQa,DQa,I3,$APP.YD,WQa,J3,OQa,GQa,YQa,WPa,rQa,M3,kQa,L3],[$APP.$s(S3,aQa,new $APP.F(null,7,[$APP.P,aQa,$APP.O,"Creates JS class based on provided Clojure map, for example:\n\n  ```cljs\n  {;; Constructor\n   :constructor (fn [this props])\n   :get-initial-state (fn [this])\n   ;; Static methods\n   :get-derived-state-from-props (fn [props state] partial-state)\n   :get-derived-state-from-error (fn [error] partial-state)\n   ;; Methods\n   :get-snapshot-before-update (fn [this old-argv new-argv] snapshot)\n   :should-component-update (fn [this old-argv new-argv])\n   :component-did-mount (fn [this])\n   :component-did-update (fn [this old-argv old-state snapshot])\n   :component-will-unmount (fn [this])\n   :component-did-catch (fn [this error info])\n   :reagent-render (fn [args....])\n   ;; Or alternatively:\n   :render (fn [this])\n   ;; Deprecated methods:\n   :UNSAFE_component-will-receive-props (fn [this new-argv])\n   :UNSAFE_component-will-update (fn [this new-argv new-state])\n   :UNSAFE_component-will-mount (fn [this])}\n  ```\n\n  Everything is optional, except either :reagent-render or :render.\n\n  Map keys should use `React.Component` method names (https://reactjs.org/docs/react-component.html),\n  and can be provided in snake-case or camelCase.\n\n  State can be initialized using constructor, which matches React.Component class,\n  or using getInitialState which matches old React createClass function and is\n  now implemented by Reagent for compatibility.\n\n  State can usually be anything, e.g. Cljs object. But if using getDerivedState\n  methods, the state has to be plain JS object as React implementation uses\n  Object.assign to merge partial state into the current state.\n\n  React built-in static methods or properties are automatically defined as statics.",$APP.X,
$APP.I(new $APP.D(null,1,5,$APP.E,[$APP.ZC],null),new $APP.D(null,2,5,$APP.E,[$APP.ZC,$APP.K3],null)),$APP.J,"reagent/core.cljs",$APP.K,68,$APP.M,7,$APP.S,Z3],null),Z3),$APP.$s(V3,DQa,new $APP.F(null,7,[$APP.P,DQa,$APP.O,"Takes a function and optional arguments, and returns a derefable\n  containing the output of that function. If the function derefs\n  Reagent atoms (or track, etc), the value will be updated whenever\n  the atom changes.\n\n  In other words, `@(track foo bar)` will produce the same result\n  as `(foo bar)`, but foo will only be called again when the atoms it\n  depends on changes, and will only trigger updates of components when\n  its result changes.\n\n  track is lazy, i.e the function is only evaluated on deref.",
$APP.X,$APP.I($APP.Se(new $APP.D(null,3,5,$APP.E,[$APP.NP,$APP.Lk,$APP.VH],null),new $APP.F(null,1,[$APP.Gp,new $APP.D(null,1,5,$APP.E,[$APP.I($APP.iM,$APP.NP)],null)],null))),$APP.J,"reagent/core.cljs",$APP.K,218,$APP.M,7,$APP.S,Z3],null),Z3),$APP.$s($APP.xe(new $APP.ee(function(){return X3},VQa,$APP.Hi([$APP.S,$APP.P,$APP.J,$APP.Ht,$APP.JQ,$APP.M,$APP.K,$APP.dt,$APP.Gt,$APP.X,$APP.O,$APP.GK],[IQa,I3,"sci/configs/reagent/reagent.cljs",23,new $APP.F(null,6,[$APP.fo,!0,$APP.dw,1,$APP.zT,1,$APP.KS,
$APP.I($APP.I($APP.MD,$APP.bG)),$APP.X,$APP.I(new $APP.D(null,3,5,$APP.E,[$APP.MD,$APP.Lk,$APP.bG],null)),$APP.wK,$APP.I(null)],null),1,10,!0,10,$APP.I(new $APP.D(null,3,5,$APP.E,[$APP.MD,$APP.Lk,$APP.bG],null)),null,$APP.k(X3)?X3.V:null]))),I3,new $APP.F(null,8,[$APP.P,I3,$APP.O,null,$APP.dt,!0,$APP.X,$APP.I(new $APP.D(null,5,5,$APP.E,[$APP.ww,$APP.ww,$APP.MD,$APP.Lk,$APP.bG],null)),$APP.J,"sci/configs/reagent/reagent.cljs",$APP.K,10,$APP.M,15,$APP.S,Z3],null),Z3),$APP.$s(U3,$APP.YD,new $APP.F(null,
7,[$APP.P,$APP.YD,$APP.O,"Like clojure.core/atom, except that it keeps track of derefs.\n  Reagent components that derefs one of these are automatically\n  re-rendered.",$APP.X,$APP.I(new $APP.D(null,1,5,$APP.E,[$APP.aQ],null),new $APP.D(null,3,5,$APP.E,[$APP.aQ,$APP.Lk,$APP.fF],null)),$APP.J,"reagent/core.cljs",$APP.K,211,$APP.M,7,$APP.S,Z3],null),Z3),$APP.$s(T3,WQa,new $APP.F(null,7,[$APP.P,WQa,$APP.O,"Function which normalizes and combines class values to a string\n\n  Reagent allows classes to be defined as:\n  - Strings\n  - Named objects (Symbols or Keywords)\n  - Collections of previous types",
$APP.X,$APP.I($APP.rh,new $APP.D(null,1,5,$APP.E,[$APP.QI],null),new $APP.D(null,2,5,$APP.E,[dQa,cQa],null),new $APP.D(null,4,5,$APP.E,[dQa,cQa,$APP.Lk,yQa],null)),$APP.J,"reagent/core.cljs",$APP.K,179,$APP.M,7,$APP.S,Z3],null),Z3),$APP.$s($APP.xe(new $APP.ee(function(){return Y3},xQa,$APP.Hi([$APP.S,$APP.P,$APP.J,$APP.Ht,$APP.JQ,$APP.M,$APP.K,$APP.dt,$APP.Gt,$APP.X,$APP.O,$APP.GK],[IQa,J3,"sci/configs/reagent/reagent.cljs",23,new $APP.F(null,6,[$APP.fo,!0,$APP.dw,-2,$APP.zT,-2,$APP.KS,$APP.I($APP.le),
$APP.X,$APP.I($APP.rh),$APP.wK,$APP.I(null)],null),1,62,!0,62,$APP.I($APP.rh),null,$APP.k(Y3)?Y3.V:null]))),J3,new $APP.F(null,8,[$APP.P,J3,$APP.O,null,$APP.dt,!0,$APP.X,$APP.I(new $APP.D(null,2,5,$APP.E,[$APP.Lk,$APP.bG],null)),$APP.J,"sci/configs/reagent/reagent.cljs",$APP.K,62,$APP.M,15,$APP.S,Z3],null),Z3),$APP.$s(Q3,OQa,new $APP.F(null,7,[$APP.P,OQa,$APP.O,"Turns a vector of Hiccup syntax into a React element. Returns form\n  unchanged if it is not a vector.",$APP.X,$APP.I(new $APP.D(null,1,
5,$APP.E,[$APP.RO],null),new $APP.D(null,2,5,$APP.E,[$APP.RO,$APP.K3],null)),$APP.J,"reagent/core.cljs",$APP.K,46,$APP.M,7,$APP.S,Z3],null),Z3),$APP.$s(R3,GQa,new $APP.F(null,7,[$APP.P,GQa,$APP.O,"Returns an adapter for a Reagent component, that may be used from\n  React, for example in JSX. A single argument, props, is passed to\n  the component, converted to a map.",$APP.X,$APP.I(new $APP.D(null,1,5,$APP.E,[$APP.MP],null),new $APP.D(null,2,5,$APP.E,[$APP.MP,$APP.K3],null)),$APP.J,"reagent/core.cljs",
$APP.K,59,$APP.M,7,$APP.S,Z3],null),Z3),$APP.$s(P3,YQa,new $APP.F(null,7,[$APP.P,YQa,$APP.O,'Create a native React element, by calling React.createElement directly.\n\n  That means the second argument must be a javascript object (or nil), and\n  that any Reagent hiccup forms must be processed with as-element. For example\n  like this:\n\n  ```cljs\n  (r/create-element "div" #js{:className "foo"}\n    "Hi " (r/as-element [:strong "world!"])\n  ```\n\n  which is equivalent to\n\n  ```cljs\n  [:div.foo "Hi" [:strong "world!"]]\n  ```',
$APP.X,$APP.I(new $APP.D(null,1,5,$APP.E,[$APP.xJ],null),new $APP.D(null,2,5,$APP.E,[$APP.xJ,lQa],null),new $APP.D(null,3,5,$APP.E,[$APP.xJ,lQa,$APP.AP],null),new $APP.D(null,5,5,$APP.E,[$APP.xJ,lQa,$APP.AP,$APP.Lk,$APP.tM],null)),$APP.J,"reagent/core.cljs",$APP.K,17,$APP.M,7,$APP.S,Z3],null),Z3),$APP.$s(function(a){return u3(a)},WPa,new $APP.F(null,7,[$APP.P,WPa,$APP.O,"Stop the result of track! from updating.",$APP.X,$APP.I(new $APP.D(null,1,5,$APP.E,[$APP.aQ],null)),$APP.J,"reagent/core.cljs",
$APP.K,242,$APP.M,7,$APP.S,Z3],null),Z3),$APP.$s(function(a,b){return new MOa(a,b)},rQa,new $APP.F(null,7,[$APP.P,rQa,$APP.O,"Provide a cursor into a Reagent atom.\n\n  Behaves like a Reagent atom but focuses updates and derefs to\n  the specified path within the wrapped Reagent atom. e.g.,\n\n  ```cljs\n  (let [c (cursor ra [:nested :content])]\n    ... @c ;; equivalent to (get-in @ra [:nested :content])\n    ... (reset! c 42) ;; equivalent to (swap! ra assoc-in [:nested :content] 42)\n    ... (swap! c inc) ;; equivalence to (swap! ra update-in [:nested :content] inc)\n    )\n  ```\n\n  The first parameter can also be a function, that should look\n  something like this:\n\n  ```cljs\n  (defn set-get\n    ([k] (get-in @state k))\n    ([k v] (swap! state assoc-in k v)))\n  ```\n\n  The function will be called with one argument – the path passed to\n  cursor – when the cursor is deref'ed, and two arguments (path and\n  new value) when the cursor is modified.\n\n  Given that set-get function, (and that state is a Reagent atom, or\n  another cursor) these cursors are equivalent:\n  `(cursor state [:foo])` and `(cursor set-get [:foo])`.\n\n  Note that a cursor is lazy: its value will not change until it is\n  used. This may be noticed with add-watch.",
$APP.X,$APP.I(new $APP.D(null,2,5,$APP.E,[vQa,$APP.IT],null)),$APP.J,"reagent/core.cljs",$APP.K,272,$APP.M,7,$APP.S,Z3],null),Z3),$APP.$s(W3,M3,new $APP.F(null,7,[$APP.P,M3,$APP.O,"An eager version of track. The function passed is called\n  immediately, and continues to be called when needed, until stopped\n  with dispose!.",$APP.X,$APP.I($APP.Se(new $APP.D(null,3,5,$APP.E,[$APP.NP,$APP.Lk,$APP.VH],null),new $APP.F(null,1,[$APP.Gp,new $APP.D(null,1,5,$APP.E,[$APP.I($APP.iM,$APP.NP)],null)],null))),
$APP.J,"reagent/core.cljs",$APP.K,234,$APP.M,7,$APP.S,Z3],null),Z3),$APP.$s(function(a){return RPa(a)},kQa,new $APP.F(null,7,[$APP.P,kQa,$APP.O,"Creates Compiler object with given `opts`,\n  this can be passed to `render`, `as-element` and other functions to control\n  how they turn the Reagent-style Hiccup into React components and elements.",$APP.X,$APP.I(new $APP.D(null,1,5,$APP.E,[$APP.zM],null)),$APP.J,"reagent/core.cljs",$APP.K,353,$APP.M,7,$APP.S,Z3],null),Z3),$APP.$s(SPa,L3,new $APP.F(null,
7,[$APP.P,L3,$APP.O,"Returns an adapter for a native React class, that may be used\n  just like a Reagent component function or class in Hiccup forms.",$APP.X,$APP.I(new $APP.D(null,1,5,$APP.E,[$APP.MP],null)),$APP.J,"reagent/core.cljs",$APP.K,52,$APP.M,7,$APP.S,Z3],null),Z3)]),$3=$APP.cY.j($APP.iT,null),dRa=$APP.Hi([$Pa,$APP.YD,PQa,hQa,gQa,nQa,pQa,sQa,UQa,TPa,M3,CQa],[$APP.$s(function(a){var b=m3;return b==null?[]:JOa($APP.Nb,b,a,null,NOa)},$Pa,new $APP.F(null,7,[$APP.P,$Pa,$APP.O,null,$APP.X,$APP.I(new $APP.D(null,
1,5,$APP.E,[$APP.lN],null)),$APP.J,"reagent/ratom.cljs",$APP.K,329,$APP.M,7,$APP.S,$3],null),$3),$APP.$s(z3,$APP.YD,new $APP.F(null,7,[$APP.P,$APP.YD,$APP.O,"Like clojure.core/atom, except that it keeps track of derefs.",$APP.X,$APP.I(new $APP.D(null,1,5,$APP.E,[$APP.aQ],null),new $APP.D(null,3,5,$APP.E,[$APP.aQ,$APP.Lk,new $APP.F(null,1,[$APP.ZF,new $APP.D(null,2,5,$APP.E,[$APP.AE,$APP.Hya],null)],null)],null)),$APP.J,"reagent/ratom.cljs",$APP.K,172,$APP.M,7,$APP.S,Z3],null),Z3),$APP.$s(KOa,PQa,
new $APP.F(null,7,[$APP.P,PQa,$APP.O,null,$APP.X,$APP.I(new $APP.D(null,2,5,$APP.E,[$APP.NP,$APP.VH],null)),$APP.J,"reagent/ratom.cljs",$APP.K,228,$APP.M,7,$APP.S,Z3],null),Z3),$APP.$s(function(a){return a.destroy},hQa,new $APP.F(null,7,[$APP.P,hQa,$APP.O,null,$APP.X,$APP.I(new $APP.D(null,1,5,$APP.E,[$APP.Se($APP.ZP,new $APP.F(null,1,[$APP.cn,$APP.iH],null))],null)),$APP.J,"sci/configs/reagent/reagent.cljs",$APP.K,106,$APP.M,7,$APP.S,$3],null),$3),$APP.$s(function(a,b){return a.generation=b.ratomGeneration},
gQa,new $APP.F(null,7,[$APP.P,gQa,$APP.O,null,$APP.X,$APP.I(new $APP.D(null,2,5,$APP.E,[$APP.Se($APP.ZP,new $APP.F(null,1,[$APP.cn,$APP.iH],null)),$APP.Se($APP.MP,new $APP.F(null,1,[$APP.cn,$APP.iH],null))],null)),$APP.J,"sci/configs/reagent/reagent.cljs",$APP.K,98,$APP.M,7,$APP.S,$3],null),$3),$APP.$s(function(){return m3!=null},nQa,new $APP.F(null,8,[$APP.P,nQa,$APP.O,null,$APP.X,$APP.I($APP.rh),$APP.cn,$APP.XN,$APP.J,"reagent/ratom.cljs",$APP.K,17,$APP.M,16,$APP.S,$3],null),$3),$APP.$s(function(a,
b){return a.destroy=b},pQa,new $APP.F(null,7,[$APP.P,pQa,$APP.O,null,$APP.X,$APP.I(new $APP.D(null,2,5,$APP.E,[$APP.Se($APP.ZP,new $APP.F(null,1,[$APP.cn,$APP.iH],null)),AQa],null)),$APP.J,"sci/configs/reagent/reagent.cljs",$APP.K,102,$APP.M,7,$APP.S,$3],null),$3),$APP.$s(q3,sQa,new $APP.F(null,7,[$APP.P,sQa,$APP.O,null,$APP.X,$APP.I(new $APP.D(null,3,5,$APP.E,[$APP.NP,$APP.Lk,new $APP.F(null,1,[$APP.ZF,new $APP.D(null,3,5,$APP.E,[eQa,UPa,RQa],null)],null)],null)),$APP.J,"reagent/ratom.cljs",$APP.K,
517,$APP.M,7,$APP.S,Z3],null),Z3),$APP.$s(function(){return m3},UQa,new $APP.F(null,7,[$APP.P,UQa,$APP.O,"Read-only access to the ratom context.",$APP.X,$APP.I($APP.rh),$APP.J,"sci/configs/reagent/reagent.cljs",$APP.K,85,$APP.M,7,$APP.S,$3],null),$3),$APP.$s(function(a){return a.generation},TPa,new $APP.F(null,7,[$APP.P,TPa,$APP.O,null,$APP.X,$APP.I(new $APP.D(null,1,5,$APP.E,[$APP.Se($APP.aQ,new $APP.F(null,1,[$APP.cn,$APP.iH],null))],null)),$APP.J,"sci/configs/reagent/reagent.cljs",$APP.K,90,$APP.M,
7,$APP.S,$3],null),$3),$APP.$s(N3,M3,new $APP.F(null,7,[$APP.P,M3,$APP.O,null,$APP.X,$APP.I($APP.Se(new $APP.D(null,3,5,$APP.E,[$APP.NP,$APP.Lk,$APP.VH],null),new $APP.F(null,1,[$APP.Gp,new $APP.D(null,1,5,$APP.E,[$APP.I($APP.iM,$APP.NP)],null)],null))),$APP.J,"reagent/ratom.cljs",$APP.K,242,$APP.M,7,$APP.S,Z3],null),Z3),$APP.$s(function(a){return a.ratomGeneration},CQa,new $APP.F(null,7,[$APP.P,CQa,$APP.O,null,$APP.X,$APP.I(new $APP.D(null,1,5,$APP.E,[$APP.Se($APP.aQ,new $APP.F(null,1,[$APP.cn,$APP.iH],
null))],null)),$APP.J,"sci/configs/reagent/reagent.cljs",$APP.K,94,$APP.M,7,$APP.S,$3],null),$3)]),a4=$APP.cY.j(FQa,null),b4=function b4(a){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return b4.o(arguments[0],arguments[1],2<c.length?new $APP.he(c.slice(2),0,null):null)};
b4.o=function(a,b,c){return $APP.k(!0)?$APP.T.h($APP.n($APP.N.o(new $APP.A(null,$APP.fE,null,1,null),new $APP.A(null,$APP.T.h($APP.n($APP.N.j(new $APP.A(null,$APP.sy,null,1,null),new $APP.A(null,HQa,null,1,null)))),null,1,null),$APP.x([new $APP.A(null,$APP.T.h($APP.n($APP.N.o(new $APP.A(null,LQa,null,1,null),new $APP.A(null,$APP.T.h($APP.n($APP.N.o(new $APP.A(null,$APP.Rk,null,1,null),new $APP.A(null,$APP.T.h($APP.n($APP.N.h(new $APP.A(null,MQa,null,1,null)))),null,1,null),$APP.x([new $APP.A(null,
QQa,null,1,null),new $APP.A(null,HQa,null,1,null)],0)))),null,1,null),$APP.x([new $APP.A(null,$APP.T.h($APP.n($APP.N.j(new $APP.A(null,$APP.my,null,1,null),c))),null,1,null)],0)))),null,1,null)],0)))):null};b4.v=2;b4.B=function(a){var b=$APP.p(a),c=$APP.q(a);a=$APP.p(c);c=$APP.q(c);return this.o(b,a,c)};
var eRa=new $APP.F(null,3,[$APP.TM,$APP.$s($APP.xe(new $APP.ee(function(){return b4},qQa,$APP.Hi([$APP.S,$APP.P,$APP.J,$APP.Ht,$APP.JQ,$APP.M,$APP.K,$APP.dt,$APP.Gt,$APP.X,$APP.O,$APP.GK],[IQa,$APP.TM,"sci/configs/reagent/reagent.cljs",20,new $APP.F(null,6,[$APP.fo,!0,$APP.dw,0,$APP.zT,0,$APP.KS,$APP.I($APP.I($APP.EL)),$APP.X,$APP.I(new $APP.D(null,2,5,$APP.E,[$APP.Lk,$APP.EL],null)),$APP.wK,$APP.I(null)],null),1,132,!0,132,$APP.I(new $APP.D(null,2,5,$APP.E,[$APP.Lk,$APP.EL],null)),"Print with console.error.",
$APP.k(b4)?b4.V:null]))),$APP.TM,new $APP.F(null,8,[$APP.P,$APP.TM,$APP.O,"Print with console.error.",$APP.dt,!0,$APP.X,$APP.I(new $APP.D(null,4,5,$APP.E,[$APP.ww,$APP.ww,$APP.Lk,$APP.EL],null)),$APP.J,"sci/configs/reagent/reagent.cljs",$APP.K,132,$APP.M,15,$APP.S,a4],null),a4),ZPa,$APP.$s(function(){return!1},ZPa,new $APP.F(null,7,[$APP.P,ZPa,$APP.O,null,$APP.X,$APP.I($APP.rh),$APP.J,"sci/configs/reagent/reagent.cljs",$APP.K,129,$APP.M,7,$APP.S,a4],null),a4),iQa,$APP.$s($Qa,iQa,new $APP.F(null,7,
[$APP.P,iQa,$APP.O,null,$APP.cn,$APP.SO,$APP.J,"reagent/debug.cljs",$APP.K,10,$APP.M,10,$APP.S,a4],null),a4)],null);$APP.Gz(new $APP.F(null,1,[$APP.wt,new $APP.F(null,3,[$APP.WN,$APP.Wi.l(cRa,L3,$APP.$s(SPa,L3,new $APP.F(null,7,[$APP.P,L3,$APP.O,"Returns an adapter for a native React class, that may be used\n  just like a Reagent component function or class in Hiccup forms.",$APP.X,$APP.I(new $APP.D(null,1,5,$APP.E,[$APP.MP],null)),$APP.J,"reagent/core.cljs",$APP.K,52,$APP.M,7,$APP.S,$APP.cY.h($APP.WN)],null),$APP.cY.h($APP.WN))),$APP.iT,dRa,FQa,eRa],null)],null));