import { $APP, shadow$provide } from "./nbb_core.js";
const shadow_esm_import = function(x) { return import(x) };
import*as esm_import$node_process from"node:process";import*as esm_import$node_module from"node:module";import*as esm_import$node_fs from"node:fs";import*as esm_import$import_meta_resolve from"import-meta-resolve";import*as esm_import$node_path from"node:path";import*as esm_import$node_url from"node:url";var bJa,dJa,WIa,VIa,cJa,$Ia,eJa,fJa;
$APP.UIa=function(a){a=$APP.me(a);a=$APP.Oo.j($APP.dg,a);a=$APP.Eo.j(function(d){return $APP.Qy($APP.qs(),d)},a);var b=$APP.zc($APP.At),c=$APP.zc($APP.mt);return $APP.Sz(a,new $APP.G(null,2,[$APP.S,b,$APP.J,c],null))};$APP.XIa=function(a,b){return VIa(WIa,a,b)};
$APP.q_=function(a,b){return Promise.resolve($APP.l($APP.zc(YIa))?null:function(){var c=esm_import$node_path.resolve($APP.l(a)?a:"script.cljs"),d=$APP.l($APP.Zz.h(b))?$APP.Xi.o(b,$APP.vT,esm_import$node_path.dirname(esm_import$node_path.resolve($APP.Zz.h(b))),$APP.x([$APP.Zz,$APP.UV.h(esm_import$node_fs.readFileSync($APP.Zz.h(b),"utf8"))],0)):function(){var g;a:{for(g=c;;){var k=esm_import$node_fs.existsSync(g);k=$APP.l(k)?esm_import$node_fs.lstatSync(g).isDirectory():k;if($APP.l(k)){k=esm_import$node_path.resolve(g,
"nbb.edn");if($APP.l(esm_import$node_fs.existsSync(k))){g=k;break a}k=esm_import$node_path.dirname(g)}else k=esm_import$node_path.dirname(g);if($APP.Fe.j(k,g)){g=null;break a}g=k}g=void 0}return $APP.l(g)?(k=$APP.UV.h(esm_import$node_fs.readFileSync(g,"utf8")),$APP.Xi.o(b,$APP.Zz,k,$APP.x([$APP.vT,esm_import$node_path.dirname(g)],0))):b}(),e=ZIa.h?ZIa.h(c):ZIa.call(null,c),f=""+$APP.H.h(esm_import$node_url.pathToFileURL(c));$APP.Uz.require=e;$APP.ck.C($APP.Wz,$APP.Xi,$APP.ko,e);$APP.ck.C($APP.Wz,
$APP.Xi,$APP.Xz,function(g){return esm_import$import_meta_resolve.resolve(g,f)});$APP.$g($APP.Yz,d);return Promise.resolve(function(){var g=function(){var B=$APP.Bb($Ia.h(d));return B?$APP.Zz.h(d):B}();if($APP.l(g)){g=$APP.ms.h(g);if($APP.l(g)){g=$APP.n(g);for(var k=null,q=0,t=0;;)if(t<q){var v=k.R(null,t);$APP.Bb(esm_import$node_path.isAbsolute(v))?$APP.$r(function(){var B=$APP.vT.h(d);return $APP.l(B)?esm_import$node_path.resolve(B,v):v}()):$APP.$r(v);t+=1}else if(g=$APP.n(g)){k=g;if($APP.ff(k))g=
$APP.Ed(k),t=$APP.Fd(k),k=g,q=$APP.Ee(g),g=t;else{var z=$APP.p(k);$APP.Bb(esm_import$node_path.isAbsolute(z))?$APP.$r(function(){var B=$APP.vT.h(d);return $APP.l(B)?esm_import$node_path.resolve(B,z):z}()):$APP.$r(z);g=$APP.r(k);k=null;q=0}t=0}else break}else $APP.$r(esm_import$node_process.cwd());return shadow_esm_import("./nbb_deps.js")}return $APP.$r(esm_import$node_process.cwd())}()).then(function(){var g=process.env.KBB_CLASSPATH_TAIL;delete process.env.KBB_CLASSPATH_TAIL;$APP.n(g)&&$APP.$r(g);
return $APP.$g(YIa,!0)})}())};$APP.aJa=function(a,b){return $APP.dy(a,b)};bJa=function(a,b){b=$APP.Py(a,$APP.ql("(keys (ns-map '%s))","%s",b));b=$APP.sk.j(function(c){return"`"+$APP.H.h(c)},b);b="["+$APP.H.h($APP.Wn.j(" ",b))+"]";a=$APP.Ny(a,b,null);return $APP.Oo.j(function(c){return $APP.Jl(""+$APP.H.h(c),"nbb.internal")},a)};
dJa=function(a,b){var c=$APP.qs();b=$APP.Dl.j(b,/\//);$APP.w.l(b,0,null);var d=$APP.w.l(b,1,null),e=$APP.Py(c,$APP.Yj.o($APP.x([$APP.T.h($APP.n($APP.N.o(new $APP.A(null,$APP.Et,null,1,null),new $APP.A(null,$APP.Ih($APP.T.h($APP.n($APP.N.j(new $APP.A(null,cJa,null,1,null),new $APP.A(null,$APP.T.h($APP.n($APP.N.j(new $APP.A(null,$APP.vta,null,1,null),new $APP.A(null,$APP.T.h($APP.n($APP.N.j(new $APP.A(null,$APP.bl,null,1,null),new $APP.A(null,a,null,1,null)))),null,1,null)))),null,1,null))))),null,
1,null),$APP.x([new $APP.A(null,$APP.T.h($APP.n($APP.N.o(new $APP.A(null,$APP.hT,null,1,null),new $APP.A(null,$APP.T.h($APP.n($APP.N.j(new $APP.A(null,$APP.cwa,null,1,null),new $APP.A(null,cJa,null,1,null)))),null,1,null),$APP.x([new $APP.A(null,cJa,null,1,null)],0)))),null,1,null)],0))))],0)));if($APP.l(e)&&(c=$APP.l(d)?function(){var k=$APP.Oa(d,"."),q=$APP.Dl.j(d,/\./);k=k?q:$APP.gj(q);q=$APP.E;var t=""+$APP.H.h(a)+"/",v=$APP.H,z=v.h;if($APP.n(k)){var B=$APP.Wn.j(".",k);B=""+$APP.H.h(B)+"."}else B=
null;return new $APP.D(null,2,5,q,[t+z.call(v,B),$APP.Wg.l($APP.Wa,e,k)],null)}():new $APP.D(null,2,5,$APP.E,[""+$APP.H.h(a)+"/",e],null),$APP.l(c))){var f=$APP.w.l(c,0,null),g=$APP.w.l(c,1,null);c=function(){for(var k=g,q=$APP.sh;;)if($APP.l(k)){var t=Object.getPrototypeOf(k);q=$APP.gi.j(q,Object.getOwnPropertyNames(k));k=t}else return q}();return $APP.sk.j(function(k){return new $APP.D(null,2,5,$APP.E,[null,""+$APP.H.h(f)+$APP.H.h(k)],null)},c)}return null};
$APP.gJa=function(a){var b=$APP.Bg(a);a=$APP.y.j(b,$APP.S);try{var c=$APP.qs(),d=$APP.l(a)?$APP.aJa(c,$APP.Mj.h(a)):null,e=$APP.zg([$APP.At,$APP.l(d)?d:$APP.zc($APP.At)]);$APP.Ts(e);try{var f=function(){var ja=$APP.an.h(b);return $APP.l(ja)?ja:$APP.SO.h(b)}();if($APP.l(f)){var g=$APP.Ta(f,"/"),k=g?function(){var ja=$APP.Dl.j(f,/\//);ja=ja==null?null:$APP.p(ja);return ja==null?null:$APP.Mj.h(ja)}():null,q=bJa(c,$APP.Ny(c,"(ns-name *ns*)",null)),t=$APP.sk.j(function(ja){return new $APP.D(null,3,5,$APP.E,
[$APP.fg(ja),$APP.hj(ja),eJa],null)},q),v=$APP.Ny(c,"(let [m (ns-aliases *ns*)] (zipmap (keys m) (map ns-name (vals m))))",null),z=$APP.ij($APP.Vi(v),$APP.Ti(v)),B=$APP.sq.h($APP.oh.o(function(ja){var na=$APP.y.j(v,ja);ja=$APP.Py(c,$APP.ql("(keys (ns-publics '%s))","%s",na));return $APP.sk.j(function(pa){return new $APP.D(null,3,5,$APP.E,[""+$APP.H.h(na),""+$APP.H.h(pa),fJa],null)},ja)},$APP.x([$APP.Ti(v)],0))),u=$APP.sk.j(function(ja){return new $APP.D(null,3,5,$APP.E,[""+$APP.H.h(ja),null,fJa],
null)},$APP.Ny(c,"(all-ns)",null)),F=g?dJa(k,f):null,Q=$APP.l(F)?null:g?function(){var ja=$APP.y.l(v,k,k),na=$APP.Py(c,$APP.ql("(and (find-ns '%s)\n                                                                                         (keys (ns-publics '%s)))","%s",ja));return $APP.sk.j(function(pa){return new $APP.D(null,3,5,$APP.E,[""+$APP.H.h(ja),""+$APP.H.h(pa),fJa],null)},na)}():null,U=$APP.N.o(t,B,$APP.x([u,Q],0)),Z=$APP.jo.j(function(ja){var na=$APP.w.l(ja,0,null);var pa=$APP.w.l(ja,1,null);
ja=$APP.w.l(ja,2,null);ja=$APP.Fe.j(eJa,ja)&&$APP.Ta(pa,f)?new $APP.D(null,2,5,$APP.E,[na,pa],null):null;$APP.l(ja)?na=ja:$APP.l(na)?(ja=""+$APP.H.h($APP.y.j(z,$APP.Mj.h(na)))+"/"+$APP.H.h(pa),ja=$APP.Ta(ja,f)?new $APP.D(null,2,5,$APP.E,[na,ja],null):null,$APP.l(ja)?na=ja:(pa=""+$APP.H.h(na)+"/"+$APP.H.h(pa),na=$APP.Ta(pa,f)?new $APP.D(null,2,5,$APP.E,[na,pa],null):null)):na=null;return na},U),ea=$APP.N.j(Z,F),ha=$APP.Ih($APP.$o.h($APP.sk.j(function(ja){var na=$APP.w.l(ja,0,null);ja=$APP.w.l(ja,1,
null);ja=new $APP.G(null,1,["candidate",""+$APP.H.h(ja)],null);return $APP.l(na)?$APP.Xi.l(ja,"ns",""+$APP.H.h(na)):ja},ea)));return new $APP.G(null,2,["completions",ha,"status",new $APP.D(null,1,5,$APP.E,["done"],null)],null)}return new $APP.G(null,1,["status",new $APP.D(null,1,5,$APP.E,["done"],null)],null)}finally{$APP.Vs()}}catch(ja){return console.warn(ja),new $APP.G(null,2,["completions",$APP.sh,"status",new $APP.D(null,1,5,$APP.E,["done"],null)],null)}};WIa={};
VIa=function VIa(a,b,c){for(;;){if(b instanceof Promise)return b;if(WIa===a){if($APP.jf(b))return $APP.QY(b,b,c,VIa);a=$APP.eA(b,c)}else{b=Promise;var e=b.resolve;var f=$APP.Ko.h(c);f=$APP.l(f)?f:$APP.Hf;c=new $APP.G(null,1,[$APP.S,$APP.S.h(c)],null);c=f.j?f.j(a,c):f.call(null,a,c);return e.call(b,c)}}};$APP.r_=new $APP.m(null,"socket-repl","socket-repl",-1615225633,null);$APP.s_=new $APP.m(null,"repl","repl",1605132860,null);
cJa=new $APP.m(null,"resolved__37165__auto__","resolved__37165__auto__",707031354,null);$Ia=new $APP.C(null,"disableConfig","disableConfig",844586790);eJa=new $APP.C(null,"unqualified","unqualified",-98904653);fJa=new $APP.C(null,"qualified","qualified",-2065109343);$APP.t_=new $APP.m(null,"start-server!","start-server!",203437330,null);$APP.u_=new $APP.C(null,"classpath","classpath",299521985);var ZIa,YIa;ZIa=function(){var a=esm_import$node_module.createRequire;return $APP.l(a)?a:function(){return function(){throw Error("createRequire is not defined, this is a no-op");}}}();YIa=$APP.bk.h(!1);$APP.v_=function v_(a){switch(arguments.length){case 1:return v_.h(arguments[0]);case 2:return v_.j(arguments[0],arguments[1]);default:throw Error(["Invalid arity: ",arguments.length].join(""));}};$APP.v_.h=function(a){return $APP.v_.j(a,null)};
$APP.v_.j=function(a,b){b=$APP.$z.o(b,$APP.x([$APP.MD,!0],0));var c=esm_import$node_path.resolve(a);$APP.$g($APP.jGa,c);return $APP.q_(c,b).then(function(){return $APP.jA(c)})};$APP.v_.v=2;$APP.w_=function w_(a){switch(arguments.length){case 1:return w_.h(arguments[0]);case 2:return w_.j(arguments[0],arguments[1]);default:throw Error(["Invalid arity: ",arguments.length].join(""));}};$APP.w_.h=function(a){return $APP.w_.j(a,null)};
$APP.w_.j=function(a,b){b=$APP.$z.o(b,$APP.x([$APP.MD,!0],0));return $APP.q_(null,b).then(function(){return $APP.iA(a)})};$APP.w_.v=2;export const loadFile=$APP.v_;export const loadString=$APP.w_;export const getClassPath=function(){return $APP.Yr()};export const addClassPath=function(a){return $APP.$r(a)};export const version=function(){return $APP.pA()};export const registerModule=function(a,b){b=$APP.Bna($APP.kl(b));return $APP.ck.C($APP.Vz,$APP.Xi,b,a)};export const printErrorReport=$APP.TY;