import { $APP, shadow$provide } from "./nbb_core.js";
import "./nbb_api.js";
const shadow_esm_import = function(x) { return import(x) };
import*as esm_import$node_net from"node:net";import*as esm_import$node_process from"node:process";import*as esm_import$node_readline from"node:readline";import*as esm_import$node_vm from"node:vm";
var CTa=function(a){var b=function(){var h=$APP.lq.j(a,"(");return $APP.k(h)?new $APP.D(null,2,5,$APP.E,[$APP.uj.l(a,0,h+1),$APP.uj.j(a,h+1)],null):new $APP.D(null,2,5,$APP.E,[null,a],null)}(),c=$APP.t.l(b,0,null),d=$APP.t.l(b,1,null);b=$APP.y;var e=b.j;try{var f=$APP.oJa(new $APP.F(null,2,[$APP.S,""+$APP.G.h($APP.xc(F2)),$APP.JO,d],null))}catch(h){console.warn(""+$APP.fAa,$APP.Ik(h)),f=null}f=e.call(b,f,"completions");return $APP.qk.j(function(h){return""+$APP.G.h(c)+$APP.G.h(h)},$APP.qh(function(h){return $APP.Ga(h,
d)},$APP.qk.j(function(h){return $APP.y.j(h,"candidate")},f)))},DTa=function(a){return[$APP.Wu.h(CTa(a)),a]},J2=function(a,b){$APP.$g(G2,!1);a.setPrompt(""+$APP.G.h($APP.xc(F2))+"\x3d\x3e ");a.prompt();return $APP.Cl($APP.xc(H2))?null:I2.j?I2.j(b,a):I2.call(null,b,a)},ETa=function(a){var b=$APP.Ql(a);a=$APP.Rl(a);var c=$APP.yl($APP.xc(H2));b=$APP.hh.j(b-1,c);c=$APP.n(b);b=$APP.p(c);c=$APP.q(c);a=$APP.k(b)?$APP.uj.j(b,a):null;$APP.$g(H2,$APP.Wn.j("\n",$APP.ag(a,c)))},FTa=function(a,b){b={f:b};esm_import$node_vm.createContext(b);
try{return $APP.k($APP.k(K2)?$APP.yb(a):K2)&&esm_import$node_process.stdin.setRawMode(!1),esm_import$node_vm.runInContext("f()",b,{displayErrors:!0,breakOnSigint:!0,microtaskMode:"afterEvaluate"}).then(function(c){var d={f:$APP.k(a)?function(){return c}:function(){var e=$APP.p(c);if($APP.k($APP.gz(e)))return e.then(function(f){$APP.Ep.o($APP.v(["#\x3cPromise "+$APP.G.h($APP.Xj.o($APP.v([f],0)))+"\x3e"],0));return c});$APP.ez.o($APP.v([e],0));return c}};esm_import$node_vm.createContext(d);return esm_import$node_vm.runInContext("f()",
d,{displayErrors:!0,breakOnSigint:!0,microtaskMode:"afterEvaluate"})}).finally(function(){return $APP.k($APP.k(K2)?$APP.yb(a):K2)?esm_import$node_process.stdin.setRawMode(!0):null})}catch(c){return b=c,$APP.k($APP.k(K2)?$APP.yb(a):K2)&&esm_import$node_process.stdin.setRawMode(!0),Promise.reject(b)}},I2=function(a,b){if($APP.k(function(){var e=$APP.xc(G2);return $APP.k(e)?e:$APP.Cl($APP.xc(H2))}()))return null;$APP.$g(G2,!0);var c=$APP.pla($APP.xc(H2)),d=function(){try{var e=$APP.yg([$APP.zt,$APP.xc(F2)]);
$APP.Ss(e);try{return $APP.Ola(c)}finally{$APP.Us()}}catch(f){e=f;if($APP.Ja($APP.Ik(e),"EOF while reading"))return GTa;ETa(c);$APP.ez.o($APP.v([""+$APP.G.h(e)],0));return HTa}}();if($APP.Ee.j(HTa,d))return J2(b,a);if($APP.Ee.j(GTa,d))return $APP.$g(G2,!1);ETa(c);if($APP.Ee.j($APP.vN,d))return $APP.$g(G2,!1);$APP.Ss($APP.yg([$APP.zt,$APP.xc(F2)]));return FTa(a,function(){return $APP.eJa(d,new $APP.F(null,3,[$APP.S,$APP.xc(F2),$APP.I,$APP.xc($APP.lt),$APP.Lo,$APP.eB],null))}).then(function(e){var f=
$APP.t.l(e,0,null);e=$APP.t.l(e,1,null);e=$APP.Ag(e);e=$APP.y.j(e,$APP.S);$APP.$g(F2,e);$APP.CW.j($APP.hW,$APP.Yg($APP.xc($APP.gW)));$APP.CW.j($APP.gW,$APP.Yg($APP.xc($APP.fW)));$APP.CW.j($APP.fW,$APP.Yg(f));if($APP.k($APP.k(a)?$APP.gz(f):a))return f.then(function(h){a.write("#\x3cPromise "+$APP.G.h($APP.Xj.o($APP.v([h],0)))+"\x3e\n");return J2(b,a)});$APP.k(a)&&a.write($APP.GC.o($APP.v([f],0)));return J2(b,a)}).catch(function(e){$APP.ez.o($APP.v([""+$APP.G.h(e)],0));$APP.CW.j($APP.iW,$APP.Yg(e));
return J2(b,a)}).finally(function(){return $APP.Us()})},ITa=function(a,b){a.on("line",function(c){$APP.bk.C(H2,$APP.G,c,"\n");return I2(b,a)})},JTa=function(a){return esm_import$node_readline.createInterface({input:a,output:a,completer:DTa})},KTa=function(a){var b=JTa(a);ITa(b,a);a.setNoDelay(!0);return a.on("close",function(){return $APP.Ep.o($APP.v(["Client closed connection."],0))})},GTa=new $APP.C("nbb.impl.repl","eof-while-reading","nbb.impl.repl/eof-while-reading",1743626215),LTa=new $APP.l(null,
"completer*","completer*",-648150376,null),MTa=new $APP.C(null,"init","init",-1875481434),NTa=new $APP.l(null,"get-completions","get-completions",1933789168,null),HTa=new $APP.C("nbb.impl.repl","continue","nbb.impl.repl/continue",-1326808644);var F2=$APP.ak.h($APP.xc($APP.zt)),H2=$APP.ak.h(""),G2=$APP.ak.h(!1),K2,OTa=esm_import$node_process.stdout.isTTY;K2=$APP.k(OTa)?esm_import$node_process.stdin.setRawMode:OTa;var L2=$APP.GW.j($APP.dD,null),M2=function M2(a){switch(arguments.length){case 0:return M2.v();case 1:return M2.h(arguments[0]);default:throw Error(["Invalid arity: ",arguments.length].join(""));}};M2.v=function(){return M2.h(null)};
M2.h=function(a){var b=function(){var d=$APP.GM.h(a);return $APP.k(d)?d:0}(),c=esm_import$node_net.createServer(KTa);return c.listen(b,"127.0.0.1",function(){var d=c.address(),e=d.address;return $APP.Ep.o($APP.v(["Socket REPL listening on port "+$APP.G.h(d.port)+" on host "+$APP.G.h(e)],0))})};M2.A=1;var N2=function N2(a){switch(arguments.length){case 0:return N2.v();case 1:return N2.h(arguments[0]);default:throw Error(["Invalid arity: ",arguments.length].join(""));}};N2.v=function(){return N2.h(null)};
N2.h=function(a){function b(e){return $APP.bJa(new $APP.A(null,$APP.bl,new $APP.A(null,new $APP.A(null,$APP.bl,new $APP.A(null,e,null,1,null),2,null),null,1,null),2,null))}$APP.k(K2)&&esm_import$node_process.stdin.setRawMode(!0);var c=$APP.t.l($APP.MW,0,null),d=$APP.t.l($APP.MW,1,null);$APP.Ep.o($APP.v(["Welcome to "+$APP.G.h("nbb")+" v"+$APP.G.h($APP.Jz())+"!"],0));return b(c).then(function(){return b(d)}).then(MTa.j(a,$APP.Cf)).then(function(){return new Promise(function(e){var f=$APP.k(null)?JTa(null):
esm_import$node_readline.createInterface({input:esm_import$node_process.stdin,output:esm_import$node_process.stdout,completer:DTa});ITa(f,null);f.setPrompt(""+$APP.G.h($APP.xc(F2))+"\x3d\x3e ");f.on("close",e);return f.prompt()})})};N2.A=1;
var PTa=new $APP.F(null,3,[$APP.nY,$APP.at(N2,$APP.nY,new $APP.F(null,7,[$APP.Q,$APP.nY,$APP.O,null,$APP.Y,$APP.H($APP.ph,new $APP.D(null,1,5,$APP.E,[$APP.QM],null)),$APP.I,"nbb/impl/repl.cljs",$APP.J,194,$APP.M,7,$APP.S,L2],null),L2),NTa,$APP.at(CTa,LTa,new $APP.F(null,7,[$APP.Q,LTa,$APP.O,"Given a line, returns a flat vector of completions",$APP.Y,$APP.H(new $APP.D(null,1,5,$APP.E,[$APP.Ura],null)),$APP.I,"nbb/impl/repl.cljs",$APP.J,16,$APP.M,7,$APP.S,L2],null),L2),$APP.mY,$APP.at(M2,$APP.mY,new $APP.F(null,
7,[$APP.Q,$APP.mY,$APP.O,null,$APP.Y,$APP.H($APP.ph,new $APP.D(null,1,5,$APP.E,[$APP.QM],null)),$APP.I,"nbb/impl/repl.cljs",$APP.J,179,$APP.M,7,$APP.S,L2],null),L2)],null);$APP.Dz(new $APP.F(null,1,[$APP.xt,new $APP.F(null,1,[$APP.dD,PTa],null)],null));