import { $APP, shadow$provide } from "./nbb_core.js";
import "./nbb_api.js";
import "./nbb_goog_string.js";
import "./nbb_pprint.js";
const shadow_esm_import = function(x) { return import(x) };
import*as esm_import$node_net from"node:net";import*as esm_import$node_process from"node:process";import*as esm_import$node_async_hooks from"node:async_hooks";import*as esm_import$node_fs from"node:fs";import*as esm_import$node_path from"node:path";
var JYa=function(a,b){a=a.indexOf(b);if(a<0)throw Error("out of input");return a},m4=function(a,b){if(a.length<b)throw Error("out of input");return a.slice(b)},n4=function(a,b){if(b>a.length)throw Error("out of input");return a.slice(0,b)},KYa=function(a){return(new TextEncoder).encode(a).length},o4=function(a){return $APP.k($APP.fz.h($APP.xc($APP.qz)))?console.debug($APP.Wn.j(" ",a)):null},MYa=function(a){return function(b,c){b=$APP.Ag(b);var d=$APP.y.j(b,$APP.tt),e=$APP.y.j(b,LYa);c=$APP.Wi.l(c,
"id",d);c=$APP.k(e)?$APP.Wi.l(c,"session",e):c;return a.j?a.j(b,c):a.call(null,b,c)}},PYa=function(){var a=NYa;return function(b,c){b=$APP.Dn.l(b,OYa,$APP.Dj);return a.j?a.j(b,c):a.call(null,b,c)}},RYa=function(){var a=QYa();return function(b,c){o4($APP.v(["request",b],0));return a.j?a.j(b,c):a.call(null,b,c)}},SYa=function(a){return function(b,c){o4($APP.v(["response",c],0));return a.j?a.j(b,c):a.call(null,b,c)}},QYa=function(){var a=PYa();return function(b,c){return a.j?a.j(b,c):a.call(null,b,c)}},
TYa=function(a){return $APP.Wi.l($APP.fj(new $APP.D(null,3,5,$APP.E,["major","minor","incremental"],null),$APP.sz.h(a.split("."))),"version-string",a)},VYa=function(a,b,c){if($APP.k(a))if(a=UYa.h?UYa.h(a):UYa.call(null,a),$APP.k(a)){b=$APP.Ag(b);var d=$APP.y.j(b,$APP.JLa),e=$APP.y.j(b,$APP.qLa),f=$APP.y.j(b,$APP.zLa);b=$APP.xj;var h=$APP.wj,m=$APP.fZ;$APP.xj=e;$APP.wj=f;$APP.fZ=d;try{var r=new $APP.mb;d=$APP.ob;e=$APP.pb;$APP.ob=!0;$APP.pb=function(u){return r.append(u)};try{a.h?a.h(c):a.call(null,
c)}finally{$APP.pb=e,$APP.ob=d}return""+$APP.G.h(r)}finally{$APP.fZ=m,$APP.wj=h,$APP.xj=b}}else return o4($APP.v(["Pretty-Printing is only supported for clojure.core/prn and clojure.pprint/pprint."],0)),$APP.Xj.o($APP.v([c],0));else return $APP.Xj.o($APP.v([c],0))},YYa=function(a,b,c){var d=$APP.t.l(c,0,null);c=$APP.t.l(c,1,null);var e=$APP.S.h(c);$APP.$g(p4,e);$APP.CW.j($APP.hW,$APP.Yg($APP.xc($APP.gW)));$APP.CW.j($APP.gW,$APP.Yg($APP.xc($APP.fW)));$APP.CW.j($APP.fW,$APP.Yg(d));if($APP.k($APP.gz(d)))return d.then(function(f){f=
new $APP.F(null,2,["value","#\x3cPromise "+$APP.G.h($APP.Xj.o($APP.v([f],0)))+"\x3e","ns",""+$APP.G.h(e)],null);return b.j?b.j(a,f):b.call(null,a,f)});d=VYa(WYa.h(a),XYa.h(a),d);d=new $APP.F(null,2,["value",d,"ns",""+$APP.G.h(e)],null);return b.j?b.j(a,d):b.call(null,a,d)},ZYa=function(a,b,c){$APP.CW.j($APP.iW,$APP.Yg(c));var d=$APP.wt.h($APP.Hk(c));d=$APP.k(d)?d:c.message;$APP.k(d)&&(d=new $APP.F(null,1,["err",""+$APP.G.h(d)+"\n"],null),a.j?a.j(b,d):a.call(null,b,d));c=new $APP.F(null,2,["ex",""+
$APP.G.h(c),"ns",""+$APP.G.h($APP.xc($APP.zt))],null);return a.j?a.j(b,c):a.call(null,b,c)},dZa=function(){if($APP.Iba($Ya,!1,!0)){var a=$APP.xc($APP.OU);$APP.CW.j($APP.OU,$APP.Yg(function(b){var c=aZa.getStore();if($APP.k(c)){var d=$APP.Ag(c);c=$APP.y.j(d,bZa);d=$APP.y.j(d,cZa);b=new $APP.F(null,1,["out",b],null);return d.j?d.j(c,b):d.call(null,c,b)}return a.h?a.h(b):a.call(null,b)}))}},gZa=function(a,b){var c=$APP.Ag(a),d=$APP.y.j(c,$APP.S);a=$APP.y.j(c,q4);var e=$APP.y.j(c,$APP.I);$APP.y.j(c,eZa);
$APP.y.j(c,fZa);var f=$APP.Yr(a),h=function u(r){try{var x=function(){var B=$APP.S.h($APP.Ke(r));if($APP.k(B))return B;B=$APP.xc(p4);return $APP.k(B)?B:d}(),z=$APP.Pla(f,new $APP.F(null,3,[$APP.S,x,$APP.I,e,$APP.Lo,$APP.eB],null));return $APP.Ee.j($APP.vN,z)?Promise.resolve(r):$APP.eJa(z,new $APP.F(null,3,[$APP.S,x,$APP.I,e,$APP.Lo,$APP.eB],null)).then(function(B){return Promise.resolve(YYa(c,b,B)).then(function(){return u(B)})})}catch(B){return ZYa(b,c,B),u(null)}};return aZa.run(new $APP.F(null,
2,[bZa,c,cZa,b],null),function(){$APP.Ss($APP.yg([$APP.zt,d,$APP.lt,e,$APP.QU,$APP.xc($APP.QU),$APP.VU,!0]));return h(null).catch($APP.lm.l(ZYa,b,c)).finally(function(){var r=new $APP.F(null,2,["ns",""+$APP.G.h($APP.xc(p4)),"status",new $APP.D(null,1,5,$APP.E,["done"],null)],null);return b.j?b.j(c,r):b.call(null,c,r)}).finally(function(){return $APP.Us()})})},hZa=function(a,b){a=$APP.Ag(a);var c=$APP.y.j(a,$APP.S),d=$APP.Wi.l;c=$APP.k(c)?$APP.iJa($APP.rs(),$APP.Lj.h(c)):null;$APP.k(c)||(c=$APP.xc(p4),
c=$APP.k(c)?c:$APP.xc($APP.zt));return gZa(d.call($APP.Wi,a,$APP.S,c),b)},iZa=function(a){return $APP.Wn.j("\n",$APP.qk.j($APP.Xj,a))},kZa=function(a,b){var c=$APP.Ag(a),d=$APP.y.j(c,$APP.S),e=OYa.h(c);try{var f=$APP.S.h(c),h=function(){var P=$APP.rta.h(c);return $APP.k(P)?P:$APP.Zm.h(c)}(),m=function(){var P=$APP.k(d)?$APP.iJa($APP.rs(),$APP.Lj.h(d)):null;if($APP.k(P))return P;P=$APP.xc(p4);return $APP.k(P)?P:$APP.xc($APP.zt)}(),r=$APP.yg([$APP.zt,m]);$APP.Ss(r);try{var u=$APP.Qy($APP.rs(),$APP.l4("\n(let [ns '%s\n      full-sym '%s]\n  (when-let [v (ns-resolve ns full-sym)]\n    (let [m (meta v)]\n      (assoc m :arglists (:arglists m)\n       :doc (:doc m)\n       :name (:name m)\n       :ns (some-\x3e m :ns ns-name)\n       :val @v))))",
f,h)),x=$APP.O.h(u),z=$APP.I.h(u),B=$APP.J.h(u),w=function(){var P=e instanceof $APP.C?e.aa:null;switch(P){case "eldoc":return P=new $APP.F(null,5,["ns",$APP.S.h(u),"name",$APP.Q.h(u),"eldoc",$APP.Fo.j(function(K){return $APP.Fo.j($APP.G,K)},$APP.Y.h(u)),"type",$APP.kf($APP.Ny.h(u))?"function":"variable","status",new $APP.D(null,1,5,$APP.E,["done"],null)],null),$APP.k(x)?$APP.Wi.l(P,"docstring",x):P;case "info":case "lookup":return P=new $APP.F(null,4,["ns",$APP.S.h(u),"name",$APP.Q.h(u),"arglists-str",
iZa($APP.Y.h(u)),"status",new $APP.D(null,1,5,$APP.E,["done"],null)],null),P=$APP.k(x)?$APP.Wi.l(P,"doc",x):P,P=$APP.k(z)?$APP.Wi.l(P,"file",z):P,$APP.k(B)?$APP.Wi.l(P,"line",B):P;default:throw Error("No matching clause: "+$APP.G.h(P));}}();return b.j?b.j(c,w):b.call(null,c,w)}finally{$APP.Us()}}catch(P){if(P instanceof Error)return a=P,f=function(){var K=new $APP.Zi(null,new $APP.F(null,1,["done",null],null),null);return $APP.Ee.j(e,jZa)?$APP.Xf.j(K,"no-eldoc"):K}(),a=new $APP.F(null,2,["status",
f,"ex",""+$APP.G.h(a)],null),b.j?b.j(c,a):b.call(null,c,a);throw P;}},lZa=function(a,b){var c=$APP.oJa(a);return b.j?b.j(a,c):b.call(null,a,c)},NYa=function(a,b){a=$APP.Ag(a);var c=$APP.y.j(a,OYa),d=$APP.y.j(mZa,c);if($APP.k(d))return d.j?d.j(a,b):d.call(null,a,b);console.warn($APP.Wn.j(" ",$APP.v(["Unhandled operation",c],0)));c=new $APP.F(null,1,["status",new $APP.D(null,3,5,$APP.E,["error","unknown-op","done"],null)],null);return b.j?b.j(a,c):b.call(null,a,c)},nZa=function(a){return function(b,
c){return a.write(r4(c))}},oZa=function(a,b){o4($APP.v(["Connection accepted"],0));b.setNoDelay(!0);var c=RYa(),d=MYa(SYa(nZa(b))),e=$APP.ak.h(null);b.on("data",function(f){var h=$APP.xc(e);if($APP.k(h)){f=""+$APP.G.h(h)+$APP.G.h(f);$APP.$g(e,null);var m=f}else m=f;a:{f=$APP.v([$APP.VC,!0],0);for(h=$APP.ph;;){var r=$APP.Wg.l(s4,m,f);m=$APP.t.l(r,0,null);r=$APP.t.l(r,1,null);if(m==null){h=new $APP.D(null,2,5,$APP.E,[h,r],null);break a}h=$APP.Xf.j(h,m);m=r}h=void 0}f=$APP.t.l(h,0,null);h=$APP.t.l(h,
1,null);$APP.Cl(h)||$APP.$g(e,h);f=$APP.n(f);h=null;for(var u=r=0;;)if(u<r)m=h.U(null,u),c(m,d),u+=1;else if(f=$APP.n(f))h=f,$APP.df(h)?(f=$APP.Dd(h),r=$APP.Fd(h),h=f,m=$APP.De(f),f=r,r=m):(m=$APP.p(h),c(m,d),f=$APP.q(h),h=null,r=0),u=0;else return null});return b.on("close",function(f){return $APP.k(f)?o4($APP.v(["Connection lost"],0)):o4($APP.v(["Connection closed"],0))})},pZa=new $APP.C(null,"completions","completions",-190930179),XYa=new $APP.C("nrepl.middleware.print","options","nrepl.middleware.print/options",
868480159),LYa=new $APP.C(null,"session","session",1008279103),qZa=new $APP.C(null,"load-file","load-file",-424586670),q4=new $APP.C(null,"code","code",1586293142),rZa=new $APP.C(null,"log_level","log_level",-1756736313),WYa=new $APP.C("nrepl.middleware.print","print","nrepl.middleware.print/print",-1616742548),sZa=new $APP.C(null,"clone","clone",711747572),tZa=new $APP.C(null,"close","close",1835149582),uZa=new $APP.C(null,"info","info",-317069002),vZa=new $APP.C(null,"macroexpand","macroexpand",
-130598183),fZa=new $APP.C(null,"_line","_line",232847719),wZa=new $APP.l(null,"server","server",-1155245649,null),xZa=new $APP.C(null,"lookup","lookup",1225356838),yZa=new $APP.C(null,"expander","expander",379138924),eZa=new $APP.C(null,"_load-file?","_load-file?",-1198848711),OYa=new $APP.C(null,"op","op",-1882987955),zZa=new $APP.C(null,"describe","describe",1369790582),jZa=new $APP.C(null,"eldoc","eldoc",-1321421900),cZa=new $APP.C(null,"send-fn","send-fn",351002041),AZa=new $APP.l(null,"stop-server!",
"stop-server!",-410772185,null),BZa=new $APP.C(null,"load-file?","load-file?",1892536169),bZa=new $APP.C(null,"request","request",1772954723);var t4=function t4(a,b){switch(""+$APP.G.h(n4(a,1))){case "i":return a=m4(a,1),b=JYa(a,"e"),new $APP.D(null,2,5,$APP.E,[parseInt(n4(a,b)),m4(a,b+1)],null);case "l":var d=a=m4(a,1);for(a=$APP.jd($APP.ph);;){if($APP.Ee.j(""+$APP.G.h(n4(d,1)),"e"))return new $APP.D(null,2,5,$APP.E,[$APP.nd(a),m4(d,1)],null);var e=t4.j?t4.j(d,b):t4.call(null,d,b),f=$APP.t.l(e,0,null),h=$APP.t.l(e,1,null);e=h;a=$APP.oh.j(a,f);d=e}break;case "d":a=m4(a,1);f=$APP.Ag(b);f=$APP.y.j(f,$APP.VC);d=a;for(e=$APP.jd($APP.zg);;){if($APP.Ee.j(""+
$APP.G.h(n4(d,1)),"e"))return new $APP.D(null,2,5,$APP.E,[$APP.nd(e),m4(d,1)],null);a=t4.j?t4.j(d,b):t4.call(null,d,b);d=$APP.t.l(a,0,null);h=$APP.t.l(a,1,null);h=t4.j?t4.j(h,b):t4.call(null,h,b);a=$APP.t.l(h,0,null);h=$APP.t.l(h,1,null);d=$APP.k(f)?$APP.Dj.h(d):d;a=$APP.ei.l(e,d,a);d=h;e=a}break;default:return b=JYa(a,":"),f=parseInt(n4(a,b)),a=m4(a,b+1),new $APP.D(null,2,5,$APP.E,[""+$APP.G.h(n4(a,f)),m4(a,f)],null)}},s4=function s4(a){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),
e+=1;else break;return s4.o(arguments[0],1<c.length?new $APP.fe(c.slice(1),0,null):null)};s4.o=function(a,b){try{return t4(a,b)}catch(c){if(c instanceof Error)return new $APP.D(null,2,5,$APP.E,[null,a],null);throw c;}};s4.A=1;s4.B=function(a){var b=$APP.p(a);a=$APP.q(a);return this.o(b,a)};
var r4=function r4(a){for(;;){if(typeof a==="string")return""+$APP.G.h(KYa(a))+":"+$APP.G.h(a);if(a instanceof $APP.C||a instanceof $APP.l)a=""+$APP.G.h(function(){var c=$APP.dg(a);return $APP.k(c)?""+$APP.G.h(c)+"/":null}())+$APP.G.h($APP.ej(a));else return typeof a==="number"?"i"+$APP.G.h(a)+"e":$APP.Ye(a)||$APP.cf(a)||a==null?"l"+$APP.G.h($APP.Wg.j($APP.G,$APP.qk.j(r4,a)))+"e":$APP.af(a)?"d"+$APP.G.h($APP.Wg.j($APP.G,$APP.qk.j(function(){return function(c){var d=$APP.t.l(c,0,null);c=$APP.t.l(c,
1,null);return""+$APP.G.h(r4.h?r4.h(d):r4.call(null,d))+$APP.G.h(r4.h?r4.h(c):r4.call(null,c))}}(a),$APP.Un.j($APP.p,a))))+"e":null}};var p4=$APP.ak.h(null),UYa=new $APP.F(null,1,["cider.nrepl.pprint/pprint",$APP.N_],null),aZa=new esm_import$node_async_hooks.AsyncLocalStorage,$Ya=$APP.ak.h(!1),mZa=$APP.Hi([$APP.pY,xZa,tZa,qZa,jZa,sZa,zZa,uZa,$APP.wp,vZa,pZa,$APP.Aza],[function(a,b){var c=new $APP.D(null,1,5,$APP.E,["done"],null);var d=$APP.$r();d=$APP.xl.j(d,$APP.vj(esm_import$node_path.delimiter));c=new $APP.F(null,2,["status",c,"classpath",d],null);return b.j?b.j(a,c):b.call(null,a,c)},kZa,function(a,b){var c=new $APP.F(null,
1,["status",new $APP.D(null,2,5,$APP.E,["done","session-closed"],null)],null);return b.j?b.j(a,c):b.call(null,a,c)},function(a,b){a=$APP.Ag(a);var c=$APP.y.j(a,$APP.I);return gZa($APP.Wi.o(a,q4,c,$APP.v([BZa,!0,$APP.S,$APP.xc($APP.zt)],0)),b)},kZa,function(a,b){var c=new $APP.F(null,2,["new-session",""+$APP.G.h($APP.Fk()),"status",new $APP.D(null,1,5,$APP.E,["done"],null)],null);return b.j?b.j(a,c):b.call(null,a,c)},function(a,b){var c=new $APP.F(null,4,["versions",new $APP.F(null,2,["nbb-nrepl",
TYa("TODO"),"node",TYa(esm_import$node_process.version)],null),"aux",$APP.zg,"ops",$APP.fj($APP.qk.j($APP.ej,$APP.Si(mZa)),$APP.Bo.h($APP.zg)),"status",new $APP.D(null,1,5,$APP.E,["done"],null)],null);return b.j?b.j(a,c):b.call(null,a,c)},kZa,lZa,function(a,b){a=$APP.Ag(a);var c=$APP.y.j(a,q4),d=$APP.y.j(a,yZa);try{return hZa($APP.Wi.l(a,q4,"( "+$APP.G.h(d)+"(quote "+$APP.G.h(c)+"))"),function(e,f){var h=f.h?f.h("value"):f.call(null,"value");f=$APP.k(h)?$APP.Wi.l(f,"expansion",h):f;return b.j?b.j(e,
f):b.call(null,e,f)})}catch(e){if(e instanceof Error)return c=new $APP.F(null,3,["ex",""+$APP.G.h(e),"ns",""+$APP.G.h($APP.xc($APP.zt)),"status",new $APP.D(null,1,5,$APP.E,["done"],null)],null),b.j?b.j(a,c):b.call(null,a,c);throw e;}},lZa,hZa]),CZa=$APP.ak.h(null),u4=function u4(a){switch(arguments.length){case 0:return u4.v();case 1:return u4.h(arguments[0]);default:throw Error(["Invalid arity: ",arguments.length].join(""));}};u4.v=function(){return u4.h($APP.xc(CZa))};
u4.h=function(a){return a.close(function(){$APP.CW.j($APP.OU,$APP.Yg($APP.pb));$APP.CW.j($APP.VU,$APP.Yg($APP.ob));return $APP.k(esm_import$node_fs.existsSync(".nrepl-port"))?esm_import$node_fs.unlinkSync(".nrepl-port"):null})};u4.A=1;
var v4=$APP.GW.j($APP.cE,null),DZa=new $APP.F(null,2,[$APP.oY,$APP.at(function(a){return Promise.resolve($APP.lY(esm_import$node_path.resolve("script.cljs"),null)).then(function(){function b(e){return $APP.bJa(new $APP.A(null,$APP.bl,new $APP.A(null,new $APP.A(null,$APP.bl,new $APP.A(null,e,null,1,null),2,null),null,1,null),2,null))}var c=$APP.t.l($APP.MW,0,null),d=$APP.t.l($APP.MW,1,null);return b(c).then(function(){return b(d)})}).then(function(){var b=$APP.gm.o($APP.v([$APP.xc($APP.qz),a],0)),
c=function(){var f=$APP.GM.h(b);return $APP.k(f)?f:0}(),d=function(){var f=$APP.CT.h(b);return $APP.k(f)?f:"127.0.0.1"}();(function(){var f=$APP.Ab(b)?b.Cm:rZa.h(b);return $APP.k(f)?f:"info"})();var e=esm_import$node_net.createServer($APP.lm.j(oZa,$APP.zg));e.listen(c,d,function(){var f=e.address(),h=f.port;f=f.address;$APP.Ep.o($APP.v(["nREPL server started on port "+$APP.G.h(h)+" on host "+$APP.G.h(f)+" - nrepl://"+$APP.G.h(f)+":"+$APP.G.h(h)],0));$APP.CW.j($APP.VU,$APP.Yg(!0));dZa();try{return esm_import$node_fs.writeFileSync(".nrepl-port",
""+$APP.G.h(h))}catch(m){return console.warn($APP.Wn.j(" ",$APP.v(["Could not write .nrepl-port",m],0)))}});return $APP.$g(CZa,e)})},$APP.oY,new $APP.F(null,7,[$APP.Q,$APP.oY,$APP.O,"Start nRepl server. Accepts options either as JS object or Clojure map.",$APP.Y,$APP.H(new $APP.D(null,1,5,$APP.E,[$APP.QM],null)),$APP.I,"nbb/impl/nrepl_server.cljs",$APP.J,350,$APP.M,7,$APP.S,v4],null),v4),AZa,$APP.at(u4,AZa,new $APP.F(null,7,[$APP.Q,AZa,$APP.O,null,$APP.Y,$APP.H($APP.ph,new $APP.D(null,1,5,$APP.E,
[wZa],null)),$APP.I,"nbb/impl/nrepl_server.cljs",$APP.J,422,$APP.M,7,$APP.S,v4],null),v4)],null);$APP.Dz(new $APP.F(null,1,[$APP.xt,new $APP.F(null,1,[$APP.cE,DZa],null)],null));