import { $APP, shadow$provide } from "./nbb_core.js";
const shadow_esm_import = function(x) { return import(x) };
var Y2=function(a,b,c){var d=$APP.De(a);if(c>=d)return-1;for(c=c>0?c:c<0?$APP.Do.j(0,c+d):c;;)if(c<d){if($APP.Ee.j($APP.t.j(a,c),b))return c;c+=1}else return-1},Z2=function(a,b,c){var d=$APP.De(a);if(d===0)return-1;for(c=c>0?$APP.im.j(d-1,c):c<0?d+c:c;;)if(c>=0){if($APP.Ee.j($APP.t.j(a,c),b))return c;--c}else return-1},hWa=function(a,b){if($APP.$e(b))if($APP.Be(a)&&$APP.Be(b)&&$APP.De(a)!==$APP.De(b))a=!1;else a:{a=$APP.n(a);for(b=$APP.n(b);;){if(a==null){a=b==null;break a}if(b!=null&&$APP.Ee.j($APP.p(a),
$APP.p(b)))a=$APP.q(a),b=$APP.q(b);else{a=!1;break a}}a=void 0}else a=null;return $APP.nb(a)},iWa=function(a,b){var c=a.ia(null);if(c===0)return b.v?b.v():b.call(null);for(var d=a.U(null,0),e=1;;)if(e<c){var f=a.U(null,e);d=b.j?b.j(d,f):b.call(null,d,f);if($APP.ue(d))return $APP.xc(d);e+=1}else return d},jWa=function(a,b,c){var d=a.ia(null),e=c;for(c=0;;)if(c<d){var f=a.U(null,c);e=b.j?b.j(e,f):b.call(null,e,f);if($APP.ue(e))return $APP.xc(e);c+=1}else return e},kWa=function(a){return typeof a===
"number"||typeof a==="string"||$APP.gf(a)||a==null},b3=function(a,b,c,d){var e=d!=null?d.h?d.h(a):d.call(null,a):null;return e==null?kWa(a)?a:$APP.Ab(a)?new $2(null,a,b,c,d,!0,null,null,null):$APP.k($APP.wb(a))?new a3(null,b,c,d,a,null):a:e},c3=function(a){return kWa(a)?a:a instanceof $2?a.ta:a instanceof a3?a.F:a},mWa=function(a,b,c,d,e){var f=$APP.ch($APP.jd(lWa));$APP.Ka(a,function(h,m){return f.$b(null,$APP.ei.l(f.Ja(null),b.h?b.h(m):b.call(null,m),$APP.k(e)?b3(h,b,c,d):h))});return $APP.vg($APP.xc(f))},
e3=function(a){a:{for(var b=a.length,c=$APP.Lb(a),d=0;;)if(d<b){var e=d;var f=a[d];f=d3.h?d3.h(f):d3.call(null,f);c[e]=f;d+=1}else{a=c;break a}a=void 0}return $APP.Fh(a)},f3=function(a,b,c,d,e,f,h){h=f[h];f=b.h?b.h(h):b.call(null,h);a=a[h];b=e?b3(a,b,c,d):a;return new $APP.sf(f,b,null)},nWa=function(a,b){return a instanceof $APP.C&&b===$APP.Dj||typeof a==="string"&&b===$APP.Cf},g3=function(a,b){var c;!(c=kWa(a))&&(c=!($APP.af(a)&&!(a instanceof $2)||$APP.cf(a)&&!(a instanceof a3)))&&(a=$APP.k(b)?
(b=$APP.Ab(a))?b:$APP.wb(a):b,c=$APP.yb(a));return c},oWa=function(a,b,c,d,e,f){this.Lb=!0;this.ta=a;this.ha=b;this.W=c;this.transform=d;this.rb=e;this.Xc=f;this.D=259;this.I=56},pWa=function(a,b,c,d,e,f,h){this.ta=a;this.ha=b;this.W=c;this.transform=d;this.rb=e;this.F=f;this.P=0;this.N=h},h3=function(a,b,c,d,e,f,h,m){this.ta=a;this.ha=b;this.W=c;this.transform=d;this.rb=e;this.F=f;this.P=h;this.K=m;this.D=2179858686;this.I=8192},$2=function(a,b,c,d,e,f,h,m,r){this.K=a;this.ta=b;this.ha=c;this.W=
d;this.transform=e;this.rb=f;this.ad=h;this.Xc=m;this.J=r;this.D=2164131599;this.I=139268},qWa=function(a,b,c,d){this.Lb=!0;this.F=a;this.ha=b;this.W=c;this.transform=d;this.I=88;this.D=275},rWa=function(a,b,c,d,e){this.ha=a;this.W=b;this.transform=c;this.F=d;this.P=0;this.N=e},i3=function(a,b,c,d,e,f){this.ha=a;this.W=b;this.transform=c;this.F=d;this.P=e;this.K=f;this.D=2179858686;this.I=8192},a3=function(a,b,c,d,e,f){this.K=a;this.ha=b;this.W=c;this.transform=d;this.F=e;this.J=f;this.D=2315150111;
this.I=141316},j3=function(a){return a instanceof $APP.C?a.aa:null},sWa=new $APP.C(null,"key-\x3eprop","key-\x3eprop",-1028452531),tWa=new $APP.l(null,"bean?","bean?",2057456095,null),uWa=new $APP.C(null,"prop-\x3ekey","prop-\x3ekey",-1297715246),vWa=new $APP.l(null,"bean","bean",-1620239896,null),wWa=new $APP.C(null,"transform","transform",1381301764),xWa=new $APP.l(null,"-\x3eclj","-\x3eclj",-1549422014,null),yWa=new $APP.l(null,"-\x3ejs","-\x3ejs",-1825590244,null);var k3={},lWa=$APP.zg;$APP.g=oWa.prototype;$APP.g.ua=function(a,b){if(this.Lb)return a=this.ta[this.W.h?this.W.h(b):this.W.call(null,b)],this.rb?b3(a,this.ha,this.W,this.transform):a;throw Error("lookup after persistent!");};$APP.g.Y=function(a,b,c){if(this.Lb)return a=$APP.Sa(this.ta,this.W.h?this.W.h(b):this.W.call(null,b),c),this.rb&&a!==c?b3(a,this.ha,this.W,this.transform):a;throw Error("lookup after persistent!");};
$APP.g.ia=function(){return this.Xc==null?this.Xc=$APP.De($APP.La(this.ta)):this.Xc};$APP.g.Pd=function(a,b){a:{if($APP.k(this.Lb)){if($APP.Ch(b)){a=this.xd(null,$APP.mc(b),$APP.nc(b));break a}if($APP.cf(b)){a=this.xd(null,b.h?b.h(0):b.call(null,0),b.h?b.h(1):b.call(null,1));break a}a=$APP.n(b);for(b=this;;){var c=$APP.p(a);if($APP.k(c))a=$APP.q(a),b=$APP.pd(b,$APP.mc(c),$APP.nc(c));else{a=b;break a}}}else throw Error("conj! after persistent!");a=void 0}return a};
$APP.g.ke=function(){if(this.Lb)return this.Lb=!1,new $2(null,this.ta,this.ha,this.W,this.transform,this.rb,null,this.Xc,null);throw Error("persistent! called twice");};$APP.g.xd=function(a,b,c){if(this.Lb){if(!nWa(b,this.ha)||!g3(c,this.rb))return $APP.pd($APP.ug(mWa(this.ta,this.ha,this.W,this.transform,this.rb)),b,c);this.ta[this.W.h?this.W.h(b):this.W.call(null,b)]=this.rb?c3(c):c;this.Xc=null;return this}throw Error("assoc! after persistent!");};
$APP.g.Af=function(a,b){if(this.Lb)return delete this.ta[this.W.h?this.W.h(b):this.W.call(null,b)],this.Xc=null,this;throw Error("dissoc! after persistent!");};$APP.g.call=function(a){switch(arguments.length-1){case 1:return this.h(arguments[1]);case 2:return this.j(arguments[1],arguments[2]);default:throw Error("Invalid arity: "+$APP.G.h(arguments.length-1));}};$APP.g.apply=function(a,b){return this.call.apply(this,[this].concat($APP.Lb(b)))};
$APP.g.h=function(a){if(this.Lb)return a=this.ta[this.W.h?this.W.h(a):this.W.call(null,a)],this.rb?b3(a,this.ha,this.W,this.transform):a;throw Error("lookup after persistent!");};$APP.g.j=function(a,b){if(this.Lb)return a=$APP.Sa(this.ta,this.W.h?this.W.h(a):this.W.call(null,a),b),this.rb&&a!==b?b3(a,this.ha,this.W,this.transform):a;throw Error("lookup after persistent!");};pWa.prototype.hasNext=function(){return this.P<this.N};
pWa.prototype.next=function(){var a=f3(this.ta,this.ha,this.W,this.transform,this.rb,this.F,this.P);this.P+=1;return a};$APP.g=h3.prototype;$APP.g.toString=function(){return $APP.Td(this)};$APP.g.equiv=function(a){return this.T(null,a)};$APP.g.indexOf=function(){var a=null;a=function(b,c){switch(arguments.length){case 1:return Y2(this,b,0);case 2:return Y2(this,b,c)}throw Error("Invalid arity: "+arguments.length);};a.h=function(b){return Y2(this,b,0)};a.j=function(b,c){return Y2(this,b,c)};return a}();
$APP.g.lastIndexOf=function(){function a(c){return Z2(this,c,$APP.De(this))}var b=null;b=function(c,d){switch(arguments.length){case 1:return a.call(this,c);case 2:return Z2(this,c,d)}throw Error("Invalid arity: "+arguments.length);};b.h=a;b.j=function(c,d){return Z2(this,c,d)};return b}();$APP.g.U=function(a,b){a=b+this.P;if(0<=a&&a<this.F.length)return f3(this.ta,this.ha,this.W,this.transform,this.rb,this.F,a);throw Error("Index out of bounds");};
$APP.g.wb=function(a,b,c){a=b+this.P;return 0<=a&&a<this.F.length?f3(this.ta,this.ha,this.W,this.transform,this.rb,this.F,a):c};$APP.g.Z=function(a,b,c){return $APP.yj(b,$APP.Cj,"("," ",")",c,this)};$APP.g.R=function(){return this.K};$APP.g.kb=function(){return new h3(this.ta,this.ha,this.W,this.transform,this.rb,this.F,this.P,this.K)};$APP.g.zb=function(){return this.P+1<this.F.length?new h3(this.ta,this.ha,this.W,this.transform,this.rb,this.F,this.P+1,null):null};
$APP.g.ia=function(){return $APP.Do.j(0,this.F.length-this.P)};$APP.g.fa=function(){return $APP.ne(this)};$APP.g.T=function(a,b){return hWa(this,b)};$APP.g.Ka=function(){return $APP.ie};$APP.g.xb=function(a,b){return iWa(this,b)};$APP.g.ub=function(a,b,c){return jWa(this,b,c)};$APP.g.yb=function(){return f3(this.ta,this.ha,this.W,this.transform,this.rb,this.F,this.P)};$APP.g.Bb=function(){return this.P+1<this.F.length?new h3(this.ta,this.ha,this.W,this.transform,this.rb,this.F,this.P+1,null):$APP.ie};
$APP.g.ka=function(){return this};$APP.g.S=function(a,b){return b===this.K?this:new h3(this.ta,this.ha,this.W,this.transform,this.rb,this.F,this.P,b)};$APP.g.na=function(a,b){return $APP.ag(b,this)};$APP.g=$2.prototype;$APP.g.dd=$APP.$d;$APP.g.ed=function(a,b){a=$APP.Sa(this.ta,this.W.h?this.W.h(b):this.W.call(null,b),k3);return a===k3?null:new $APP.sf(b,this.rb?b3(a,this.ha,this.W,this.transform):a,null)};$APP.g.toString=function(){return $APP.Td(this)};
$APP.g.equiv=function(a){return this.T(null,a)};$APP.g.keys=function(){return $APP.le($APP.Si(this))};$APP.g.entries=function(){return $APP.Xh($APP.n(this))};$APP.g.values=function(){return $APP.le($APP.Ui(this))};$APP.g.has=function(a){return $APP.rf(this,a)};$APP.g.get=function(a,b){return this.Y(null,a,b)};
$APP.g.forEach=function(a){for(var b=$APP.n(this),c=null,d=0,e=0;;)if(e<d){var f=c.U(null,e),h=$APP.t.l(f,0,null);f=$APP.t.l(f,1,null);a.j?a.j(f,h):a.call(null,f,h);e+=1}else if(b=$APP.n(b))$APP.df(b)?(c=$APP.Dd(b),b=$APP.Fd(b),h=c,d=$APP.De(c),c=h):(c=$APP.p(b),h=$APP.t.l(c,0,null),f=$APP.t.l(c,1,null),a.j?a.j(f,h):a.call(null,f,h),b=$APP.q(b),c=null,d=0),e=0;else return null};
$APP.g.ua=function(a,b){a=this.ta[this.W.h?this.W.h(b):this.W.call(null,b)];return this.rb?b3(a,this.ha,this.W,this.transform):a};$APP.g.Y=function(a,b,c){a=$APP.Sa(this.ta,this.W.h?this.W.h(b):this.W.call(null,b),c);return this.rb&&a!==c?b3(a,this.ha,this.W,this.transform):a};
$APP.g.Kb=function(a,b,c){var d=this;try{var e=$APP.ch(c);$APP.Ka(d.ta,function(f,h){var m=e.$b;var r=e.Ja(null);h=d.ha.h?d.ha.h(h):d.ha.call(null,h);f=d.rb?b3(f,d.ha,d.W,d.transform):f;r=b.l?b.l(r,h,f):b.call(null,r,h,f);m=m.call(e,null,r);if($APP.ue(m))throw m;return null});return $APP.xc(e)}catch(f){a=f;if($APP.ue(a))return $APP.xc(a);throw a;}};$APP.g.Z=function(a,b,c){return $APP.Ej(this,$APP.Cj,b,c)};
$APP.g.pb=function(){this.ad==null&&(this.ad=$APP.La(this.ta));return new pWa(this.ta,this.ha,this.W,this.transform,this.rb,this.ad,this.ia(null))};$APP.g.R=function(){return this.K};$APP.g.kb=function(){return new $2(this.K,this.ta,this.ha,this.W,this.transform,this.rb,this.ad,this.Xc,this.J)};$APP.g.ia=function(){return this.Xc==null?(this.ad==null&&(this.ad=$APP.La(this.ta)),this.Xc=this.ad.length):this.Xc};$APP.g.fa=function(){var a=this.J;return a!=null?a:this.J=a=$APP.oe(this)};
$APP.g.T=function(a,b){return $APP.Vh(this,b)};$APP.g.Xd=function(){return new oWa($APP.Ta(this.ta),this.ha,this.W,this.transform,this.rb,this.Xc)};$APP.g.Ka=function(){return new $2(this.K,{},this.ha,this.W,this.transform,this.rb,[],0,null)};$APP.g.xb=function(a,b){return $APP.JB(this.ka(null),b)};$APP.g.ub=function(a,b,c){return this.Kb(null,function(d,e,f){e=new $APP.sf(e,f,null);return b.j?b.j(d,e):b.call(null,d,e)},c)};
$APP.g.Vb=function(a,b){a=this.K;var c=$APP.Ta(this.ta);delete c[this.W.h?this.W.h(b):this.W.call(null,b)];return new $2(a,c,this.ha,this.W,this.transform,this.rb,null,null,null)};$APP.g.ra=function(a,b,c){if(nWa(b,this.ha)&&g3(c,this.rb)){a=this.K;var d=$APP.Ta(this.ta);d[this.W.h?this.W.h(b):this.W.call(null,b)]=this.rb?c3(c):c;b=new $2(a,d,this.ha,this.W,this.transform,this.rb,null,null,null)}else b=$APP.gc($APP.Se(mWa(this.ta,this.ha,this.W,this.transform,this.rb),this.K),b,c);return b};
$APP.g.Fb=function(a,b){return this.Y(null,b,k3)!==k3};$APP.g.ka=function(){this.ad==null&&(this.ad=$APP.La(this.ta));return this.ad.length>0?new h3(this.ta,this.ha,this.W,this.transform,this.rb,this.ad,0,null):null};$APP.g.S=function(a,b){return b===this.K?this:new $2(b,this.ta,this.ha,this.W,this.transform,this.rb,this.ad,this.Xc,this.J)};
$APP.g.na=function(a,b){a:if($APP.cf(b))a=this.ra(null,$APP.Pe(b,0),$APP.Pe(b,1));else{a=this;for(b=$APP.n(b);;){if(b==null)break a;var c=$APP.p(b);if($APP.cf(c))a=$APP.gc(a,$APP.Pe(c,0),$APP.Pe(c,1)),b=$APP.q(b);else throw Error("conj on a map takes map entries or seqables of map entries");}a=void 0}return a};
$APP.g.call=function(a){switch(arguments.length-1){case 1:return this.h(arguments[1]);case 2:return this.j(arguments[1],arguments[2]);default:throw Error("Invalid arity: "+$APP.G.h(arguments.length-1));}};$APP.g.apply=function(a,b){return this.call.apply(this,[this].concat($APP.Lb(b)))};$APP.g.h=function(a){a=this.ta[this.W.h?this.W.h(a):this.W.call(null,a)];return this.rb?b3(a,this.ha,this.W,this.transform):a};
$APP.g.j=function(a,b){a=$APP.Sa(this.ta,this.W.h?this.W.h(a):this.W.call(null,a),b);return this.rb&&a!==b?b3(a,this.ha,this.W,this.transform):a};$APP.g=qWa.prototype;$APP.g.Pd=function(a,b){if(this.Lb)return g3(b,!0)?(this.F.push(c3(b)),this):$APP.md($APP.ug(e3(this.F)),b);throw Error("conj! after persistent!");};$APP.g.ke=function(){if(this.Lb)return this.Lb=!1,new a3(null,this.ha,this.W,this.transform,this.F,null);throw Error("persistent! called twice");};
$APP.g.xd=function(a,b,c){if(typeof b==="number")a=this.af(null,b,c);else throw Error(""+$APP.G.h("TransientArrayVector")+"'s key for assoc! must be a number.");return a};
$APP.g.af=function(a,b,c){if(this.Lb){if(g3(c,!0)){if(0<=b&&b<this.F.length)return this.F[b]=c3(c),this;if(b===this.F.length)return this.Pd(null,c);throw Error("Index "+$APP.G.h(b)+" out of bounds for TransientArrayVector of length"+$APP.G.h(this.F.length));}return $APP.wd($APP.ug(e3(this.F)),b,c)}throw Error("assoc! after persistent!");};
$APP.g.rg=function(){if(this.Lb){if(this.F.length===0)throw Error("Can't pop empty vector");this.F=this.F.slice(0,this.F.length-1);return this}throw Error("pop! after persistent!");};$APP.g.ia=function(){if(this.Lb)return this.F.length;throw Error("count after persistent!");};$APP.g.U=function(a,b){if(this.Lb)return b3(this.F[b],this.ha,this.W,this.transform);throw Error("nth after persistent!");};$APP.g.wb=function(a,b,c){return 0<=b&&b<this.F.length?this.U(null,b):c};
$APP.g.ua=function(a,b){return this.Y(null,b,null)};$APP.g.Y=function(a,b,c){return typeof b==="number"?this.wb(null,b,c):c};$APP.g.call=function(a){switch(arguments.length-1){case 1:return this.h(arguments[1]);case 2:return this.j(arguments[1],arguments[2]);default:throw Error("Invalid arity: "+$APP.G.h(arguments.length-1));}};$APP.g.apply=function(a,b){return this.call.apply(this,[this].concat($APP.Lb(b)))};$APP.g.h=function(a){return this.ua(null,a)};
$APP.g.j=function(a,b){return this.Y(null,a,b)};rWa.prototype.hasNext=function(){return this.P<this.N};rWa.prototype.next=function(){var a=b3(this.F[this.P],this.ha,this.W,this.transform);this.P+=1;return a};$APP.g=i3.prototype;$APP.g.toString=function(){return $APP.Td(this)};$APP.g.equiv=function(a){return this.T(null,a)};
$APP.g.indexOf=function(){var a=null;a=function(b,c){switch(arguments.length){case 1:return Y2(this,b,0);case 2:return Y2(this,b,c)}throw Error("Invalid arity: "+arguments.length);};a.h=function(b){return Y2(this,b,0)};a.j=function(b,c){return Y2(this,b,c)};return a}();
$APP.g.lastIndexOf=function(){function a(c){return Z2(this,c,$APP.De(this))}var b=null;b=function(c,d){switch(arguments.length){case 1:return a.call(this,c);case 2:return Z2(this,c,d)}throw Error("Invalid arity: "+arguments.length);};b.h=a;b.j=function(c,d){return Z2(this,c,d)};return b}();$APP.g.U=function(a,b){a=b+this.P;if(0<=a&&a<this.F.length)return b3(this.F[a],this.ha,this.W,this.transform);throw Error("Index out of bounds");};
$APP.g.wb=function(a,b,c){a=b+this.P;return 0<=a&&a<this.F.length?b3(this.F[a],this.ha,this.W,this.transform):c};$APP.g.Z=function(a,b,c){return $APP.yj(b,$APP.Cj,"("," ",")",c,this)};$APP.g.R=function(){return this.K};$APP.g.kb=function(){return new i3(this.ha,this.W,this.transform,this.F,this.P,this.K)};$APP.g.zb=function(){return this.P+1<this.F.length?new i3(this.ha,this.W,this.transform,this.F,this.P+1,null):null};$APP.g.ia=function(){return $APP.Do.j(0,this.F.length-this.P)};$APP.g.fa=function(){return $APP.ne(this)};
$APP.g.T=function(a,b){return hWa(this,b)};$APP.g.Ka=function(){return $APP.ie};$APP.g.xb=function(a,b){return iWa(this,b)};$APP.g.ub=function(a,b,c){return jWa(this,b,c)};$APP.g.yb=function(){return b3(this.F[this.P],this.ha,this.W,this.transform)};$APP.g.Bb=function(){return this.P+1<this.F.length?new i3(this.ha,this.W,this.transform,this.F,this.P+1,null):$APP.ie};$APP.g.ka=function(){return this};$APP.g.S=function(a,b){return b===this.K?this:new i3(this.ha,this.W,this.transform,this.F,this.P,b)};
$APP.g.na=function(a,b){return $APP.ag(b,this)};$APP.g=a3.prototype;$APP.g.dd=$APP.$d;$APP.g.ed=function(a,b){return 0<=b&&b<this.F.length?new $APP.sf(b,b3(this.F[b],this.ha,this.W,this.transform),null):null};$APP.g.toString=function(){return $APP.Td(this)};$APP.g.equiv=function(a){return this.T(null,a)};
$APP.g.indexOf=function(){var a=null;a=function(b,c){switch(arguments.length){case 1:return Y2(this,b,0);case 2:return Y2(this,b,c)}throw Error("Invalid arity: "+arguments.length);};a.h=function(b){return Y2(this,b,0)};a.j=function(b,c){return Y2(this,b,c)};return a}();
$APP.g.lastIndexOf=function(){var a=null;a=function(b,c){switch(arguments.length){case 1:return Z2(this,b,$APP.De(this));case 2:return Z2(this,b,c)}throw Error("Invalid arity: "+arguments.length);};a.h=function(b){return Z2(this,b,$APP.De(this))};a.j=function(b,c){return Z2(this,b,c)};return a}();$APP.g.ua=function(a,b){return this.Y(null,b,null)};$APP.g.Y=function(a,b,c){return typeof b==="number"?this.wb(null,b,c):c};
$APP.g.Kb=function(a,b,c){a=0;for(var d=c;;)if(a<this.F.length){c=this.F.length;var e;a:{for(e=0;;)if(e<c){var f=e+a,h=b3(this.F[e],this.ha,this.W,this.transform);d=b.l?b.l(d,f,h):b.call(null,d,f,h);if($APP.ue(d)){e=d;break a}e+=1}else{e=d;break a}e=void 0}if($APP.ue(e))return $APP.xc(e);a+=c;d=e}else return d};$APP.g.U=function(a,b){if(0<=b&&b<this.F.length)return b3(this.F[b],this.ha,this.W,this.transform);throw Error("No item "+$APP.G.h(b)+" in vector of length "+$APP.G.h(this.F.length));};
$APP.g.wb=function(a,b,c){return 0<=b&&b<this.F.length?b3(this.F[b],this.ha,this.W,this.transform):c};$APP.g.Z=function(a,b,c){return $APP.yj(b,$APP.Cj,"["," ","]",c,this)};$APP.g.Pc=function(a,b,c){if(0<=b&&b<this.F.length)return g3(c,!0)?(a=$APP.Lb(this.F),a[b]=c3(c),new a3(this.K,this.ha,this.W,this.transform,a,null)):$APP.vc(e3(this.F),b,c);if(b===this.F.length)return this.na(null,c);throw Error("Index "+$APP.G.h(b)+" out of bounds  [0,"+$APP.G.h(this.F.length)+"]");};
$APP.g.pb=function(){return new rWa(this.ha,this.W,this.transform,this.F,this.F.length)};$APP.g.R=function(){return this.K};$APP.g.kb=function(){return new a3(this.K,this.ha,this.W,this.transform,this.F,this.J)};$APP.g.ia=function(){return this.F.length};$APP.g.vd=function(){return this.F.length>0?this.U(null,this.F.length-1):null};
$APP.g.wd=function(){if(this.F.length===0)throw Error("Can't pop empty vector");if(1===this.F.length)return this.Ka(null);var a=$APP.Lb(this.F);return new a3(this.K,this.ha,this.W,this.transform,a.slice(0,a.length-1),null)};$APP.g.ud=function(){return this.F.length>0?new $APP.Je(this,this.F.length-1,null):null};$APP.g.fa=function(){var a=this.J;return a!=null?a:this.J=a=$APP.ne(this)};
$APP.g.T=function(a,b){a:if(b instanceof a3)if(this.F.length===$APP.De(b)){a=this.pb(null);for(b=$APP.Qd(b);;){if(a.hasNext()){var c=a.next(),d=b.next();if($APP.Ee.j(c,d))continue;else{a=!1;break a}}else{a=!0;break a}break}a=void 0}else a=!1;else a=hWa(this,b);return a};$APP.g.Xd=function(){return new qWa($APP.Lb(this.F),this.ha,this.W,this.transform)};$APP.g.Ka=function(){return new a3(this.K,this.ha,this.W,this.transform,[],null)};$APP.g.xb=function(a,b){return iWa(this,b)};
$APP.g.ub=function(a,b,c){return jWa(this,b,c)};$APP.g.ra=function(a,b,c){if(typeof b==="number")a=this.Pc(null,b,c);else throw Error("Vector's key for assoc must be a number.");return a};$APP.g.Fb=function(a,b){return $APP.lf(b)?0<=b&&b<this.F.length:!1};$APP.g.ka=function(){return this.F.length>0?new i3(this.ha,this.W,this.transform,this.F,0,null):null};$APP.g.S=function(a,b){return b===this.K?this:new a3(b,this.ha,this.W,this.transform,this.F,this.J)};
$APP.g.na=function(a,b){return g3(b,!0)?(a=$APP.Lb(this.F),a[a.length]=c3(b),new a3(this.K,this.ha,this.W,this.transform,a,null)):$APP.Wb(e3(this.F),b)};$APP.g.call=function(a){switch(arguments.length-1){case 1:return this.h(arguments[1]);case 2:return this.j(arguments[1],arguments[2]);default:throw Error("Invalid arity: "+$APP.G.h(arguments.length-1));}};$APP.g.apply=function(a,b){return this.call.apply(this,[this].concat($APP.Lb(b)))};$APP.g.h=function(a){return this.U(null,a)};
$APP.g.j=function(a,b){return this.wb(null,a,b)};$APP.g.Oc=function(a,b){if($APP.cf(b)){a=$APP.De(this);var c=$APP.De(b);if(a<c)b=-1;else if(a>c)b=1;else if(a===0)b=0;else a:{for(c=0;;){var d=$APP.vf($APP.t.j(this,c),$APP.t.j(b,c));if(d===0&&c+1<a)c+=1;else{b=d;break a}}b=void 0}return b}throw Error("Cannot compare "+$APP.G.h(this)+" to "+$APP.G.h(b));};
var l3=function l3(a){switch(arguments.length){case 0:return l3.v();case 1:return l3.h(arguments[0]);default:for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return l3.o(arguments[0],1<c.length?new $APP.fe(c.slice(1),0,null):null)}};l3.v=function(){return new $2(null,{},$APP.Dj,j3,null,!1,[],0,null)};l3.h=function(a){return new $2(null,a,$APP.Dj,j3,null,!1,null,null,null)};
l3.o=function(a,b){var c=$APP.Ag(b);b=$APP.y.j(c,$APP.VC);var d=$APP.y.j(c,uWa),e=$APP.y.j(c,sWa),f=$APP.y.j(c,wWa);c=$APP.y.j(c,$APP.tD);return b===!1?new $2(null,a,$APP.Cf,$APP.Cf,f,$APP.nb(c),null,null,null):d!=null&&e!=null?new $2(null,a,d,e,f,$APP.nb(c),null,null,null):new $2(null,a,$APP.Dj,j3,f,$APP.nb(c),null,null,null)};l3.B=function(a){var b=$APP.p(a);a=$APP.q(a);return this.o(b,a)};l3.A=1;
var d3=function d3(a){switch(arguments.length){case 1:return d3.h(arguments[0]);default:for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return d3.o(arguments[0],1<c.length?new $APP.fe(c.slice(1),0,null):null)}};d3.h=function(a){return b3(a,$APP.Dj,j3,null)};d3.o=function(a,b){var c=$APP.Ag(b);b=$APP.y.j(c,$APP.VC);var d=$APP.y.j(c,uWa),e=$APP.y.j(c,sWa);c=$APP.y.j(c,wWa);return b===!1?b3(a,$APP.Cf,$APP.Cf,c):d!=null&&e!=null?b3(a,d,e,c):b3(a,$APP.Dj,j3,c)};
d3.B=function(a){var b=$APP.p(a);a=$APP.q(a);return this.o(b,a)};d3.A=1;var m3=function m3(a){switch(arguments.length){case 1:return m3.h(arguments[0]);default:for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return m3.o(arguments[0],1<c.length?new $APP.fe(c.slice(1),0,null):null)}};m3.h=function(a){return a instanceof $2?a.ta:a instanceof a3?a.F:$APP.TC.o(a,$APP.v([$APP.UC,j3],0))};
m3.o=function(a,b){if(a instanceof $2)return a.ta;if(a instanceof a3)return a.F;b=$APP.Ag(b);b=$APP.y.l(b,sWa,j3);return $APP.TC.o(a,$APP.v([$APP.UC,b],0))};m3.B=function(a){var b=$APP.p(a);a=$APP.q(a);return this.o(b,a)};m3.A=1;var n3=$APP.GW.j($APP.$J,null),zWa=new $APP.F(null,5,[vWa,$APP.at(l3,vWa,new $APP.F(null,7,[$APP.Q,vWa,$APP.O,"Takes a JavaScript object and returns a read-only implementation of the map\n  abstraction backed by the object.\n\n  By default, bean produces beans that keywordize the keys. Supply\n  :keywordize-keys false to suppress this behavior. You can alternatively\n  supply :prop-\x3ekey and :key-\x3eprop with functions that control the mapping\n  between properties and keys.\n\n  Supply :recursive true to create a bean which recursively converts\n  JavaScript object values to beans and JavaScript arrays into vectors.\n\n  Supply :transform and a function of one argument to transform values being\n  converted from JavaScript to ClojureScript. This function should return nil\n  if no conversion is to be performed, thus allowing default logic to be applied.\n\n  Calling (bean) produces an empty bean.",
$APP.Y,$APP.H($APP.ph,new $APP.D(null,1,5,$APP.E,[$APP.uQ],null),new $APP.D(null,3,5,$APP.E,[$APP.uQ,$APP.Kk,$APP.QM],null)),$APP.I,"cljs_bean/core.cljs",$APP.J,702,$APP.M,7,$APP.S,n3],null),n3),tWa,$APP.at(function(a){return a instanceof $2},tWa,new $APP.F(null,7,[$APP.Q,tWa,$APP.O,"Returns true if x is a bean.",$APP.Y,$APP.H(new $APP.D(null,1,5,$APP.E,[$APP.uQ],null)),$APP.I,"cljs_bean/core.cljs",$APP.J,735,$APP.M,7,$APP.S,n3],null),n3),$APP.nP,$APP.at(function(a){return a.ta},$APP.nP,new $APP.F(null,
8,[$APP.Q,$APP.nP,$APP.O,"Takes a bean and returns a JavaScript object.",$APP.Y,$APP.H(new $APP.D(null,1,5,$APP.E,[$APP.bQ],null)),$APP.bn,$APP.oH,$APP.I,"cljs_bean/core.cljs",$APP.J,740,$APP.M,11,$APP.S,n3],null),n3),yWa,$APP.at(m3,yWa,new $APP.F(null,7,[$APP.Q,yWa,$APP.O,"Recursively converts ClojureScript values to JavaScript.\n\n  Where possible, directly returns the backing objects and arrays for values\n  produced using -\x3eclj and bean.\n\n  Otherwise delegates to clj-\x3ejs to perform the conversion, converting keyword\n  keys using their qualified names. You can alternatively supply :key-\x3eprop with\n  a function that controls the mapping from keys to properties.",
$APP.Y,$APP.H(new $APP.D(null,1,5,$APP.E,[$APP.uQ],null),new $APP.D(null,3,5,$APP.E,[$APP.uQ,$APP.Kk,$APP.QM],null)),$APP.I,"cljs_bean/core.cljs",$APP.J,775,$APP.M,7,$APP.S,n3],null),n3),xWa,$APP.at(d3,xWa,new $APP.F(null,7,[$APP.Q,xWa,$APP.O,"Recursively converts JavaScript values to ClojureScript.\n\n  JavaScript objects are converted to beans with keywords for keys.\n\n  JavaScript arrays are converted to read-only implementations of the vector\n  abstraction, backed by the supplied array.\n\n  By default, -\x3eclj produces values that keywordize the keys. Supply\n  :keywordize-keys false to suppress this behavior. You can alternatively\n  supply :prop-\x3ekey and :key-\x3eprop with functions that control the mapping\n  between properties and keys.\n\n  Supply :transform and a function of one argument to transform values being\n  converted from JavaScript to ClojureScript. This function should return nil\n  if no conversion is to be performed, thus allowing default logic to be applied.",
$APP.Y,$APP.H(new $APP.D(null,1,5,$APP.E,[$APP.uQ],null),new $APP.D(null,3,5,$APP.E,[$APP.uQ,$APP.Kk,$APP.QM],null)),$APP.I,"cljs_bean/core.cljs",$APP.J,745,$APP.M,7,$APP.S,n3],null),n3)],null);$APP.Dz(new $APP.F(null,1,[$APP.xt,new $APP.F(null,1,[$APP.$J,zWa],null)],null));