import { $APP, shadow$provide } from "./nbb_core.js";
import "./nbb_api.js";
const shadow_esm_import = function(x) { return import(x) };
import*as esm_import$node_process from"node:process";import*as esm_import$node_path from"node:path";var mTa,nTa,pTa,qTa,oTa,rTa;mTa=function(a){a=$APP.Lj.h(a);var b=$APP.gg(a)?$APP.Lj.j(""+$APP.G.h(a),"-main"):a,c=$APP.dg(b);return $APP.ql("(require '$1) (apply $2 *command-line-args*)",/\$(\d)/,function(d){d=$APP.Ke(d);switch(d){case "1":return c;case "2":return b;default:throw Error("No matching clause: "+$APP.G.h(d));}})};
nTa=function(a){var b=$APP.Lj.h(a),c=$APP.dg(b);return $APP.ql("\n(require '[babashka.cli])\n(require '$1)\n(let [the-var (resolve '$2)\n      the-var-meta (meta the-var)\n      ns (:ns (meta the-var))\n      ns-meta (meta ns)\n      cli-opts (babashka.cli/merge-opts (:org.babashka/cli ns-meta)\n                                        (:org.babashka/cli the-var-meta))\n      opts (babashka.cli/parse-opts *command-line-args* cli-opts)]\n  (the-var opts))\n",/\$(\d)/,function(d){d=$APP.Ke(d);switch(d){case "1":return c;
case "2":return b;default:throw Error("No matching clause: "+$APP.G.h(d));}})};
$APP.y2=function(a){for(var b=$APP.zg,c=a;;){if($APP.k(c)){var d=$APP.p(c);a=$APP.q(c);switch(d){case "--help":case "-h":return $APP.Wi.l(b,$APP.aq,!0);case "--version":case "-v":return $APP.Wi.l(b,oTa,!0);case "-e":b=$APP.Wi.l(b,$APP.pr,$APP.p(a));c=a=$APP.q(a);continue;case "-m":case "--main":return $APP.Wi.o(b,$APP.pr,mTa($APP.p(a)),$APP.v([$APP.wo,$APP.q(a)],0));case "-x":case "--exec":return $APP.Wi.o(b,$APP.pr,nTa($APP.p(a)),$APP.v([$APP.wo,$APP.q(a)],0));case "-cp":case "--classpath":b=$APP.Wi.l(b,
$APP.pY,$APP.p(a));c=a=$APP.q(a);continue;case "--config":b=$APP.Wi.l(b,$APP.rz,$APP.p(a));c=a=$APP.q(a);continue;case "--debug":b=$APP.Wi.l(b,$APP.fz,!0);c=a;continue;case "nrepl-server":b=$APP.Wi.l(b,$APP.w2,!0);c=a;continue;case "socket-repl":b=$APP.Wi.l(b,pTa,!0);c=a;continue;case ":port":case "--port":b=$APP.Wi.l(b,$APP.GM,$APP.p(a));c=a=$APP.q(a);continue;case ":host":case "--host":b=$APP.Wi.l(b,$APP.CT,$APP.p(a));c=a=$APP.q(a);continue;case "repl":b=$APP.Wi.l(b,qTa,!0);c=a;continue;case "bundle":return $APP.Wi.l(b,
$APP.SQ,$APP.zp.j(a,new $APP.F(null,1,[$APP.ro,new $APP.F(null,2,[rTa,$APP.qAa,$APP.bq,$APP.aq],null)],null)));default:if($APP.yb($APP.pr.h(c)))return $APP.Wi.o(b,$APP.x2,d,$APP.v([$APP.wo,$APP.q(c)],0));throw $APP.xm.j("Unrecognized options:"+$APP.G.h(c),$APP.zg);}}else return b;break}};
$APP.z2=function(){var a=$APP.n(function(){var h=globalThis.nbb_args;return $APP.k(h)?h:esm_import$node_process.argv}());$APP.p(a);a=$APP.q(a);$APP.p(a);a=$APP.q(a);var b=$APP.y2(a);$APP.$g(sTa,b);var c=$APP.x2.h(b),d=$APP.pr.h(b);a=$APP.pY.h(b);$APP.k(a)&&$APP.as(a);a=$APP.w2.h(b);var e=function(){var h=qTa.h(b);if($APP.k(h))return h;h=pTa.h(b);return $APP.k(h)?h:$APP.We($APP.hm.o(b,$APP.pY,$APP.v([$APP.fz,$APP.rz],0)))}(),f=$APP.SQ.h(b);$APP.k($APP.aq.h(b))&&($APP.Ep.o($APP.v([$APP.qaa("nbb"),"version:",
$APP.Jz()],0)),$APP.Ep.o($APP.v(["\nHelp:\n\n -h / --help: print this help text and exit.\n -v / --version: print the current version of nbb.\n\nGlobal options:\n\n --debug: print additional debug info.\n -cp / --classpath: set the classpath.\n\nEvaluation:\n\n -e: execute expression\n -m / --main: execute main function\n -x / --exec: execute function using babashka.cli\n\nREPL:\n\n repl: start console REPL.\n nrepl-server: start nrepl server. [1,2]\n socket-repl: start socket repl server. [1]\n\n 1: Provide :port \x3cport\x3e to specify port\n 2: Provide :host \x3chost\x3e to specify host\n\nTooling:\n\n  bundle: produce single JS file for usage with bundlers.\n"],
0)),esm_import$node_process.exit(0));$APP.k(oTa.h(b))&&($APP.Ep.o($APP.v([""+$APP.G.h("nbb")+" v"+$APP.G.h($APP.Jz())],0)),esm_import$node_process.exit(0));return $APP.k($APP.k(c)?c:$APP.k(d)?d:$APP.k(a)?a:$APP.k(e)?e:f)?($APP.CW.j($APP.BGa,$APP.Yg($APP.wo.h(b))),Promise.resolve($APP.lY($APP.k(e)?esm_import$node_path.resolve("script.cljs"):c,b)).then(function(){return($APP.k(c)?$APP.qY.h(c):$APP.k(d)?$APP.rY.h(d):$APP.k($APP.w2.h(b))?shadow_esm_import("./nbb_nrepl_server.js").then(function(){var h=
$APP.y.j($APP.y.j($APP.xt.h($APP.ve($APP.st.h($APP.rs()))),$APP.cE),$APP.oY);return h.h?h.h(b):h.call(null,b)}):$APP.k($APP.k(e)?pTa.h(b):e)?shadow_esm_import("./nbb_repl.js").then(function(){var h=new $APP.F(null,1,[$APP.GM,$APP.GM.h(b)],null),m=$APP.y.j($APP.y.j($APP.xt.h($APP.ve($APP.st.h($APP.rs()))),$APP.dD),$APP.mY);return m.h?m.h(h):m.call(null,h)}):$APP.k($APP.SQ.h(b))?shadow_esm_import("./nbb_bundler.js"):$APP.k(e)?shadow_esm_import("./nbb_repl.js").then(function(){var h=$APP.y.j($APP.y.j($APP.xt.h($APP.ve($APP.st.h($APP.rs()))),
$APP.dD),$APP.nY);return h.v?h.v():h.call(null)}):null).then(function(h){$APP.k($APP.k(d)?h!=null:d)&&$APP.ez.o($APP.v([h],0));return h}).catch(function(h){$APP.Bla(h,b);$APP.k($APP.fz.h(b))&&console.error(h);throw Error($APP.Ik(h));})})):console.error("Usage: "+$APP.G.h("nbb")+" \x3cscript\x3e or nbb -e \x3cexpr\x3e.")};$APP.w2=new $APP.C(null,"nrepl-server","nrepl-server",557025430);pTa=new $APP.C(null,"socket-repl","socket-repl",1039210136);$APP.x2=new $APP.C(null,"script","script",-1304443801);
qTa=new $APP.C(null,"repl","repl",-35398667);oTa=new $APP.C(null,"version","version",425292698);rTa=new $APP.C(null,"o","o",-1350007228);var sTa=$APP.ak.h(null);