import { $APP, shadow$provide } from "./nbb_core.js";
const shadow_esm_import = function(x) { return import(x) };
var e4=function(a,b){return $APP.u.j(a,b)?new $APP.E(null,3,5,$APP.F,[null,null,a],null):new $APP.E(null,3,5,$APP.F,[a,b,null],null)},Z1a=function(a){return $APP.n(a)?$APP.yf.l(function(b,c){var d=$APP.x.l(c,0,null);c=$APP.x.l(c,1,null);return $APP.Ti.l(b,d,c)},$APP.Dh($APP.zo.j($APP.Tg.j($APP.Ao,$APP.Pi(a)),null)),a):null},a2a=function(a,b,c){var d=$APP.z.j(a,c),e=$APP.z.j(b,c),f=$1a(d,e),g=$APP.x.l(f,0,null),m=$APP.x.l(f,1,null);f=$APP.x.l(f,2,null);a=$APP.qf(a,c);b=$APP.qf(b,c);d=a&&b&&(f!=null||
d==null&&e==null);return new $APP.E(null,3,5,$APP.F,[!a||g==null&&d?null:$APP.wg([c,g]),!b||m==null&&d?null:$APP.wg([c,m]),d?$APP.wg([c,f]):null],null)},b2a=function(a,b){return $APP.Dh($APP.pk.j(Z1a,f4.l($APP.af(a)?a:$APP.Dh(a),$APP.af(b)?b:$APP.Dh(b),$APP.Eo.h($APP.Ao.j($APP.De(a),$APP.De(b))))))},c2a=function(a,b){return new $APP.E(null,3,5,$APP.F,[$APP.zg($APP.hV.j(a,b)),$APP.zg($APP.hV.j(b,a)),$APP.zg($APP.gV.j(a,b))],null)},g4=function(a){if(a!=null&&a.mk!=null)a=a.mk(a);else{var b=g4[$APP.ca(a==
null?null:a)];if(b!=null)a=b.h?b.h(a):b.call(null,a);else if(b=g4._,b!=null)a=b.h?b.h(a):b.call(null,a);else throw $APP.Gb("EqualityPartition.equality-partition",a);}return a},h4=function(a,b){if(a!=null&&a.lk!=null)a=a.lk(a,b);else{var c=h4[$APP.ca(a==null?null:a)];if(c!=null)a=c.j?c.j(a,b):c.call(null,a,b);else if(c=h4._,c!=null)a=c.j?c.j(a,b):c.call(null,a,b);else throw $APP.Gb("Diff.diff-similar",a);}return a},$1a=function(a,b){return $APP.u.j(a,b)?new $APP.E(null,3,5,$APP.F,[null,null,a],null):
$APP.u.j(g4(a),g4(b))?h4(a,b):e4(a,b)},d2a=new $APP.D(null,"sequential","sequential",-1082983960),i4=new $APP.D(null,"atom","atom",-397043653),e2a=new $APP.l(null,"diff","diff",-518492986,null);var f4=function f4(a){switch(arguments.length){case 2:return f4.j(arguments[0],arguments[1]);case 3:return f4.l(arguments[0],arguments[1],arguments[2]);default:throw Error(["Invalid arity: ",arguments.length].join(""));}};f4.j=function(a,b){return f4.l(a,b,$APP.fV.j($APP.Pi(a),$APP.Pi(b)))};f4.l=function(a,b,c){return $APP.yf.l(function(d,e){return $APP.qq.h($APP.pk.l($APP.em,d,e))},new $APP.E(null,3,5,$APP.F,[null,null,null],null),$APP.pk.j($APP.hm.l(a2a,a,b),c))};f4.A=3;g4["null"]=function(){return i4};
g4.string=function(){return i4};g4.number=function(){return i4};g4.array=function(){return d2a};g4["function"]=function(){return i4};g4["boolean"]=function(){return i4};g4._=function(a){return(a!=null?a.H&1024||$APP.Yd===a.th||(a.H?0:$APP.Eb($APP.ic,a)):$APP.Eb($APP.ic,a))?$APP.Tm:(a!=null?a.H&4096||$APP.Yd===a.vh||(a.H?0:$APP.Eb($APP.oc,a)):$APP.Eb($APP.oc,a))?$APP.bn:(a!=null?a.H&16777216||$APP.Yd===a.Ef||(a.H?0:$APP.Eb($APP.Lc,a)):$APP.Eb($APP.Lc,a))?d2a:i4};
h4["null"]=function(a,b){return e4(a,b)};h4.string=function(a,b){return e4(a,b)};h4.number=function(a,b){return e4(a,b)};h4.array=function(a,b){return b2a(a,b)};h4["function"]=function(a,b){return e4(a,b)};h4["boolean"]=function(a,b){return e4(a,b)};
h4._=function(a,b){var c=function(){var d=g4(a);d=d instanceof $APP.D?d.ca:null;switch(d){case "atom":return e4;case "set":return c2a;case "sequential":return b2a;case "map":return f4;default:throw Error("No matching clause: "+$APP.I.h(d));}}();return c.j?c.j(a,b):c.call(null,a,b)};var f2a=$APP.fX.j($APP.UFa,null),g2a=new $APP.G(null,1,[e2a,$APP.$s($1a,e2a,new $APP.G(null,7,[$APP.R,e2a,$APP.Q,"Recursively compares a and b, returning a tuple of\n  [things-only-in-a things-only-in-b things-in-both].\n  Comparison rules:\n\n  * For equal a and b, return [nil nil a].\n  * Maps are subdiffed where keys match and values differ.\n  * Sets are never subdiffed.\n  * All sequential things are treated as associative collections\n    by their indexes, with results returned as vectors.\n  * Everything else (including strings!) is treated as\n    an atom and compared for equality.",
$APP.Y,$APP.J(new $APP.E(null,2,5,$APP.F,[$APP.jS,$APP.iS],null)),$APP.K,"clojure/data.cljs",$APP.M,144,$APP.N,7,$APP.T,f2a],null),f2a)],null);$APP.sD(new $APP.G(null,1,[$APP.wt,new $APP.G(null,1,[$APP.UFa,g2a],null)],null));