import { $APP, shadow$provide } from "./nbb_core.js";
const shadow_esm_import = function(x) { return import(x) };
var A2=function(a,b){return $APP.Ee.j(a,b)?new $APP.D(null,3,5,$APP.E,[null,null,a],null):new $APP.D(null,3,5,$APP.E,[a,b,null],null)},tTa=function(a){return $APP.n(a)?$APP.Af.l(function(b,c){var d=$APP.t.l(c,0,null);c=$APP.t.l(c,1,null);return $APP.Wi.l(b,d,c)},$APP.Fh($APP.Bo.j($APP.Wg.j($APP.Do,$APP.Si(a)),null)),a):null},vTa=function(a,b,c){var d=$APP.y.j(a,c),e=$APP.y.j(b,c),f=uTa(d,e),h=$APP.t.l(f,0,null),m=$APP.t.l(f,1,null);f=$APP.t.l(f,2,null);a=$APP.rf(a,c);b=$APP.rf(b,c);d=a&&b&&(f!=null||
d==null&&e==null);return new $APP.D(null,3,5,$APP.E,[!a||h==null&&d?null:$APP.yg([c,h]),!b||m==null&&d?null:$APP.yg([c,m]),d?$APP.yg([c,f]):null],null)},wTa=function(a,b){return $APP.Fh($APP.qk.j(tTa,B2.l($APP.cf(a)?a:$APP.Fh(a),$APP.cf(b)?b:$APP.Fh(b),$APP.Ho.h($APP.Do.j($APP.De(a),$APP.De(b))))))},xTa=function(a,b){return new $APP.D(null,3,5,$APP.E,[$APP.Bg($APP.IU.j(a,b)),$APP.Bg($APP.IU.j(b,a)),$APP.Bg($APP.HU.j(a,b))],null)},C2=function(a){if(a!=null&&a.Xj!=null)a=a.Xj(a);else{var b=C2[$APP.ca(a==
null?null:a)];if(b!=null)a=b.h?b.h(a):b.call(null,a);else if(b=C2._,b!=null)a=b.h?b.h(a):b.call(null,a);else throw $APP.Ib("EqualityPartition.equality-partition",a);}return a},D2=function(a,b){if(a!=null&&a.Wj!=null)a=a.Wj(a,b);else{var c=D2[$APP.ca(a==null?null:a)];if(c!=null)a=c.j?c.j(a,b):c.call(null,a,b);else if(c=D2._,c!=null)a=c.j?c.j(a,b):c.call(null,a,b);else throw $APP.Ib("Diff.diff-similar",a);}return a},uTa=function(a,b){return $APP.Ee.j(a,b)?new $APP.D(null,3,5,$APP.E,[null,null,a],null):
$APP.Ee.j(C2(a),C2(b))?D2(a,b):A2(a,b)},yTa=new $APP.C(null,"sequential","sequential",-1082983960),E2=new $APP.C(null,"atom","atom",-397043653),zTa=new $APP.l(null,"diff","diff",-518492986,null);var B2=function B2(a){switch(arguments.length){case 2:return B2.j(arguments[0],arguments[1]);case 3:return B2.l(arguments[0],arguments[1],arguments[2]);default:throw Error(["Invalid arity: ",arguments.length].join(""));}};B2.j=function(a,b){return B2.l(a,b,$APP.GU.j($APP.Si(a),$APP.Si(b)))};B2.l=function(a,b,c){return $APP.Af.l(function(d,e){return $APP.tq.h($APP.qk.l($APP.gm,d,e))},new $APP.D(null,3,5,$APP.E,[null,null,null],null),$APP.qk.j($APP.lm.l(vTa,a,b),c))};B2.A=3;C2["null"]=function(){return E2};
C2.string=function(){return E2};C2.number=function(){return E2};C2.array=function(){return yTa};C2["function"]=function(){return E2};C2["boolean"]=function(){return E2};C2._=function(a){return(a!=null?a.D&1024||$APP.$d===a.fh||(a.D?0:$APP.Fb($APP.jc,a)):$APP.Fb($APP.jc,a))?$APP.Vm:(a!=null?a.D&4096||$APP.$d===a.hh||(a.D?0:$APP.Fb($APP.pc,a)):$APP.Fb($APP.pc,a))?$APP.dn:(a!=null?a.D&16777216||$APP.$d===a.vf||(a.D?0:$APP.Fb($APP.Mc,a)):$APP.Fb($APP.Mc,a))?yTa:E2};
D2["null"]=function(a,b){return A2(a,b)};D2.string=function(a,b){return A2(a,b)};D2.number=function(a,b){return A2(a,b)};D2.array=function(a,b){return wTa(a,b)};D2["function"]=function(a,b){return A2(a,b)};D2["boolean"]=function(a,b){return A2(a,b)};
D2._=function(a,b){var c=function(){var d=C2(a);d=d instanceof $APP.C?d.aa:null;switch(d){case "atom":return A2;case "set":return xTa;case "sequential":return wTa;case "map":return B2;default:throw Error("No matching clause: "+$APP.G.h(d));}}();return c.j?c.j(a,b):c.call(null,a,b)};var ATa=$APP.GW.j($APP.iS,null),BTa=new $APP.F(null,1,[zTa,$APP.at(uTa,zTa,new $APP.F(null,7,[$APP.Q,zTa,$APP.O,"Recursively compares a and b, returning a tuple of\n  [things-only-in-a things-only-in-b things-in-both].\n  Comparison rules:\n\n  * For equal a and b, return [nil nil a].\n  * Maps are subdiffed where keys match and values differ.\n  * Sets are never subdiffed.\n  * All sequential things are treated as associative collections\n    by their indexes, with results returned as vectors.\n  * Everything else (including strings!) is treated as\n    an atom and compared for equality.",
$APP.Y,$APP.H(new $APP.D(null,2,5,$APP.E,[$APP.cQ,$APP.bQ],null)),$APP.I,"clojure/data.cljs",$APP.J,144,$APP.M,7,$APP.S,ATa],null),ATa)],null);$APP.Dz(new $APP.F(null,1,[$APP.xt,new $APP.F(null,1,[$APP.iS,BTa],null)],null));