import { $APP, shadow$provide } from "./nbb_core.js";
const shadow_esm_import = function(x) { return import(x) };
import*as esm_import$node_process from"node:process";import*as esm_import$node_module from"node:module";import*as esm_import$node_fs from"node:fs";import*as esm_import$import_meta_resolve from"import-meta-resolve";import*as esm_import$node_path from"node:path";import*as esm_import$node_url from"node:url";var PSa,RSa,JSa,ISa,NSa,SSa,TSa,QSa;
$APP.HSa=function(a){a=$APP.ie(a);a=$APP.Mo.j($APP.bg,a);a=$APP.Co.j(function(d){return $APP.Qy($APP.qs(),d)},a);var b=$APP.wc($APP.yt),c=$APP.wc($APP.kt);return $APP.$C(a,new $APP.G(null,2,[$APP.T,b,$APP.K,c],null))};$APP.KSa=function(a,b){return ISa(JSa,a,b)};
$APP.TZ=function(a,b){return Promise.resolve($APP.k($APP.wc(LSa))?null:function(){var c=esm_import$node_path.resolve($APP.k(a)?a:"script.cljs"),d=$APP.k($APP.gD.h(b))?$APP.Ti.o(b,$APP.CT,esm_import$node_path.dirname(esm_import$node_path.resolve($APP.gD.h(b))),$APP.y([$APP.gD,$APP.EU.h(esm_import$node_fs.readFileSync($APP.gD.h(b),"utf8"))],0)):function(){var g;a:{for(g=c;;){var m=esm_import$node_fs.existsSync(g);m=$APP.k(m)?esm_import$node_fs.lstatSync(g).isDirectory():m;if($APP.k(m)){m=esm_import$node_path.resolve(g,
"nbb.edn");if($APP.k(esm_import$node_fs.existsSync(m))){g=m;break a}m=esm_import$node_path.dirname(g)}else m=esm_import$node_path.dirname(g);if($APP.u.j(m,g)){g=null;break a}g=m}g=void 0}return $APP.k(g)?(m=$APP.EU.h(esm_import$node_fs.readFileSync(g,"utf8")),$APP.Ti.o(b,$APP.gD,m,$APP.y([$APP.CT,esm_import$node_path.dirname(g)],0))):b}(),e=MSa.h?MSa.h(c):MSa.call(null,c),f=""+$APP.I.h(esm_import$node_url.pathToFileURL(c));$APP.bD.require=e;$APP.ak.D($APP.dD,$APP.Ti,$APP.io,e);$APP.ak.D($APP.dD,$APP.Ti,
$APP.eD,function(g){return esm_import$import_meta_resolve.resolve(g,f)});$APP.Xg($APP.fD,d);return Promise.resolve(function(){var g=function(){var C=$APP.yb(NSa.h(d));return C?$APP.gD.h(d):C}();if($APP.k(g)){g=$APP.ms.h(g);if($APP.k(g)){g=$APP.n(g);for(var m=null,q=0,t=0;;)if(t<q){var w=m.S(null,t);$APP.yb(esm_import$node_path.isAbsolute(w))?$APP.Zr(function(){var C=$APP.CT.h(d);return $APP.k(C)?esm_import$node_path.resolve(C,w):w}()):$APP.Zr(w);t+=1}else if(g=$APP.n(g)){m=g;if($APP.bf(m))g=$APP.Cd(m),
t=$APP.Dd(m),m=g,q=$APP.De(g),g=t;else{var B=$APP.p(m);$APP.yb(esm_import$node_path.isAbsolute(B))?$APP.Zr(function(){var C=$APP.CT.h(d);return $APP.k(C)?esm_import$node_path.resolve(C,B):B}()):$APP.Zr(B);g=$APP.r(m);m=null;q=0}t=0}else break}else $APP.Zr(esm_import$node_process.cwd());return shadow_esm_import("./nbb_deps.js")}return $APP.Zr(esm_import$node_process.cwd())}()).then(function(){var g=process.env.KBB_CLASSPATH_TAIL;delete process.env.KBB_CLASSPATH_TAIL;$APP.n(g)&&$APP.Zr(g);return $APP.Xg(LSa,
!0)})}())};$APP.OSa=function(a,b){return $APP.dy(a,b)};PSa=function(a,b){b=$APP.Py(a,$APP.pl("(keys (ns-map '%s))","%s",b));b=$APP.pk.j(function(c){return"`"+$APP.I.h(c)},b);b="["+$APP.I.h($APP.Un.j(" ",b))+"]";a=$APP.Ny(a,b,null);return $APP.Mo.j(function(c){return $APP.Cl(""+$APP.I.h(c),"nbb.internal")},a)};
RSa=function(a,b){var c=$APP.qs();b=$APP.wl.j(b,/\//);$APP.x.l(b,0,null);var d=$APP.x.l(b,1,null),e=$APP.Py(c,$APP.Wj.o($APP.y([$APP.U.h($APP.n($APP.O.o(new $APP.A(null,$APP.Ct,null,1,null),new $APP.A(null,$APP.Dh($APP.U.h($APP.n($APP.O.j(new $APP.A(null,QSa,null,1,null),new $APP.A(null,$APP.U.h($APP.n($APP.O.j(new $APP.A(null,$APP.Lva,null,1,null),new $APP.A(null,$APP.U.h($APP.n($APP.O.j(new $APP.A(null,$APP.$k,null,1,null),new $APP.A(null,a,null,1,null)))),null,1,null)))),null,1,null))))),null,
1,null),$APP.y([new $APP.A(null,$APP.U.h($APP.n($APP.O.o(new $APP.A(null,$APP.wT,null,1,null),new $APP.A(null,$APP.U.h($APP.n($APP.O.j(new $APP.A(null,$APP.Dya,null,1,null),new $APP.A(null,QSa,null,1,null)))),null,1,null),$APP.y([new $APP.A(null,QSa,null,1,null)],0)))),null,1,null)],0))))],0)));if($APP.k(e)&&(c=$APP.k(d)?function(){var m=$APP.Fa(d,"."),q=$APP.wl.j(d,/\./);m=m?q:$APP.bj(q);q=$APP.F;var t=""+$APP.I.h(a)+"/",w=$APP.I,B=w.h;if($APP.n(m)){var C=$APP.Un.j(".",m);C=""+$APP.I.h(C)+"."}else C=
null;return new $APP.E(null,2,5,q,[t+B.call(w,C),$APP.Tg.l($APP.Oa,e,m)],null)}():new $APP.E(null,2,5,$APP.F,[""+$APP.I.h(a)+"/",e],null),$APP.k(c))){var f=$APP.x.l(c,0,null),g=$APP.x.l(c,1,null);c=function(){for(var m=g,q=$APP.nh;;)if($APP.k(m)){var t=Object.getPrototypeOf(m);q=$APP.ai.j(q,Object.getOwnPropertyNames(m));m=t}else return q}();return $APP.pk.j(function(m){return new $APP.E(null,2,5,$APP.F,[null,""+$APP.I.h(f)+$APP.I.h(m)],null)},c)}return null};
$APP.USa=function(a){var b=$APP.yg(a);a=$APP.z.j(b,$APP.T);try{var c=$APP.qs(),d=$APP.k(a)?$APP.OSa(c,$APP.Ij.h(a)):null,e=$APP.wg([$APP.yt,$APP.k(d)?d:$APP.wc($APP.yt)]);$APP.Rs(e);try{var f=function(){var ia=$APP.Xm.h(b);return $APP.k(ia)?ia:$APP.MR.h(b)}();if($APP.k(f)){var g=$APP.La(f,"/"),m=g?function(){var ia=$APP.wl.j(f,/\//);ia=ia==null?null:$APP.p(ia);return ia==null?null:$APP.Ij.h(ia)}():null,q=PSa(c,$APP.Ny(c,"(ns-name *ns*)",null)),t=$APP.pk.j(function(ia){return new $APP.E(null,3,5,$APP.F,
[$APP.dg(ia),$APP.cj(ia),SSa],null)},q),w=$APP.Ny(c,"(let [m (ns-aliases *ns*)] (zipmap (keys m) (map ns-name (vals m))))",null),B=$APP.dj($APP.Ri(w),$APP.Pi(w)),C=$APP.qq.h($APP.jh.o(function(ia){var pa=$APP.z.j(w,ia);ia=$APP.Py(c,$APP.pl("(keys (ns-publics '%s))","%s",pa));return $APP.pk.j(function(ra){return new $APP.E(null,3,5,$APP.F,[""+$APP.I.h(pa),""+$APP.I.h(ra),TSa],null)},ia)},$APP.y([$APP.Pi(w)],0))),v=$APP.pk.j(function(ia){return new $APP.E(null,3,5,$APP.F,[""+$APP.I.h(ia),null,TSa],
null)},$APP.Ny(c,"(all-ns)",null)),H=g?RSa(m,f):null,P=$APP.k(H)?null:g?function(){var ia=$APP.z.l(w,m,m),pa=$APP.Py(c,$APP.pl("(and (find-ns '%s)\n                                                                                         (keys (ns-publics '%s)))","%s",ia));return $APP.pk.j(function(ra){return new $APP.E(null,3,5,$APP.F,[""+$APP.I.h(ia),""+$APP.I.h(ra),TSa],null)},pa)}():null,V=$APP.O.o(t,C,$APP.y([v,P],0)),aa=$APP.ho.j(function(ia){var pa=$APP.x.l(ia,0,null);var ra=$APP.x.l(ia,1,null);
ia=$APP.x.l(ia,2,null);ia=$APP.u.j(SSa,ia)&&$APP.La(ra,f)?new $APP.E(null,2,5,$APP.F,[pa,ra],null):null;$APP.k(ia)?pa=ia:$APP.k(pa)?(ia=""+$APP.I.h($APP.z.j(B,$APP.Ij.h(pa)))+"/"+$APP.I.h(ra),ia=$APP.La(ia,f)?new $APP.E(null,2,5,$APP.F,[pa,ia],null):null,$APP.k(ia)?pa=ia:(ra=""+$APP.I.h(pa)+"/"+$APP.I.h(ra),pa=$APP.La(ra,f)?new $APP.E(null,2,5,$APP.F,[pa,ra],null):null)):pa=null;return pa},V),ea=$APP.O.j(aa,H),ha=$APP.Dh($APP.Zo.h($APP.pk.j(function(ia){var pa=$APP.x.l(ia,0,null);ia=$APP.x.l(ia,1,
null);ia=new $APP.G(null,1,["candidate",""+$APP.I.h(ia)],null);return $APP.k(pa)?$APP.Ti.l(ia,"ns",""+$APP.I.h(pa)):ia},ea)));return new $APP.G(null,2,["completions",ha,"status",new $APP.E(null,1,5,$APP.F,["done"],null)],null)}return new $APP.G(null,1,["status",new $APP.E(null,1,5,$APP.F,["done"],null)],null)}finally{$APP.Ts()}}catch(ia){return console.warn(ia),new $APP.G(null,2,["completions",$APP.nh,"status",new $APP.E(null,1,5,$APP.F,["done"],null)],null)}};JSa={};
ISa=function ISa(a,b,c){for(;;){if(b instanceof Promise)return b;if(JSa===a){if($APP.ff(b))return $APP.nY(b,b,c,ISa);a=$APP.mD(b,c)}else{b=Promise;var e=b.resolve;var f=$APP.Io.h(c);f=$APP.k(f)?f:$APP.Af;c=new $APP.G(null,1,[$APP.T,$APP.T.h(c)],null);c=f.j?f.j(a,c):f.call(null,a,c);return e.call(b,c)}}};$APP.UZ=new $APP.l(null,"socket-repl","socket-repl",-1615225633,null);$APP.VZ=new $APP.l(null,"repl","repl",1605132860,null);NSa=new $APP.D(null,"disableConfig","disableConfig",844586790);
SSa=new $APP.D(null,"unqualified","unqualified",-98904653);TSa=new $APP.D(null,"qualified","qualified",-2065109343);$APP.WZ=new $APP.l(null,"start-server!","start-server!",203437330,null);QSa=new $APP.l(null,"resolved__37280__auto__","resolved__37280__auto__",-1312201702,null);$APP.XZ=new $APP.D(null,"classpath","classpath",299521985);var MSa,LSa;MSa=function(){var a=esm_import$node_module.createRequire;return $APP.k(a)?a:function(){return function(){throw Error("createRequire is not defined, this is a no-op");}}}();LSa=$APP.Zj.h(!1);$APP.YZ=function YZ(a){switch(arguments.length){case 1:return YZ.h(arguments[0]);case 2:return YZ.j(arguments[0],arguments[1]);default:throw Error(["Invalid arity: ",arguments.length].join(""));}};$APP.YZ.h=function(a){return $APP.YZ.j(a,null)};
$APP.YZ.j=function(a,b){b=$APP.hD.o(b,$APP.y([$APP.SG,!0],0));var c=esm_import$node_path.resolve(a);$APP.Xg($APP.DPa,c);return $APP.TZ(c,b).then(function(){return $APP.rD(c)})};$APP.YZ.A=2;$APP.ZZ=function ZZ(a){switch(arguments.length){case 1:return ZZ.h(arguments[0]);case 2:return ZZ.j(arguments[0],arguments[1]);default:throw Error(["Invalid arity: ",arguments.length].join(""));}};$APP.ZZ.h=function(a){return $APP.ZZ.j(a,null)};
$APP.ZZ.j=function(a,b){b=$APP.hD.o(b,$APP.y([$APP.SG,!0],0));return $APP.TZ(null,b).then(function(){return $APP.qD(a)})};$APP.ZZ.A=2;export const loadFile=$APP.YZ;export const loadString=$APP.ZZ;export const getClassPath=function(){return $APP.Xr()};export const addClassPath=function(a){return $APP.Zr(a)};export const version=function(){return $APP.xD()};export const registerModule=function(a,b){b=$APP.Cna($APP.jl(b));return $APP.ak.D($APP.cD,$APP.Ti,b,a)};export const printErrorReport=$APP.qY;