import { $APP, shadow$provide } from "./nbb_core.js";
import "./nbb_api.js";
import "./nbb_goog_string.js";
import "./nbb_pprint.js";
const shadow_esm_import = function(x) { return import(x) };
import*as esm_import$node_net from"node:net";import*as esm_import$node_process from"node:process";import*as esm_import$node_async_hooks from"node:async_hooks";import*as esm_import$node_fs from"node:fs";import*as esm_import$node_path from"node:path";
var aXa=function(a,b){a=a.indexOf(b);if(a<0)throw Error("out of input");return a},Z5=function(a,b){if(a.length<b)throw Error("out of input");return a.slice(b)},$5=function(a,b){if(b>a.length)throw Error("out of input");return a.slice(0,b)},bXa=function(a){return(new TextEncoder).encode(a).length},a6=function(a){return $APP.k($APP.dz.h($APP.yc($APP.oz)))?console.debug($APP.Un.j(" ",a)):null},dXa=function(a){return function(b,c){b=$APP.Bg(b);var d=$APP.y.j(b,$APP.tt),e=$APP.y.j(b,cXa);c=$APP.Wi.l(c,
"id",d);c=$APP.k(e)?$APP.Wi.l(c,"session",e):c;return a.j?a.j(b,c):a.call(null,b,c)}},gXa=function(){var a=eXa;return function(b,c){b=$APP.Cn.l(b,fXa,$APP.Fj);return a.j?a.j(b,c):a.call(null,b,c)}},iXa=function(){var a=hXa();return function(b,c){a6($APP.x(["request",b],0));return a.j?a.j(b,c):a.call(null,b,c)}},jXa=function(a){return function(b,c){a6($APP.x(["response",c],0));return a.j?a.j(b,c):a.call(null,b,c)}},hXa=function(){var a=gXa();return function(b,c){return a.j?a.j(b,c):a.call(null,b,c)}},
kXa=function(a){return $APP.Wi.l($APP.gj(new $APP.D(null,3,5,$APP.E,["major","minor","incremental"],null),$APP.qz.h(a.split("."))),"version-string",a)},mXa=function(a,b,c){if($APP.k(a))if(a=lXa.h?lXa.h(a):lXa.call(null,a),$APP.k(a)){b=$APP.Bg(b);var d=$APP.y.j(b,$APP.HJa),e=$APP.y.j(b,$APP.oJa),f=$APP.y.j(b,$APP.xJa);b=$APP.yj;var g=$APP.xj,m=$APP.N_;$APP.yj=e;$APP.xj=f;$APP.N_=d;try{var r=new $APP.pb;d=$APP.sb;e=$APP.tb;$APP.sb=!0;$APP.tb=function(t){return r.append(t)};try{a.h?a.h(c):a.call(null,
c)}finally{$APP.tb=e,$APP.sb=d}return""+$APP.G.h(r)}finally{$APP.N_=m,$APP.xj=g,$APP.yj=b}}else return a6($APP.x(["Pretty-Printing is only supported for clojure.core/prn and clojure.pprint/pprint."],0)),$APP.Xj.o($APP.x([c],0));else return $APP.Xj.o($APP.x([c],0))},pXa=function(a,b,c){var d=$APP.w.l(c,0,null);c=$APP.w.l(c,1,null);var e=$APP.S.h(c);$APP.$g(b6,e);$APP.bY.j($APP.HX,$APP.Yg($APP.yc($APP.GX)));$APP.bY.j($APP.GX,$APP.Yg($APP.yc($APP.FX)));$APP.bY.j($APP.FX,$APP.Yg(d));if($APP.k($APP.ez(d)))return d.then(function(f){f=
new $APP.F(null,2,["value","#\x3cPromise "+$APP.G.h($APP.Xj.o($APP.x([f],0)))+"\x3e","ns",""+$APP.G.h(e)],null);return b.j?b.j(a,f):b.call(null,a,f)});d=mXa(nXa.h(a),oXa.h(a),d);d=new $APP.F(null,2,["value",d,"ns",""+$APP.G.h(e)],null);return b.j?b.j(a,d):b.call(null,a,d)},qXa=function(a,b,c){$APP.bY.j($APP.IX,$APP.Yg(c));var d=$APP.wt.h($APP.Ik(c));d=$APP.k(d)?d:c.message;$APP.k(d)&&(d=new $APP.F(null,1,["err",""+$APP.G.h(d)+"\n"],null),a.j?a.j(b,d):a.call(null,b,d));c=new $APP.F(null,2,["ex",""+
$APP.G.h(c),"ns",""+$APP.G.h($APP.yc($APP.zt))],null);return a.j?a.j(b,c):a.call(null,b,c)},vXa=function(){if($APP.Jba(rXa,!1,!0)){var a=$APP.yc($APP.mW);$APP.bY.j($APP.mW,$APP.Yg(function(b){var c=sXa.getStore();if($APP.k(c)){var d=$APP.Bg(c);c=$APP.y.j(d,tXa);d=$APP.y.j(d,uXa);b=new $APP.F(null,1,["out",b],null);return d.j?d.j(c,b):d.call(null,c,b)}return a.h?a.h(b):a.call(null,b)}))}},yXa=function(a,b){var c=$APP.Bg(a),d=$APP.y.j(c,$APP.S);a=$APP.y.j(c,c6);var e=$APP.y.j(c,$APP.J);$APP.y.j(c,wXa);
$APP.y.j(c,xXa);var f=$APP.Vr(a),g=function t(r){try{var v=function(){var C=$APP.S.h($APP.Ke(r));if($APP.k(C))return C;C=$APP.yc(b6);return $APP.k(C)?C:d}(),z=$APP.mna(f,new $APP.F(null,3,[$APP.S,v,$APP.J,e,$APP.Jo,$APP.hB],null));return $APP.Fe.j($APP.gN,z)?Promise.resolve(r):$APP.cHa(z,new $APP.F(null,3,[$APP.S,v,$APP.J,e,$APP.Jo,$APP.hB],null)).then(function(C){return Promise.resolve(pXa(c,b,C)).then(function(){return t(C)})})}catch(C){return qXa(b,c,C),t(null)}};return sXa.run(new $APP.F(null,
2,[tXa,c,uXa,b],null),function(){$APP.Ss($APP.zg([$APP.zt,d,$APP.lt,e,$APP.oW,$APP.yc($APP.oW),$APP.tW,!0]));return g(null).catch($APP.nm.l(qXa,b,c)).finally(function(){var r=new $APP.F(null,2,["ns",""+$APP.G.h($APP.yc(b6)),"status",new $APP.D(null,1,5,$APP.E,["done"],null)],null);return b.j?b.j(c,r):b.call(null,c,r)}).finally(function(){return $APP.Us()})})},zXa=function(a,b){a=$APP.Bg(a);var c=$APP.y.j(a,$APP.S),d=$APP.Wi.l;c=$APP.k(c)?$APP.gHa($APP.ps(),$APP.Lj.h(c)):null;$APP.k(c)||(c=$APP.yc(b6),
c=$APP.k(c)?c:$APP.yc($APP.zt));return yXa(d.call($APP.Wi,a,$APP.S,c),b)},AXa=function(a){return $APP.Un.j("\n",$APP.qk.j($APP.Xj,a))},CXa=function(a,b){var c=$APP.Bg(a),d=$APP.y.j(c,$APP.S),e=fXa.h(c);try{var f=$APP.S.h(c),g=function(){var H=$APP.sta.h(c);return $APP.k(H)?H:$APP.$m.h(c)}(),m=function(){var H=$APP.k(d)?$APP.gHa($APP.ps(),$APP.Lj.h(d)):null;if($APP.k(H))return H;H=$APP.yc(b6);return $APP.k(H)?H:$APP.yc($APP.zt)}(),r=$APP.zg([$APP.zt,m]);$APP.Ss(r);try{var t=$APP.Oy($APP.ps(),$APP.Y5("\n(let [ns '%s\n      full-sym '%s]\n  (when-let [v (ns-resolve ns full-sym)]\n    (let [m (meta v)]\n      (assoc m :arglists (:arglists m)\n       :doc (:doc m)\n       :name (:name m)\n       :ns (some-\x3e m :ns ns-name)\n       :val @v))))",
f,g)),v=$APP.O.h(t),z=$APP.J.h(t),C=$APP.K.h(t),u=function(){var H=e instanceof $APP.B?e.aa:null;switch(H){case "eldoc":return H=new $APP.F(null,5,["ns",$APP.S.h(t),"name",$APP.P.h(t),"eldoc",$APP.Do.j(function(Q){return $APP.Do.j($APP.G,Q)},$APP.X.h(t)),"type",$APP.lf($APP.Ly.h(t))?"function":"variable","status",new $APP.D(null,1,5,$APP.E,["done"],null)],null),$APP.k(v)?$APP.Wi.l(H,"docstring",v):H;case "info":case "lookup":return H=new $APP.F(null,4,["ns",$APP.S.h(t),"name",$APP.P.h(t),"arglists-str",
AXa($APP.X.h(t)),"status",new $APP.D(null,1,5,$APP.E,["done"],null)],null),H=$APP.k(v)?$APP.Wi.l(H,"doc",v):H,H=$APP.k(z)?$APP.Wi.l(H,"file",z):H,$APP.k(C)?$APP.Wi.l(H,"line",C):H;default:throw Error("No matching clause: "+$APP.G.h(H));}}();return b.j?b.j(c,u):b.call(null,c,u)}finally{$APP.Us()}}catch(H){if(H instanceof Error)return a=H,f=function(){var Q=new $APP.Zi(null,new $APP.F(null,1,["done",null],null),null);return $APP.Fe.j(e,BXa)?$APP.$f.j(Q,"no-eldoc"):Q}(),a=new $APP.F(null,2,["status",
f,"ex",""+$APP.G.h(a)],null),b.j?b.j(c,a):b.call(null,c,a);throw H;}},DXa=function(a,b){var c=$APP.mHa(a);return b.j?b.j(a,c):b.call(null,a,c)},eXa=function(a,b){a=$APP.Bg(a);var c=$APP.y.j(a,fXa),d=$APP.y.j(EXa,c);if($APP.k(d))return d.j?d.j(a,b):d.call(null,a,b);console.warn($APP.Un.j(" ",$APP.x(["Unhandled operation",c],0)));c=new $APP.F(null,1,["status",new $APP.D(null,3,5,$APP.E,["error","unknown-op","done"],null)],null);return b.j?b.j(a,c):b.call(null,a,c)},FXa=function(a){return function(b,
c){return a.write(d6(c))}},GXa=function(a,b){a6($APP.x(["Connection accepted"],0));b.setNoDelay(!0);var c=iXa(),d=dXa(jXa(FXa(b))),e=$APP.ak.h(null);b.on("data",function(f){var g=$APP.yc(e);if($APP.k(g)){f=""+$APP.G.h(g)+$APP.G.h(f);$APP.$g(e,null);var m=f}else m=f;a:{f=$APP.x([$APP.SC,!0],0);for(g=$APP.rh;;){var r=$APP.Wg.l(e6,m,f);m=$APP.w.l(r,0,null);r=$APP.w.l(r,1,null);if(m==null){g=new $APP.D(null,2,5,$APP.E,[g,r],null);break a}g=$APP.$f.j(g,m);m=r}g=void 0}f=$APP.w.l(g,0,null);g=$APP.w.l(g,
1,null);$APP.Dl(g)||$APP.$g(e,g);f=$APP.n(f);g=null;for(var t=r=0;;)if(t<r)m=g.R(null,t),c(m,d),t+=1;else if(f=$APP.n(f))g=f,$APP.ef(g)?(f=$APP.Ed(g),r=$APP.Fd(g),g=f,m=$APP.Ee(f),f=r,r=m):(m=$APP.p(g),c(m,d),f=$APP.q(g),g=null,r=0),t=0;else return null});return b.on("close",function(f){return $APP.k(f)?a6($APP.x(["Connection lost"],0)):a6($APP.x(["Connection closed"],0))})},HXa=new $APP.B(null,"completions","completions",-190930179),oXa=new $APP.B("nrepl.middleware.print","options","nrepl.middleware.print/options",
868480159),cXa=new $APP.B(null,"session","session",1008279103),IXa=new $APP.B(null,"load-file","load-file",-424586670),c6=new $APP.B(null,"code","code",1586293142),JXa=new $APP.B(null,"log_level","log_level",-1756736313),nXa=new $APP.B("nrepl.middleware.print","print","nrepl.middleware.print/print",-1616742548),KXa=new $APP.B(null,"clone","clone",711747572),LXa=new $APP.B(null,"close","close",1835149582),MXa=new $APP.B(null,"info","info",-317069002),NXa=new $APP.B(null,"macroexpand","macroexpand",
-130598183),xXa=new $APP.B(null,"_line","_line",232847719),OXa=new $APP.l(null,"server","server",-1155245649,null),PXa=new $APP.B(null,"lookup","lookup",1225356838),QXa=new $APP.B(null,"expander","expander",379138924),wXa=new $APP.B(null,"_load-file?","_load-file?",-1198848711),fXa=new $APP.B(null,"op","op",-1882987955),RXa=new $APP.B(null,"describe","describe",1369790582),BXa=new $APP.B(null,"eldoc","eldoc",-1321421900),uXa=new $APP.B(null,"send-fn","send-fn",351002041),SXa=new $APP.l(null,"stop-server!",
"stop-server!",-410772185,null),TXa=new $APP.B(null,"load-file?","load-file?",1892536169),tXa=new $APP.B(null,"request","request",1772954723);var f6=function f6(a,b){switch(""+$APP.G.h($5(a,1))){case "i":return a=Z5(a,1),b=aXa(a,"e"),new $APP.D(null,2,5,$APP.E,[parseInt($5(a,b)),Z5(a,b+1)],null);case "l":var d=a=Z5(a,1);for(a=$APP.od($APP.rh);;){if($APP.Fe.j(""+$APP.G.h($5(d,1)),"e"))return new $APP.D(null,2,5,$APP.E,[$APP.rd(a),Z5(d,1)],null);var e=f6.j?f6.j(d,b):f6.call(null,d,b),f=$APP.w.l(e,0,null),g=$APP.w.l(e,1,null);e=g;a=$APP.qh.j(a,f);d=e}break;case "d":a=Z5(a,1);f=$APP.Bg(b);f=$APP.y.j(f,$APP.SC);d=a;for(e=$APP.od($APP.Ag);;){if($APP.Fe.j(""+
$APP.G.h($5(d,1)),"e"))return new $APP.D(null,2,5,$APP.E,[$APP.rd(e),Z5(d,1)],null);a=f6.j?f6.j(d,b):f6.call(null,d,b);d=$APP.w.l(a,0,null);g=$APP.w.l(a,1,null);g=f6.j?f6.j(g,b):f6.call(null,g,b);a=$APP.w.l(g,0,null);g=$APP.w.l(g,1,null);d=$APP.k(f)?$APP.Fj.h(d):d;a=$APP.hi.l(e,d,a);d=g;e=a}break;default:return b=aXa(a,":"),f=parseInt($5(a,b)),a=Z5(a,b+1),new $APP.D(null,2,5,$APP.E,[""+$APP.G.h($5(a,f)),Z5(a,f)],null)}},e6=function e6(a){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),
e+=1;else break;return e6.o(arguments[0],1<c.length?new $APP.he(c.slice(1),0,null):null)};e6.o=function(a,b){try{return f6(a,b)}catch(c){if(c instanceof Error)return new $APP.D(null,2,5,$APP.E,[null,a],null);throw c;}};e6.v=1;e6.B=function(a){var b=$APP.p(a);a=$APP.q(a);return this.o(b,a)};
var d6=function d6(a){for(;;){if(typeof a==="string")return""+$APP.G.h(bXa(a))+":"+$APP.G.h(a);if(a instanceof $APP.B||a instanceof $APP.l)a=""+$APP.G.h(function(){var c=$APP.fg(a);return $APP.k(c)?""+$APP.G.h(c)+"/":null}())+$APP.G.h($APP.fj(a));else return typeof a==="number"?"i"+$APP.G.h(a)+"e":$APP.Ze(a)||$APP.df(a)||a==null?"l"+$APP.G.h($APP.Wg.j($APP.G,$APP.qk.j(d6,a)))+"e":$APP.bf(a)?"d"+$APP.G.h($APP.Wg.j($APP.G,$APP.qk.j(function(){return function(c){var d=$APP.w.l(c,0,null);c=$APP.w.l(c,
1,null);return""+$APP.G.h(d6.h?d6.h(d):d6.call(null,d))+$APP.G.h(d6.h?d6.h(c):d6.call(null,c))}}(a),$APP.Sn.j($APP.p,a))))+"e":null}};var b6=$APP.ak.h(null),lXa=new $APP.F(null,1,["cider.nrepl.pprint/pprint",$APP.u1],null),sXa=new esm_import$node_async_hooks.AsyncLocalStorage,rXa=$APP.ak.h(!1),EXa=$APP.Hi([$APP.XZ,PXa,LXa,IXa,BXa,KXa,RXa,MXa,$APP.up,NXa,HXa,$APP.Aza],[function(a,b){var c=new $APP.F(null,2,["status",new $APP.D(null,1,5,$APP.E,["done"],null),"classpath",$APP.Yr($APP.Xr())],null);return b.j?b.j(a,c):b.call(null,a,c)},CXa,function(a,b){var c=new $APP.F(null,1,["status",new $APP.D(null,2,5,$APP.E,["done","session-closed"],
null)],null);return b.j?b.j(a,c):b.call(null,a,c)},function(a,b){a=$APP.Bg(a);var c=$APP.y.j(a,$APP.J);return yXa($APP.Wi.o(a,c6,c,$APP.x([TXa,!0,$APP.S,$APP.yc($APP.zt)],0)),b)},CXa,function(a,b){var c=new $APP.F(null,2,["new-session",""+$APP.G.h($APP.Gk()),"status",new $APP.D(null,1,5,$APP.E,["done"],null)],null);return b.j?b.j(a,c):b.call(null,a,c)},function(a,b){var c=new $APP.F(null,4,["versions",new $APP.F(null,2,["nbb-nrepl",kXa("TODO"),"node",kXa(esm_import$node_process.version)],null),"aux",
$APP.Ag,"ops",$APP.gj($APP.qk.j($APP.fj,$APP.Si(EXa)),$APP.Ao.h($APP.Ag)),"status",new $APP.D(null,1,5,$APP.E,["done"],null)],null);return b.j?b.j(a,c):b.call(null,a,c)},CXa,DXa,function(a,b){a=$APP.Bg(a);var c=$APP.y.j(a,c6),d=$APP.y.j(a,QXa);try{return zXa($APP.Wi.l(a,c6,"( "+$APP.G.h(d)+"(quote "+$APP.G.h(c)+"))"),function(e,f){var g=f.h?f.h("value"):f.call(null,"value");f=$APP.k(g)?$APP.Wi.l(f,"expansion",g):f;return b.j?b.j(e,f):b.call(null,e,f)})}catch(e){if(e instanceof Error)return c=new $APP.F(null,
3,["ex",""+$APP.G.h(e),"ns",""+$APP.G.h($APP.yc($APP.zt)),"status",new $APP.D(null,1,5,$APP.E,["done"],null)],null),b.j?b.j(a,c):b.call(null,a,c);throw e;}},DXa,zXa]),UXa=$APP.ak.h(null),g6=function g6(a){switch(arguments.length){case 0:return g6.A();case 1:return g6.h(arguments[0]);default:throw Error(["Invalid arity: ",arguments.length].join(""));}};g6.A=function(){return g6.h($APP.yc(UXa))};
g6.h=function(a){return a.close(function(){$APP.bY.j($APP.mW,$APP.Yg($APP.tb));$APP.bY.j($APP.tW,$APP.Yg($APP.sb));return $APP.k(esm_import$node_fs.existsSync(".nrepl-port"))?esm_import$node_fs.unlinkSync(".nrepl-port"):null})};g6.v=1;
var h6=$APP.fY.j($APP.qE,null),VXa=new $APP.F(null,2,[$APP.WZ,$APP.at(function(a){return Promise.resolve($APP.TZ(esm_import$node_path.resolve("script.cljs"),null)).then(function(){function b(e){return $APP.$Ga(new $APP.A(null,$APP.al,new $APP.A(null,new $APP.A(null,$APP.al,new $APP.A(null,e,null,1,null),2,null),null,1,null),2,null))}var c=$APP.w.l($APP.lY,0,null),d=$APP.w.l($APP.lY,1,null);return b(c).then(function(){return b(d)})}).then(function(){var b=$APP.km.o($APP.x([$APP.yc($APP.oz),a],0)),
c=function(){var f=$APP.tM.h(b);return $APP.k(f)?f:0}(),d=function(){var f=$APP.yU.h(b);return $APP.k(f)?f:"127.0.0.1"}();(function(){var f=$APP.Cb(b)?b.Fl:JXa.h(b);return $APP.k(f)?f:"info"})();var e=esm_import$node_net.createServer($APP.nm.j(GXa,$APP.Ag));e.listen(c,d,function(){var f=e.address(),g=f.port;f=f.address;$APP.Dp.o($APP.x(["nREPL server started on port "+$APP.G.h(g)+" on host "+$APP.G.h(f)+" - nrepl://"+$APP.G.h(f)+":"+$APP.G.h(g)],0));$APP.bY.j($APP.tW,$APP.Yg(!0));vXa();try{return esm_import$node_fs.writeFileSync(".nrepl-port",
""+$APP.G.h(g))}catch(m){return console.warn($APP.Un.j(" ",$APP.x(["Could not write .nrepl-port",m],0)))}});return $APP.$g(UXa,e)})},$APP.WZ,new $APP.F(null,7,[$APP.P,$APP.WZ,$APP.O,"Start nRepl server. Accepts options either as JS object or Clojure map.",$APP.X,$APP.I(new $APP.D(null,1,5,$APP.E,[$APP.DM],null)),$APP.J,"nbb/impl/nrepl_server.cljs",$APP.K,350,$APP.M,7,$APP.S,h6],null),h6),SXa,$APP.at(g6,SXa,new $APP.F(null,7,[$APP.P,SXa,$APP.O,null,$APP.X,$APP.I($APP.rh,new $APP.D(null,1,5,$APP.E,
[OXa],null)),$APP.J,"nbb/impl/nrepl_server.cljs",$APP.K,422,$APP.M,7,$APP.S,h6],null),h6)],null);$APP.Hz(new $APP.F(null,1,[$APP.xt,new $APP.F(null,1,[$APP.qE,VXa],null)],null));