import { $APP, shadow$provide } from "./nbb_core.js";
import "./nbb_api.js";
import "./nbb_impl_main.js";
const shadow_esm_import = function(x) { return import(x) };
import*as esm_import$node_process from"node:process";import*as esm_import$node_path from"node:path";
var N4a=function(a){a=$APP.Ij.h(a);var b=$APP.fg(a)?$APP.Ij.j(""+$APP.I.h(a),"-main"):a,c=$APP.dg(b);return $APP.pl("(require '$1) (apply $2 *command-line-args*)",/\$(\d)/,function(d){d=$APP.Ie(d);switch(d){case "1":return c;case "2":return b;default:throw Error("No matching clause: "+$APP.I.h(d));}})},O4a=function(a){var b=$APP.Ij.h(a),c=$APP.dg(b);return $APP.pl("\n(require '[babashka.cli])\n(require '$1)\n(let [the-var (resolve '$2)\n      the-var-meta (meta the-var)\n      ns (:ns (meta the-var))\n      ns-meta (meta ns)\n      cli-opts (babashka.cli/merge-opts (:org.babashka/cli ns-meta)\n                                        (:org.babashka/cli the-var-meta))\n      opts (babashka.cli/parse-opts *command-line-args* cli-opts)]\n  (the-var opts))\n",/\$(\d)/,
function(d){d=$APP.Ie(d);switch(d){case "1":return c;case "2":return b;default:throw Error("No matching clause: "+$APP.I.h(d));}})},P4a=function(a){for(var b=$APP.xg,c=a;;){if($APP.k(c)){var d=$APP.p(c);a=$APP.r(c);switch(d){case "--help":case "-h":return $APP.Ti.l(b,$APP.Zp,!0);case "--version":case "-v":return $APP.Ti.l(b,$APP.W1a,!0);case "-e":b=$APP.Ti.l(b,$APP.nr,$APP.p(a));c=a=$APP.r(a);continue;case "-m":case "--main":return $APP.Ti.o(b,$APP.nr,N4a($APP.p(a)),$APP.y([$APP.uo,$APP.r(a)],0));
case "-x":case "--exec":return $APP.Ti.o(b,$APP.nr,O4a($APP.p(a)),$APP.y([$APP.uo,$APP.r(a)],0));case "-cp":case "--classpath":b=$APP.Ti.l(b,$APP.XZ,$APP.p(a));c=a=$APP.r(a);continue;case "--config":b=$APP.Ti.l(b,$APP.gD,$APP.p(a));c=a=$APP.r(a);continue;case "--debug":b=$APP.Ti.l(b,$APP.ez,!0);c=a;continue;case "nrepl-server":b=$APP.Ti.l(b,$APP.S1a,!0);c=a;continue;case "socket-repl":b=$APP.Ti.l(b,$APP.T1a,!0);c=a;continue;case ":port":case "--port":b=$APP.Ti.l(b,$APP.iQ,$APP.p(a));c=a=$APP.r(a);
continue;case ":host":case "--host":b=$APP.Ti.l(b,$APP.cU,$APP.p(a));c=a=$APP.r(a);continue;case "repl":b=$APP.Ti.l(b,$APP.V1a,!0);c=a;continue;case "bundle":return $APP.Ti.l(b,$APP.KS,$APP.xp.j(a,new $APP.G(null,1,[$APP.po,new $APP.G(null,2,[$APP.X1a,$APP.dC,$APP.$p,$APP.Zp],null)],null)));default:if($APP.yb($APP.nr.h(c)))return $APP.Ti.o(b,$APP.U1a,d,$APP.y([$APP.uo,$APP.r(c)],0));throw $APP.pm.j("Unrecognized options:"+$APP.I.h(c),$APP.xg);}}else return b;break}};if($APP.k(esm_import$node_process.on))esm_import$node_process.on("unhandledRejection",function(a){console.error($APP.Hk(a));return process.exitCode=1});(function(){var a=$APP.n(function(){var g=globalThis.nbb_args;return $APP.k(g)?g:esm_import$node_process.argv}());$APP.p(a);a=$APP.r(a);$APP.p(a);a=$APP.r(a);var b=P4a(a);$APP.Xg($APP.Y1a,b);var c=$APP.U1a.h(b),d=$APP.nr.h(b);a=$APP.XZ.h(b);$APP.k(a)&&$APP.Zr(a);a=$APP.S1a.h(b);var e=function(){var g=$APP.V1a.h(b);if($APP.k(g))return g;g=$APP.T1a.h(b);return $APP.k(g)?g:$APP.Ue($APP.fm.o(b,$APP.XZ,$APP.y([$APP.ez,$APP.gD],0)))}(),f=$APP.KS.h(b);$APP.k($APP.Zp.h(b))&&($APP.Cp.o($APP.y([$APP.qaa("nbb"),
"version:",$APP.xD()],0)),$APP.Cp.o($APP.y(["\nHelp:\n\n -h / --help: print this help text and exit.\n -v / --version: print the current version of nbb.\n\nGlobal options:\n\n --debug: print additional debug info.\n -cp / --classpath: set the classpath.\n\nEvaluation:\n\n -e: execute expression\n -m / --main: execute main function\n -x / --exec: execute function using babashka.cli\n\nREPL:\n\n repl: start console REPL.\n nrepl-server: start nrepl server. [1,2]\n socket-repl: start socket repl server. [1]\n\n 1: Provide :port \x3cport\x3e to specify port\n 2: Provide :host \x3chost\x3e to specify host\n\nTooling:\n\n  bundle: produce single JS file for usage with bundlers.\n"],
0)),esm_import$node_process.exit(0));$APP.k($APP.W1a.h(b))&&($APP.Cp.o($APP.y([""+$APP.I.h("nbb")+" v"+$APP.I.h($APP.xD())],0)),esm_import$node_process.exit(0));return $APP.k($APP.k(c)?c:$APP.k(d)?d:$APP.k(a)?a:$APP.k(e)?e:f)?($APP.bX.j($APP.vPa,$APP.Vg($APP.uo.h(b))),Promise.resolve($APP.TZ($APP.k(e)?esm_import$node_path.resolve("script.cljs"):c,b)).then(function(){return($APP.k(c)?$APP.YZ.h(c):$APP.k(d)?$APP.ZZ.h(d):$APP.k($APP.S1a.h(b))?shadow_esm_import("./nbb_nrepl_server.js").then(function(){var g=
$APP.z.j($APP.z.j($APP.wt.h($APP.ve($APP.rt.h($APP.qs()))),$APP.cI),$APP.WZ);return g.h?g.h(b):g.call(null,b)}):$APP.k($APP.k(e)?$APP.T1a.h(b):e)?shadow_esm_import("./nbb_repl.js").then(function(){var g=new $APP.G(null,1,[$APP.iQ,$APP.iQ.h(b)],null),m=$APP.z.j($APP.z.j($APP.wt.h($APP.ve($APP.rt.h($APP.qs()))),$APP.aH),$APP.UZ);return m.h?m.h(g):m.call(null,g)}):$APP.k($APP.KS.h(b))?shadow_esm_import("./nbb_bundler.js"):$APP.k(e)?shadow_esm_import("./nbb_repl.js").then(function(){var g=$APP.z.j($APP.z.j($APP.wt.h($APP.ve($APP.rt.h($APP.qs()))),
$APP.aH),$APP.VZ);return g.B?g.B():g.call(null)}):null).then(function(g){$APP.k($APP.k(d)?g!=null:d)&&$APP.dz.o($APP.y([g],0));return g}).catch(function(g){$APP.Dla(g,b);$APP.k($APP.ez.h(b))&&console.error(g);throw Error($APP.Hk(g));})})):console.error("Usage: "+$APP.I.h("nbb")+" \x3cscript\x3e or nbb -e \x3cexpr\x3e.")})();