import { $APP, shadow$provide } from "./nbb_core.js";
const shadow_esm_import = function(x) { return import(x) };
var A4=function(a,b,c){var d=$APP.Ee(a);if(c>=d)return-1;for(c=c>0?c:c<0?$APP.Bo.j(0,c+d):c;;)if(c<d){if($APP.Fe.j($APP.w.j(a,c),b))return c;c+=1}else return-1},B4=function(a,b,c){var d=$APP.Ee(a);if(d===0)return-1;for(c=c>0?$APP.mm.j(d-1,c):c<0?d+c:c;;)if(c>=0){if($APP.Fe.j($APP.w.j(a,c),b))return c;--c}else return-1},dUa=function(a,b){if($APP.af(b))if($APP.Ce(a)&&$APP.Ce(b)&&$APP.Ee(a)!==$APP.Ee(b))a=!1;else a:{a=$APP.n(a);for(b=$APP.n(b);;){if(a==null){a=b==null;break a}if(b!=null&&$APP.Fe.j($APP.p(a),
$APP.p(b)))a=$APP.q(a),b=$APP.q(b);else{a=!1;break a}}a=void 0}else a=null;return $APP.qb(a)},eUa=function(a,b){var c=a.ha(null);if(c===0)return b.A?b.A():b.call(null);for(var d=a.R(null,0),e=1;;)if(e<c){var f=a.R(null,e);d=b.j?b.j(d,f):b.call(null,d,f);if($APP.we(d))return $APP.yc(d);e+=1}else return d},fUa=function(a,b,c){var d=a.ha(null),e=c;for(c=0;;)if(c<d){var f=a.R(null,c);e=b.j?b.j(e,f):b.call(null,e,f);if($APP.we(e))return $APP.yc(e);c+=1}else return e},gUa=function(a){return typeof a===
"number"||typeof a==="string"||$APP.gf(a)||a==null},E4=function(a,b,c,d){var e=d!=null?d.h?d.h(a):d.call(null,a):null;return e==null?gUa(a)?a:$APP.Cb(a)?new C4(null,a,b,c,d,!0,null,null,null):$APP.k($APP.yb(a))?new D4(null,b,c,d,a,null):a:e},F4=function(a){return gUa(a)?a:a instanceof C4?a.ra:a instanceof D4?a.D:a},iUa=function(a,b,c,d,e){var f=$APP.ch($APP.od(hUa));$APP.Sa(a,function(g,m){return f.cc(null,$APP.hi.l(f.Ha(null),b.h?b.h(m):b.call(null,m),$APP.k(e)?E4(g,b,c,d):g))});return $APP.wg($APP.yc(f))},
H4=function(a){a:{for(var b=a.length,c=$APP.Mb(a),d=0;;)if(d<b){var e=d;var f=a[d];f=G4.h?G4.h(f):G4.call(null,f);c[e]=f;d+=1}else{a=c;break a}a=void 0}return $APP.Gh(a)},I4=function(a,b,c,d,e,f,g){g=f[g];f=b.h?b.h(g):b.call(null,g);a=a[g];b=e?E4(a,b,c,d):a;return new $APP.tf(f,b,null)},jUa=function(a,b){return a instanceof $APP.B&&b===$APP.Fj||typeof a==="string"&&b===$APP.Gf},J4=function(a,b){var c;!(c=gUa(a))&&(c=!($APP.bf(a)&&!(a instanceof C4)||$APP.df(a)&&!(a instanceof D4)))&&(a=$APP.k(b)?
(b=$APP.Cb(a))?b:$APP.yb(a):b,c=$APP.Ab(a));return c},kUa=function(a,b,c,d,e,f){this.Jb=!0;this.ra=a;this.ga=b;this.S=c;this.transform=d;this.pb=e;this.Uc=f;this.G=259;this.K=56},lUa=function(a,b,c,d,e,f,g){this.ra=a;this.ga=b;this.S=c;this.transform=d;this.pb=e;this.D=f;this.O=0;this.M=g},K4=function(a,b,c,d,e,f,g,m){this.ra=a;this.ga=b;this.S=c;this.transform=d;this.pb=e;this.D=f;this.O=g;this.I=m;this.G=2179858686;this.K=8192},C4=function(a,b,c,d,e,f,g,m,r){this.I=a;this.ra=b;this.ga=c;this.S=
d;this.transform=e;this.pb=f;this.Zc=g;this.Uc=m;this.H=r;this.G=2164131599;this.K=139268},mUa=function(a,b,c,d){this.Jb=!0;this.D=a;this.ga=b;this.S=c;this.transform=d;this.K=88;this.G=275},nUa=function(a,b,c,d,e){this.ga=a;this.S=b;this.transform=c;this.D=d;this.O=0;this.M=e},L4=function(a,b,c,d,e,f){this.ga=a;this.S=b;this.transform=c;this.D=d;this.O=e;this.I=f;this.G=2179858686;this.K=8192},D4=function(a,b,c,d,e,f){this.I=a;this.ga=b;this.S=c;this.transform=d;this.D=e;this.H=f;this.G=2315150111;
this.K=141316},M4=function(a){return a instanceof $APP.B?a.aa:null},oUa=new $APP.B(null,"key-\x3eprop","key-\x3eprop",-1028452531),pUa=new $APP.l(null,"bean?","bean?",2057456095,null),qUa=new $APP.B(null,"prop-\x3ekey","prop-\x3ekey",-1297715246),rUa=new $APP.l(null,"bean","bean",-1620239896,null),sUa=new $APP.B(null,"transform","transform",1381301764),tUa=new $APP.l(null,"-\x3eclj","-\x3eclj",-1549422014,null),uUa=new $APP.l(null,"-\x3ejs","-\x3ejs",-1825590244,null);var N4={},hUa=$APP.Ag;$APP.h=kUa.prototype;$APP.h.sa=function(a,b){if(this.Jb)return a=this.ra[this.S.h?this.S.h(b):this.S.call(null,b)],this.pb?E4(a,this.ga,this.S,this.transform):a;throw Error("lookup after persistent!");};$APP.h.W=function(a,b,c){if(this.Jb)return a=$APP.Xa(this.ra,this.S.h?this.S.h(b):this.S.call(null,b),c),this.pb&&a!==c?E4(a,this.ga,this.S,this.transform):a;throw Error("lookup after persistent!");};
$APP.h.ha=function(){return this.Uc==null?this.Uc=$APP.Ee($APP.Va(this.ra)):this.Uc};$APP.h.Nd=function(a,b){a:{if($APP.k(this.Jb)){if($APP.Dh(b)){a=this.vd(null,$APP.oc(b),$APP.pc(b));break a}if($APP.df(b)){a=this.vd(null,b.h?b.h(0):b.call(null,0),b.h?b.h(1):b.call(null,1));break a}a=$APP.n(b);for(b=this;;){var c=$APP.p(a);if($APP.k(c))a=$APP.q(a),b=$APP.td(b,$APP.oc(c),$APP.pc(c));else{a=b;break a}}}else throw Error("conj! after persistent!");a=void 0}return a};
$APP.h.ie=function(){if(this.Jb)return this.Jb=!1,new C4(null,this.ra,this.ga,this.S,this.transform,this.pb,null,this.Uc,null);throw Error("persistent! called twice");};$APP.h.vd=function(a,b,c){if(this.Jb){if(!jUa(b,this.ga)||!J4(c,this.pb))return $APP.td($APP.vg(iUa(this.ra,this.ga,this.S,this.transform,this.pb)),b,c);this.ra[this.S.h?this.S.h(b):this.S.call(null,b)]=this.pb?F4(c):c;this.Uc=null;return this}throw Error("assoc! after persistent!");};
$APP.h.yf=function(a,b){if(this.Jb)return delete this.ra[this.S.h?this.S.h(b):this.S.call(null,b)],this.Uc=null,this;throw Error("dissoc! after persistent!");};$APP.h.call=function(a){switch(arguments.length-1){case 1:return this.h(arguments[1]);case 2:return this.j(arguments[1],arguments[2]);default:throw Error("Invalid arity: "+$APP.G.h(arguments.length-1));}};$APP.h.apply=function(a,b){return this.call.apply(this,[this].concat($APP.Mb(b)))};
$APP.h.h=function(a){if(this.Jb)return a=this.ra[this.S.h?this.S.h(a):this.S.call(null,a)],this.pb?E4(a,this.ga,this.S,this.transform):a;throw Error("lookup after persistent!");};$APP.h.j=function(a,b){if(this.Jb)return a=$APP.Xa(this.ra,this.S.h?this.S.h(a):this.S.call(null,a),b),this.pb&&a!==b?E4(a,this.ga,this.S,this.transform):a;throw Error("lookup after persistent!");};lUa.prototype.hasNext=function(){return this.O<this.M};
lUa.prototype.next=function(){var a=I4(this.ra,this.ga,this.S,this.transform,this.pb,this.D,this.O);this.O+=1;return a};$APP.h=K4.prototype;$APP.h.toString=function(){return $APP.Ud(this)};$APP.h.equiv=function(a){return this.P(null,a)};$APP.h.indexOf=function(){var a=null;a=function(b,c){switch(arguments.length){case 1:return A4(this,b,0);case 2:return A4(this,b,c)}throw Error("Invalid arity: "+arguments.length);};a.h=function(b){return A4(this,b,0)};a.j=function(b,c){return A4(this,b,c)};return a}();
$APP.h.lastIndexOf=function(){function a(c){return B4(this,c,$APP.Ee(this))}var b=null;b=function(c,d){switch(arguments.length){case 1:return a.call(this,c);case 2:return B4(this,c,d)}throw Error("Invalid arity: "+arguments.length);};b.h=a;b.j=function(c,d){return B4(this,c,d)};return b}();$APP.h.R=function(a,b){a=b+this.O;if(0<=a&&a<this.D.length)return I4(this.ra,this.ga,this.S,this.transform,this.pb,this.D,a);throw Error("Index out of bounds");};
$APP.h.ub=function(a,b,c){a=b+this.O;return 0<=a&&a<this.D.length?I4(this.ra,this.ga,this.S,this.transform,this.pb,this.D,a):c};$APP.h.Y=function(a,b,c){return $APP.zj(b,$APP.Dj,"("," ",")",c,this)};$APP.h.U=function(){return this.I};$APP.h.ib=function(){return new K4(this.ra,this.ga,this.S,this.transform,this.pb,this.D,this.O,this.I)};$APP.h.xb=function(){return this.O+1<this.D.length?new K4(this.ra,this.ga,this.S,this.transform,this.pb,this.D,this.O+1,null):null};
$APP.h.ha=function(){return $APP.Bo.j(0,this.D.length-this.O)};$APP.h.ea=function(){return $APP.pe(this)};$APP.h.P=function(a,b){return dUa(this,b)};$APP.h.Ia=function(){return $APP.le};$APP.h.vb=function(a,b){return eUa(this,b)};$APP.h.sb=function(a,b,c){return fUa(this,b,c)};$APP.h.wb=function(){return I4(this.ra,this.ga,this.S,this.transform,this.pb,this.D,this.O)};$APP.h.zb=function(){return this.O+1<this.D.length?new K4(this.ra,this.ga,this.S,this.transform,this.pb,this.D,this.O+1,null):$APP.le};
$APP.h.ia=function(){return this};$APP.h.X=function(a,b){return b===this.I?this:new K4(this.ra,this.ga,this.S,this.transform,this.pb,this.D,this.O,b)};$APP.h.la=function(a,b){return $APP.cg(b,this)};$APP.h=C4.prototype;$APP.h.bd=$APP.ae;$APP.h.cd=function(a,b){a=$APP.Xa(this.ra,this.S.h?this.S.h(b):this.S.call(null,b),N4);return a===N4?null:new $APP.tf(b,this.pb?E4(a,this.ga,this.S,this.transform):a,null)};$APP.h.toString=function(){return $APP.Ud(this)};
$APP.h.equiv=function(a){return this.P(null,a)};$APP.h.keys=function(){return $APP.ne($APP.Si(this))};$APP.h.entries=function(){return $APP.$h($APP.n(this))};$APP.h.values=function(){return $APP.ne($APP.Ui(this))};$APP.h.has=function(a){return $APP.sf(this,a)};$APP.h.get=function(a,b){return this.W(null,a,b)};
$APP.h.forEach=function(a){for(var b=$APP.n(this),c=null,d=0,e=0;;)if(e<d){var f=c.R(null,e),g=$APP.w.l(f,0,null);f=$APP.w.l(f,1,null);a.j?a.j(f,g):a.call(null,f,g);e+=1}else if(b=$APP.n(b))$APP.ef(b)?(c=$APP.Ed(b),b=$APP.Fd(b),g=c,d=$APP.Ee(c),c=g):(c=$APP.p(b),g=$APP.w.l(c,0,null),f=$APP.w.l(c,1,null),a.j?a.j(f,g):a.call(null,f,g),b=$APP.q(b),c=null,d=0),e=0;else return null};
$APP.h.sa=function(a,b){a=this.ra[this.S.h?this.S.h(b):this.S.call(null,b)];return this.pb?E4(a,this.ga,this.S,this.transform):a};$APP.h.W=function(a,b,c){a=$APP.Xa(this.ra,this.S.h?this.S.h(b):this.S.call(null,b),c);return this.pb&&a!==c?E4(a,this.ga,this.S,this.transform):a};
$APP.h.Ib=function(a,b,c){var d=this;try{var e=$APP.ch(c);$APP.Sa(d.ra,function(f,g){var m=e.cc;var r=e.Ha(null);g=d.ga.h?d.ga.h(g):d.ga.call(null,g);f=d.pb?E4(f,d.ga,d.S,d.transform):f;r=b.l?b.l(r,g,f):b.call(null,r,g,f);m=m.call(e,null,r);if($APP.we(m))throw m;return null});return $APP.yc(e)}catch(f){a=f;if($APP.we(a))return $APP.yc(a);throw a;}};$APP.h.Y=function(a,b,c){return $APP.Gj(this,$APP.Dj,b,c)};
$APP.h.nb=function(){this.Zc==null&&(this.Zc=$APP.Va(this.ra));return new lUa(this.ra,this.ga,this.S,this.transform,this.pb,this.Zc,this.ha(null))};$APP.h.U=function(){return this.I};$APP.h.ib=function(){return new C4(this.I,this.ra,this.ga,this.S,this.transform,this.pb,this.Zc,this.Uc,this.H)};$APP.h.ha=function(){return this.Uc==null?(this.Zc==null&&(this.Zc=$APP.Va(this.ra)),this.Uc=this.Zc.length):this.Uc};$APP.h.ea=function(){var a=this.H;return a!=null?a:this.H=a=$APP.qe(this)};
$APP.h.P=function(a,b){return $APP.Yh(this,b)};$APP.h.Vd=function(){return new kUa($APP.Ya(this.ra),this.ga,this.S,this.transform,this.pb,this.Uc)};$APP.h.Ia=function(){return new C4(this.I,{},this.ga,this.S,this.transform,this.pb,[],0,null)};$APP.h.vb=function(a,b){return $APP.FB(this.ia(null),b)};$APP.h.sb=function(a,b,c){return this.Ib(null,function(d,e,f){e=new $APP.tf(e,f,null);return b.j?b.j(d,e):b.call(null,d,e)},c)};
$APP.h.Tb=function(a,b){a=this.I;var c=$APP.Ya(this.ra);delete c[this.S.h?this.S.h(b):this.S.call(null,b)];return new C4(a,c,this.ga,this.S,this.transform,this.pb,null,null,null)};$APP.h.pa=function(a,b,c){if(jUa(b,this.ga)&&J4(c,this.pb)){a=this.I;var d=$APP.Ya(this.ra);d[this.S.h?this.S.h(b):this.S.call(null,b)]=this.pb?F4(c):c;b=new C4(a,d,this.ga,this.S,this.transform,this.pb,null,null,null)}else b=$APP.hc($APP.Se(iUa(this.ra,this.ga,this.S,this.transform,this.pb),this.I),b,c);return b};
$APP.h.Db=function(a,b){return this.W(null,b,N4)!==N4};$APP.h.ia=function(){this.Zc==null&&(this.Zc=$APP.Va(this.ra));return this.Zc.length>0?new K4(this.ra,this.ga,this.S,this.transform,this.pb,this.Zc,0,null):null};$APP.h.X=function(a,b){return b===this.I?this:new C4(b,this.ra,this.ga,this.S,this.transform,this.pb,this.Zc,this.Uc,this.H)};
$APP.h.la=function(a,b){a:if($APP.df(b))a=this.pa(null,$APP.Pe(b,0),$APP.Pe(b,1));else{a=this;for(b=$APP.n(b);;){if(b==null)break a;var c=$APP.p(b);if($APP.df(c))a=$APP.hc(a,$APP.Pe(c,0),$APP.Pe(c,1)),b=$APP.q(b);else throw Error("conj on a map takes map entries or seqables of map entries");}a=void 0}return a};
$APP.h.call=function(a){switch(arguments.length-1){case 1:return this.h(arguments[1]);case 2:return this.j(arguments[1],arguments[2]);default:throw Error("Invalid arity: "+$APP.G.h(arguments.length-1));}};$APP.h.apply=function(a,b){return this.call.apply(this,[this].concat($APP.Mb(b)))};$APP.h.h=function(a){a=this.ra[this.S.h?this.S.h(a):this.S.call(null,a)];return this.pb?E4(a,this.ga,this.S,this.transform):a};
$APP.h.j=function(a,b){a=$APP.Xa(this.ra,this.S.h?this.S.h(a):this.S.call(null,a),b);return this.pb&&a!==b?E4(a,this.ga,this.S,this.transform):a};$APP.h=mUa.prototype;$APP.h.Nd=function(a,b){if(this.Jb)return J4(b,!0)?(this.D.push(F4(b)),this):$APP.qd($APP.vg(H4(this.D)),b);throw Error("conj! after persistent!");};$APP.h.ie=function(){if(this.Jb)return this.Jb=!1,new D4(null,this.ga,this.S,this.transform,this.D,null);throw Error("persistent! called twice");};
$APP.h.vd=function(a,b,c){if(typeof b==="number")a=this.Ze(null,b,c);else throw Error(""+$APP.G.h("TransientArrayVector")+"'s key for assoc! must be a number.");return a};
$APP.h.Ze=function(a,b,c){if(this.Jb){if(J4(c,!0)){if(0<=b&&b<this.D.length)return this.D[b]=F4(c),this;if(b===this.D.length)return this.Nd(null,c);throw Error("Index "+$APP.G.h(b)+" out of bounds for TransientArrayVector of length"+$APP.G.h(this.D.length));}return $APP.xd($APP.vg(H4(this.D)),b,c)}throw Error("assoc! after persistent!");};
$APP.h.pg=function(){if(this.Jb){if(this.D.length===0)throw Error("Can't pop empty vector");this.D=this.D.slice(0,this.D.length-1);return this}throw Error("pop! after persistent!");};$APP.h.ha=function(){if(this.Jb)return this.D.length;throw Error("count after persistent!");};$APP.h.R=function(a,b){if(this.Jb)return E4(this.D[b],this.ga,this.S,this.transform);throw Error("nth after persistent!");};$APP.h.ub=function(a,b,c){return 0<=b&&b<this.D.length?this.R(null,b):c};
$APP.h.sa=function(a,b){return this.W(null,b,null)};$APP.h.W=function(a,b,c){return typeof b==="number"?this.ub(null,b,c):c};$APP.h.call=function(a){switch(arguments.length-1){case 1:return this.h(arguments[1]);case 2:return this.j(arguments[1],arguments[2]);default:throw Error("Invalid arity: "+$APP.G.h(arguments.length-1));}};$APP.h.apply=function(a,b){return this.call.apply(this,[this].concat($APP.Mb(b)))};$APP.h.h=function(a){return this.sa(null,a)};
$APP.h.j=function(a,b){return this.W(null,a,b)};nUa.prototype.hasNext=function(){return this.O<this.M};nUa.prototype.next=function(){var a=E4(this.D[this.O],this.ga,this.S,this.transform);this.O+=1;return a};$APP.h=L4.prototype;$APP.h.toString=function(){return $APP.Ud(this)};$APP.h.equiv=function(a){return this.P(null,a)};
$APP.h.indexOf=function(){var a=null;a=function(b,c){switch(arguments.length){case 1:return A4(this,b,0);case 2:return A4(this,b,c)}throw Error("Invalid arity: "+arguments.length);};a.h=function(b){return A4(this,b,0)};a.j=function(b,c){return A4(this,b,c)};return a}();
$APP.h.lastIndexOf=function(){function a(c){return B4(this,c,$APP.Ee(this))}var b=null;b=function(c,d){switch(arguments.length){case 1:return a.call(this,c);case 2:return B4(this,c,d)}throw Error("Invalid arity: "+arguments.length);};b.h=a;b.j=function(c,d){return B4(this,c,d)};return b}();$APP.h.R=function(a,b){a=b+this.O;if(0<=a&&a<this.D.length)return E4(this.D[a],this.ga,this.S,this.transform);throw Error("Index out of bounds");};
$APP.h.ub=function(a,b,c){a=b+this.O;return 0<=a&&a<this.D.length?E4(this.D[a],this.ga,this.S,this.transform):c};$APP.h.Y=function(a,b,c){return $APP.zj(b,$APP.Dj,"("," ",")",c,this)};$APP.h.U=function(){return this.I};$APP.h.ib=function(){return new L4(this.ga,this.S,this.transform,this.D,this.O,this.I)};$APP.h.xb=function(){return this.O+1<this.D.length?new L4(this.ga,this.S,this.transform,this.D,this.O+1,null):null};$APP.h.ha=function(){return $APP.Bo.j(0,this.D.length-this.O)};$APP.h.ea=function(){return $APP.pe(this)};
$APP.h.P=function(a,b){return dUa(this,b)};$APP.h.Ia=function(){return $APP.le};$APP.h.vb=function(a,b){return eUa(this,b)};$APP.h.sb=function(a,b,c){return fUa(this,b,c)};$APP.h.wb=function(){return E4(this.D[this.O],this.ga,this.S,this.transform)};$APP.h.zb=function(){return this.O+1<this.D.length?new L4(this.ga,this.S,this.transform,this.D,this.O+1,null):$APP.le};$APP.h.ia=function(){return this};$APP.h.X=function(a,b){return b===this.I?this:new L4(this.ga,this.S,this.transform,this.D,this.O,b)};
$APP.h.la=function(a,b){return $APP.cg(b,this)};$APP.h=D4.prototype;$APP.h.bd=$APP.ae;$APP.h.cd=function(a,b){return 0<=b&&b<this.D.length?new $APP.tf(b,E4(this.D[b],this.ga,this.S,this.transform),null):null};$APP.h.toString=function(){return $APP.Ud(this)};$APP.h.equiv=function(a){return this.P(null,a)};
$APP.h.indexOf=function(){var a=null;a=function(b,c){switch(arguments.length){case 1:return A4(this,b,0);case 2:return A4(this,b,c)}throw Error("Invalid arity: "+arguments.length);};a.h=function(b){return A4(this,b,0)};a.j=function(b,c){return A4(this,b,c)};return a}();
$APP.h.lastIndexOf=function(){var a=null;a=function(b,c){switch(arguments.length){case 1:return B4(this,b,$APP.Ee(this));case 2:return B4(this,b,c)}throw Error("Invalid arity: "+arguments.length);};a.h=function(b){return B4(this,b,$APP.Ee(this))};a.j=function(b,c){return B4(this,b,c)};return a}();$APP.h.sa=function(a,b){return this.W(null,b,null)};$APP.h.W=function(a,b,c){return typeof b==="number"?this.ub(null,b,c):c};
$APP.h.Ib=function(a,b,c){a=0;for(var d=c;;)if(a<this.D.length){c=this.D.length;var e;a:{for(e=0;;)if(e<c){var f=e+a,g=E4(this.D[e],this.ga,this.S,this.transform);d=b.l?b.l(d,f,g):b.call(null,d,f,g);if($APP.we(d)){e=d;break a}e+=1}else{e=d;break a}e=void 0}if($APP.we(e))return $APP.yc(e);a+=c;d=e}else return d};$APP.h.R=function(a,b){if(0<=b&&b<this.D.length)return E4(this.D[b],this.ga,this.S,this.transform);throw Error("No item "+$APP.G.h(b)+" in vector of length "+$APP.G.h(this.D.length));};
$APP.h.ub=function(a,b,c){return 0<=b&&b<this.D.length?E4(this.D[b],this.ga,this.S,this.transform):c};$APP.h.Y=function(a,b,c){return $APP.zj(b,$APP.Dj,"["," ","]",c,this)};$APP.h.Nc=function(a,b,c){if(0<=b&&b<this.D.length)return J4(c,!0)?(a=$APP.Mb(this.D),a[b]=F4(c),new D4(this.I,this.ga,this.S,this.transform,a,null)):$APP.wc(H4(this.D),b,c);if(b===this.D.length)return this.la(null,c);throw Error("Index "+$APP.G.h(b)+" out of bounds  [0,"+$APP.G.h(this.D.length)+"]");};
$APP.h.nb=function(){return new nUa(this.ga,this.S,this.transform,this.D,this.D.length)};$APP.h.U=function(){return this.I};$APP.h.ib=function(){return new D4(this.I,this.ga,this.S,this.transform,this.D,this.H)};$APP.h.ha=function(){return this.D.length};$APP.h.td=function(){return this.D.length>0?this.R(null,this.D.length-1):null};
$APP.h.ud=function(){if(this.D.length===0)throw Error("Can't pop empty vector");if(1===this.D.length)return this.Ia(null);var a=$APP.Mb(this.D);return new D4(this.I,this.ga,this.S,this.transform,a.slice(0,a.length-1),null)};$APP.h.sd=function(){return this.D.length>0?new $APP.Je(this,this.D.length-1,null):null};$APP.h.ea=function(){var a=this.H;return a!=null?a:this.H=a=$APP.pe(this)};
$APP.h.P=function(a,b){a:if(b instanceof D4)if(this.D.length===$APP.Ee(b)){a=this.nb(null);for(b=$APP.Qd(b);;){if(a.hasNext()){var c=a.next(),d=b.next();if($APP.Fe.j(c,d))continue;else{a=!1;break a}}else{a=!0;break a}break}a=void 0}else a=!1;else a=dUa(this,b);return a};$APP.h.Vd=function(){return new mUa($APP.Mb(this.D),this.ga,this.S,this.transform)};$APP.h.Ia=function(){return new D4(this.I,this.ga,this.S,this.transform,[],null)};$APP.h.vb=function(a,b){return eUa(this,b)};
$APP.h.sb=function(a,b,c){return fUa(this,b,c)};$APP.h.pa=function(a,b,c){if(typeof b==="number")a=this.Nc(null,b,c);else throw Error("Vector's key for assoc must be a number.");return a};$APP.h.Db=function(a,b){return $APP.mf(b)?0<=b&&b<this.D.length:!1};$APP.h.ia=function(){return this.D.length>0?new L4(this.ga,this.S,this.transform,this.D,0,null):null};$APP.h.X=function(a,b){return b===this.I?this:new D4(b,this.ga,this.S,this.transform,this.D,this.H)};
$APP.h.la=function(a,b){return J4(b,!0)?(a=$APP.Mb(this.D),a[a.length]=F4(b),new D4(this.I,this.ga,this.S,this.transform,a,null)):$APP.Xb(H4(this.D),b)};$APP.h.call=function(a){switch(arguments.length-1){case 1:return this.h(arguments[1]);case 2:return this.j(arguments[1],arguments[2]);default:throw Error("Invalid arity: "+$APP.G.h(arguments.length-1));}};$APP.h.apply=function(a,b){return this.call.apply(this,[this].concat($APP.Mb(b)))};$APP.h.h=function(a){return this.R(null,a)};
$APP.h.j=function(a,b){return this.ub(null,a,b)};$APP.h.Mc=function(a,b){if($APP.df(b)){a=$APP.Ee(this);var c=$APP.Ee(b);if(a<c)b=-1;else if(a>c)b=1;else if(a===0)b=0;else a:{for(c=0;;){var d=$APP.vf($APP.w.j(this,c),$APP.w.j(b,c));if(d===0&&c+1<a)c+=1;else{b=d;break a}}b=void 0}return b}throw Error("Cannot compare "+$APP.G.h(this)+" to "+$APP.G.h(b));};
var O4=function O4(a){switch(arguments.length){case 0:return O4.A();case 1:return O4.h(arguments[0]);default:for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return O4.o(arguments[0],1<c.length?new $APP.he(c.slice(1),0,null):null)}};O4.A=function(){return new C4(null,{},$APP.Fj,M4,null,!1,[],0,null)};O4.h=function(a){return new C4(null,a,$APP.Fj,M4,null,!1,null,null,null)};
O4.o=function(a,b){var c=$APP.Bg(b);b=$APP.y.j(c,$APP.RC);var d=$APP.y.j(c,qUa),e=$APP.y.j(c,oUa),f=$APP.y.j(c,sUa);c=$APP.y.j(c,$APP.GD);return b===!1?new C4(null,a,$APP.Gf,$APP.Gf,f,$APP.qb(c),null,null,null):d!=null&&e!=null?new C4(null,a,d,e,f,$APP.qb(c),null,null,null):new C4(null,a,$APP.Fj,M4,f,$APP.qb(c),null,null,null)};O4.B=function(a){var b=$APP.p(a);a=$APP.q(a);return this.o(b,a)};O4.v=1;
var G4=function G4(a){switch(arguments.length){case 1:return G4.h(arguments[0]);default:for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return G4.o(arguments[0],1<c.length?new $APP.he(c.slice(1),0,null):null)}};G4.h=function(a){return E4(a,$APP.Fj,M4,null)};G4.o=function(a,b){var c=$APP.Bg(b);b=$APP.y.j(c,$APP.RC);var d=$APP.y.j(c,qUa),e=$APP.y.j(c,oUa);c=$APP.y.j(c,sUa);return b===!1?E4(a,$APP.Gf,$APP.Gf,c):d!=null&&e!=null?E4(a,d,e,c):E4(a,$APP.Fj,M4,c)};
G4.B=function(a){var b=$APP.p(a);a=$APP.q(a);return this.o(b,a)};G4.v=1;var P4=function P4(a){switch(arguments.length){case 1:return P4.h(arguments[0]);default:for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return P4.o(arguments[0],1<c.length?new $APP.he(c.slice(1),0,null):null)}};P4.h=function(a){return a instanceof C4?a.ra:a instanceof D4?a.D:$APP.PC.o(a,$APP.x([$APP.QC,M4],0))};
P4.o=function(a,b){if(a instanceof C4)return a.ra;if(a instanceof D4)return a.D;b=$APP.Bg(b);b=$APP.y.l(b,oUa,M4);return $APP.PC.o(a,$APP.x([$APP.QC,b],0))};P4.B=function(a){var b=$APP.p(a);a=$APP.q(a);return this.o(b,a)};P4.v=1;var Q4=$APP.cY.j($APP.VJ,null),vUa=new $APP.F(null,5,[rUa,$APP.$s(O4,rUa,new $APP.F(null,7,[$APP.Q,rUa,$APP.P,"Takes a JavaScript object and returns a read-only implementation of the map\n  abstraction backed by the object.\n\n  By default, bean produces beans that keywordize the keys. Supply\n  :keywordize-keys false to suppress this behavior. You can alternatively\n  supply :prop-\x3ekey and :key-\x3eprop with functions that control the mapping\n  between properties and keys.\n\n  Supply :recursive true to create a bean which recursively converts\n  JavaScript object values to beans and JavaScript arrays into vectors.\n\n  Supply :transform and a function of one argument to transform values being\n  converted from JavaScript to ClojureScript. This function should return nil\n  if no conversion is to be performed, thus allowing default logic to be applied.\n\n  Calling (bean) produces an empty bean.",
$APP.Y,$APP.I($APP.rh,new $APP.D(null,1,5,$APP.E,[$APP.bQ],null),new $APP.D(null,3,5,$APP.E,[$APP.bQ,$APP.Lk,$APP.zM],null)),$APP.J,"cljs_bean/core.cljs",$APP.K,702,$APP.M,7,$APP.S,Q4],null),Q4),pUa,$APP.$s(function(a){return a instanceof C4},pUa,new $APP.F(null,7,[$APP.Q,pUa,$APP.P,"Returns true if x is a bean.",$APP.Y,$APP.I(new $APP.D(null,1,5,$APP.E,[$APP.bQ],null)),$APP.J,"cljs_bean/core.cljs",$APP.K,735,$APP.M,7,$APP.S,Q4],null),Q4),$APP.SO,$APP.$s(function(a){return a.ra},$APP.SO,new $APP.F(null,
8,[$APP.Q,$APP.SO,$APP.P,"Takes a bean and returns a JavaScript object.",$APP.Y,$APP.I(new $APP.D(null,1,5,$APP.E,[$APP.JP],null)),$APP.cn,$APP.jH,$APP.J,"cljs_bean/core.cljs",$APP.K,740,$APP.M,11,$APP.S,Q4],null),Q4),uUa,$APP.$s(P4,uUa,new $APP.F(null,7,[$APP.Q,uUa,$APP.P,"Recursively converts ClojureScript values to JavaScript.\n\n  Where possible, directly returns the backing objects and arrays for values\n  produced using -\x3eclj and bean.\n\n  Otherwise delegates to clj-\x3ejs to perform the conversion, converting keyword\n  keys using their qualified names. You can alternatively supply :key-\x3eprop with\n  a function that controls the mapping from keys to properties.",
$APP.Y,$APP.I(new $APP.D(null,1,5,$APP.E,[$APP.bQ],null),new $APP.D(null,3,5,$APP.E,[$APP.bQ,$APP.Lk,$APP.zM],null)),$APP.J,"cljs_bean/core.cljs",$APP.K,775,$APP.M,7,$APP.S,Q4],null),Q4),tUa,$APP.$s(G4,tUa,new $APP.F(null,7,[$APP.Q,tUa,$APP.P,"Recursively converts JavaScript values to ClojureScript.\n\n  JavaScript objects are converted to beans with keywords for keys.\n\n  JavaScript arrays are converted to read-only implementations of the vector\n  abstraction, backed by the supplied array.\n\n  By default, -\x3eclj produces values that keywordize the keys. Supply\n  :keywordize-keys false to suppress this behavior. You can alternatively\n  supply :prop-\x3ekey and :key-\x3eprop with functions that control the mapping\n  between properties and keys.\n\n  Supply :transform and a function of one argument to transform values being\n  converted from JavaScript to ClojureScript. This function should return nil\n  if no conversion is to be performed, thus allowing default logic to be applied.",
$APP.Y,$APP.I(new $APP.D(null,1,5,$APP.E,[$APP.bQ],null),new $APP.D(null,3,5,$APP.E,[$APP.bQ,$APP.Lk,$APP.zM],null)),$APP.J,"cljs_bean/core.cljs",$APP.K,745,$APP.M,7,$APP.S,Q4],null),Q4)],null);$APP.Gz(new $APP.F(null,1,[$APP.wt,new $APP.F(null,1,[$APP.VJ,vUa],null)],null));