import { $APP, shadow$provide } from "./nbb_core.js";
const shadow_esm_import = function(x) { return import(x) };
var Y4=function(a,b,c){var d=$APP.Ee(a);if(c>=d)return-1;for(c=c>0?c:c<0?$APP.Co.j(0,c+d):c;;)if(c<d){if($APP.Fe.j($APP.w.j(a,c),b))return c;c+=1}else return-1},Z4=function(a,b,c){var d=$APP.Ee(a);if(d===0)return-1;for(c=c>0?$APP.nm.j(d-1,c):c<0?d+c:c;;)if(c>=0){if($APP.Fe.j($APP.w.j(a,c),b))return c;--c}else return-1},cWa=function(a,b){if($APP.af(b))if($APP.Ce(a)&&$APP.Ce(b)&&$APP.Ee(a)!==$APP.Ee(b))a=!1;else a:{a=$APP.n(a);for(b=$APP.n(b);;){if(a==null){a=b==null;break a}if(b!=null&&$APP.Fe.j($APP.p(a),
$APP.p(b)))a=$APP.r(a),b=$APP.r(b);else{a=!1;break a}}a=void 0}else a=null;return $APP.rb(a)},dWa=function(a,b){var c=a.ha(null);if(c===0)return b.A?b.A():b.call(null);for(var d=a.R(null,0),e=1;;)if(e<c){var f=a.R(null,e);d=b.j?b.j(d,f):b.call(null,d,f);if($APP.we(d))return $APP.zc(d);e+=1}else return d},eWa=function(a,b,c){var d=a.ha(null),e=c;for(c=0;;)if(c<d){var f=a.R(null,c);e=b.j?b.j(e,f):b.call(null,e,f);if($APP.we(e))return $APP.zc(e);c+=1}else return e},fWa=function(a){return typeof a===
"number"||typeof a==="string"||$APP.hf(a)||a==null},b5=function(a,b,c,d){var e=d!=null?d.h?d.h(a):d.call(null,a):null;return e==null?fWa(a)?a:$APP.Db(a)?new $4(null,a,b,c,d,!0,null,null,null):$APP.l($APP.yb(a))?new a5(null,b,c,d,a,null):a:e},c5=function(a){return fWa(a)?a:a instanceof $4?a.ra:a instanceof a5?a.D:a},hWa=function(a,b,c,d,e){var f=$APP.dh($APP.od(gWa));$APP.Ua(a,function(g,k){return f.bc(null,$APP.ji.l(f.Ha(null),b.h?b.h(k):b.call(null,k),$APP.l(e)?b5(g,b,c,d):g))});return $APP.wg($APP.zc(f))},
e5=function(a){a:{for(var b=a.length,c=$APP.Mb(a),d=0;;)if(d<b){var e=d;var f=a[d];f=d5.h?d5.h(f):d5.call(null,f);c[e]=f;d+=1}else{a=c;break a}a=void 0}return $APP.Ih(a)},f5=function(a,b,c,d,e,f,g){g=f[g];f=b.h?b.h(g):b.call(null,g);a=a[g];b=e?b5(a,b,c,d):a;return new $APP.wf(f,b,null)},iWa=function(a,b){return a instanceof $APP.C&&b===$APP.Gj||typeof a==="string"&&b===$APP.Hf},g5=function(a,b){var c;!(c=fWa(a))&&(c=!($APP.cf(a)&&!(a instanceof $4)||$APP.ef(a)&&!(a instanceof a5)))&&(a=$APP.l(b)?
(b=$APP.Db(a))?b:$APP.yb(a):b,c=$APP.Bb(a));return c},jWa=function(a,b,c,d,e,f){this.Jb=!0;this.ra=a;this.ga=b;this.S=c;this.transform=d;this.pb=e;this.Uc=f;this.G=259;this.K=56},kWa=function(a,b,c,d,e,f,g){this.ra=a;this.ga=b;this.S=c;this.transform=d;this.pb=e;this.D=f;this.O=0;this.M=g},h5=function(a,b,c,d,e,f,g,k){this.ra=a;this.ga=b;this.S=c;this.transform=d;this.pb=e;this.D=f;this.O=g;this.I=k;this.G=2179858686;this.K=8192},$4=function(a,b,c,d,e,f,g,k,q){this.I=a;this.ra=b;this.ga=c;this.S=
d;this.transform=e;this.pb=f;this.Zc=g;this.Uc=k;this.H=q;this.G=2164131599;this.K=139268},lWa=function(a,b,c,d){this.Jb=!0;this.D=a;this.ga=b;this.S=c;this.transform=d;this.K=88;this.G=275},mWa=function(a,b,c,d,e){this.ga=a;this.S=b;this.transform=c;this.D=d;this.O=0;this.M=e},i5=function(a,b,c,d,e,f){this.ga=a;this.S=b;this.transform=c;this.D=d;this.O=e;this.I=f;this.G=2179858686;this.K=8192},a5=function(a,b,c,d,e,f){this.I=a;this.ga=b;this.S=c;this.transform=d;this.D=e;this.H=f;this.G=2315150111;
this.K=141316},j5=function(a){return a instanceof $APP.C?a.aa:null},nWa=new $APP.C(null,"key-\x3eprop","key-\x3eprop",-1028452531),oWa=new $APP.m(null,"bean?","bean?",2057456095,null),pWa=new $APP.C(null,"prop-\x3ekey","prop-\x3ekey",-1297715246),qWa=new $APP.m(null,"bean","bean",-1620239896,null),rWa=new $APP.C(null,"transform","transform",1381301764),sWa=new $APP.m(null,"-\x3eclj","-\x3eclj",-1549422014,null),tWa=new $APP.m(null,"-\x3ejs","-\x3ejs",-1825590244,null);var k5={},gWa=$APP.Ag;$APP.h=jWa.prototype;$APP.h.sa=function(a,b){if(this.Jb)return a=this.ra[this.S.h?this.S.h(b):this.S.call(null,b)],this.pb?b5(a,this.ga,this.S,this.transform):a;throw Error("lookup after persistent!");};$APP.h.W=function(a,b,c){if(this.Jb)return a=$APP.Xa(this.ra,this.S.h?this.S.h(b):this.S.call(null,b),c),this.pb&&a!==c?b5(a,this.ga,this.S,this.transform):a;throw Error("lookup after persistent!");};
$APP.h.ha=function(){return this.Uc==null?this.Uc=$APP.Ee($APP.Va(this.ra)):this.Uc};$APP.h.Od=function(a,b){a:{if($APP.l(this.Jb)){if($APP.Eh(b)){a=this.vd(null,$APP.oc(b),$APP.pc(b));break a}if($APP.ef(b)){a=this.vd(null,b.h?b.h(0):b.call(null,0),b.h?b.h(1):b.call(null,1));break a}a=$APP.n(b);for(b=this;;){var c=$APP.p(a);if($APP.l(c))a=$APP.r(a),b=$APP.td(b,$APP.oc(c),$APP.pc(c));else{a=b;break a}}}else throw Error("conj! after persistent!");a=void 0}return a};
$APP.h.ie=function(){if(this.Jb)return this.Jb=!1,new $4(null,this.ra,this.ga,this.S,this.transform,this.pb,null,this.Uc,null);throw Error("persistent! called twice");};$APP.h.vd=function(a,b,c){if(this.Jb){if(!iWa(b,this.ga)||!g5(c,this.pb))return $APP.td($APP.vg(hWa(this.ra,this.ga,this.S,this.transform,this.pb)),b,c);this.ra[this.S.h?this.S.h(b):this.S.call(null,b)]=this.pb?c5(c):c;this.Uc=null;return this}throw Error("assoc! after persistent!");};
$APP.h.yf=function(a,b){if(this.Jb)return delete this.ra[this.S.h?this.S.h(b):this.S.call(null,b)],this.Uc=null,this;throw Error("dissoc! after persistent!");};$APP.h.call=function(a){switch(arguments.length-1){case 1:return this.h(arguments[1]);case 2:return this.j(arguments[1],arguments[2]);default:throw Error("Invalid arity: "+$APP.H.h(arguments.length-1));}};$APP.h.apply=function(a,b){return this.call.apply(this,[this].concat($APP.Mb(b)))};
$APP.h.h=function(a){if(this.Jb)return a=this.ra[this.S.h?this.S.h(a):this.S.call(null,a)],this.pb?b5(a,this.ga,this.S,this.transform):a;throw Error("lookup after persistent!");};$APP.h.j=function(a,b){if(this.Jb)return a=$APP.Xa(this.ra,this.S.h?this.S.h(a):this.S.call(null,a),b),this.pb&&a!==b?b5(a,this.ga,this.S,this.transform):a;throw Error("lookup after persistent!");};kWa.prototype.hasNext=function(){return this.O<this.M};
kWa.prototype.next=function(){var a=f5(this.ra,this.ga,this.S,this.transform,this.pb,this.D,this.O);this.O+=1;return a};$APP.h=h5.prototype;$APP.h.toString=function(){return $APP.Ud(this)};$APP.h.equiv=function(a){return this.P(null,a)};$APP.h.indexOf=function(){var a=null;a=function(b,c){switch(arguments.length){case 1:return Y4(this,b,0);case 2:return Y4(this,b,c)}throw Error("Invalid arity: "+arguments.length);};a.h=function(b){return Y4(this,b,0)};a.j=function(b,c){return Y4(this,b,c)};return a}();
$APP.h.lastIndexOf=function(){function a(c){return Z4(this,c,$APP.Ee(this))}var b=null;b=function(c,d){switch(arguments.length){case 1:return a.call(this,c);case 2:return Z4(this,c,d)}throw Error("Invalid arity: "+arguments.length);};b.h=a;b.j=function(c,d){return Z4(this,c,d)};return b}();$APP.h.R=function(a,b){a=b+this.O;if(0<=a&&a<this.D.length)return f5(this.ra,this.ga,this.S,this.transform,this.pb,this.D,a);throw Error("Index out of bounds");};
$APP.h.ub=function(a,b,c){a=b+this.O;return 0<=a&&a<this.D.length?f5(this.ra,this.ga,this.S,this.transform,this.pb,this.D,a):c};$APP.h.Y=function(a,b,c){return $APP.Aj(b,$APP.Fj,"("," ",")",c,this)};$APP.h.U=function(){return this.I};$APP.h.ib=function(){return new h5(this.ra,this.ga,this.S,this.transform,this.pb,this.D,this.O,this.I)};$APP.h.xb=function(){return this.O+1<this.D.length?new h5(this.ra,this.ga,this.S,this.transform,this.pb,this.D,this.O+1,null):null};
$APP.h.ha=function(){return $APP.Co.j(0,this.D.length-this.O)};$APP.h.ea=function(){return $APP.pe(this)};$APP.h.P=function(a,b){return cWa(this,b)};$APP.h.Ia=function(){return $APP.le};$APP.h.vb=function(a,b){return dWa(this,b)};$APP.h.sb=function(a,b,c){return eWa(this,b,c)};$APP.h.wb=function(){return f5(this.ra,this.ga,this.S,this.transform,this.pb,this.D,this.O)};$APP.h.zb=function(){return this.O+1<this.D.length?new h5(this.ra,this.ga,this.S,this.transform,this.pb,this.D,this.O+1,null):$APP.le};
$APP.h.ia=function(){return this};$APP.h.X=function(a,b){return b===this.I?this:new h5(this.ra,this.ga,this.S,this.transform,this.pb,this.D,this.O,b)};$APP.h.la=function(a,b){return $APP.cg(b,this)};$APP.h=$4.prototype;$APP.h.bd=$APP.ae;$APP.h.cd=function(a,b){a=$APP.Xa(this.ra,this.S.h?this.S.h(b):this.S.call(null,b),k5);return a===k5?null:new $APP.wf(b,this.pb?b5(a,this.ga,this.S,this.transform):a,null)};$APP.h.toString=function(){return $APP.Ud(this)};
$APP.h.equiv=function(a){return this.P(null,a)};$APP.h.keys=function(){return $APP.ne($APP.Ti(this))};$APP.h.entries=function(){return $APP.ai($APP.n(this))};$APP.h.values=function(){return $APP.ne($APP.Vi(this))};$APP.h.has=function(a){return $APP.vf(this,a)};$APP.h.get=function(a,b){return this.W(null,a,b)};
$APP.h.forEach=function(a){for(var b=$APP.n(this),c=null,d=0,e=0;;)if(e<d){var f=c.R(null,e),g=$APP.w.l(f,0,null);f=$APP.w.l(f,1,null);a.j?a.j(f,g):a.call(null,f,g);e+=1}else if(b=$APP.n(b))$APP.ff(b)?(c=$APP.Ed(b),b=$APP.Fd(b),g=c,d=$APP.Ee(c),c=g):(c=$APP.p(b),g=$APP.w.l(c,0,null),f=$APP.w.l(c,1,null),a.j?a.j(f,g):a.call(null,f,g),b=$APP.r(b),c=null,d=0),e=0;else return null};
$APP.h.sa=function(a,b){a=this.ra[this.S.h?this.S.h(b):this.S.call(null,b)];return this.pb?b5(a,this.ga,this.S,this.transform):a};$APP.h.W=function(a,b,c){a=$APP.Xa(this.ra,this.S.h?this.S.h(b):this.S.call(null,b),c);return this.pb&&a!==c?b5(a,this.ga,this.S,this.transform):a};
$APP.h.Ib=function(a,b,c){var d=this;try{var e=$APP.dh(c);$APP.Ua(d.ra,function(f,g){var k=e.bc;var q=e.Ha(null);g=d.ga.h?d.ga.h(g):d.ga.call(null,g);f=d.pb?b5(f,d.ga,d.S,d.transform):f;q=b.l?b.l(q,g,f):b.call(null,q,g,f);k=k.call(e,null,q);if($APP.we(k))throw k;return null});return $APP.zc(e)}catch(f){a=f;if($APP.we(a))return $APP.zc(a);throw a;}};$APP.h.Y=function(a,b,c){return $APP.Hj(this,$APP.Fj,b,c)};
$APP.h.nb=function(){this.Zc==null&&(this.Zc=$APP.Va(this.ra));return new kWa(this.ra,this.ga,this.S,this.transform,this.pb,this.Zc,this.ha(null))};$APP.h.U=function(){return this.I};$APP.h.ib=function(){return new $4(this.I,this.ra,this.ga,this.S,this.transform,this.pb,this.Zc,this.Uc,this.H)};$APP.h.ha=function(){return this.Uc==null?(this.Zc==null&&(this.Zc=$APP.Va(this.ra)),this.Uc=this.Zc.length):this.Uc};$APP.h.ea=function(){var a=this.H;return a!=null?a:this.H=a=$APP.qe(this)};
$APP.h.P=function(a,b){return $APP.Zh(this,b)};$APP.h.Vd=function(){return new jWa($APP.Ya(this.ra),this.ga,this.S,this.transform,this.pb,this.Uc)};$APP.h.Ia=function(){return new $4(this.I,{},this.ga,this.S,this.transform,this.pb,[],0,null)};$APP.h.vb=function(a,b){return $APP.jC(this.ia(null),b)};$APP.h.sb=function(a,b,c){return this.Ib(null,function(d,e,f){e=new $APP.wf(e,f,null);return b.j?b.j(d,e):b.call(null,d,e)},c)};
$APP.h.Tb=function(a,b){a=this.I;var c=$APP.Ya(this.ra);delete c[this.S.h?this.S.h(b):this.S.call(null,b)];return new $4(a,c,this.ga,this.S,this.transform,this.pb,null,null,null)};$APP.h.pa=function(a,b,c){if(iWa(b,this.ga)&&g5(c,this.pb)){a=this.I;var d=$APP.Ya(this.ra);d[this.S.h?this.S.h(b):this.S.call(null,b)]=this.pb?c5(c):c;b=new $4(a,d,this.ga,this.S,this.transform,this.pb,null,null,null)}else b=$APP.ic($APP.Te(hWa(this.ra,this.ga,this.S,this.transform,this.pb),this.I),b,c);return b};
$APP.h.Db=function(a,b){return this.W(null,b,k5)!==k5};$APP.h.ia=function(){this.Zc==null&&(this.Zc=$APP.Va(this.ra));return this.Zc.length>0?new h5(this.ra,this.ga,this.S,this.transform,this.pb,this.Zc,0,null):null};$APP.h.X=function(a,b){return b===this.I?this:new $4(b,this.ra,this.ga,this.S,this.transform,this.pb,this.Zc,this.Uc,this.H)};
$APP.h.la=function(a,b){a:if($APP.ef(b))a=this.pa(null,$APP.Pe(b,0),$APP.Pe(b,1));else{a=this;for(b=$APP.n(b);;){if(b==null)break a;var c=$APP.p(b);if($APP.ef(c))a=$APP.ic(a,$APP.Pe(c,0),$APP.Pe(c,1)),b=$APP.r(b);else throw Error("conj on a map takes map entries or seqables of map entries");}a=void 0}return a};
$APP.h.call=function(a){switch(arguments.length-1){case 1:return this.h(arguments[1]);case 2:return this.j(arguments[1],arguments[2]);default:throw Error("Invalid arity: "+$APP.H.h(arguments.length-1));}};$APP.h.apply=function(a,b){return this.call.apply(this,[this].concat($APP.Mb(b)))};$APP.h.h=function(a){a=this.ra[this.S.h?this.S.h(a):this.S.call(null,a)];return this.pb?b5(a,this.ga,this.S,this.transform):a};
$APP.h.j=function(a,b){a=$APP.Xa(this.ra,this.S.h?this.S.h(a):this.S.call(null,a),b);return this.pb&&a!==b?b5(a,this.ga,this.S,this.transform):a};$APP.h=lWa.prototype;$APP.h.Od=function(a,b){if(this.Jb)return g5(b,!0)?(this.D.push(c5(b)),this):$APP.qd($APP.vg(e5(this.D)),b);throw Error("conj! after persistent!");};$APP.h.ie=function(){if(this.Jb)return this.Jb=!1,new a5(null,this.ga,this.S,this.transform,this.D,null);throw Error("persistent! called twice");};
$APP.h.vd=function(a,b,c){if(typeof b==="number")a=this.$e(null,b,c);else throw Error(""+$APP.H.h("TransientArrayVector")+"'s key for assoc! must be a number.");return a};
$APP.h.$e=function(a,b,c){if(this.Jb){if(g5(c,!0)){if(0<=b&&b<this.D.length)return this.D[b]=c5(c),this;if(b===this.D.length)return this.Od(null,c);throw Error("Index "+$APP.H.h(b)+" out of bounds for TransientArrayVector of length"+$APP.H.h(this.D.length));}return $APP.xd($APP.vg(e5(this.D)),b,c)}throw Error("assoc! after persistent!");};
$APP.h.pg=function(){if(this.Jb){if(this.D.length===0)throw Error("Can't pop empty vector");this.D=this.D.slice(0,this.D.length-1);return this}throw Error("pop! after persistent!");};$APP.h.ha=function(){if(this.Jb)return this.D.length;throw Error("count after persistent!");};$APP.h.R=function(a,b){if(this.Jb)return b5(this.D[b],this.ga,this.S,this.transform);throw Error("nth after persistent!");};$APP.h.ub=function(a,b,c){return 0<=b&&b<this.D.length?this.R(null,b):c};
$APP.h.sa=function(a,b){return this.W(null,b,null)};$APP.h.W=function(a,b,c){return typeof b==="number"?this.ub(null,b,c):c};$APP.h.call=function(a){switch(arguments.length-1){case 1:return this.h(arguments[1]);case 2:return this.j(arguments[1],arguments[2]);default:throw Error("Invalid arity: "+$APP.H.h(arguments.length-1));}};$APP.h.apply=function(a,b){return this.call.apply(this,[this].concat($APP.Mb(b)))};$APP.h.h=function(a){return this.sa(null,a)};
$APP.h.j=function(a,b){return this.W(null,a,b)};mWa.prototype.hasNext=function(){return this.O<this.M};mWa.prototype.next=function(){var a=b5(this.D[this.O],this.ga,this.S,this.transform);this.O+=1;return a};$APP.h=i5.prototype;$APP.h.toString=function(){return $APP.Ud(this)};$APP.h.equiv=function(a){return this.P(null,a)};
$APP.h.indexOf=function(){var a=null;a=function(b,c){switch(arguments.length){case 1:return Y4(this,b,0);case 2:return Y4(this,b,c)}throw Error("Invalid arity: "+arguments.length);};a.h=function(b){return Y4(this,b,0)};a.j=function(b,c){return Y4(this,b,c)};return a}();
$APP.h.lastIndexOf=function(){function a(c){return Z4(this,c,$APP.Ee(this))}var b=null;b=function(c,d){switch(arguments.length){case 1:return a.call(this,c);case 2:return Z4(this,c,d)}throw Error("Invalid arity: "+arguments.length);};b.h=a;b.j=function(c,d){return Z4(this,c,d)};return b}();$APP.h.R=function(a,b){a=b+this.O;if(0<=a&&a<this.D.length)return b5(this.D[a],this.ga,this.S,this.transform);throw Error("Index out of bounds");};
$APP.h.ub=function(a,b,c){a=b+this.O;return 0<=a&&a<this.D.length?b5(this.D[a],this.ga,this.S,this.transform):c};$APP.h.Y=function(a,b,c){return $APP.Aj(b,$APP.Fj,"("," ",")",c,this)};$APP.h.U=function(){return this.I};$APP.h.ib=function(){return new i5(this.ga,this.S,this.transform,this.D,this.O,this.I)};$APP.h.xb=function(){return this.O+1<this.D.length?new i5(this.ga,this.S,this.transform,this.D,this.O+1,null):null};$APP.h.ha=function(){return $APP.Co.j(0,this.D.length-this.O)};$APP.h.ea=function(){return $APP.pe(this)};
$APP.h.P=function(a,b){return cWa(this,b)};$APP.h.Ia=function(){return $APP.le};$APP.h.vb=function(a,b){return dWa(this,b)};$APP.h.sb=function(a,b,c){return eWa(this,b,c)};$APP.h.wb=function(){return b5(this.D[this.O],this.ga,this.S,this.transform)};$APP.h.zb=function(){return this.O+1<this.D.length?new i5(this.ga,this.S,this.transform,this.D,this.O+1,null):$APP.le};$APP.h.ia=function(){return this};$APP.h.X=function(a,b){return b===this.I?this:new i5(this.ga,this.S,this.transform,this.D,this.O,b)};
$APP.h.la=function(a,b){return $APP.cg(b,this)};$APP.h=a5.prototype;$APP.h.bd=$APP.ae;$APP.h.cd=function(a,b){return 0<=b&&b<this.D.length?new $APP.wf(b,b5(this.D[b],this.ga,this.S,this.transform),null):null};$APP.h.toString=function(){return $APP.Ud(this)};$APP.h.equiv=function(a){return this.P(null,a)};
$APP.h.indexOf=function(){var a=null;a=function(b,c){switch(arguments.length){case 1:return Y4(this,b,0);case 2:return Y4(this,b,c)}throw Error("Invalid arity: "+arguments.length);};a.h=function(b){return Y4(this,b,0)};a.j=function(b,c){return Y4(this,b,c)};return a}();
$APP.h.lastIndexOf=function(){var a=null;a=function(b,c){switch(arguments.length){case 1:return Z4(this,b,$APP.Ee(this));case 2:return Z4(this,b,c)}throw Error("Invalid arity: "+arguments.length);};a.h=function(b){return Z4(this,b,$APP.Ee(this))};a.j=function(b,c){return Z4(this,b,c)};return a}();$APP.h.sa=function(a,b){return this.W(null,b,null)};$APP.h.W=function(a,b,c){return typeof b==="number"?this.ub(null,b,c):c};
$APP.h.Ib=function(a,b,c){a=0;for(var d=c;;)if(a<this.D.length){c=this.D.length;var e;a:{for(e=0;;)if(e<c){var f=e+a,g=b5(this.D[e],this.ga,this.S,this.transform);d=b.l?b.l(d,f,g):b.call(null,d,f,g);if($APP.we(d)){e=d;break a}e+=1}else{e=d;break a}e=void 0}if($APP.we(e))return $APP.zc(e);a+=c;d=e}else return d};$APP.h.R=function(a,b){if(0<=b&&b<this.D.length)return b5(this.D[b],this.ga,this.S,this.transform);throw Error("No item "+$APP.H.h(b)+" in vector of length "+$APP.H.h(this.D.length));};
$APP.h.ub=function(a,b,c){return 0<=b&&b<this.D.length?b5(this.D[b],this.ga,this.S,this.transform):c};$APP.h.Y=function(a,b,c){return $APP.Aj(b,$APP.Fj,"["," ","]",c,this)};$APP.h.Nc=function(a,b,c){if(0<=b&&b<this.D.length)return g5(c,!0)?(a=$APP.Mb(this.D),a[b]=c5(c),new a5(this.I,this.ga,this.S,this.transform,a,null)):$APP.xc(e5(this.D),b,c);if(b===this.D.length)return this.la(null,c);throw Error("Index "+$APP.H.h(b)+" out of bounds  [0,"+$APP.H.h(this.D.length)+"]");};
$APP.h.nb=function(){return new mWa(this.ga,this.S,this.transform,this.D,this.D.length)};$APP.h.U=function(){return this.I};$APP.h.ib=function(){return new a5(this.I,this.ga,this.S,this.transform,this.D,this.H)};$APP.h.ha=function(){return this.D.length};$APP.h.td=function(){return this.D.length>0?this.R(null,this.D.length-1):null};
$APP.h.ud=function(){if(this.D.length===0)throw Error("Can't pop empty vector");if(1===this.D.length)return this.Ia(null);var a=$APP.Mb(this.D);return new a5(this.I,this.ga,this.S,this.transform,a.slice(0,a.length-1),null)};$APP.h.sd=function(){return this.D.length>0?new $APP.Je(this,this.D.length-1,null):null};$APP.h.ea=function(){var a=this.H;return a!=null?a:this.H=a=$APP.pe(this)};
$APP.h.P=function(a,b){a:if(b instanceof a5)if(this.D.length===$APP.Ee(b)){a=this.nb(null);for(b=$APP.Rd(b);;){if(a.hasNext()){var c=a.next(),d=b.next();if($APP.Fe.j(c,d))continue;else{a=!1;break a}}else{a=!0;break a}break}a=void 0}else a=!1;else a=cWa(this,b);return a};$APP.h.Vd=function(){return new lWa($APP.Mb(this.D),this.ga,this.S,this.transform)};$APP.h.Ia=function(){return new a5(this.I,this.ga,this.S,this.transform,[],null)};$APP.h.vb=function(a,b){return dWa(this,b)};
$APP.h.sb=function(a,b,c){return eWa(this,b,c)};$APP.h.pa=function(a,b,c){if(typeof b==="number")a=this.Nc(null,b,c);else throw Error("Vector's key for assoc must be a number.");return a};$APP.h.Db=function(a,b){return $APP.mf(b)?0<=b&&b<this.D.length:!1};$APP.h.ia=function(){return this.D.length>0?new i5(this.ga,this.S,this.transform,this.D,0,null):null};$APP.h.X=function(a,b){return b===this.I?this:new a5(b,this.ga,this.S,this.transform,this.D,this.H)};
$APP.h.la=function(a,b){return g5(b,!0)?(a=$APP.Mb(this.D),a[a.length]=c5(b),new a5(this.I,this.ga,this.S,this.transform,a,null)):$APP.Yb(e5(this.D),b)};$APP.h.call=function(a){switch(arguments.length-1){case 1:return this.h(arguments[1]);case 2:return this.j(arguments[1],arguments[2]);default:throw Error("Invalid arity: "+$APP.H.h(arguments.length-1));}};$APP.h.apply=function(a,b){return this.call.apply(this,[this].concat($APP.Mb(b)))};$APP.h.h=function(a){return this.R(null,a)};
$APP.h.j=function(a,b){return this.ub(null,a,b)};$APP.h.Mc=function(a,b){if($APP.ef(b)){a=$APP.Ee(this);var c=$APP.Ee(b);if(a<c)b=-1;else if(a>c)b=1;else if(a===0)b=0;else a:{for(c=0;;){var d=$APP.yf($APP.w.j(this,c),$APP.w.j(b,c));if(d===0&&c+1<a)c+=1;else{b=d;break a}}b=void 0}return b}throw Error("Cannot compare "+$APP.H.h(this)+" to "+$APP.H.h(b));};
var l5=function l5(a){switch(arguments.length){case 0:return l5.A();case 1:return l5.h(arguments[0]);default:for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return l5.o(arguments[0],1<c.length?new $APP.ie(c.slice(1),0,null):null)}};l5.A=function(){return new $4(null,{},$APP.Gj,j5,null,!1,[],0,null)};l5.h=function(a){return new $4(null,a,$APP.Gj,j5,null,!1,null,null,null)};
l5.o=function(a,b){var c=$APP.Bg(b);b=$APP.y.j(c,$APP.MD);var d=$APP.y.j(c,pWa),e=$APP.y.j(c,nWa),f=$APP.y.j(c,rWa);c=$APP.y.j(c,$APP.kE);return b===!1?new $4(null,a,$APP.Hf,$APP.Hf,f,$APP.rb(c),null,null,null):d!=null&&e!=null?new $4(null,a,d,e,f,$APP.rb(c),null,null,null):new $4(null,a,$APP.Gj,j5,f,$APP.rb(c),null,null,null)};l5.B=function(a){var b=$APP.p(a);a=$APP.r(a);return this.o(b,a)};l5.v=1;
var d5=function d5(a){switch(arguments.length){case 1:return d5.h(arguments[0]);default:for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return d5.o(arguments[0],1<c.length?new $APP.ie(c.slice(1),0,null):null)}};d5.h=function(a){return b5(a,$APP.Gj,j5,null)};d5.o=function(a,b){var c=$APP.Bg(b);b=$APP.y.j(c,$APP.MD);var d=$APP.y.j(c,pWa),e=$APP.y.j(c,nWa);c=$APP.y.j(c,rWa);return b===!1?b5(a,$APP.Hf,$APP.Hf,c):d!=null&&e!=null?b5(a,d,e,c):b5(a,$APP.Gj,j5,c)};
d5.B=function(a){var b=$APP.p(a);a=$APP.r(a);return this.o(b,a)};d5.v=1;var m5=function m5(a){switch(arguments.length){case 1:return m5.h(arguments[0]);default:for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return m5.o(arguments[0],1<c.length?new $APP.ie(c.slice(1),0,null):null)}};m5.h=function(a){return a instanceof $4?a.ra:a instanceof a5?a.D:$APP.KD.o(a,$APP.x([$APP.LD,j5],0))};
m5.o=function(a,b){if(a instanceof $4)return a.ra;if(a instanceof a5)return a.D;b=$APP.Bg(b);b=$APP.y.l(b,nWa,j5);return $APP.KD.o(a,$APP.x([$APP.LD,b],0))};m5.B=function(a){var b=$APP.p(a);a=$APP.r(a);return this.o(b,a)};m5.v=1;var n5=$APP.vY.j($APP.yK,null),uWa=new $APP.G(null,5,[qWa,$APP.bt(l5,qWa,new $APP.G(null,7,[$APP.P,qWa,$APP.O,"Takes a JavaScript object and returns a read-only implementation of the map\n  abstraction backed by the object.\n\n  By default, bean produces beans that keywordize the keys. Supply\n  :keywordize-keys false to suppress this behavior. You can alternatively\n  supply :prop-\x3ekey and :key-\x3eprop with functions that control the mapping\n  between properties and keys.\n\n  Supply :recursive true to create a bean which recursively converts\n  JavaScript object values to beans and JavaScript arrays into vectors.\n\n  Supply :transform and a function of one argument to transform values being\n  converted from JavaScript to ClojureScript. This function should return nil\n  if no conversion is to be performed, thus allowing default logic to be applied.\n\n  Calling (bean) produces an empty bean.",
$APP.X,$APP.I($APP.sh,new $APP.D(null,1,5,$APP.E,[$APP.FQ],null),new $APP.D(null,3,5,$APP.E,[$APP.FQ,$APP.Mk,$APP.$M],null)),$APP.J,"cljs_bean/core.cljs",$APP.K,702,$APP.M,7,$APP.S,n5],null),n5),oWa,$APP.bt(function(a){return a instanceof $4},oWa,new $APP.G(null,7,[$APP.P,oWa,$APP.O,"Returns true if x is a bean.",$APP.X,$APP.I(new $APP.D(null,1,5,$APP.E,[$APP.FQ],null)),$APP.J,"cljs_bean/core.cljs",$APP.K,735,$APP.M,7,$APP.S,n5],null),n5),$APP.zP,$APP.bt(function(a){return a.ra},$APP.zP,new $APP.G(null,
8,[$APP.P,$APP.zP,$APP.O,"Takes a bean and returns a JavaScript object.",$APP.X,$APP.I(new $APP.D(null,1,5,$APP.E,[$APP.lQ],null)),$APP.dn,$APP.LH,$APP.J,"cljs_bean/core.cljs",$APP.K,740,$APP.M,11,$APP.S,n5],null),n5),tWa,$APP.bt(m5,tWa,new $APP.G(null,7,[$APP.P,tWa,$APP.O,"Recursively converts ClojureScript values to JavaScript.\n\n  Where possible, directly returns the backing objects and arrays for values\n  produced using -\x3eclj and bean.\n\n  Otherwise delegates to clj-\x3ejs to perform the conversion, converting keyword\n  keys using their qualified names. You can alternatively supply :key-\x3eprop with\n  a function that controls the mapping from keys to properties.",
$APP.X,$APP.I(new $APP.D(null,1,5,$APP.E,[$APP.FQ],null),new $APP.D(null,3,5,$APP.E,[$APP.FQ,$APP.Mk,$APP.$M],null)),$APP.J,"cljs_bean/core.cljs",$APP.K,775,$APP.M,7,$APP.S,n5],null),n5),sWa,$APP.bt(d5,sWa,new $APP.G(null,7,[$APP.P,sWa,$APP.O,"Recursively converts JavaScript values to ClojureScript.\n\n  JavaScript objects are converted to beans with keywords for keys.\n\n  JavaScript arrays are converted to read-only implementations of the vector\n  abstraction, backed by the supplied array.\n\n  By default, -\x3eclj produces values that keywordize the keys. Supply\n  :keywordize-keys false to suppress this behavior. You can alternatively\n  supply :prop-\x3ekey and :key-\x3eprop with functions that control the mapping\n  between properties and keys.\n\n  Supply :transform and a function of one argument to transform values being\n  converted from JavaScript to ClojureScript. This function should return nil\n  if no conversion is to be performed, thus allowing default logic to be applied.",
$APP.X,$APP.I(new $APP.D(null,1,5,$APP.E,[$APP.FQ],null),new $APP.D(null,3,5,$APP.E,[$APP.FQ,$APP.Mk,$APP.$M],null)),$APP.J,"cljs_bean/core.cljs",$APP.K,745,$APP.M,7,$APP.S,n5],null),n5)],null);$APP.kA(new $APP.G(null,1,[$APP.yt,new $APP.G(null,1,[$APP.yK,uWa],null)],null));