import { $APP, shadow$provide } from "./nbb_core.js";
import "./nbb_api.js";
import "./nbb_impl_main.js";
const shadow_esm_import = function(x) { return import(x) };
import*as esm_import$node_process from"node:process";import*as esm_import$node_path from"node:path";
var aUa=function(a){a=$APP.Lj.h(a);var b=$APP.hg(a)?$APP.Lj.j(""+$APP.G.h(a),"-main"):a,c=$APP.fg(b);return $APP.pl("(require '$1) (apply $2 *command-line-args*)",/\$(\d)/,function(d){d=$APP.Ke(d);switch(d){case "1":return c;case "2":return b;default:throw Error("No matching clause: "+$APP.G.h(d));}})},bUa=function(a){var b=$APP.Lj.h(a),c=$APP.fg(b);return $APP.pl("\n(require '[babashka.cli])\n(require '$1)\n(let [the-var (resolve '$2)\n      the-var-meta (meta the-var)\n      ns (:ns (meta the-var))\n      ns-meta (meta ns)\n      cli-opts (babashka.cli/merge-opts (:org.babashka/cli ns-meta)\n                                        (:org.babashka/cli the-var-meta))\n      opts (babashka.cli/parse-opts *command-line-args* cli-opts)]\n  (the-var opts))\n",/\$(\d)/,
function(d){d=$APP.Ke(d);switch(d){case "1":return c;case "2":return b;default:throw Error("No matching clause: "+$APP.G.h(d));}})},cUa=function(a){for(var b=$APP.Ag,c=a;;){if($APP.k(c)){var d=$APP.p(c);a=$APP.q(c);switch(d){case "--help":case "-h":return $APP.Wi.l(b,$APP.$p,!0);case "--version":case "-v":return $APP.Wi.l(b,$APP.jRa,!0);case "-e":b=$APP.Wi.l(b,$APP.or,$APP.p(a));c=a=$APP.q(a);continue;case "-m":case "--main":return $APP.Wi.o(b,$APP.or,aUa($APP.p(a)),$APP.x([$APP.vo,$APP.q(a)],0));
case "-x":case "--exec":return $APP.Wi.o(b,$APP.or,bUa($APP.p(a)),$APP.x([$APP.vo,$APP.q(a)],0));case "-cp":case "--classpath":b=$APP.Wi.l(b,$APP.XZ,$APP.p(a));c=a=$APP.q(a);continue;case "--config":b=$APP.Wi.l(b,$APP.oz,$APP.p(a));c=a=$APP.q(a);continue;case "--debug":b=$APP.Wi.l(b,$APP.cz,!0);c=a;continue;case "nrepl-server":b=$APP.Wi.l(b,$APP.fRa,!0);c=a;continue;case "socket-repl":b=$APP.Wi.l(b,$APP.gRa,!0);c=a;continue;case ":port":case "--port":b=$APP.Wi.l(b,$APP.oM,$APP.p(a));c=a=$APP.q(a);
continue;case ":host":case "--host":b=$APP.Wi.l(b,$APP.yU,$APP.p(a));c=a=$APP.q(a);continue;case "repl":b=$APP.Wi.l(b,$APP.iRa,!0);c=a;continue;case "bundle":return $APP.Wi.l(b,$APP.zQ,$APP.xp.j(a,new $APP.F(null,1,[$APP.qo,new $APP.F(null,2,[$APP.kRa,$APP.iAa,$APP.aq,$APP.$p],null)],null)));default:if($APP.Ab($APP.or.h(c)))return $APP.Wi.o(b,$APP.hRa,d,$APP.x([$APP.vo,$APP.q(c)],0));throw $APP.vm.j("Unrecognized options:"+$APP.G.h(c),$APP.Ag);}}else return b;break}};if($APP.k(esm_import$node_process.on))esm_import$node_process.on("unhandledRejection",function(a){console.error($APP.Jk(a));return process.exitCode=1});(function(){var a=$APP.n(function(){var g=globalThis.nbb_args;return $APP.k(g)?g:esm_import$node_process.argv}());$APP.p(a);a=$APP.q(a);$APP.p(a);a=$APP.q(a);var b=cUa(a);$APP.$g($APP.lRa,b);var c=$APP.hRa.h(b),d=$APP.or.h(b);a=$APP.XZ.h(b);$APP.k(a)&&$APP.Yr(a);a=$APP.fRa.h(b);var e=function(){var g=$APP.iRa.h(b);if($APP.k(g))return g;g=$APP.gRa.h(b);return $APP.k(g)?g:$APP.We($APP.lm.o(b,$APP.XZ,$APP.x([$APP.cz,$APP.oz],0)))}(),f=$APP.zQ.h(b);$APP.k($APP.$p.h(b))&&($APP.Dp.o($APP.x([$APP.qaa("nbb"),
"version:",$APP.Lz()],0)),$APP.Dp.o($APP.x(["\nHelp:\n\n -h / --help: print this help text and exit.\n -v / --version: print the current version of nbb.\n\nGlobal options:\n\n --debug: print additional debug info.\n -cp / --classpath: set the classpath.\n\nEvaluation:\n\n -e: execute expression\n -m / --main: execute main function\n -x / --exec: execute function using babashka.cli\n\nREPL:\n\n repl: start console REPL.\n nrepl-server: start nrepl server. [1,2]\n socket-repl: start socket repl server. [1]\n\n 1: Provide :port \x3cport\x3e to specify port\n 2: Provide :host \x3chost\x3e to specify host\n\nTooling:\n\n  bundle: produce single JS file for usage with bundlers.\n"],
0)),esm_import$node_process.exit(0));$APP.k($APP.jRa.h(b))&&($APP.Dp.o($APP.x([""+$APP.G.h("nbb")+" v"+$APP.G.h($APP.Lz())],0)),esm_import$node_process.exit(0));return $APP.k($APP.k(c)?c:$APP.k(d)?d:$APP.k(a)?a:$APP.k(e)?e:f)?($APP.ZX.j($APP.FEa,$APP.Yg($APP.vo.h(b))),Promise.resolve($APP.TZ($APP.k(e)?esm_import$node_path.resolve("script.cljs"):c,b)).then(function(){return($APP.k(c)?$APP.YZ.h(c):$APP.k(d)?$APP.ZZ.h(d):$APP.k($APP.fRa.h(b))?shadow_esm_import("./nbb_nrepl_server.js").then(function(){var g=
$APP.y.j($APP.y.j($APP.wt.h($APP.xe($APP.rt.h($APP.os()))),$APP.qE),$APP.WZ);return g.h?g.h(b):g.call(null,b)}):$APP.k($APP.k(e)?$APP.gRa.h(b):e)?shadow_esm_import("./nbb_repl.js").then(function(){var g=new $APP.F(null,1,[$APP.oM,$APP.oM.h(b)],null),m=$APP.y.j($APP.y.j($APP.wt.h($APP.xe($APP.rt.h($APP.os()))),$APP.$C),$APP.UZ);return m.h?m.h(g):m.call(null,g)}):$APP.k($APP.zQ.h(b))?shadow_esm_import("./nbb_bundler.js"):$APP.k(e)?shadow_esm_import("./nbb_repl.js").then(function(){var g=$APP.y.j($APP.y.j($APP.wt.h($APP.xe($APP.rt.h($APP.os()))),
$APP.$C),$APP.VZ);return g.A?g.A():g.call(null)}):null).then(function(g){$APP.k($APP.k(d)?g!=null:d)&&$APP.bz.o($APP.x([g],0));return g}).catch(function(g){$APP.Zma(g,b);$APP.k($APP.cz.h(b))&&console.error(g);throw Error($APP.Jk(g));})})):console.error("Usage: "+$APP.G.h("nbb")+" \x3cscript\x3e or nbb -e \x3cexpr\x3e.")})();