import { $APP, shadow$provide } from "./nbb_core.js";
const shadow_esm_import = function(x) { return import(x) };
var NFa=function(a,b){b&=63;if(b==0)return a;var c=a.kb;return b<32?$APP.ua(a.Eb>>>b|c<<32-b,c>>>b):b==32?$APP.ua(c,0):$APP.ua(c>>>b-32,0)},FY=function(){return Math.round(Math.random()*15).toString(16)},OFa=function(a,b){if(a.length>3){if(b)return!0;b=a.charAt(1);return a.charAt(0)==="~"?b===":"||b==="$"||b==="#":!1}return!1},PFa=function(a){var b=Math.floor(a/44);a=String.fromCharCode(a%44+48);return b===0?"^"+a:"^"+String.fromCharCode(b+48)+a},GY=function(){this.Cj=this.Df=this.ob=0;this.cache=
{}},HY=function(){this.ob=0;this.cache=[]},JY=function(a,b){if(a==null)return b==null;if(a===b)return!0;if(typeof a==="object"){if(IY(a)){if(IY(b)&&a.length===b.length){for(var c=0;c<a.length;c++)if(!JY(a[c],b[c]))return!1;return!0}return!1}if(a.gd)return a.gd(b);if(b!=null&&typeof b==="object"){if(b.gd)return b.gd(a);c=0;var d=KY(b).length,e;for(e in a)if(a.hasOwnProperty(e)&&(c++,!b.hasOwnProperty(e)||!JY(a[e],b[e])))return!1;return c===d}}return!1},LY=function(a,b){return a^b+2654435769+(a<<6)+
(a>>2)},NY=function(a){var b=0;if(a.forEach!=null)a.forEach(function(g,m){b=(b+(MY(m)^MY(g)))%4503599627370496});else for(var c=KY(a),d=0;d<c.length;d++){var e=c[d],f=a[e];b=(b+(MY(e)^MY(f)))%4503599627370496}return b},QFa=function(a){var b=0;if(IY(a))for(var c=0;c<a.length;c++)b=LY(b,MY(a[c]));else a.forEach&&a.forEach(function(d){b=LY(b,MY(d))});return b},MY=function(a){if(a==null)return 0;switch(typeof a){case "number":return a;case "boolean":return a===!0?1:0;case "string":var b=OY[a];if(b!=null)a=
b;else{for(var c=b=0;c<a.length;++c)b=31*b+a.charCodeAt(c),b%=4294967296;PY++;PY>=256&&(OY={},PY=1);a=OY[a]=b}return a;case "function":return b=a.transit$hashCode$,b||(b=RFa,typeof Object.defineProperty!="undefined"?Object.defineProperty(a,"transit$hashCode$",{value:b,enumerable:!1}):a.transit$hashCode$=b,RFa++),b;default:return a instanceof Date?a.valueOf():IY(a)?QFa(a):a.yd?a.yd():NY(a)}},QY=function(a,b){this.tag=a;this.rep=b;this.Ab=-1},RY=function(a,b){return new QY(a,b)},UFa=function(a){if(typeof a===
"number"||a instanceof $APP.ta)return a;a=$APP.Aa(a,10);return a.compare(SFa)>0||a.compare(TFa)<0?a:$APP.Ba(a)},SY=function(a){this.Nb=a;this.Ab=-1},TY=function(a){this.Nb=a;this.Ab=-1},UY=function(a,b,c){var d="";c=c||b+1;for(var e=(7-b)*8,f=$APP.faa(255).shiftLeft(e);b<c;b++,e-=8,f=NFa(f,8)){var g=NFa(a.and(f),e).toString(16);g.length==1&&(g="0"+g);d+=g}return d},VY=function(a,b){this.high=a;this.low=b;this.Ab=-1},WY=function(a,b){this.entries=a;this.type=b||0;this.ob=0},XY=function(a,b){this.map=
a;this.type=b||0;this.keys=this.map.Fe();this.ob=0;this.pe=null;this.fe=0},$Y=function(a,b){if(a instanceof YY&&(b instanceof ZY||b instanceof YY)){if(a.size!==b.size)return!1;for(var c in a.map)for(var d=a.map[c],e=0;e<d.length;e+=2)if(!JY(d[e+1],b.get(d[e])))return!1;return!0}if(a instanceof ZY&&(b instanceof ZY||b instanceof YY)){if(a.size!==b.size)return!1;a=a.Cb;for(e=0;e<a.length;e+=2)if(!JY(a[e+1],b.get(a[e])))return!1;return!0}if(b!=null&&typeof b==="object"&&(e=KY(b),c=e.length,a.size===
c)){for(d=0;d<c;d++){var f=e[d];if(!a.has(f)||!JY(b[f],a.get(f)))return!1}return!0}return!1},VFa=function(a){return a==null?"null":$APP.ca(a)==="array"?"["+a.toString()+"]":$APP.ca(a)==="string"?'"'+a+'"':a.toString()},WFa=function(a){var b=0,c="TransitMap {";a.forEach(function(d,e){c+=VFa(e)+" \x3d\x3e "+VFa(d);b<a.size-1&&(c+=", ");b++});return c+"}"},XFa=function(a){var b=0,c="TransitSet {";a.forEach(function(d){c+=VFa(d);b<a.size-1&&(c+=", ");b++});return c+"}"},ZY=function(a){this.Cb=a;this.Bb=
null;this.Ab=-1;this.size=a.length/2;this.Hh=0},YFa=function(a){if(a.Bb)throw Error("Invalid operation, already converted");if(a.size<8)return!1;a.Hh++;return a.Hh>32?(a.Bb=aZ(a.Cb,!1,!0),a.Cb=[],!0):!1},YY=function(a,b,c){this.map=b||{};this.Se=a||[];this.size=c||0;this.Ab=-1},aZ=function(a,b,c){a=a||[];b=b===!1?b:!0;if((c!==!0||!c)&&a.length<=64){if(b){var d=a;a=[];for(b=0;b<d.length;b+=2){var e=!1;for(c=0;c<a.length;c+=2)if(JY(a[c],d[b])){a[c+1]=d[b+1];e=!0;break}e||(a.push(d[b]),a.push(d[b+1]))}}return new ZY(a)}d=
{};e=[];var f=0;for(b=0;b<a.length;b+=2){c=MY(a[b]);var g=d[c];if(g==null)e.push(c),d[c]=[a[b],a[b+1]],f++;else{var m=!0;for(c=0;c<g.length;c+=2)if(JY(g[c],a[b])){g[c+1]=a[b+1];m=!1;break}m&&(g.push(a[b]),g.push(a[b+1]),f++)}}return new YY(e,d,f)},bZ=function(a){this.map=a;this.size=a.size},ZFa=function(a){a=a||[];for(var b={},c=[],d=0,e=0;e<a.length;e++){var f=MY(a[e]),g=b[f];if(g==null)c.push(f),b[f]=[a[e],a[e]],d++;else{f=!0;for(var m=0;m<g.length;m+=2)if(JY(g[m],a[e])){f=!1;break}f&&(g.push(a[e]),
g.push(a[e]),d++)}}return new bZ(new YY(c,b,d))},$Fa=function(a){this.uc=a},cZ=function(a){this.options=a||{};this.Zb={};for(var b in this.Af.Zb)this.Zb[b]=this.Af.Zb[b];for(b in this.options.handlers){a:{switch(b){case "_":case "s":case "?":case "i":case "d":case "b":case "'":case "array":case "map":a=!0;break a}a=!1}if(a)throw Error('Cannot override handler for ground type "'+b+'"');this.Zb[b]=this.options.handlers[b]}this.Dg=this.options.preferStrings!=null?this.options.preferStrings:this.Af.Dg;
this.wh=this.options.preferBuffers!=null?this.options.preferBuffers:this.Af.wh;this.qh=this.options.defaultHandler||this.Af.qh;this.md=this.options.mapBuilder;this.Te=this.options.arrayBuilder},aGa=function(a,b,c,d,e){if(e){var f=[];for(e=0;e<b.length;e++)f.push(a.decode(b[e],c,d,!1));return f}f=c&&c.ob;if(b.length===2&&typeof b[0]==="string"&&(e=a.decode(b[0],c,!1,!1))&&e instanceof $Fa)return b=b[1],f=a.Zb[e.uc],f!=null?f=f(a.decode(b,c,d,!0),a):RY(e.uc,a.decode(b,c,d,!1));c&&f!=c.ob&&(c.ob=f);
if(a.Te){if(b.length<=32&&a.Te.fromArray){f=[];for(e=0;e<b.length;e++)f.push(a.decode(b[e],c,d,!1));return a.Te.fromArray(f,b)}f=a.Te.init(b);for(e=0;e<b.length;e++)f=a.Te.add(f,a.decode(b[e],c,d,!1),b);return a.Te.finalize(f,b)}f=[];for(e=0;e<b.length;e++)f.push(a.decode(b[e],c,d,!1));return f},bGa=function(a,b){if(b.charAt(0)==="~"){var c=b.charAt(1);if(c==="~"||c==="^"||c==="`")return b.substring(1);if(c==="#")return new $Fa(b.substring(2));var d=a.Zb[c];return d==null?a.qh(c,b.substring(2)):d(b.substring(2),
a)}return b},cGa=function(a){this.$j=new cZ(a)},dZ=function(a,b){this.tl=a;this.options=b||{};this.cache=this.options.cache?this.options.cache:new HY},fGa=function(a){if(a==null)return"null";if(a===String)return"string";if(a===Boolean)return"boolean";if(a===Number)return"number";if(a===Array)return"array";if(a===Object)return"map";var b=a[dGa];b==null&&(typeof Object.defineProperty!="undefined"?(b=++eGa,Object.defineProperty(a,dGa,{value:b,enumerable:!1})):a[dGa]=b=++eGa);return b},eZ=function(a,
b){a=a.toString();for(var c=a.length;c<b;c++)a="0"+a;return a},fZ=function(){},gZ=function(){},hZ=function(){},iZ=function(){},jZ=function(){},kZ=function(){},lZ=function(){},mZ=function(){},nZ=function(){},oZ=function(){},pZ=function(){},qZ=function(){},rZ=function(){},sZ=function(){},tZ=function(){},uZ=function(){},vZ=function(){},wZ=function(){},xZ=function(){this.Zb={};this.set(null,new fZ);this.set(String,new gZ);this.set(Number,new hZ);this.set($APP.ta,new iZ);this.set(Boolean,new jZ);this.set(Array,
new kZ);this.set(Object,new lZ);this.set(Date,new nZ);this.set(VY,new oZ);this.set(SY,new pZ);this.set(TY,new qZ);this.set(QY,new rZ);this.set(bZ,new sZ);this.set(ZY,new tZ);this.set(YY,new uZ);typeof $APP.kz.Rg!="undefined"&&this.set($APP.kz.Rg,new vZ);typeof Uint8Array!="undefined"&&this.set(Uint8Array,new wZ)},gGa=function(a){this.Jc=a||{};this.Dg=this.Jc.preferStrings!=null?this.Jc.preferStrings:!0;this.ti=this.Jc.objectBuilder||null;this.transform=this.Jc.transform||null;this.Zb=new xZ;if(a=
this.Jc.handlers){if(IY(a)||!a.forEach)throw Error('transit writer "handlers" option must be a map');var b=this;a.forEach(function(c,d){if(d!==void 0)b.Zb.set(d,c);else throw Error("Cannot create handler for JavaScript undefined");})}this.Ef=this.Jc.handlerForForeign;this.Ng=this.Jc.unpack||function(c){return c instanceof ZY&&c.Bb===null?c.Cb:!1};this.Wf=this.Jc&&this.Jc.verbose||!1},hGa=function(a,b){var c=a.Zb.get(b==null?null:b.constructor);return c!=null?c:(b=b&&b.transitTag)?a.Zb.get(b):null},
zZ=function(a,b,c,d,e){a=a+b+c;return e?e.write(a,d):a},iGa=function(a,b,c){var d=[];if(IY(b))for(var e=0;e<b.length;e++)d.push(AZ(a,b[e],!1,c));else b.forEach(function(f){d.push(AZ(a,f,!1,c))});return d},jGa=function(a,b){return typeof b!=="string"?(a=hGa(a,b))&&a.tag(b).length===1:!0},kGa=function(a,b){var c=a.Ng(b),d=!0;if(c){for(b=0;b<c.length&&(d=jGa(a,c[b]),d);b+=2);return d}if(b.keys){c=b.keys();var e=null;if(c.next){for(e=c.next();!e.done;){d=jGa(a,e.value);if(!d)break;e=c.next()}return d}}if(b.forEach)return b.forEach(function(f,
g){d=d&&jGa(a,g)}),d;throw Error("Cannot walk keys of object type "+(b==null?null:b.constructor).name);},lGa=function(a){if(a.constructor.transit$isObject)return!0;var b=a.constructor.toString();b=b.substr(9);b=b.substr(0,b.indexOf("("));b=b=="Object";typeof Object.defineProperty!="undefined"?Object.defineProperty(a.constructor,"transit$isObject",{value:b,enumerable:!1}):a.constructor.transit$isObject=b;return b},mGa=function(a,b,c){var d=null,e=null,f=null;d=null;var g=0;if(b.constructor===Object||
b.forEach!=null||a.Ef&&lGa(b)){if(a.Wf){if(b.forEach!=null)if(kGa(a,b)){var m={};b.forEach(function(r,t){m[AZ(a,t,!0,!1)]=AZ(a,r,!1,c)})}else{d=a.Ng(b);e=[];f=zZ("~#","cmap","",!0,c);if(d)for(;g<d.length;g+=2)e.push(AZ(a,d[g],!1,!1)),e.push(AZ(a,d[g+1],!1,c));else b.forEach(function(r,t){e.push(AZ(a,t,!1,!1));e.push(AZ(a,r,!1,c))});m={};m[f]=e}else for(d=KY(b),m={};g<d.length;g++)m[AZ(a,d[g],!0,!1)]=AZ(a,b[d[g]],!1,c);return m}if(b.forEach!=null){if(kGa(a,b)){d=a.Ng(b);m=["^ "];if(d)for(;g<d.length;g+=
2)m.push(AZ(a,d[g],!0,c)),m.push(AZ(a,d[g+1],!1,c));else b.forEach(function(r,t){m.push(AZ(a,t,!0,c));m.push(AZ(a,r,!1,c))});return m}d=a.Ng(b);e=[];f=zZ("~#","cmap","",!0,c);if(d)for(;g<d.length;g+=2)e.push(AZ(a,d[g],!1,c)),e.push(AZ(a,d[g+1],!1,c));else b.forEach(function(r,t){e.push(AZ(a,t,!1,c));e.push(AZ(a,r,!1,c))});return[f,e]}m=["^ "];for(d=KY(b);g<d.length;g++)m.push(AZ(a,d[g],!0,c)),m.push(AZ(a,b[d[g]],!1,c));return m}if(a.ti!=null)return a.ti(b,function(r){return AZ(a,r,!0,c)},function(r){return AZ(a,
r,!1,c)});g=(b==null?null:b.constructor).name;d=Error("Cannot write "+g);d.data={ra:b,type:g};throw d;},AZ=function(a,b,c,d){a.transform!==null&&(b=a.transform(b));var e=hGa(a,b)||(a.Ef?a.Ef(b,a.Zb):null),f=e?e.tag(b):null,g=e?e.rep(b):null;if(e!=null&&f!=null)switch(f){case "_":return c?zZ("~","_","",c,d):null;case "s":return g.length>0?(a=g.charAt(0),a=a==="~"||a==="^"||a==="`"?"~"+g:g):a=g,zZ("","",a,c,d);case "?":return c?zZ("~","?",g.toString()[0],c,d):g;case "i":return g===Infinity?zZ("~","z",
"INF",c,d):g===-Infinity?zZ("~","z","-INF",c,d):isNaN(g)?zZ("~","z","NaN",c,d):c||typeof g==="string"||g instanceof $APP.ta?zZ("~","i",g.toString(),c,d):g;case "d":return c?zZ(g.zl,"d",g,c,d):g;case "b":return zZ("~","b",g,c,d);case "'":return a.Wf?(c={},b=zZ("~#","'","",!0,d),c[b]=AZ(a,g,!1,d),d=c):d=[zZ("~#","'","",!0,d),AZ(a,g,!1,d)],d;case "array":return iGa(a,g,d);case "map":return mGa(a,g,d);default:a:{if(f.length===1){if(typeof g==="string"){d=zZ("~",f,g,c,d);break a}if(c||a.Dg){(a=a.Wf&&e.getVerboseHandler())?
(f=a.tag(b),g=a.stringRep(b,a)):g=e.stringRep(b,e);if(g!==null){d=zZ("~",f,g,c,d);break a}d=Error('Tag "'+f+'" cannot be encoded as string');d.data={tag:f,rep:g,ra:b};throw d;}}c=f;b=g;a.Wf?(e={},e[zZ("~#",c,"",!0,d)]=AZ(a,b,!1,d),d=e):d=[zZ("~#",c,"",!0,d),AZ(a,b,!1,d)]}return d}else throw d=(b==null?null:b.constructor).name,a=Error("Cannot write "+d),a.data={ra:b,type:d},a;},BZ=function(a,b){this.jf=a;this.options=b||{};this.cache=this.options.cache===!1?null:this.options.cache?this.options.cache:
new GY},nGa=function(a,b){if(a==="json"||a==="json-verbose"||a==null)return a=new cGa(b),new dZ(a,b);throw Error("Cannot create reader of type "+a);},oGa=function(a,b){if(a==="json"||a==="json-verbose"||a==null)return a==="json-verbose"&&(b==null&&(b={}),b.verbose=!0),a=new gGa(b),new BZ(a,b);b=Error('Type must be "json"');b.data={type:a};throw b;},pGa=function(a,b){for(var c=$APP.n($APP.Va(b)),d=null,e=0,f=0;;)if(f<e){var g=d.R(null,f);a[g]=$APP.Xa(b,g);f+=1}else if(c=$APP.n(c))d=c,$APP.ef(d)?(c=
$APP.Ed(d),f=$APP.Fd(d),d=c,e=$APP.Ee(c),c=f):(c=$APP.p(d),a[c]=$APP.Xa(b,c),c=$APP.q(d),d=null,e=0),f=0;else break;return a},CZ=function(){},DZ=function(){},EZ=function(){},FZ=function(){},GZ=function(){},HZ=function(){},IZ=function(){},JZ=function(){},KZ=function(){},qGa=function(a,b){this.value=a;this.I=b},LZ=function(){},rGa=function(a,b,c,d,e){this.Mg=a;this.Fg=b;this.Vf=c;this.Xf=d;this.Fk=e;this.G=393216;this.K=0};$APP.ta.prototype.Ab=$APP.ba(0,function(){return this.Eb^this.kb});
var sGa=new $APP.l(null,"write-meta","write-meta",-1711397117,null),tGa=new $APP.l(null,"from-rep","from-rep",911750077,null),uGa=new $APP.l(null,"str-rep-fn","str-rep-fn",-1179615016,null),vGa=new $APP.l(null,"ListHandler","ListHandler",-856350412,null),MZ=new $APP.B(null,"handlers","handlers",79528781),wGa=new $APP.B(null,"arrayBuilder","arrayBuilder",1446317421),xGa=new $APP.B(null,"mapBuilder","mapBuilder",-278083754),yGa=new $APP.B(null,"preferStrings","preferStrings",-1532249482),zGa=new $APP.l(null,
"tag-fn","tag-fn",242055482,null),AGa=new $APP.l(null,"rep-fn","rep-fn",-1724891035,null),BGa=new $APP.l(null,"rep","rep",413710963,null),CGa=new $APP.l(null,"tagged-value","tagged-value",-110559503,null),DGa=new $APP.l(null,"write-handler","write-handler",-692059351,null),EGa=new $APP.B(null,"map-builder","map-builder",-1843343288),FGa=new $APP.B(null,"prefer-strings","prefer-strings",1254507185),GGa=new $APP.B(null,"array-builder","array-builder",1275998041),HGa=new $APP.l(null,"read-handler","read-handler",
1426618230,null),IGa=new $APP.B(null,"prefer-buffers","prefer-buffers",377042081),JGa=new $APP.l(null,"w","w",1994700528,null),KGa=new $APP.B(null,"preferBuffers","preferBuffers",1843176451),LGa=new $APP.l(null,"verbose-handler-fn","verbose-handler-fn",547340594,null),MGa=new $APP.l(null,"integer","integer",1035809817,null),NGa=new $APP.l(null,"write","write",-217117641,null);var KY=typeof Object.keys!="undefined"?function(a){return Object.keys(a)}:function(a){return $APP.Va(a)},IY=typeof Array.isArray!="undefined"?function(a){return Array.isArray(a)}:function(a){return $APP.ca(a)==="array"};GY.prototype.write=function(a,b){return OFa(a,b)?(this.Cj===4096?(this.clear(),this.Df=0,this.cache={}):this.ob===1936&&this.clear(),b=this.cache[a],b==null?(this.cache[a]=[PFa(this.ob),this.Df],this.ob++,a):b[1]!=this.Df?(b[1]=this.Df,b[0]=PFa(this.ob),this.ob++,a):b[0]):a};GY.prototype.clear=function(){this.ob=0;this.Df++};HY.prototype.write=function(a){this.ob==1936&&(this.ob=0);this.cache[this.ob]=a;this.ob++;return a};
HY.prototype.read=function(a){return this.cache[a.length===2?a.charCodeAt(1)-48:(a.charCodeAt(1)-48)*44+(a.charCodeAt(2)-48)]};HY.prototype.clear=function(){this.ob=0};var RFa=1,OY={},PY=0;var NZ=typeof Symbol!="undefined"?Symbol.iterator:"@@iterator";QY.prototype.toString=function(){return"[TaggedValue: "+this.tag+", "+this.rep+"]"};QY.prototype.equiv=function(a){return JY(this,a)};QY.prototype.equiv=QY.prototype.equiv;QY.prototype.gd=function(a){return a instanceof QY?this.tag===a.tag&&JY(this.rep,a.rep):!1};QY.prototype.yd=function(){this.Ab===-1&&(this.Ab=LY(MY(this.tag),MY(this.rep)));return this.Ab};var SFa=$APP.Aa("9007199254740991"),TFa=$APP.Aa("-9007199254740991");
$APP.ta.prototype.equiv=function(a){return JY(this,a)};$APP.ta.prototype.equiv=$APP.ta.prototype.equiv;$APP.ta.prototype.gd=function(a){return a instanceof $APP.ta&&$APP.Ea(this,a)};$APP.ta.prototype.yd=function(){return this.Eb};SY.prototype.toString=function(){return":"+this.Nb};SY.prototype.namespace=function(){var a=this.Nb.indexOf("/");return a!=-1?this.Nb.substring(0,a):null};SY.prototype.name=function(){var a=this.Nb.indexOf("/");return a!=-1?this.Nb.substring(a+1,this.Nb.length):this.Nb};
SY.prototype.equiv=function(a){return JY(this,a)};SY.prototype.equiv=SY.prototype.equiv;SY.prototype.gd=function(a){return a instanceof SY&&this.Nb==a.Nb};SY.prototype.yd=function(){this.Ab===-1&&(this.Ab=MY(this.Nb));return this.Ab};TY.prototype.namespace=function(){var a=this.Nb.indexOf("/");return a!=-1?this.Nb.substring(0,a):null};TY.prototype.name=function(){var a=this.Nb.indexOf("/");return a!=-1?this.Nb.substring(a+1,this.Nb.length):this.Nb};TY.prototype.toString=function(){return this.Nb};
TY.prototype.equiv=function(a){return JY(this,a)};TY.prototype.equiv=TY.prototype.equiv;TY.prototype.gd=function(a){return a instanceof TY&&this.Nb==a.Nb};TY.prototype.yd=function(){this.Ab===-1&&(this.Ab=MY(this.Nb));return this.Ab};VY.prototype.toString=function(){var a=this.high,b=this.low;var c=UY(a,0,4)+"-";c+=UY(a,4,6)+"-";c+=UY(a,6,8)+"-";c+=UY(b,0,2)+"-";return c+=UY(b,2,8)};VY.prototype.equiv=function(a){return JY(this,a)};VY.prototype.equiv=VY.prototype.equiv;
VY.prototype.gd=function(a){return a instanceof VY&&$APP.Ea(this.high,a.high)&&$APP.Ea(this.low,a.low)};VY.prototype.yd=function(){this.Ab===-1&&(this.Ab=MY(this.toString()));return this.Ab};Date.prototype.gd=function(a){return a instanceof Date?this.valueOf()===a.valueOf():!1};Date.prototype.yd=function(){return this.valueOf()};
WY.prototype.next=function(){if(this.ob<this.entries.length){var a={value:this.type===0?this.entries[this.ob]:this.type===1?this.entries[this.ob+1]:[this.entries[this.ob],this.entries[this.ob+1]],done:!1};this.ob+=2;return a}return{value:null,done:!0}};WY.prototype.next=WY.prototype.next;WY.prototype[NZ]=function(){return this};
XY.prototype.next=function(){if(this.ob<this.map.size){this.pe!=null&&this.fe<this.pe.length||(this.pe=this.map.map[this.keys[this.ob]],this.fe=0);var a={value:this.type===0?this.pe[this.fe]:this.type===1?this.pe[this.fe+1]:[this.pe[this.fe],this.pe[this.fe+1]],done:!1};this.ob++;this.fe+=2;return a}return{value:null,done:!0}};XY.prototype.next=XY.prototype.next;XY.prototype[NZ]=function(){return this};ZY.prototype.toString=function(){return WFa(this)};ZY.prototype.inspect=function(){return this.toString()};
ZY.prototype.clear=function(){this.Ab=-1;this.Bb?this.Bb.clear():this.Cb=[];this.size=0};ZY.prototype.clear=ZY.prototype.clear;ZY.prototype.keys=function(){return this.Bb?this.Bb.keys():new WY(this.Cb,0)};ZY.prototype.keys=ZY.prototype.keys;ZY.prototype.Ie=function(){if(this.Bb)return this.Bb.Ie();for(var a=[],b=0,c=0;c<this.Cb.length;b++,c+=2)a[b]=this.Cb[c];return a};ZY.prototype.keySet=ZY.prototype.Ie;ZY.prototype.entries=function(){return this.Bb?this.Bb.entries():new WY(this.Cb,2)};
ZY.prototype.entries=ZY.prototype.entries;ZY.prototype.values=function(){return this.Bb?this.Bb.values():new WY(this.Cb,1)};ZY.prototype.values=ZY.prototype.values;ZY.prototype.forEach=function(a){if(this.Bb)this.Bb.forEach(a);else for(var b=0;b<this.Cb.length;b+=2)a(this.Cb[b+1],this.Cb[b])};ZY.prototype.forEach=ZY.prototype.forEach;
ZY.prototype.get=function(a,b){if(this.Bb)return this.Bb.get(a);if(YFa(this))return this.get(a);for(var c=0;c<this.Cb.length;c+=2)if(JY(this.Cb[c],a))return this.Cb[c+1];return b};ZY.prototype.get=ZY.prototype.get;ZY.prototype.has=function(a){if(this.Bb)return this.Bb.has(a);if(YFa(this))return this.has(a);for(var b=0;b<this.Cb.length;b+=2)if(JY(this.Cb[b],a))return!0;return!1};ZY.prototype.has=ZY.prototype.has;
ZY.prototype.set=function(a,b){this.Ab=-1;if(this.Bb)this.Bb.set(a,b),this.size=this.Bb.size;else{for(var c=0;c<this.Cb.length;c+=2)if(JY(this.Cb[c],a)){this.Cb[c+1]=b;return}this.Cb.push(a);this.Cb.push(b);this.size++;this.size>32&&(this.Bb=aZ(this.Cb,!1,!0),this.Cb=null)}};ZY.prototype.set=ZY.prototype.set;
ZY.prototype["delete"]=function(a){this.Ab=-1;if(this.Bb)return a=this.Bb.delete(a),this.size=this.Bb.size,a;for(var b=0;b<this.Cb.length;b+=2)if(JY(this.Cb[b],a))return a=this.Cb[b+1],this.Cb.splice(b,2),this.size--,a};ZY.prototype.clone=function(){var a=aZ();this.forEach(function(b,c){a.set(c,b)});return a};ZY.prototype.clone=ZY.prototype.clone;ZY.prototype[NZ]=function(){return this.entries()};ZY.prototype.yd=function(){if(this.Bb)return this.Bb.yd();this.Ab===-1&&(this.Ab=NY(this));return this.Ab};
ZY.prototype.gd=function(a){return this.Bb?$Y(this.Bb,a):$Y(this,a)};YY.prototype.toString=function(){return WFa(this)};YY.prototype.inspect=function(){return this.toString()};YY.prototype.clear=function(){this.Ab=-1;this.map={};this.Se=[];this.size=0};YY.prototype.clear=YY.prototype.clear;YY.prototype.Fe=function(){return this.Se!=null?this.Se:KY(this.map)};
YY.prototype["delete"]=function(a){this.Ab=-1;this.Se=null;for(var b=MY(a),c=this.map[b],d=0;d<c.length;d+=2)if(JY(a,c[d]))return a=c[d+1],c.splice(d,2),c.length===0&&delete this.map[b],this.size--,a};YY.prototype.entries=function(){return new XY(this,2)};YY.prototype.entries=YY.prototype.entries;YY.prototype.forEach=function(a){for(var b=this.Fe(),c=0;c<b.length;c++)for(var d=this.map[b[c]],e=0;e<d.length;e+=2)a(d[e+1],d[e],this)};YY.prototype.forEach=YY.prototype.forEach;
YY.prototype.get=function(a,b){var c=MY(a);c=this.map[c];if(c!=null)for(b=0;b<c.length;b+=2){if(JY(a,c[b]))return c[b+1]}else return b};YY.prototype.get=YY.prototype.get;YY.prototype.has=function(a){var b=MY(a);b=this.map[b];if(b!=null)for(var c=0;c<b.length;c+=2)if(JY(a,b[c]))return!0;return!1};YY.prototype.has=YY.prototype.has;YY.prototype.keys=function(){return new XY(this,0)};YY.prototype.keys=YY.prototype.keys;
YY.prototype.Ie=function(){for(var a=this.Fe(),b=[],c=0;c<a.length;c++)for(var d=this.map[a[c]],e=0;e<d.length;e+=2)b.push(d[e]);return b};YY.prototype.keySet=YY.prototype.Ie;YY.prototype.set=function(a,b){this.Ab=-1;var c=MY(a),d=this.map[c];if(d==null)this.Se&&this.Se.push(c),this.map[c]=[a,b],this.size++;else{c=!0;for(var e=0;e<d.length;e+=2)if(JY(b,d[e])){c=!1;d[e]=b;break}c&&(d.push(a),d.push(b),this.size++)}};YY.prototype.set=YY.prototype.set;
YY.prototype.values=function(){return new XY(this,1)};YY.prototype.values=YY.prototype.values;YY.prototype.clone=function(){var a=aZ();this.forEach(function(b,c){a.set(c,b)});return a};YY.prototype.clone=YY.prototype.clone;YY.prototype[NZ]=function(){return this.entries()};YY.prototype.yd=function(){this.Ab===-1&&(this.Ab=NY(this));return this.Ab};YY.prototype.gd=function(a){return $Y(this,a)};bZ.prototype.toString=function(){return XFa(this)};bZ.prototype.inspect=function(){return this.toString()};
bZ.prototype.add=function(a){this.map.set(a,a);this.size=this.map.size};bZ.prototype.add=bZ.prototype.add;bZ.prototype.clear=function(){this.map=new YY;this.size=0};bZ.prototype.clear=bZ.prototype.clear;bZ.prototype["delete"]=function(a){a=this.map.delete(a);this.size=this.map.size;return a};bZ.prototype.entries=function(){return this.map.entries()};bZ.prototype.entries=bZ.prototype.entries;bZ.prototype.forEach=function(a){var b=this;this.map.forEach(function(c,d){a(d,b)})};bZ.prototype.forEach=bZ.prototype.forEach;
bZ.prototype.has=function(a){return this.map.has(a)};bZ.prototype.has=bZ.prototype.has;bZ.prototype.keys=function(){return this.map.keys()};bZ.prototype.keys=bZ.prototype.keys;bZ.prototype.Ie=function(){return this.map.Ie()};bZ.prototype.keySet=bZ.prototype.Ie;bZ.prototype.values=function(){return this.map.values()};bZ.prototype.values=bZ.prototype.values;bZ.prototype.clone=function(){var a=ZFa();this.forEach(function(b){a.add(b)});return a};bZ.prototype.clone=bZ.prototype.clone;
bZ.prototype[NZ]=function(){return this.values()};bZ.prototype.gd=function(a){if(a instanceof bZ){if(this.size===a.size)return JY(this.map,a.map)}else return!1};bZ.prototype.yd=function(){return MY(this.map)};cZ.prototype.Af={Zb:{_:function(){return null},"?":function(a){return a==="t"},b:function(a,b){if(b&&b.wh===!1||typeof $APP.kz.Rg=="undefined")if(typeof Uint8Array!="undefined"){if(typeof atob!="undefined")var c=atob(a);else{a=String(a).replace(/=+$/,"");if(a.length%4==1)throw Error("'atob' failed: The string to be decoded is not correctly encoded.");b=0;for(var d,e=0,f="";d=a.charAt(e++);~d&&(c=b%4?c*64+d:d,b++%4)?f+=String.fromCharCode(255&c>>(-2*b&6)):0)d="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/\x3d".indexOf(d);
c=f}a=c.length;b=new Uint8Array(a);for(d=0;d<a;d++)b[d]=c.charCodeAt(d);c=b}else c=RY("b",a);else c=new $APP.kz.Rg(a,"base64");return c},i:function(a){return UFa(a)},n:function(a){return RY("n",a)},d:function(a){return parseFloat(a)},f:function(a){return RY("f",a)},c:function(a){return a},":":function(a){return new SY(a)},$:function(a){return new TY(a)},r:function(a){return RY("r",a)},z:function(a){a:switch(a){case "-INF":a=-Infinity;break a;case "INF":a=Infinity;break a;case "NaN":a=NaN;break a;
default:throw Error("Invalid special double value "+a);}return a},"'":function(a){return a},m:function(a){a=typeof a==="number"?a:parseInt(a,10);return new Date(a)},t:function(a){return new Date(a)},u:function(a){a=a.replace(/-/g,"");var b,c;var d=b=0;for(c=24;d<8;d+=2,c-=8)b|=parseInt(a.substring(d,d+2),16)<<c;var e=0;d=8;for(c=24;d<16;d+=2,c-=8)e|=parseInt(a.substring(d,d+2),16)<<c;var f=$APP.ua(e,b);b=0;d=16;for(c=24;d<24;d+=2,c-=8)b|=parseInt(a.substring(d,d+2),16)<<c;e=0;for(c=d=24;d<32;d+=2,
c-=8)e|=parseInt(a.substring(d,d+2),16)<<c;return new VY(f,$APP.ua(e,b))},set:function(a){return ZFa(a)},list:function(a){return RY("list",a)},link:function(a){return RY("link",a)},cmap:function(a){return aZ(a,!1)}},qh:function(a,b){return RY(a,b)},Dg:!0,wh:!0};
cZ.prototype.decode=function(a,b,c,d){if(a==null)return null;switch(typeof a){case "string":return OFa(a,c)?(a=bGa(this,a),b&&b.write(a,c),b=a):b=a.charAt(0)==="^"&&a.charAt(1)!==" "?b.read(a,c):bGa(this,a),b;case "object":if(IY(a))if(a[0]==="^ ")if(this.md)if(a.length<17&&this.md.fromArray){d=[];for(c=1;c<a.length;c+=2)d.push(this.decode(a[c],b,!0,!1)),d.push(this.decode(a[c+1],b,!1,!1));b=this.md.fromArray(d,a)}else{d=this.md.init(a);for(c=1;c<a.length;c+=2)d=this.md.add(d,this.decode(a[c],b,!0,
!1),this.decode(a[c+1],b,!1,!1),a);b=this.md.finalize(d,a)}else{d=[];for(c=1;c<a.length;c+=2)d.push(this.decode(a[c],b,!0,!1)),d.push(this.decode(a[c+1],b,!1,!1));b=aZ(d,!1)}else b=aGa(this,a,b,c,d);else{c=KY(a);var e=c[0];if((d=c.length==1?this.decode(e,b,!1,!1):null)&&d instanceof $Fa)a=a[e],c=this.Zb[d.uc],b=c!=null?c(this.decode(a,b,!1,!0),this):RY(d.uc,this.decode(a,b,!1,!1));else if(this.md)if(c.length<16&&this.md.fromArray){var f=[];for(d=0;d<c.length;d++)e=c[d],f.push(this.decode(e,b,!0,!1)),
f.push(this.decode(a[e],b,!1,!1));b=this.md.fromArray(f,a)}else{f=this.md.init(a);for(d=0;d<c.length;d++)e=c[d],f=this.md.add(f,this.decode(e,b,!0,!1),this.decode(a[e],b,!1,!1),a);b=this.md.finalize(f,a)}else{f=[];for(d=0;d<c.length;d++)e=c[d],f.push(this.decode(e,b,!0,!1)),f.push(this.decode(a[e],b,!1,!1));b=aZ(f,!1)}}return b}return a};cZ.prototype.decode=cZ.prototype.decode;dZ.prototype.read=function(a){var b=this.cache;a=this.tl.$j.decode(JSON.parse(a),b);this.cache.clear();return a};dZ.prototype.read=dZ.prototype.read;var eGa=0,OGa=(8|3&Math.round(Math.random()*14)).toString(16),dGa="transit$guid$"+(FY()+FY()+FY()+FY()+FY()+FY()+FY()+FY()+"-"+FY()+FY()+FY()+FY()+"-4"+FY()+FY()+FY()+"-"+OGa+FY()+FY()+FY()+"-"+FY()+FY()+FY()+FY()+FY()+FY()+FY()+FY()+FY()+FY()+FY()+FY());fZ.prototype.tag=function(){return"_"};fZ.prototype.rep=function(){return null};fZ.prototype.stringRep=function(){return"null"};gZ.prototype.tag=function(){return"s"};gZ.prototype.rep=function(a){return a};gZ.prototype.stringRep=function(a){return a};
hZ.prototype.tag=function(){return"i"};hZ.prototype.rep=function(a){return a};hZ.prototype.stringRep=function(a){return a.toString()};iZ.prototype.tag=function(){return"i"};iZ.prototype.rep=function(a){return a.toString()};iZ.prototype.stringRep=function(a){return a.toString()};jZ.prototype.tag=function(){return"?"};jZ.prototype.rep=function(a){return a};jZ.prototype.stringRep=function(a){return a.toString()};kZ.prototype.tag=function(){return"array"};kZ.prototype.rep=function(a){return a};
kZ.prototype.stringRep=function(){return null};lZ.prototype.tag=function(){return"map"};lZ.prototype.rep=function(a){return a};lZ.prototype.stringRep=function(){return null};mZ.prototype.tag=function(){return"t"};mZ.prototype.rep=function(a){return a.getUTCFullYear()+"-"+eZ(a.getUTCMonth()+1,2)+"-"+eZ(a.getUTCDate(),2)+"T"+eZ(a.getUTCHours(),2)+":"+eZ(a.getUTCMinutes(),2)+":"+eZ(a.getUTCSeconds(),2)+"."+eZ(a.getUTCMilliseconds(),3)+"Z"};mZ.prototype.stringRep=function(a,b){return b.rep(a)};
nZ.prototype.tag=function(){return"m"};nZ.prototype.rep=function(a){return a.valueOf()};nZ.prototype.stringRep=function(a){return a.valueOf().toString()};nZ.prototype.getVerboseHandler=function(){return new mZ};oZ.prototype.tag=function(){return"u"};oZ.prototype.rep=function(a){return a.toString()};oZ.prototype.stringRep=function(a){return a.toString()};pZ.prototype.tag=function(){return":"};pZ.prototype.rep=function(a){return a.Nb};pZ.prototype.stringRep=function(a,b){return b.rep(a)};
qZ.prototype.tag=function(){return"$"};qZ.prototype.rep=function(a){return a.Nb};qZ.prototype.stringRep=function(a,b){return b.rep(a)};rZ.prototype.tag=function(a){return a.tag};rZ.prototype.rep=function(a){return a.rep};rZ.prototype.stringRep=function(){return null};sZ.prototype.tag=function(){return"set"};sZ.prototype.rep=function(a){var b=[];a.forEach(function(c){b.push(c)});return RY("array",b)};sZ.prototype.stringRep=function(){return null};tZ.prototype.tag=function(){return"map"};
tZ.prototype.rep=function(a){return a};tZ.prototype.stringRep=function(){return null};uZ.prototype.tag=function(){return"map"};uZ.prototype.rep=function(a){return a};uZ.prototype.stringRep=function(){return null};vZ.prototype.tag=function(){return"b"};vZ.prototype.rep=function(a){return a.toString("base64")};vZ.prototype.stringRep=function(){return null};wZ.prototype.tag=function(){return"b"};
wZ.prototype.rep=function(a){for(var b,c=0,d=a.length,e="",f;c<d;)f=a.subarray(c,Math.min(c+32768,d)),e+=String.fromCharCode.apply(null,f),c+=32768;if(typeof btoa!="undefined")b=btoa(e);else{a=String(e);d=0;e="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/\x3d";for(f="";a.charAt(d|0)||(e="\x3d",d%1);f+=e.charAt(63&b>>8-d%1*8)){c=a.charCodeAt(d+=.75);if(c>255)throw Error("'btoa' failed: The string to be encoded contains characters outside of the Latin1 range.");b=b<<8|c}b=f}return b};
wZ.prototype.stringRep=function(){return null};xZ.prototype.get=function(a){a=typeof a==="string"?this.Zb[a]:this.Zb[fGa(a)];return a!=null?a:this.Zb["default"]};xZ.prototype.get=xZ.prototype.get;xZ.prototype.set=function(a,b){var c;if(c=typeof a==="string")a:{switch(a){case "null":case "string":case "boolean":case "number":case "array":case "map":c=!1;break a}c=!0}c?this.Zb[a]=b:this.Zb[fGa(a)]=b};BZ.prototype.rk=function(){return this.jf};BZ.prototype.marshaller=BZ.prototype.rk;
BZ.prototype.write=function(a,b){var c=b||{};b=c.asMapKey||!1;var d=this.jf.Wf?!1:this.cache;if(c.marshalTop===!1)a=AZ(this.jf,a,b,d);else{c=this.jf;var e=JSON,f=e.stringify,g=AZ;var m=hGa(c,a)||(c.Ef?c.Ef(a,c.Zb):null);if(m!=null)a=m.tag(a).length===1?RY("'",a):a;else throw b=(a==null?null:a.constructor).name,d=Error("Cannot write "+b),d.data={ra:a,type:b},d;a=f.call(e,g(c,a,b,d))}this.cache!=null&&this.cache.clear();return a};BZ.prototype.write=BZ.prototype.write;
BZ.prototype.register=function(a,b){this.jf.Zb.set(a,b)};BZ.prototype.register=BZ.prototype.register;$APP.Ek.prototype.Ue=$APP.ae;$APP.Ek.prototype.P=function(a,b){return b instanceof $APP.Ek?this.Yc===b.Yc:b instanceof VY?this.Yc===b.toString():!1};$APP.Ek.prototype.ad=$APP.ae;$APP.Ek.prototype.Mc=function(a,b){if(b instanceof $APP.Ek||b instanceof VY)return $APP.vf(this.toString(),b.toString());throw Error("Cannot compare "+$APP.G.h(this)+" to "+$APP.G.h(b));};VY.prototype.ad=$APP.ae;
VY.prototype.Mc=function(a,b){if(b instanceof $APP.Ek||b instanceof VY)return $APP.vf(this.toString(),b.toString());throw Error("Cannot compare "+$APP.G.h(this)+" to "+$APP.G.h(b));};$APP.ta.prototype.Ue=$APP.ae;$APP.ta.prototype.P=function(a,b){return this.equiv(b)};VY.prototype.Ue=$APP.ae;VY.prototype.P=function(a,b){return b instanceof $APP.Ek?b.P(null,this):this.equiv(b)};QY.prototype.Ue=$APP.ae;QY.prototype.P=function(a,b){return this.equiv(b)};$APP.ta.prototype.sf=$APP.ae;
$APP.ta.prototype.ea=function(){return MY(this)};VY.prototype.sf=$APP.ae;VY.prototype.ea=function(){return $APP.be(this.toString())};QY.prototype.sf=$APP.ae;QY.prototype.ea=function(){return MY(this)};VY.prototype.hh=$APP.ae;VY.prototype.Ga=$APP.ae;VY.prototype.Y=function(a,b){return $APP.cd(b,'#uuid "'+$APP.G.h(this.toString())+'"')};CZ.prototype.init=function(){return $APP.od($APP.Ag)};CZ.prototype.add=function(a,b,c){return $APP.hi.l(a,b,c)};CZ.prototype.finalize=function(a){return $APP.rd(a)};
CZ.prototype.fromArray=function(a){return $APP.di.l?$APP.di.l(a,!0,!0):$APP.di.call(null,a,!0,!0)};DZ.prototype.init=function(){return $APP.od($APP.rh)};DZ.prototype.add=function(a,b){return $APP.qh.j(a,b)};DZ.prototype.finalize=function(a){return $APP.rd(a)};DZ.prototype.fromArray=function(a){return $APP.Ch.j?$APP.Ch.j(a,!0):$APP.Ch.call(null,a,!0)};
var OZ=function OZ(a){switch(arguments.length){case 1:return OZ.h(arguments[0]);case 2:return OZ.j(arguments[0],arguments[1]);default:throw Error(["Invalid arity: ",arguments.length].join(""));}};OZ.h=function(a){return OZ.j(a,null)};
OZ.j=function(a,b){return nGa($APP.fj(a),pGa({handlers:$APP.QC($APP.km.o($APP.x([new $APP.F(null,6,["$",function(c){return $APP.Lj.h(c)},":",function(c){return $APP.Fj.h(c)},"set",function(c){return $APP.fi.j($APP.$i,c)},"list",function(c){return $APP.fi.j($APP.le,c.reverse())},"cmap",function(c){for(var d=0,e=$APP.od($APP.Ag);;)if(d<c.length){var f=d+2;e=$APP.hi.l(e,c[d],c[d+1]);d=f}else return $APP.rd(e)},"with-meta",function(c){return $APP.Se(c[0],c[1])}],null),$APP.lm.j(MZ.h(b),$APP.ln)],0))),
defaultHandler:$APP.ln.h(MZ.h(b)),mapBuilder:new CZ,arrayBuilder:new DZ,preferStrings:!1,preferBuffers:!1},$APP.QC($APP.Qx($APP.lm.j(b,MZ),new $APP.F(null,4,[GGa,wGa,EGa,xGa,FGa,yGa,IGa,KGa],null)))))};OZ.v=2;EZ.prototype.tag=function(){return":"};EZ.prototype.rep=function(a){return a.aa};EZ.prototype.stringRep=function(a){return a.aa};FZ.prototype.tag=function(){return"$"};FZ.prototype.rep=function(a){return a.uc};FZ.prototype.stringRep=function(a){return a.uc};GZ.prototype.tag=function(){return"list"};
GZ.prototype.rep=function(a){var b=[];a=$APP.n(a);for(var c=null,d=0,e=0;;)if(e<d){var f=c.R(null,e);b.push(f);e+=1}else if(a=$APP.n(a))c=a,$APP.ef(c)?(a=$APP.Ed(c),e=$APP.Fd(c),c=a,d=$APP.Ee(a),a=e):(a=$APP.p(c),b.push(a),a=$APP.q(c),c=null,d=0),e=0;else break;return RY("array",b)};GZ.prototype.stringRep=function(){return null};HZ.prototype.tag=function(){return"map"};HZ.prototype.rep=function(a){return a};HZ.prototype.stringRep=function(){return null};IZ.prototype.tag=function(){return"set"};
IZ.prototype.rep=function(a){var b=[];a=$APP.n(a);for(var c=null,d=0,e=0;;)if(e<d){var f=c.R(null,e);b.push(f);e+=1}else if(a=$APP.n(a))c=a,$APP.ef(c)?(a=$APP.Ed(c),e=$APP.Fd(c),c=a,d=$APP.Ee(a),a=e):(a=$APP.p(c),b.push(a),a=$APP.q(c),c=null,d=0),e=0;else break;return RY("array",b)};IZ.prototype.stringRep=function(){return null};JZ.prototype.tag=function(){return"array"};
JZ.prototype.rep=function(a){var b=[];a=$APP.n(a);for(var c=null,d=0,e=0;;)if(e<d){var f=c.R(null,e);b.push(f);e+=1}else if(a=$APP.n(a))c=a,$APP.ef(c)?(a=$APP.Ed(c),e=$APP.Fd(c),c=a,d=$APP.Ee(a),a=e):(a=$APP.p(c),b.push(a),a=$APP.q(c),c=null,d=0),e=0;else break;return b};JZ.prototype.stringRep=function(){return null};KZ.prototype.tag=function(){return"u"};KZ.prototype.rep=function(a){return a.Yc};KZ.prototype.stringRep=function(a){return this.rep(a)};LZ.prototype.tag=function(){return"with-meta"};
LZ.prototype.rep=function(a){return RY("array",[a.value,a.I])};LZ.prototype.stringRep=function(){return null};var PZ=function PZ(a){switch(arguments.length){case 1:return PZ.h(arguments[0]);case 2:return PZ.j(arguments[0],arguments[1]);default:throw Error(["Invalid arity: ",arguments.length].join(""));}};PZ.h=function(a){return PZ.j(a,null)};
PZ.j=function(a,b){var c=new GZ,d=new HZ,e=new IZ,f=new JZ,g=$APP.km.o($APP.x([$APP.Hi([$APP.Gi,$APP.bg,$APP.F,$APP.xi,$APP.Wh,$APP.he,$APP.B,$APP.Oi,$APP.Zf,$APP.lg,$APP.Mh,$APP.Vh,$APP.Bi,$APP.Ti,qGa,$APP.bi,$APP.D,$APP.A,$APP.Je,$APP.Zi,$APP.Pi,$APP.Ri,$APP.Hh,$APP.bj,$APP.pg,$APP.l,$APP.Ek,$APP.nj,$APP.Li,$APP.Ni],[d,c,d,c,c,c,new EZ,f,c,c,f,c,c,c,new LZ,c,f,c,c,e,d,c,c,e,c,new FZ,new KZ,c,c,f]),typeof $APP.zB!=="undefined"&&typeof $APP.AB!=="undefined"&&typeof $APP.Rj!=="undefined"?$APP.zg([$APP.Rj,
c]):null,typeof $APP.zB!=="undefined"&&typeof $APP.AB!=="undefined"&&typeof $APP.jh!=="undefined"?$APP.zg([$APP.jh,c]):null,typeof $APP.zB!=="undefined"&&typeof $APP.AB!=="undefined"&&typeof $APP.tf!=="undefined"?$APP.zg([$APP.tf,f]):null,MZ.h(b)],0));return oGa($APP.fj(a),pGa({objectBuilder:function(m,r,t){return $APP.Ff(function(v,z,C){v.push(r.h?r.h(z):r.call(null,z),t.h?t.h(C):t.call(null,C));return v},["^ "],m)},handlers:function(){var m=$APP.Rb(g);m.forEach=function(r){for(var t=$APP.n(this),
v=null,z=0,C=0;;)if(C<z){var u=v.R(null,C),H=$APP.w.l(u,0,null);u=$APP.w.l(u,1,null);$APP.Fe.j($APP.ln,H)?r.j?r.j(u,"default"):r.call(null,u,"default"):r.j?r.j(u,H):r.call(null,u,H);C+=1}else if(t=$APP.n(t))$APP.ef(t)?(v=$APP.Ed(t),t=$APP.Fd(t),H=v,z=$APP.Ee(v),v=H):(v=$APP.p(t),H=$APP.w.l(v,0,null),u=$APP.w.l(v,1,null),$APP.Fe.j($APP.ln,H)?r.j?r.j(u,"default"):r.call(null,u,"default"):r.j?r.j(u,H):r.call(null,u,H),t=$APP.q(t),v=null,z=0),C=0;else return null};return m}(),unpack:function(m){return m instanceof
$APP.F?m.D:!1}},$APP.QC($APP.lm.j(b,MZ))))};PZ.v=2;$APP.h=rGa.prototype;$APP.h.X=function(a,b){return new rGa(this.Mg,this.Fg,this.Vf,this.Xf,b)};$APP.h.U=function(){return this.Fk};$APP.h.tag=function(a){return this.Mg.h?this.Mg.h(a):this.Mg.call(null,a)};$APP.h.rep=function(a){return this.Fg.h?this.Fg.h(a):this.Fg.call(null,a)};$APP.h.stringRep=function(a){return $APP.k(this.Vf)?this.Vf.h?this.Vf.h(a):this.Vf.call(null,a):null};
$APP.h.getVerboseHandler=function(){return $APP.k(this.Xf)?this.Xf.A?this.Xf.A():this.Xf.call(null):null};var QZ=function QZ(a){switch(arguments.length){case 2:return QZ.j(arguments[0],arguments[1]);case 3:return QZ.l(arguments[0],arguments[1],arguments[2]);case 4:return QZ.C(arguments[0],arguments[1],arguments[2],arguments[3]);default:throw Error(["Invalid arity: ",arguments.length].join(""));}};QZ.j=function(a,b){return QZ.C(a,b,null,null)};QZ.l=function(a,b,c){return QZ.C(a,b,c,null)};
QZ.C=function(a,b,c,d){return new rGa($APP.Qe(a)?a:$APP.Yg(a),$APP.Qe(b)?b:$APP.Yg(b),$APP.Qe(c)?c:$APP.Yg(c),$APP.Qe(d)?d:$APP.Yg(d),$APP.Ag)};QZ.v=4;var RZ=$APP.fY.j($APP.tO,null),PGa=$APP.Hi([DGa,CGa,NGa,$APP.jG,vGa,sGa,MGa,HGa,$APP.BE,$APP.dE],[$APP.at(QZ,DGa,new $APP.F(null,7,[$APP.P,DGa,$APP.O,"Creates a transit write handler whose tag, rep,\n   stringRep, and verboseWriteHandler methods\n   invoke the provided fns.",$APP.X,$APP.I(new $APP.D(null,2,5,$APP.E,[zGa,AGa],null),new $APP.D(null,3,5,$APP.E,[zGa,AGa,uGa],null),new $APP.D(null,4,5,$APP.E,[zGa,AGa,uGa,LGa],null)),$APP.J,"cognitect/transit.cljs",$APP.K,309,$APP.M,7,$APP.S,RZ],null),
RZ),$APP.at(function(a,b){return RY(a,b)},CGa,new $APP.F(null,7,[$APP.P,CGa,$APP.O,"Construct a tagged value. tag must be a string and rep can\n   be any transit encodeable value.",$APP.X,$APP.I(new $APP.D(null,2,5,$APP.E,[$APP.eO,BGa],null)),$APP.J,"cognitect/transit.cljs",$APP.K,332,$APP.M,7,$APP.S,RZ],null),RZ),$APP.at(function(a,b){return a.write(b)},NGa,new $APP.F(null,7,[$APP.P,NGa,$APP.O,"Encode an object into a transit string given a transit writer.",$APP.X,$APP.I(new $APP.D(null,2,5,$APP.E,
[JGa,$APP.$P],null)),$APP.J,"cognitect/transit.cljs",$APP.K,294,$APP.M,7,$APP.S,RZ],null),RZ),$APP.at(function(a,b){return a.read(b)},$APP.jG,new $APP.F(null,7,[$APP.P,$APP.jG,$APP.O,"Read a transit encoded string into ClojureScript values given a\n   transit reader.",$APP.X,$APP.I(new $APP.D(null,2,5,$APP.E,[$APP.aQ,$APP.PN],null)),$APP.J,"cognitect/transit.cljs",$APP.K,146,$APP.M,7,$APP.S,RZ],null),RZ),$APP.at(GZ,vGa,new $APP.F(null,7,[$APP.P,vGa,$APP.O,null,$APP.cn,$APP.II,$APP.J,"cognitect/transit.cljs",
$APP.K,164,$APP.M,19,$APP.S,RZ],null),RZ),$APP.at(function(a){if(a!=null&&(a.G&131072||$APP.ae===a.Wd)){var b=a.U(null);return b!=null?new qGa(a.X(null,null),b):a}return a},sGa,new $APP.F(null,7,[$APP.P,sGa,$APP.O,"For :transform. Will write any metadata present on the value.",$APP.X,$APP.I(new $APP.D(null,1,5,$APP.E,[$APP.fQ],null)),$APP.J,"cognitect/transit.cljs",$APP.K,432,$APP.M,7,$APP.S,RZ],null),RZ),$APP.at(function(a){return UFa(a)},MGa,new $APP.F(null,7,[$APP.P,MGa,$APP.O,"Construct a transit integer value. Returns JavaScript number if\n  in the 53bit integer range, a goog.math.Long instance if above. s\n  may be a string or a JavaScript number.",
$APP.X,$APP.I(new $APP.D(null,1,5,$APP.E,[$APP.cQ],null)),$APP.J,"cognitect/transit.cljs",$APP.K,343,$APP.M,7,$APP.S,RZ],null),RZ),$APP.at(function(a){return a},HGa,new $APP.F(null,7,[$APP.P,HGa,$APP.O,"Construct a read handler. Implemented as identity, exists primarily\n   for API compatiblity with transit-clj",$APP.X,$APP.I(new $APP.D(null,1,5,$APP.E,[tGa],null)),$APP.J,"cognitect/transit.cljs",$APP.K,299,$APP.M,7,$APP.S,RZ],null),RZ),$APP.at(OZ,$APP.BE,new $APP.F(null,7,[$APP.P,$APP.BE,$APP.O,
"Return a transit reader. type may be either :json or :json-verbose.\n   opts may be a map optionally containing a :handlers entry. The value\n   of :handlers should be map from string tag to a decoder function of one\n   argument which returns the in-memory representation of the semantic transit\n   value. If a :default handler is provided, it will be used when no matching\n   read handler can be found.",$APP.X,$APP.I(new $APP.D(null,1,5,$APP.E,[$APP.AJ],null),new $APP.D(null,2,5,$APP.E,[$APP.AJ,
$APP.DM],null)),$APP.J,"cognitect/transit.cljs",$APP.K,106,$APP.M,7,$APP.S,RZ],null),RZ),$APP.at(PZ,$APP.dE,new $APP.F(null,7,[$APP.P,$APP.dE,$APP.O,"Return a transit writer. type maybe either :json or :json-verbose.\n  opts is a map with the following optional keys:\n\n    :handlers  - a map of type constructors to handler instances. Can optionally\n                 provide a :default write handler which will be used if no\n                 matching handler can be found.\n    :transform - a function of one argument returning a transformed value. Will\n                 be invoked on a value before it is written.",
$APP.X,$APP.I(new $APP.D(null,1,5,$APP.E,[$APP.AJ],null),new $APP.D(null,2,5,$APP.E,[$APP.AJ,$APP.DM],null)),$APP.J,"cognitect/transit.cljs",$APP.K,212,$APP.M,7,$APP.S,RZ],null),RZ)]);$APP.Hz(new $APP.F(null,1,[$APP.xt,new $APP.F(null,1,[$APP.tO,PGa],null)],null));