import { $APP, shadow$provide } from "./nbb_core.js";
import "./nbb_api.js";
import "./nbb_goog_string.js";
import "./nbb_pprint.js";
const shadow_esm_import = function(x) { return import(x) };
import*as esm_import$node_net from"node:net";import*as esm_import$node_process from"node:process";import*as esm_import$node_async_hooks from"node:async_hooks";import*as esm_import$node_fs from"node:fs";import*as esm_import$node_path from"node:path";
var UYa=function(a,b){a=a.indexOf(b);if(a<0)throw Error("out of input");return a},x6=function(a,b){if(a.length<b)throw Error("out of input");return a.slice(b)},y6=function(a,b){if(b>a.length)throw Error("out of input");return a.slice(0,b)},VYa=function(a){return(new TextEncoder).encode(a).length},z6=function(a){return $APP.l($APP.kz.h($APP.zc($APP.Yz)))?console.debug($APP.Wn.j(" ",a)):null},XYa=function(a){return function(b,c){b=$APP.Bg(b);var d=$APP.y.j(b,$APP.ut),e=$APP.y.j(b,WYa);c=$APP.Xi.l(c,
"id",d);c=$APP.l(e)?$APP.Xi.l(c,"session",e):c;return a.j?a.j(b,c):a.call(null,b,c)}},$Ya=function(){var a=YYa;return function(b,c){b=$APP.Dn.l(b,ZYa,$APP.Gj);return a.j?a.j(b,c):a.call(null,b,c)}},bZa=function(){var a=aZa();return function(b,c){z6($APP.x(["request",b],0));return a.j?a.j(b,c):a.call(null,b,c)}},cZa=function(a){return function(b,c){z6($APP.x(["response",c],0));return a.j?a.j(b,c):a.call(null,b,c)}},aZa=function(){var a=$Ya();return function(b,c){return a.j?a.j(b,c):a.call(null,b,c)}},
dZa=function(a){return $APP.Xi.l($APP.ij(new $APP.D(null,3,5,$APP.E,["major","minor","incremental"],null),$APP.$z.h(a.split("."))),"version-string",a)},fZa=function(a,b,c){if($APP.l(a))if(a=eZa.h?eZa.h(a):eZa.call(null,a),$APP.l(a)){b=$APP.Bg(b);var d=$APP.y.j(b,$APP.BLa),e=$APP.y.j(b,$APP.iLa),f=$APP.y.j(b,$APP.rLa);b=$APP.zj;var g=$APP.yj,k=$APP.k0;$APP.zj=e;$APP.yj=f;$APP.k0=d;try{var q=new $APP.qb;d=$APP.sb;e=$APP.tb;$APP.sb=!0;$APP.tb=function(t){return q.append(t)};try{a.h?a.h(c):a.call(null,
c)}finally{$APP.tb=e,$APP.sb=d}return""+$APP.H.h(q)}finally{$APP.k0=k,$APP.yj=g,$APP.zj=b}}else return z6($APP.x(["Pretty-Printing is only supported for clojure.core/prn and clojure.pprint/pprint."],0)),$APP.Yj.o($APP.x([c],0));else return $APP.Yj.o($APP.x([c],0))},iZa=function(a,b,c){var d=$APP.w.l(c,0,null);c=$APP.w.l(c,1,null);var e=$APP.S.h(c);$APP.$g(A6,e);$APP.rY.j($APP.XX,$APP.Yg($APP.zc($APP.WX)));$APP.rY.j($APP.WX,$APP.Yg($APP.zc($APP.VX)));$APP.rY.j($APP.VX,$APP.Yg(d));if($APP.l($APP.Oz(d)))return d.then(function(f){f=
new $APP.G(null,2,["value","#\x3cPromise "+$APP.H.h($APP.Yj.o($APP.x([f],0)))+"\x3e","ns",""+$APP.H.h(e)],null);return b.j?b.j(a,f):b.call(null,a,f)});d=fZa(gZa.h(a),hZa.h(a),d);d=new $APP.G(null,2,["value",d,"ns",""+$APP.H.h(e)],null);return b.j?b.j(a,d):b.call(null,a,d)},jZa=function(a,b,c){$APP.rY.j($APP.YX,$APP.Yg(c));var d=$APP.xt.h($APP.Jk(c));d=$APP.l(d)?d:c.message;$APP.l(d)&&(d=new $APP.G(null,1,["err",""+$APP.H.h(d)+"\n"],null),a.j?a.j(b,d):a.call(null,b,d));c=new $APP.G(null,2,["ex",""+
$APP.H.h(c),"ns",""+$APP.H.h($APP.zc($APP.At))],null);return a.j?a.j(b,c):a.call(null,b,c)},oZa=function(){if($APP.bh(kZa,!1,!0)){var a=$APP.zc($APP.DW);$APP.rY.j($APP.DW,$APP.Yg(function(b){var c=lZa.getStore();if($APP.l(c)){var d=$APP.Bg(c);c=$APP.y.j(d,mZa);d=$APP.y.j(d,nZa);b=new $APP.G(null,1,["out",b],null);return d.j?d.j(c,b):d.call(null,c,b)}return a.h?a.h(b):a.call(null,b)}))}},rZa=function(a,b){var c=$APP.Bg(a),d=$APP.y.j(c,$APP.S);a=$APP.y.j(c,B6);var e=$APP.y.j(c,$APP.J);$APP.y.j(c,pZa);
$APP.y.j(c,qZa);var f=$APP.Wr(a),g=function t(q){try{var v=function(){var B=$APP.S.h($APP.Ke(q));if($APP.l(B))return B;B=$APP.zc(A6);return $APP.l(B)?B:d}(),z=$APP.Hna(f,new $APP.G(null,3,[$APP.S,v,$APP.J,e,$APP.Ko,$APP.LB],null));return $APP.Fe.j($APP.DN,z)?Promise.resolve(q):$APP.XIa(z,new $APP.G(null,3,[$APP.S,v,$APP.J,e,$APP.Ko,$APP.LB],null)).then(function(B){return Promise.resolve(iZa(c,b,B)).then(function(){return t(B)})})}catch(B){return jZa(b,c,B),t(null)}};return lZa.run(new $APP.G(null,
2,[mZa,c,nZa,b],null),function(){$APP.Ts($APP.zg([$APP.At,d,$APP.mt,e,$APP.FW,$APP.zc($APP.FW),$APP.KW,!0]));return g(null).catch($APP.om.l(jZa,b,c)).finally(function(){var q=new $APP.G(null,2,["ns",""+$APP.H.h($APP.zc(A6)),"status",new $APP.D(null,1,5,$APP.E,["done"],null)],null);return b.j?b.j(c,q):b.call(null,c,q)}).finally(function(){return $APP.Vs()})})},sZa=function(a,b){a=$APP.Bg(a);var c=$APP.y.j(a,$APP.S),d=$APP.Xi.l;c=$APP.l(c)?$APP.aJa($APP.qs(),$APP.Mj.h(c)):null;$APP.l(c)||(c=$APP.zc(A6),
c=$APP.l(c)?c:$APP.zc($APP.At));return rZa(d.call($APP.Xi,a,$APP.S,c),b)},tZa=function(a){return $APP.Wn.j("\n",$APP.sk.j($APP.Yj,a))},vZa=function(a,b){var c=$APP.Bg(a),d=$APP.y.j(c,$APP.S),e=ZYa.h(c);try{var f=$APP.S.h(c),g=function(){var F=$APP.Sta.h(c);return $APP.l(F)?F:$APP.an.h(c)}(),k=function(){var F=$APP.l(d)?$APP.aJa($APP.qs(),$APP.Mj.h(d)):null;if($APP.l(F))return F;F=$APP.zc(A6);return $APP.l(F)?F:$APP.zc($APP.At)}(),q=$APP.zg([$APP.At,k]);$APP.Ts(q);try{var t=$APP.Py($APP.qs(),$APP.w6("\n(let [ns '%s\n      full-sym '%s]\n  (when-let [v (ns-resolve ns full-sym)]\n    (let [m (meta v)]\n      (assoc m :arglists (:arglists m)\n       :doc (:doc m)\n       :name (:name m)\n       :ns (some-\x3e m :ns ns-name)\n       :val @v))))",
f,g)),v=$APP.O.h(t),z=$APP.J.h(t),B=$APP.K.h(t),u=function(){var F=e instanceof $APP.C?e.aa:null;switch(F){case "eldoc":return F=new $APP.G(null,5,["ns",$APP.S.h(t),"name",$APP.P.h(t),"eldoc",$APP.Eo.j(function(Q){return $APP.Eo.j($APP.H,Q)},$APP.X.h(t)),"type",$APP.lf($APP.My.h(t))?"function":"variable","status",new $APP.D(null,1,5,$APP.E,["done"],null)],null),$APP.l(v)?$APP.Xi.l(F,"docstring",v):F;case "info":case "lookup":return F=new $APP.G(null,4,["ns",$APP.S.h(t),"name",$APP.P.h(t),"arglists-str",
tZa($APP.X.h(t)),"status",new $APP.D(null,1,5,$APP.E,["done"],null)],null),F=$APP.l(v)?$APP.Xi.l(F,"doc",v):F,F=$APP.l(z)?$APP.Xi.l(F,"file",z):F,$APP.l(B)?$APP.Xi.l(F,"line",B):F;default:throw Error("No matching clause: "+$APP.H.h(F));}}();return b.j?b.j(c,u):b.call(null,c,u)}finally{$APP.Vs()}}catch(F){if(F instanceof Error)return a=F,f=function(){var Q=new $APP.aj(null,new $APP.G(null,1,["done",null],null),null);return $APP.Fe.j(e,uZa)?$APP.$f.j(Q,"no-eldoc"):Q}(),a=new $APP.G(null,2,["status",
f,"ex",""+$APP.H.h(a)],null),b.j?b.j(c,a):b.call(null,c,a);throw F;}},wZa=function(a,b){var c=$APP.gJa(a);return b.j?b.j(a,c):b.call(null,a,c)},YYa=function(a,b){a=$APP.Bg(a);var c=$APP.y.j(a,ZYa),d=$APP.y.j(xZa,c);if($APP.l(d))return d.j?d.j(a,b):d.call(null,a,b);console.warn($APP.Wn.j(" ",$APP.x(["Unhandled operation",c],0)));c=new $APP.G(null,1,["status",new $APP.D(null,3,5,$APP.E,["error","unknown-op","done"],null)],null);return b.j?b.j(a,c):b.call(null,a,c)},yZa=function(a){return function(b,
c){return a.write(C6(c))}},zZa=function(a,b){z6($APP.x(["Connection accepted"],0));b.setNoDelay(!0);var c=bZa(),d=XYa(cZa(yZa(b))),e=$APP.bk.h(null);b.on("data",function(f){var g=$APP.zc(e);if($APP.l(g)){f=""+$APP.H.h(g)+$APP.H.h(f);$APP.$g(e,null);var k=f}else k=f;a:{f=$APP.x([$APP.MD,!0],0);for(g=$APP.sh;;){var q=$APP.Wg.l(D6,k,f);k=$APP.w.l(q,0,null);q=$APP.w.l(q,1,null);if(k==null){g=new $APP.D(null,2,5,$APP.E,[g,q],null);break a}g=$APP.$f.j(g,k);k=q}g=void 0}f=$APP.w.l(g,0,null);g=$APP.w.l(g,
1,null);$APP.Il(g)||$APP.$g(e,g);f=$APP.n(f);g=null;for(var t=q=0;;)if(t<q)k=g.R(null,t),c(k,d),t+=1;else if(f=$APP.n(f))g=f,$APP.ff(g)?(f=$APP.Ed(g),q=$APP.Fd(g),g=f,k=$APP.Ee(f),f=q,q=k):(k=$APP.p(g),c(k,d),f=$APP.r(g),g=null,q=0),t=0;else return null});return b.on("close",function(f){return $APP.l(f)?z6($APP.x(["Connection lost"],0)):z6($APP.x(["Connection closed"],0))})},AZa=new $APP.C(null,"completions","completions",-190930179),hZa=new $APP.C("nrepl.middleware.print","options","nrepl.middleware.print/options",
868480159),WYa=new $APP.C(null,"session","session",1008279103),BZa=new $APP.C(null,"load-file","load-file",-424586670),B6=new $APP.C(null,"code","code",1586293142),CZa=new $APP.C(null,"log_level","log_level",-1756736313),gZa=new $APP.C("nrepl.middleware.print","print","nrepl.middleware.print/print",-1616742548),DZa=new $APP.C(null,"clone","clone",711747572),EZa=new $APP.C(null,"close","close",1835149582),FZa=new $APP.C(null,"info","info",-317069002),GZa=new $APP.C(null,"macroexpand","macroexpand",
-130598183),qZa=new $APP.C(null,"_line","_line",232847719),HZa=new $APP.m(null,"server","server",-1155245649,null),IZa=new $APP.C(null,"lookup","lookup",1225356838),JZa=new $APP.C(null,"expander","expander",379138924),pZa=new $APP.C(null,"_load-file?","_load-file?",-1198848711),ZYa=new $APP.C(null,"op","op",-1882987955),KZa=new $APP.C(null,"describe","describe",1369790582),uZa=new $APP.C(null,"eldoc","eldoc",-1321421900),nZa=new $APP.C(null,"send-fn","send-fn",351002041),LZa=new $APP.m(null,"stop-server!",
"stop-server!",-410772185,null),MZa=new $APP.C(null,"load-file?","load-file?",1892536169),mZa=new $APP.C(null,"request","request",1772954723);var E6=function E6(a,b){switch(""+$APP.H.h(y6(a,1))){case "i":return a=x6(a,1),b=UYa(a,"e"),new $APP.D(null,2,5,$APP.E,[parseInt(y6(a,b)),x6(a,b+1)],null);case "l":var d=a=x6(a,1);for(a=$APP.od($APP.sh);;){if($APP.Fe.j(""+$APP.H.h(y6(d,1)),"e"))return new $APP.D(null,2,5,$APP.E,[$APP.rd(a),x6(d,1)],null);var e=E6.j?E6.j(d,b):E6.call(null,d,b),f=$APP.w.l(e,0,null),g=$APP.w.l(e,1,null);e=g;a=$APP.rh.j(a,f);d=e}break;case "d":a=x6(a,1);f=$APP.Bg(b);f=$APP.y.j(f,$APP.MD);d=a;for(e=$APP.od($APP.Ag);;){if($APP.Fe.j(""+
$APP.H.h(y6(d,1)),"e"))return new $APP.D(null,2,5,$APP.E,[$APP.rd(e),x6(d,1)],null);a=E6.j?E6.j(d,b):E6.call(null,d,b);d=$APP.w.l(a,0,null);g=$APP.w.l(a,1,null);g=E6.j?E6.j(g,b):E6.call(null,g,b);a=$APP.w.l(g,0,null);g=$APP.w.l(g,1,null);d=$APP.l(f)?$APP.Gj.h(d):d;a=$APP.ji.l(e,d,a);d=g;e=a}break;default:return b=UYa(a,":"),f=parseInt(y6(a,b)),a=x6(a,b+1),new $APP.D(null,2,5,$APP.E,[""+$APP.H.h(y6(a,f)),x6(a,f)],null)}},D6=function D6(a){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),
e+=1;else break;return D6.o(arguments[0],1<c.length?new $APP.ie(c.slice(1),0,null):null)};D6.o=function(a,b){try{return E6(a,b)}catch(c){if(c instanceof Error)return new $APP.D(null,2,5,$APP.E,[null,a],null);throw c;}};D6.v=1;D6.B=function(a){var b=$APP.p(a);a=$APP.r(a);return this.o(b,a)};
var C6=function C6(a){for(;;){if(typeof a==="string")return""+$APP.H.h(VYa(a))+":"+$APP.H.h(a);if(a instanceof $APP.C||a instanceof $APP.m)a=""+$APP.H.h(function(){var c=$APP.fg(a);return $APP.l(c)?""+$APP.H.h(c)+"/":null}())+$APP.H.h($APP.hj(a));else return typeof a==="number"?"i"+$APP.H.h(a)+"e":$APP.Ze(a)||$APP.ef(a)||a==null?"l"+$APP.H.h($APP.Wg.j($APP.H,$APP.sk.j(C6,a)))+"e":$APP.cf(a)?"d"+$APP.H.h($APP.Wg.j($APP.H,$APP.sk.j(function(){return function(c){var d=$APP.w.l(c,0,null);c=$APP.w.l(c,
1,null);return""+$APP.H.h(C6.h?C6.h(d):C6.call(null,d))+$APP.H.h(C6.h?C6.h(c):C6.call(null,c))}}(a),$APP.Un.j($APP.p,a))))+"e":null}};var A6=$APP.bk.h(null),eZa=new $APP.G(null,1,["cider.nrepl.pprint/pprint",$APP.S1],null),lZa=new esm_import$node_async_hooks.AsyncLocalStorage,kZa=$APP.bk.h(!1),xZa=$APP.Ji([$APP.u_,IZa,EZa,BZa,uZa,DZa,KZa,FZa,$APP.wp,GZa,AZa,$APP.yAa],[function(a,b){var c=new $APP.G(null,2,["status",new $APP.D(null,1,5,$APP.E,["done"],null),"classpath",$APP.Zr($APP.Yr())],null);return b.j?b.j(a,c):b.call(null,a,c)},vZa,function(a,b){var c=new $APP.G(null,1,["status",new $APP.D(null,2,5,$APP.E,["done","session-closed"],
null)],null);return b.j?b.j(a,c):b.call(null,a,c)},function(a,b){a=$APP.Bg(a);var c=$APP.y.j(a,$APP.J);return rZa($APP.Xi.o(a,B6,c,$APP.x([MZa,!0,$APP.S,$APP.zc($APP.At)],0)),b)},vZa,function(a,b){var c=new $APP.G(null,2,["new-session",""+$APP.H.h($APP.Hk()),"status",new $APP.D(null,1,5,$APP.E,["done"],null)],null);return b.j?b.j(a,c):b.call(null,a,c)},function(a,b){var c=new $APP.G(null,4,["versions",new $APP.G(null,2,["nbb-nrepl",dZa("TODO"),"node",dZa(esm_import$node_process.version)],null),"aux",
$APP.Ag,"ops",$APP.ij($APP.sk.j($APP.hj,$APP.Ti(xZa)),$APP.Bo.h($APP.Ag)),"status",new $APP.D(null,1,5,$APP.E,["done"],null)],null);return b.j?b.j(a,c):b.call(null,a,c)},vZa,wZa,function(a,b){a=$APP.Bg(a);var c=$APP.y.j(a,B6),d=$APP.y.j(a,JZa);try{return sZa($APP.Xi.l(a,B6,"( "+$APP.H.h(d)+"(quote "+$APP.H.h(c)+"))"),function(e,f){var g=f.h?f.h("value"):f.call(null,"value");f=$APP.l(g)?$APP.Xi.l(f,"expansion",g):f;return b.j?b.j(e,f):b.call(null,e,f)})}catch(e){if(e instanceof Error)return c=new $APP.G(null,
3,["ex",""+$APP.H.h(e),"ns",""+$APP.H.h($APP.zc($APP.At)),"status",new $APP.D(null,1,5,$APP.E,["done"],null)],null),b.j?b.j(a,c):b.call(null,a,c);throw e;}},wZa,sZa]),NZa=$APP.bk.h(null),F6=function F6(a){switch(arguments.length){case 0:return F6.A();case 1:return F6.h(arguments[0]);default:throw Error(["Invalid arity: ",arguments.length].join(""));}};F6.A=function(){return F6.h($APP.zc(NZa))};
F6.h=function(a){return a.close(function(){$APP.rY.j($APP.DW,$APP.Yg($APP.tb));$APP.rY.j($APP.KW,$APP.Yg($APP.sb));return $APP.l(esm_import$node_fs.existsSync(".nrepl-port"))?esm_import$node_fs.unlinkSync(".nrepl-port"):null})};F6.v=1;
var G6=$APP.vY.j($APP.UE,null),OZa=new $APP.G(null,2,[$APP.t_,$APP.bt(function(a){return Promise.resolve($APP.q_(esm_import$node_path.resolve("script.cljs"),null)).then(function(){function b(e){return $APP.UIa(new $APP.A(null,$APP.bl,new $APP.A(null,new $APP.A(null,$APP.bl,new $APP.A(null,e,null,1,null),2,null),null,1,null),2,null))}var c=$APP.w.l($APP.NY,0,null),d=$APP.w.l($APP.NY,1,null);return b(c).then(function(){return b(d)})}).then(function(){var b=$APP.lm.o($APP.x([$APP.zc($APP.Yz),a],0)),
c=function(){var f=$APP.QM.h(b);return $APP.l(f)?f:0}(),d=function(){var f=$APP.TU.h(b);return $APP.l(f)?f:"127.0.0.1"}();(function(){var f=$APP.Db(b)?b.Hl:CZa.h(b);return $APP.l(f)?f:"info"})();var e=esm_import$node_net.createServer($APP.om.j(zZa,$APP.Ag));e.listen(c,d,function(){var f=e.address(),g=f.port;f=f.address;$APP.Ep.o($APP.x(["nREPL server started on port "+$APP.H.h(g)+" on host "+$APP.H.h(f)+" - nrepl://"+$APP.H.h(f)+":"+$APP.H.h(g)],0));$APP.rY.j($APP.KW,$APP.Yg(!0));oZa();try{return esm_import$node_fs.writeFileSync(".nrepl-port",
""+$APP.H.h(g))}catch(k){return console.warn($APP.Wn.j(" ",$APP.x(["Could not write .nrepl-port",k],0)))}});return $APP.$g(NZa,e)})},$APP.t_,new $APP.G(null,7,[$APP.P,$APP.t_,$APP.O,"Start nRepl server. Accepts options either as JS object or Clojure map.",$APP.X,$APP.I(new $APP.D(null,1,5,$APP.E,[$APP.$M],null)),$APP.J,"nbb/impl/nrepl_server.cljs",$APP.K,350,$APP.M,7,$APP.S,G6],null),G6),LZa,$APP.bt(F6,LZa,new $APP.G(null,7,[$APP.P,LZa,$APP.O,null,$APP.X,$APP.I($APP.sh,new $APP.D(null,1,5,$APP.E,
[HZa],null)),$APP.J,"nbb/impl/nrepl_server.cljs",$APP.K,422,$APP.M,7,$APP.S,G6],null),G6)],null);$APP.kA(new $APP.G(null,1,[$APP.yt,new $APP.G(null,1,[$APP.UE,OZa],null)],null));